export const ZH_TW = `
<localize>
  <string id="% Completed">已完成 %</string>
  <string id="% Completed:">已完成 %：</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;版本資訊&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">（選擇性）請輸入說明</string>
  <string id="( Username must be a Distinguished Name )">（使用者名稱必須是「識別名稱」）</string>
  <string id="(1-999)"> (1-999)</string>
  <string id="(Cron expression)">（Cron 運算式）</string>
  <string id="(progress)">（進度）</string>
  <string id="* Software Client License Not Found.">* 找不到軟體用戶端授權。</string>
  <string id="[EXTERNAL]">[外部]</string>
  <string id="[None]">[無]</string>
  <string id="1 Button">1 個按鈕</string>
  <string id="1 minute load">1 分鐘載入</string>
  <string id="1. cSF Apps">1. cSF 應用程式</string>
  <string id="1. Device Groups">1. 裝置群組</string>
  <string id="1. Search">1. 搜尋</string>
  <string id="1. Services">1. 服務</string>
  <string id="1. Software Client Groups">1. 軟體用戶端群組</string>
  <string id="1. Solutions">1. 解決方案</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. 請輸入搜尋準則，然後按一下「搜尋」按鈕。</string>
  <string id="1. WebApps">1. Web 應用程式</string>
  <string id="10 Buttons">10 個按鈕</string>
  <string id="15 minute load">15 分鐘載入</string>
  <string id="15sec">15 秒鐘</string>
  <string id="2 Buttons">2 個按鈕</string>
  <string id="2. Choose one or more devices if any are found.">2. 若找到裝置，請選擇一或多個裝置。</string>
  <string id="2. Devices">2. 裝置</string>
  <string id="2. Tasks">2. 作業</string>
  <string id="3 Buttons">3 個按鈕</string>
  <string id="3. Choose a Task.">3. 請選擇作業。</string>
  <string id="3. Tasks">3. 作業</string>
  <string id="30sec">30 秒鐘</string>
  <string id="4 Buttons">4 個按鈕</string>
  <string id="4-16 Buttons">4-16 個按鈕</string>
  <string id="5 Buttons">5 個按鈕</string>
  <string id="5 minute load">5 分鐘載入</string>
  <string id="5sec">5 秒鐘</string>
  <string id="6 Buttons">6 個按鈕</string>
  <string id="60sec">60 秒鐘</string>
  <string id="7 Buttons">7 個按鈕</string>
  <string id="8 Buttons">8 個按鈕</string>
  <string id="9 Buttons">9 個按鈕</string>
  <string id="A Policy Update is currently running...">目前正在執行「策略更新」...</string>
  <string id="About">關於</string>
  <string id="Action">動作</string>
  <string id="Action Settings...">動作設定...</string>
  <string id="Action Settings:">動作設定：</string>
  <string id="Action:">動作：</string>
  <string id="Add">新增</string>
  <string id="Add a cSF App to deploy:"> 新增要部署的 cSF 應用程式：</string>
  <string id="Add a new Group to the system">將新群組新增至系統</string>
  <string id="Add a new report to the system">將新報告新增至系統</string>
  <string id="Add a solution to deploy: Step 1 of 2"> 新增要部署的解決方案：步驟 1（共 2 個步驟）</string>
  <string id="Add a solution to deploy: Step 2 of 2"> 新增要部署的解決方案：步驟 2（共 2 個步驟）</string>
  <string id="Add a solution: Step 1 of 2">新增解決方案：步驟 1（共 2 個步驟）</string>
  <string id="Add a solution: Step 2 of 2">新增解決方案：步驟 2（共 2 個步驟）</string>
  <string id="Add a task to Schedule : Step 1 of 3">將作業新增至排程：步驟 1（共 3 個步驟）</string>
  <string id="Add Device Group">新增裝置群組</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">將裝置群組新增至排程：步驟 2（共 3 個步驟）</string>
  <string id="Add Forms Printer">新增表單印表機</string>
  <string id="Add License">新增授權</string>
  <string id="Add Software Client Group">新增軟體用戶端群組</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">將頻率新增至排程：步驟 3（共 3 個步驟）</string>
  <string id="Add...">新增...</string>
  <string id="Adding Formset(s)...">正在新增表單集...</string>
  <string id="Adding Group Name from LDAP...">正在從 LDAP 新增群組名稱...</string>
  <string id="Adding solution to software client group...">正在將解決方案新增至軟體用戶端群組...</string>
  <string id="Additional Options">其他選項</string>
  <string id="Additional Parameters">其他參數</string>
  <string id="Additional Parameters...">其他參數...</string>
  <string id="Additional Report Parameters">其他報告參數</string>
  <string id="Address">位址</string>
  <string id="Address:">位址：</string>
  <string id="Admin password:">管理者密碼：</string>
  <string id="All">全部</string>
  <string id="All cSF Apps">所有 cSF 應用程式</string>
  <string id="All Device Groups">所有裝置群組</string>
  <string id="All scheduled tasks for the system.">系統的所有排程作業。</string>
  <string id="All scheduled tasks for this device group:"> 此裝置群組的所有排程作業：</string>
  <string id="All scheduled tasks for this sftClient group">此 sftClient 群組的所有排程作業</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">所有選定裝置都會從系統中全部移除。您確定要移除這些裝置嗎？</string>
  <string id="All Servers Offline">所有離線伺服器</string>
  <string id="All Servers Online">所有線上伺服器</string>
  <string id="All Software Client Groups">所有軟體用戶端群組</string>
  <string id="All Solutions">所有解決方案</string>
  <string id="All Tabs">所有標籤</string>
  <string id="An error occurred while attempting to connect to this device,">嘗試連接至此裝置時發生錯誤，</string>
  <string id="Anonymous">匿名</string>
  <string id="Any changes here will require">這裡的所有變更都需要</string>
  <string id="Any Changes to the parameters are temporary and will">參數的任何變更都是暫時的，並將</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">參數的任何變更都是暫時的，並將於下次回復為預設值。</string>
  <string id="AP (Advanced Prompting) Bundle Upload">AP（進階提示）軟體組上傳</string>
  <string id="AP Bundle">AP 軟體組</string>
  <string id="AP Bundle Application File">AP 軟體組應用程式檔案</string>
  <string id="AP Bundle descriptor">AP 軟體組描述子</string>
  <string id="AP Bundle Descriptor File">AP 軟體組描述子檔案</string>
  <string id="App Reservation">應用程式保留</string>
  <string id="Application">應用程式</string>
  <string id="Apply">套用</string>
  <string id="Are you sure you want to change the edited profile?">您確定要變更已編輯的設定檔嗎？</string>
  <string id="Are you sure you want to change these profiles?">您確定要變更這些設定檔嗎？</string>
  <string id="Are you sure you want to delete all the forms?">您確定要刪除所有的表單嗎？</string>
  <string id="Are you sure you want to delete all the profiles?">您確定要刪除所有的設定檔嗎？</string>
  <string id="Are you sure you want to delete all the solutions?">您確定要刪除所有解決方案嗎？</string>
  <string id="Are you sure you want to delete the selected forms?">您確定要刪除選取的表單嗎？</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">您確定要刪除選取的群組嗎？關聯於此群組的所有權限也會一併自動刪除。</string>
  <string id="Are you sure you want to delete the selected profiles?">您確定要刪除選取的設定檔嗎？</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">您確定要刪除選取的報告嗎？此報告的所有已排程報告作業也會一併自動刪除。</string>
  <string id="Are you sure you want to delete the selected solutions?">您確定要刪除選取的解決方案嗎？</string>
  <string id="Are you sure you want to delete these profiles?">您確定要刪除這些設定檔嗎？</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">您確定要取消部署所有 cSF 應用程式嗎？</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">您確定要取消部署選取的 cSF 應用程式嗎？</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">您確定要刪除此 +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">您確定要刪除此「裝置群組」嗎？</string>
  <string id="Are you sure you would like to delete this forms printer?">您確定要刪除此表單印表機嗎？</string>
  <string id="Are you sure you would like to delete this scheduled task?">您確定要刪除此排程作業嗎？</string>
  <string id="Are you sure you would like to delete this software client Group?">您確定要刪除此軟體用戶端群組嗎？</string>
  <string id="Are you sure you would like to delete this solution?">您確定要刪除此解決方案嗎？</string>
  <string id="Associated Device Group :">關聯的裝置群組：</string>
  <string id="Associated Solution :">關聯的解決方案：</string>
  <string id="Associated Solution:">關聯的解決方案：</string>
  <string id="Authentication Method:">鑑別方式：</string>
  <string id="Author">作者</string>
  <string id="Auto Refresh:">自動重新整理：</string>
  <string id="Available Columns">可用的直欄</string>
  <string id="Available Reports">可用的報告</string>
  <string id="Back">上一步</string>
  <string id="Background Image:">背景影像：</string>
  <string id="Backup &amp; Restore information">備份與回復資訊</string>
  <string id="Backup amp; Restore">備份與回復</string>
  <string id="Backup Jobs Logs Database">備份工作日誌資料庫</string>
  <string id="Backup Share Path">備份共用路徑</string>
  <string id="Bar Chart">條狀圖</string>
  <string id="Binary Files">二進位檔案</string>
  <string id="Bookmarks">書籤</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">必須同時備有 cacert.pem 和 key.pem 檔案，才能更新 cSF 應用程式憑證。</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">必須同時備有 eSF 快閃記憶體和描述子檔案，才能更新 AP 軟體組。</string>
  <string id="Browse">瀏覽</string>
  <string id="Browse...">瀏覽...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">依預設，多功能複合機會自動排列「主畫面」上的按鈕。</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">依預設，單功能印表機會將設定檔新增至「保留工作」資料夾。</string>
  <string id="Cancel">取消</string>
  <string id="Canceled">已取消</string>
  <string id="Canceling...">取消中...</string>
  <string id="Change Default Values">變更預設值</string>
  <string id="Change Language">變更語言</string>
  <string id="Change Password">變更密碼</string>
  <string id="Change Username">變更使用者名稱</string>
  <string id="Changing name...">正在變更名稱...</string>
  <string id="Choose a cSF App to deploy:"> 選擇要部署的 cSF 應用程式：</string>
  <string id="Choose a solution to deploy:">選擇要部署的解決方案：</string>
  <string id="Choose a solution:">選擇解決方案：</string>
  <string id="Choose Client Groups">選擇用戶端群組</string>
  <string id="Choose deployment settings for">選擇下列項目的部署設定：</string>
  <string id="Choose Device Groups">選擇裝置群組</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">選擇每個按鈕，然後設定它的動作。不含動作的按鈕不會出現在「主畫面」上。</string>
  <string id="Choose one...">選擇一個...</string>
  <string id="Choose task">請選擇作業</string>
  <string id="Choose the frequency">選擇頻率</string>
  <string id="Choose the group type">選擇群組類型</string>
  <string id="Class">類別</string>
  <string id="Click">按一下</string>
  <string id="Click Add to create a Home screen button.">按一下「新增」，以建立「主畫面」按鈕。</string>
  <string id="Click on checkboxes to select or deselect privileges.">按一下勾選框，以選取或取消選取權限。</string>
  <string id="Click on the square, then release the mouse button to select a new color.">按一下方形，然後放開滑鼠按鈕以選取新色彩。</string>
  <string id="Client Groups:">用戶端群組：</string>
  <string id="Client Profile created.">已建立「用戶端設定檔」。</string>
  <string id="Client Profiles">用戶端設定檔</string>
  <string id="Close">關閉</string>
  <string id="Color :">色彩：</string>
  <string id="Column Chart.">直欄圖。</string>
  <string id="Compile">編譯</string>
  <string id="Compile Options:">編譯選項：</string>
  <string id="Completed">已完成</string>
  <string id="Components">元件</string>
  <string id="Config Service">配置服務</string>
  <string id="Configuration">配置</string>
  <string id="Configuration:">配置：</string>
  <string id="Configurations for this discovery:">此尋找的配置：</string>
  <string id="Connect To App">連接到應用程式</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">已連接到目標 VM，位址：127.0.0.1:61023，傳輸：socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">連線已逾時。請檢查伺服器配置，包括防火牆設定。</string>
  <string id="Contact Location">聯絡位置</string>
  <string id="Contact Location:">聯絡位置：</string>
  <string id="Contact Name">聯絡人名稱</string>
  <string id="Contact Name:">聯絡人名稱：</string>
  <string id="Content :">內容：</string>
  <string id="Copy">複印</string>
  <string id="Copy + Profile">複印 + 設定檔</string>
  <string id="Copy Shortcuts">複印快捷鍵</string>
  <string id="CPU Usage">CPU 用法</string>
  <string id="Creating client profile...">正在建立用戶端設定檔...</string>
  <string id="Creating device group...">正在建立裝置群組...</string>
  <string id="Creating discovery profile...">正在建立尋找設定檔...</string>
  <string id="Creating or updating a forms printer...">正在建立或更新表單印表機...</string>
  <string id="Creating software client group...">正在建立軟體用戶端群組...</string>
  <string id="Creatingupdating the scheduled task...">正在建立/更新排程作業...</string>
  <string id="Cron expression)">（Cron 運算式）</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">現行直欄</string>
  <string id="Current password is incorrect.">現行密碼不正確。</string>
  <string id="Current Password:">現行密碼：</string>
  <string id="Currently discovering Missing Devices...">目前正在尋找找不到的裝置...</string>
  <string id="Currently discovering Unlicensed Devices...">目前正在尋找未獲授權的裝置...</string>
  <string id="Custom">自訂</string>
  <string id="Custom icons:">自訂圖示：</string>
  <string id="Custom...">自訂...</string>
  <string id="Customize Jobs Table">自訂工作表</string>
  <string id="Customize Logs Table">自訂日誌表</string>
  <string id="Customize Table...">自訂表格...</string>
  <string id="Danger, Will Robinson!">危險，Will Robinson！</string>
  <string id="Darkness :">明暗度：</string>
  <string id="Database Driver:">資料庫驅動程式：</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>資料庫完整主電腦名稱或 IP 位址</string> 
  <string id="Database URL:">資料庫 URL：</string>
  <string id="Datasource:">資料來源：</string>
  <string id="Datatype Filter">資料類型過濾器</string>
  <string id="Datatype filter:">資料類型過濾器：</string>
  <string id="Date">日期</string>
  <string id="Debug">偵錯</string>
  <string id="Default">預設值</string>
  <string id="Default Group">預設群組</string>
  <string id="Default Group can not be deleted.">無法刪除「預設群組」。</string>
  <string id="Default Output Format:">預設輸出格式：</string>
  <string id="Default: 389">預設值：389</string>
  <string id="Delete">刪除</string>
  <string id="Delete file on failure?">要在失敗時刪除檔案嗎？</string>
  <string id="Delete file on success?">要在成功時刪除檔案嗎？</string>
  <string id="Deleted device group. One or more devices must now be updated.">已刪除裝置群組。有一或多個裝置必須立即更新。</string>
  <string id="Deleted selected FormSet(s).">已刪除選取的表單集。</string>
  <string id="Deleted software client group.">已刪除軟體用戶端群組。</string>
  <string id="Deleting All FormSet(s)...">正在刪除所有表單集...</string>
  <string id="Deleting All solution(s)...">正在刪除所有解決方案...</string>
  <string id="Deleting client profile(s)...">正在刪除用戶端設定檔...</string>
  <string id="Deleting device group...">正在刪除裝置群組...</string>
  <string id="Deleting discovery profile(s)...">正在刪除尋找設定檔...</string>
  <string id="Deleting forms printer...">正在刪除表單印表機...</string>
  <string id="Deleting Formset(s)...">正在刪除表單集...</string>
  <string id="Deleting scheduled task...">正在刪除排程作業...</string>
  <string id="Deleting selected FormSet(s)...">正在刪除選取的表單集...</string>
  <string id="Deleting software client group...">正在刪除軟體用戶端群組...</string>
  <string id="Deleting solution(s)...">正在刪除解決方案...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">部署至：</string>
  <string id="Deploy:">部署：</string>
  <string id="Deploying home screen to"> 正在將主畫面部署至下列項目：</string>
  <string id="Deploying solution to device group..."> 正在將解決方案部署至裝置群組...</string>
  <string id="Deploying WAR file:">正在部署 WAR 檔案： </string>
  <string id="Description">說明</string>
  <string id="Description:">說明：</string>
  <string id="Descriptor">描述子</string>
  <string id="Destination Folder Path">目的地資料夾路徑</string>
  <string id="Developer Forums">開發人員論壇</string>
  <string id="Developer Network">開發人員網路</string>
  <string id="Device Address">裝置位址</string>
  <string id="Device Address:">裝置位址：</string>
  <string id="Device Class">裝置類別</string>
  <string id="Device Group">裝置群組</string>
  <string id="Device Group created">已建立「裝置群組」</string>
  <string id="Device Group was successfully removed from the system.">已從系統中成功移除「裝置群組」。</string>
  <string id="Device Group:">裝置群組：</string>
  <string id="Device Groups">裝置群組</string>
  <string id="Device Groups:">裝置群組：</string>
  <string id="Device Information Directions">裝置資訊指示</string>
  <string id="Device Model">裝置型號</string>
  <string id="Device Model:">裝置型號：</string>
  <string id="Device Profiles">裝置設定檔</string>
  <string id="Device Summary">裝置摘要</string>
  <string id="Device update complete.">裝置更新完成。</string>
  <string id="Device update started...">已起始裝置更新...</string>    
  <string id="DeviceGroup">DeviceGroup</string>
  <string id="Devices">裝置</string>
  <string id="Directory">目錄</string>
  <string id="Directory Path">目錄路徑</string>
  <string id="Directory path*">目錄路徑*</string>
  <string id="Directory Watcher">目錄觀測器</string>
  <string id='Directory Watcher information'>目錄觀測器資訊</string>
  <string id="Disabled">已停用</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">已中斷目標 VM 的連線，位址：127.0.0.1:60902，傳輸：socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">已中斷目標 VM 的連線，位址：127.0.0.1:61015，傳輸：socket</string>
  <string id="Discover">尋找</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">使用每個群組本身的「尋找設定檔」，在所選裝置群組中尋找裝置。</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">使用此裝置群組的「尋找設定檔」，在此群組中尋找裝置。</string>
  <string id="Discover Missing">尋找找不到的</string>
  <string id="Discover new devices only">只尋找新裝置</string>
  <string id="Discover Unlicensed">尋找未獲授權的</string>
  <string id="Discover...">尋找...</string>
  <string id="Discovered">已找到</string>
  <string id="Discovered Devices">找到的裝置</string>
  <string id="Discovered Devices:">找到的裝置：</string>
  <string id="Discovery">尋找</string>
  <string id="Discovery has Completed for...">下列項目的尋找作業已完成...</string>
  <string id="Discovery in Progress for...">下列項目的尋找作業處理中...</string>
  <string id="Discovery Profile created.">已建立「尋找設定檔」。</string>
  <string id="Discovery Profiles">尋找設定檔</string>
  <string id="Discovery Profiles:">尋找設定檔：</string>
  <string id="Display Text">顯示文字</string>
  <string id="Display Text:">顯示文字：</string>
  <string id="Documentation">說明文件</string>
  <string id="Done">完成</string>
  <string id="Done generating the jobs report for downloading.">已產生可供下載的工作報告。</string>
  <string id="Done generating the logs report for downloading.">已產生可供下載的日誌報告。</string>
  <string id="Down icon">下圖示</string>
  <string id="Down icon:">下圖示：</string>
  <string id='Download Details'>下載詳細資料</string>
  <string id="Duplex :">雙面列印：</string>
  <string id="Edit">編輯</string>
  <string id="Edit a solution">編輯解決方案</string>
  <string id="Edit a solution to deploy">編輯要部署的解決方案</string>
  <string id="Edit the information about the report :">編輯報告相關資訊：</string>
  <string id="Edit the report settings">編輯報告設定</string>
  <string id="Edit...">編輯...</string>
  <string id="EForms">電子表單</string>
  <string id="E-Forms">電子表單</string>
  <string id="EForms:">電子表單：</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">必須同時填寫「起始」日期和時間欄位，或將這兩個欄位同時留白。</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">必須同時填寫「結束」日期和時間欄位，或將這兩個欄位同時留白。</string>
  <string id="Email">電子郵件</string>
  <string id="Email + Profile">電子郵件 + 設定檔</string>
  <string id="Email Shortcuts">電子郵件快捷鍵</string>
  <string id="Email the Report">以電子郵件寄送報告</string>
  <string id="Email To">電子郵件收件人</string>
  <string id="Enable Fax Forwarding.">啟用傳真轉發。</string>
  <string id="Enable LDAP Authentication.">啟用 LDAP 鑑別。</string>
  <string id="Enabled for Credentials">認證已啟用</string>
  <string id="Enabled for Session">階段作業已啟用</string>
  <string id="End Time">結束時間</string>
  <string id="End Time:">結束時間：</string>
  <string id="Enter a unique group name">輸入唯一群組名稱</string>
  <string id="Enter a unique name for this group">輸入此群組的唯一名稱</string>
  <string id="Enter appropriate fields and click the Add button:">輸入適當的欄位，然後按一下「新增」按鈕：</string>
  <string id="Enter appropriate fields and click the Save button:">輸入適當的欄位，然後按一下「儲存」按鈕：</string>
  <string id="Enter the appropriate fields and click the Add button:">輸入適當的欄位，然後按一下「新增」按鈕：</string>
  <string id="Enter the information about the new report :">輸入新報告的相關資訊：</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">輸入逾時值（以毫秒計），各重試項目之間以空格區隔。</string>
  <string id="Error">錯誤</string>
  <string id="Error importing license.">匯入授權時發生錯誤。</string>
  <string id="Error in changing name.">變更名稱時發生錯誤。</string>
  <string id="Error in creating device group...">建立裝置群組時發生錯誤...</string>
  <string id="Error in creating software client group...">建立軟體用戶端群組時發生錯誤..</string>
  <string id="Error in deleting device group.">刪除裝置群組時發生錯誤。</string>
  <string id="Error in deleting software client group.">刪除軟體用戶端群組時發生錯誤。</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">刪除表單集時發生錯誤。如需其他詳細資料，請檢查日誌。</string>
  <string id="Error in generating the report.">產生報告時發生錯誤。</string>
  <string id="Error in saving Ldap settings.">儲存 LDAP 設定時發生錯誤。</string>
  <string id="Error in saving settings.">儲存設定時發生錯誤。</string>
  <string id="Error in updating password.">更新密碼時發生錯誤。</string>
  <string id="Error in updating security settings.">更新安全設定時發生錯誤。</string>
  <string id="Error in updating service settings.">更新服務設定時發生錯誤。</string>
  <string id="Error in updating solution settings.">更新解決方案設定時發生錯誤。</string>
  <string id="Error while deploying home screen to">將主畫面部署至下列項目時發生錯誤：</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">在 +app_url} 中評估</string>
  <string id="Evaluate in remote app">在遠端應用程式中評估</string>
  <string id="Every">每個</string>
  <string id="Expiration Date">過期日</string>
  <string id="Expired Formset">已過期的表單集</string>
  <string id="Expired!">已過期！</string>
  <string id="Expires on:">過期日：</string>
  <string id="Export Report">匯出報告</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">失敗</string>
  <string id="FALSE">假</string>
  <string id="Fax">傳真</string>
  <string id="Fax + Profile">傳真 + 設定檔</string>
  <string id="Fax Forward settings updated."> 已更新「傳真轉發」設定。</string>
  <string id="Fax Forwarding">傳真轉發</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax"> 傳真轉發目的地快捷鍵：（電子郵件、FTP、傳真</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">傳真轉發目的地快捷鍵（電子郵件、FTP、傳真）</string>
  <string id="Fax Forwarding Destination:">傳真轉發目的地：</string>
  <string id="Fax Forwarding LDSS Script:"> 傳真轉發 LDSS Script：</string>
  <string id="Fax Forwarding Receive Mode:">傳真轉發接收模式：</string>
  <string id="Fax Shortcuts">傳真快捷鍵</string>
  <string id="Feature Id">功能 ID</string>
  <string id="Filter">過濾器</string>
  <string id="Filters...">過濾基準...</string>
  <string id="Finish">結束</string>
  <string id="Finished AP Bundle Descriptor File">已完成 AP 軟體組描述子檔案</string>
  <string id="Finished AP Bundle Flash File">已完成 AP 軟體組快閃檔案</string>
  <string id="Finished upload of key.pem File.">已完成 key.pem 檔上傳。</string>
  <string id="First">第一</string>
  <string id="Form field must be a single word or valid email address.">表單欄位必須是單字或有效的電子郵件位址。</string>
  <string id="Form Printers">表單印表機</string>
  <string id="Format :">格式：</string>
  <string id="Forms">表單</string>
  <string id="Forms Printer is unlicensed">表單印表機未獲授權</string>
  <string id="Forms printer successfully created or updated.">已成功建立或更新表單印表機。</string>
  <string id="Forms printer successfully deleted.">已成功刪除表單印表機。</string>
  <string id="Formsets">表單集</string>
  <string id="FormsetsSubforms">表單集/子表單</string>
  <string id="Forward Only">僅轉呈</string>
  <string id="Fourth">第四</string>
  <string id="FRAMEWORK">組織架構</string>
  <string id="Fri">星期五</string>
  <string id="From:">寄件人：</string>
  <string id="Ftp">Ftp</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">Ftp + 設定檔</string>
  <string id="Ftp Shortcuts">FTP 快捷鍵</string>
  <string id="Generating logs report for downloading...">正在產生可供下載的日誌報告...</string>
  <string id="Generating Report">產生報告</string>
  <string id="Generating Report...">正在產生報告...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">在一般營業時間產生報告，對系統效能可能會有負面影響。建議在下班時間才執行報告。</string>
  <string id="Generating the jobs report for downloading...">正在產生可供下載的工作報告...</string>
  <string id="Graphic">圖形</string>
  <string id="Graphic:">圖形：</string>
  <string id="Group Description placeholder">群組說明位置保留符號</string>
  <string id="Group Identifier:">群組識別碼：</string>
  <string id="Group Names from LDAP">來自 LDAP 的群組名稱</string>
  <string id="Group Names from LDAP:">來自 LDAP 的群組名稱：</string>
  <string id="Group search base must be set for adding group based">必須設定新增群組時所依據的群組搜尋基礎 </string>
  <string id="Group search base must be set in">群組搜尋基礎必須在其中設定：</string>
  <string id="Group Search Base:">群組搜尋基礎：</string>
  <string id="Group Search Filter:">群組搜尋過濾基準：</string>
  <string id="Group Search Identifier:">群組搜尋識別碼：</string>
  <string id="Groups">群組</string>
  <string id="Held Jobs">保留工作</string>
  <string id="Hide Settings">隱藏設定</string>
  <string id="Home">首頁</string>
  <string id="Home Screen">主畫面</string>
  <string id="Home screen deployed to">主畫面已部署至</string>
  <string id="Home Screens">主畫面</string>
  <string id="Home Tab">首頁標籤</string>
  <string id="Hostname">主電腦名稱</string>
  <string id="Hostname:">主電腦名稱：</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">IDR 授權摘要</string>
  <string id="IDR License Summary:">IDR 授權摘要：</string>
  <string id="Images">影像</string>
  <string id="Import">匯入</string>
  <string id="Import...">匯入...</string>
  <string id="Importing AP Bundle Descriptor File...">正在匯入 AP 軟體組描述子檔案...</string>
  <string id="Importing AP Bundle Flash File...">正在匯入 AP 軟體組快閃檔案...</string>
  <string id='Importing Binary String...'>正在匯入二進位字串...</string>    
  <string id="Importing CaCert pem File...">正在匯入 CaCert pem 檔案...</string>
  <string id="Importing license...">正在匯入授權...</string>
  <string id="Importing software client group profile...">正在匯入軟體用戶端群組設定檔...</string>
  <string id="Importing Solution(s)...">正在匯入解決方案...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">插入 - 這項作業會插入剪下按鈕，並按下其餘按鈕</string>
  <string id="Install Time">安裝時間</string>
  <string id="Install Time:">安裝時間：</string>
  <string id="Install-Upgrade">安裝/升級</string>
  <string id="It is recommended to run reports during off hours.">建議在下班時間才執行報告。</string>
  <string id="Items">項目</string>
  <string id="Jasper Report File Name:">Jasper 報告檔名：</string>
  <string id="Job State">工作狀態</string>
  <string id="Job State:">工作狀態：</string>
  <string id="Jobs">工作</string>
  <string id="Jobs by user">使用者的工作</string>
  <string id="Jobs Filters Table">工作過濾基準表</string>
  <string id="Jobs Report">工作報告</string>
  <string id="Jobs Report - CSV">工作報告 - CSV</string>
  <string id="Keep previous backups">保留先前的備份</string>
  <string id="Krank">Krank</string>  
  <string id='Language:'>語言:</string>
  <string id="Last">最後</string>
  <string id="Last 12 Hours">前 12 小時</string>
  <string id="Last 15 Minutes">前 15 分鐘</string>
  <string id="Last 24 Hours">前 24 小時</string>
  <string id="Last 3 Hours">前 3 小時</string>
  <string id="Last 30 Days">前 30 天</string>
  <string id="Last 30 Minutes">前 30 分鐘</string>
  <string id="Last 6 Hours">前 6 小時</string>
  <string id="Last 7 Days">前 7 天</string>
  <string id="Last Discovered">最後一次找到</string>
  <string id="Last Discovered:">最後一次找到：</string>
  <string id="Last Hour">前一個小時</string>
  <string id="Last Kranked">最後已 Kranked</string>
  <string id="Last Modified">最後修改日期</string>
  <string id="Layout">版面配置</string>
  <string id="Layout:">版面配置：</string>
  <string id="LDAP Server Settings:">LDAP 伺服器設定：</string>
  <string id="Ldap Settings Saved.">已儲存 LDAP 設定。</string>
  <string id="LDAP Setup">LDAP 設定</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark 列印管理</string>
  <string id="License">授權</string>
  <string id="LICENSE">授權</string>
  <string id="License Files">授權檔案</string>
  <string id="License Type">授權類型</string>
  <string id="License Upload Results.">授權上傳結果。</string>
  <string id="License Upload Results:">授權上傳結果：</string>
  <string id="Licensed">已授權</string>
  <string id="Licenses">授權</string>
  <string id="Licenses in Use">授權使用中</string>
  <string id="Limit batch size">限制批次大小</string>
  <string id="Line Chart with Time Period Slider.">附時段滑桿的線條圖。</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>負載平衡器完整主電腦名稱或 IP 位址</string> 
  <string id="LOADING">載入中</string>
  <string id="Loading...">載入中...</string>
  <string id="LOADING...">載入中...</string>
  <string id="Lock Device">鎖定裝置</string>
  <string id="Log">記錄</string>
  <string id="Log Report - CSV">日誌報告 - CSV</string>
  <string id="Log Report - Failed Jobs">日誌報告 - 失敗的工作</string>
  <string id="Log State">日誌狀態</string>
  <string id="Log State:">日誌狀態：</string>
  <string id="Logging In">登入中</string>
  <string id="Login">登入</string>
  <string id="Logout">登出</string>
  <string id="Logs Filters Table">日誌過濾基準表</string>
  <string id='Max:'>上限：</string>  
  <string id="Member of Group(s):">群組成員：</string>
  <string id="Memory Usage">記憶體用法</string>
  <string id="Message">訊息</string>
  <string id="Message:">訊息：</string>
  <string id="Messages">訊息</string>
  <string id='Min:'>下限：</string>
  <string id='Minimum length:'>長度下限：</string>
  <string id='Minimum:'>下限：</string>  
  <string id="Missing">找不到</string>
  <string id="Missing Device">找不到的裝置</string>
  <string id="Missing Devices">找不到的裝置</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">找不到的裝置是指先前找到，但在最近尋找時卻找不到的裝置（例如：由於裝置離線）。</string>
  <string id="Missing devices:">找不到的裝置：</string>
  <string id="Missing Devices:">找不到的裝置：</string>
  <string id="Model">型號</string>
  <string id="Model:">型號：</string>
  <string id="Mon">星期一</string>
  <string id="MONITOR">監視器</string>
  <string id="Move Down">下移</string>
  <string id="Move Up">上移</string>
  <string id="Name">名稱</string>
  <string id="Name :">名稱：</string>
  <string id="Name changed.">已變更名稱。</string>
  <string id="Name:">名稱：</string>
  <string id="Network Load">網路負載</string>
  <string id="Network share password">網路共用區密碼</string>
  <string id="Network share user name">網路共用區使用者名稱</string>
  <string id="New Password:">新密碼：</string>
  <string id="New Username:">新使用者名稱：</string>
  <string id="Next">下一步</string>
  <string id="No">否</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>此裝置群組的「cSF 應用程式」不存在。您必須至少有一個「cSF 應用程式」，才能將此動作關聯於按鈕。</string>
  <string id="No devices are currently Out of Policy for the system.">目前系統沒有不符策略的裝置。</string>
  <string id="No devices are currently Out of Policy for this device group.">目前此裝置群組沒有不符策略的裝置。</string>
  <string id="No home screen is configured for this device type.">尚未配置此裝置類型的主畫面。</string>
  <string id="No matches found">找不到符合的項目</string>
  <string id='No Privilege'>無取用權</string>    
  <string id="No Privilege Alert">無權限警示</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">由於未建立含有設定檔之解決方案的關聯，此裝置群組的設定檔不存在。</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">此裝置群組的設定檔不存在。您必須至少有一個設定檔，才能將此動作關聯於此按鈕。</string>
  <string id="No records match the selected filter criteria.">沒有符合所選過濾基準的記錄。</string>
  <string id="No records matched the filter criteria.">沒有符合過濾基準的記錄。</string>
  <string id="No schedulable scripts are available.">沒有可用的可排程 Script。</string>
  <string id="No UCF File selected">未選取「安全設定檔」</string>
  <string id="None">無</string>
  <string id="None of the selected devices are missing.">沒有找不到的所選裝置。</string>
  <string id="None of the selected devices are unlicensed.">沒有未獲授權的所選裝置。</string>
  <string id="Number of Jobs per Page">每頁工作數</string>
  <string id="Number of Licenses">授權數量</string>
  <string id="Number of Logs per Page">每頁日誌數</string>
  <string id="Off">關閉</string>
  <string id="OK">確定</string>
  <string id="Once">一次</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">現行配置中的一或多個按鈕無效。&lt;font color="#ff0000"&gt;(以紅色呈現)&lt;/font&gt; 請確認所有按鈕均為有效。</string>
  <string id="One or more tests did not pass.">一或多項測試尚未通過。</string>
  <string id="Only"> 僅</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">一次只能進行一項尋找。您可以在目前的尋找完成後，開始新的「尋找」。</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">一次只能執行一項「策略更新」。您可以在現行策略更新結束後，再開始進行新的「策略更新」。</string>
  <string id="Only update those devices which are Out of Policy">僅更新那些不符策略的裝置</string>
  <string id="Orientation :">方向：</string>
  <string id="Out of Policy">不符策略</string>
  <string id="Out of Policy Device">不符策略的裝置</string>
  <string id="Out of Policy Devices">不符策略的裝置</string>
  <string id="Out of Policy Devices:">不符策略的裝置：</string>
  <string id="Output Format">輸出格式</string>
  <string id="Overwrite if file already exists">若檔案已存在，便改寫檔案</string>
  <string id="Page 1">第 1 頁</string>
  <string id="Page 2">第 2 頁</string>
  <string id="Page 3">第 3 頁</string>
  <string id="Page 4">第 4 頁</string>
  <string id="Paper Size :">紙張尺寸：</string>
  <string id="Parameters">參數</string>
  <string id="Password Changed Successfully.">順利變更了密碼。</string>
  <string id="Password updated.">已更新密碼。</string>
  <string id="Password*">密碼*</string>
  <string id="Password:">密碼：</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">使用每個群組的「策略」，執行所選裝置群組的「策略更新」。</string>
  <string id="Perform a Policy Update for selected devices.">執行所選裝置的「策略更新」。</string>
  <string id="Perform a Policy Update for this device group.">執行此裝置群組的「策略更新」。</string>
  <string id="Placeholder">位置保留符號</string>
  <string id="Please choose a filter:">請選擇過濾器：</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">請在已排程 Script 中，選擇能夠存取解決方案的本端解決方案設定的群組類型：</string>
  <string id="Please choose a script:">請選擇 Script：</string>
  <string id="Please choose a task to schedule :">請選擇要排程的作業：</string>
  <string id="Please choose an action:">請選擇動作：</string>
  <string id="Please choose client groups to schedule :">請選擇要排程的用戶端群組：</string>
  <string id="Please choose device groups to schedule :">請選擇要排程的裝置群組：</string>
  <string id="Please choose one of the following options:">請選擇下列任一選項：</string>
  <string id="Please choose solution and script :">請選擇解決方案和 Script：</string>
  <string id="Please choose solution and script to schedule :">請選擇要排程的解決方案和 Script：</string>
  <string id="Please choose start time and frequency :">請選擇開始時間和頻率：</string>
  <string id="Please choose the datasource for the new report.">請選擇新報告的資料來源。</string>
  <string id="Please choose the jasper filename for the new report.">請選擇新報告的 jasper 檔名。</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">請選擇新報告的 jasper 檔名。若尚未列出 jasper 報告，請上傳該報告。</string>
  <string id="Please choose the output format for the new report.">請選擇新報告的輸出格式。</string>
  <string id="Please choose the report to schedule :">請選擇要排程的報告：</string>
  <string id="Please Contact Lexmark for Software Client License Information.">請聯絡 Lexmark，以取得軟體用戶端授權資訊。</string>
  <string id="Please enter a non-expired date">請輸入未過期的日期 (mm/dd/yyyy)。</string>
  <string id="Please enter a valid Address.">請輸入有效的「位址」。</string>
  <string id="Please enter a valid date">請輸入有效的日期 (mm/dd/yyyy)。</string>
  <string id="Please enter a valid End From Time">請輸入有效的「結束起始時間」(HH:MM AM/PM)。</string>
  <string id="Please enter a valid End To Time">請輸入有效的「結束終止時間」(HH:MM AM/PM)。</string>
  <string id="Please enter a valid From date">請輸入有效的「起始日期」(mm/dd/yyyy)。</string>
  <string id="Please enter a valid From time">請輸入有效的「起始時間」(hh:mm AM/PM)。</string>
  <string id='Please enter a valid range:'>請輸入有效的範圍：</string>  
  <string id="Please enter a valid range: 1 - 12">請輸入有效的範圍： 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">請輸入有效的範圍： 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">請輸入有效的範圍： 1 - 59</string>
  <string id="Please enter a valid Start From Time">請輸入有效的「開始起始時間」(HH:MM AM/PM)。</string>
  <string id="Please enter a valid Start To Time">請輸入有效的「開始終止時間」(HH:MM AM/PM)。</string>
  <string id="Please enter a valid time">請輸入有效的時間 (HH:MM AM/PM)。</string>
  <string id="Please enter a valid To date">請輸入有效的「結束日期」(mm/dd/yyyy)。</string>
  <string id="Please enter a valid To time">請輸入有效的「終止時間」(hh:mm AM/PM)。</string>
  <string id="Please enter the Database driver and URL for the external database.">請輸入外部資料庫的「資料庫」驅動程式和 URL。</string>
  <string id="Please enter the Directory information:">請輸入「目錄」資訊：</string>
  <string id="Please enter the location where you want the report to be saved.">請輸入您要儲存報告的位置。</string>
  <string id="Please enter the name of the new report.">請輸入新報告的名稱。</string>
  <string id="Please enter the network share user name and password.">請輸入網路共用使用者名稱和密碼。</string>
  <string id="Please enter the recipients to whom the report will be emailed.">請輸入以電子郵件接收報告的收件人。</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">請輸入「備份與回復」的必要資訊：</string>
  <string id="Please make sure that all the necessary fields are filled in.">請確認已填寫所有必要欄位。</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">請確認您的 Cron 運算式有 6 或 7 個以空格區隔的選項。</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">請確認 Cron 運算式的第 4 或第 6 個位置有一個「?」（而不是兩個位置都有「?」）。</string>
  <string id="Please select a file to upload.">請選取要上傳的檔案。</string>
  <string id="Please select a group on the left to modify its task privileges.">請在左邊選取群組，以修改它的作業權限。</string>
  <string id="Please select a group to save privileges for.">請選取要儲存權限的群組。</string>
  <string id="Please select a profile to view its settings.">請選取設定檔，以檢視它的設定。</string>
  <string id="Please select the Group to delete.">請選取要刪除的群組。</string>
  <string id="Please select the report to delete.">請選取要刪除的報告。</string>
  <string id="Please select the report to edit.">請選取要編輯的報告。</string>
  <string id="Please select the report to run.">請選取要執行的報告。</string>
  <string id="Please specify a port:">請指定連接埠：</string>
  <string id="Please Verify MinMax, Length and Required Settings.">請驗證「最小值/最大值」、「長度」和「必要設定」。</string>
  <string id="Policy Last Applied">最後套用的策略</string>
  <string id="Policy Update">策略更新</string>
  <string id="Policy Update has Completed for...">已完成下列項目的策略更新...</string>
  <string id="Policy Update in Progress for...">正在處理下列項目的策略更新...</string>
  <string id="Policy Update on all effected Device Groups.">所有受影響的「裝置群組」上的「策略更新」。</string>
  <string id="Port">連接埠</string>
  <string id="Port:">連接埠：</string>
  <string id="Present">展示</string>
  <string id="Previous">上一頁</string>
  <string id="Print (Default)">列印（預設值）</string>
  <string id="Print and Forward">列印並轉呈</string>
  <string id="Printer Panel">印表機面板</string>
  <string id="Printer Report">印表機報告</string>
  <string id="Privileges">權限</string>
  <string id="Process finished with exit code 0">處理程序已結束，結束碼為 0</string>
  <string id="Profile Filters">設定檔過濾基準</string>
  <string id="Profile:">設定檔：</string>
  <string id="Profiles">設定檔</string>
  <string id="Profiles :">設定檔：</string>
  <string id="Profiles:"> 設定檔：</string>
  <string id="Progress %">進度百分比</string>
  <string id="Property Tag">內容標籤</string>
  <string id="Property Tag:">內容標籤：</string>
  <string id="Quality :">品質：</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">循環</string>
  <string id="Refresh">重新整理</string>
  <string id="Refresh Defaults">重新整理預設值</string>
  <string id="Regular Expression">規則運算式</string>
  <string id="Release Held Faxes">釋放保留傳真</string>
  <string id="Remove">移除</string>
  <string id="Remove All">全部移除</string>
  <string id="Remove from System">從系統移除</string>
  <string id="Remove Server(s)">移除伺服器</string>
  <string id="RemoveAll">全部移除</string>
  <string id="Removing selected servers...">正在移除選取的伺服器...</string>
  <string id="Repeat this event :">重複此事件：</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">置換 - 這項作業會刪除所選按鈕，並以剪下按鈕加以置換。</string>
  <string id="Replace Me">置換我</string>
  <string id="Report">報告</string>
  <string id="Report by Time">按時間分類的報告</string>
  <string id="Report Files">報告檔案</string>
  <string id="Report From">報告提供者</string>
  <string id="Report Name:">報告名稱：</string>
  <string id="Report Parameters:">報告參數：</string>
  <string id="Report To">報告接收者</string>
  <string id="REPORT_NAME successfully generated">已成功產生 REPORT_NAME</string>
  <string id="Reporting Period">報告期間</string>
  <string id="Reports">報告</string>
  <string id="Reports:">報告：</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">要求逾時。請縮小搜尋基準的範圍，然後重試。</string>
  <string id="Required field">必填欄位</string>
  <string id="Reset">重設</string>
  <string id="Reset Filter">重設過濾器</string>
  <string id="Reset to Default">重設為預設值</string>
  <string id="Resolution :">解析度：</string>
  <string id="Return to Original">返回原始</string>
  <string id="Retype New Password:">重新輸入新密碼：</string>
  <string id="Retype New Username:">重新輸入新使用者名稱：</string>
  <string id="Run on All Servers">在所有伺服器上執行</string>
  <string id="Run Report">執行報告</string>
  <string id="Running">正在執行</string>
  <string id="Running Tasks">正在執行作業</string>
  <string id="Running...">正在執行...</string>
  <string id="Sat">星期六</string>
  <string id="Save">儲存</string>
  <string id="Save Privileges">儲存權限</string>
  <string id="Save Settings">儲存設定</string>
  <string id="Save To">儲存至</string>
  <string id="Saving eSF Settings..."> 正在儲存 eSF 設定...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">正在儲存 LDAP 設定...</string>
  <string id="Schedule">排程</string>
  <string id="Scheduled task createdupdated">已建立/更新排程作業</string>
  <string id="Scheduled task deleted">已刪除排程作業</string>
  <string id="Scheduled tasks for all client groups:">所有用戶端群組的排程作業：</string>
  <string id="Scheduled tasks for all device groups:">所有裝置群組的排程作業：</string>
  <string id="Script">Script</string>
  <string id="Script:">Script：</string>
  <string id="Search">搜尋</string>
  <string id="Search Base:">搜尋基礎：</string>
  <string id="Search Held Jobs">搜尋保留工作</string>
  <string id="Search LDAP for Groups:">搜尋群組的 LDAP：</string>
  <string id="Searching...">搜尋中...</string>
  <string id="Second">第二</string>
  <string id="Secure Server Communication">安全伺服器通訊</string>
  <string id="Secure Server Communication:">安全伺服器通訊：</string>
  <string id="Security">安全性</string>
  <string id="Security setting updated.">已更新安全設定。</string>
  <string id="Security setup file updated successfully">已成功更新安全設定檔</string>
  <string id="Security setup file update failed">安全設定檔更新失敗</string>  
  <string id="Select a Group Name:">選取群組名稱：</string>
  <string id="Select a report">選取報告</string>
  <string id="Select a script task">選取 Script 作業</string>
  <string id="Select one...">選取一項...</string>
  <string id="Select Profile...">選取設定檔...</string>
  <string id="Select the group to copy">選取要複製的群組</string>
  <string id="Sent when any leaf is checked or unchecked, in">若有任一頁已勾選或未勾選則傳送，但以下項目除外：</string>
  <string id="Serial Number">序號</string>
  <string id="Serial Number:">序號：</string>
  <string id="Server Address">伺服器位址</string>
  <string id="Server Address:">伺服器位址：</string>
  <string id="Server handling this LMC session">伺服器正在處理此 LMC 階段作業</string>
  <string id="Server is currently offline">伺服器目前離線</string>
  <string id="Server is not communicating">伺服器沒有通訊</string>
  <string id="Server is unlicensed">伺服器未獲授權</string>
  <string id="Server Port:">伺服器連接埠：</string>
  <string id="Server Report">伺服器報告</string>
  <string id="Server(s) Error">伺服器錯誤</string>
  <string id="Server(s) Offline">伺服器離線</string>
  <string id="Servers">伺服器</string>
  <string id="Service settings updated">已更新服務設定</string>
  <string id="Services">服務</string>
  <string id="Set Offline">離線設定</string>
  <string id="Set Online">線上設定</string>
  <string id="Setting selected servers offline...">正在離線設定選取的伺服器...</string>
  <string id="Setting selected servers online...">正在線上設定選取的伺服器...</string>
  <string id="Settings :">設定：</string>
  <string id="Settings:">設定：</string>
  <string id="SFP e-Task">單功能印表機 e-Task</string>
  <string id="SFP e-Task home screen updated."> 已更新單功能印表機 e-Task 主畫面。</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated."> 已更新單功能印表機 e-Task2 主畫面</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated."> 已更新單功能印表機 e-Task2+ 主畫面。</string>
  <string id="SFP e-Task3">單功能印表機 e-Task3</string>
  <string id="SFP e-Task3 home screen updated."> 已更新單功能印表機 e-Task3 主畫面。</string>
  <string id="SFP e-Task4">單功能印表機 e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4（7 英吋）</string>
  <string id="SFP e-Task4 (7in.) home screen updated."> 已更新單功能印表機 e-Task4（7 英吋）主畫面。</string>
  <string id="SFP e-Task4 home screen updated."> 已更新單功能印表機 e-Task4 主畫面。</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">快捷鍵</string>
  <string id="Shortcut :">快捷鍵：</string>
  <string id="Shortcut:">快捷鍵：</string>
  <string id="Show Settings">顯示設定</string>
  <string id="Since Last Month">從上個月之後</string>
  <string id="Since Yesterday">從昨天之後</string>
  <string id="Single Profile">單一設定檔</string>
  <string id="SNMP Timeout Retries:">SNMP 逾時重試次數：</string>
  <string id="Software Client Group">軟體用戶端群組</string>
  <string id="Software Client Group created">已建立軟體用戶端群組</string>
  <string id="Software Client Group:">軟體用戶端群組：</string>
  <string id="Software Client Groups">軟體用戶端群組</string>
  <string id="Software Client Report">軟體用戶端報告</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">解決方案</string>
  <string id="Solution deleted from software client group.">已從軟體用戶端群組刪除解決方案。</string>
  <string id="Solution deployed to device group"> 已將解決方案部署至裝置群組</string>
  <string id="Solution deployed to software client group">已將解決方案部署至軟體用戶端群組</string>
  <string id="Solution Name">解決方案名稱</string>
  <string id="Solution Name:">解決方案名稱：</string>
  <string id="Solution Report">解決方案報告</string>
  <string id="Solution settings updated.">已更新解決方案設定。</string>
  <string id="Solution: Deleting device group deployment..."> 解決方案：正在刪除裝置群組部署...</string>
  <string id="Solution: Deleting solution from software client group...">解決方案：正在從軟體用戶端群組刪除解決方案...</string>
  <string id="Solution: device group deployment deleted."> 解決方案：已刪除裝置群組部署。</string>
  <string id="SOLUTIONINFO">解決方案資訊</string>
  <string id="Solutions">解決方案</string>
  <string id="Solutions to deploy:">要部署的解決方案：</string>
  <string id="Solutions:">解決方案：</string>
  <string id='Specify Restore system information'>指定回復系統資訊</string>    
  <string id="Specify where the generated report should be saved">指定所產生報告的儲存位置</string>
  <string id="Start Button Default Action">開始按鈕的預設動作</string>
  <string id="Start Date :">開始日期：</string>
  <string id="Start Time">開始時間</string>
  <string id="Start Time:">開始時間：</string>
  <string id="State">省/州</string>
  <string id="Status">狀態</string>
  <string id="Steps for viewing device information:">檢視裝置資訊的步驟：</string>
  <string id="Stop">停止</string>
  <string id="Stop Task">停止作業</string>
  <string id="Subform">子表單</string>
  <string id="Subject:">主旨：</string>
  <string id="Success">成功</string>
  <string id="Successfully added the group.">已成功新增群組。</string>
  <string id="Successfully Deleted All Solution(s) from the System.">已從「系統」成功刪除所有「解決方案」。</string>
  <string id="Successfully Deleted Solution(s) from the System.">已從「系統」成功刪除「解決方案」。</string>
  <string id="Successfully Imported Solution(s) into the System.">已將「解決方案」成功匯入「系統」。</string>
  <string id="Summary">摘要</string>
  <string id="Sun">星期日</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">切換 - 這項作業會切換所選按鈕與剪下按鈕之間的位置。</string>
  <string id="System">系統</string>
  <string id="System Health...">系統健全狀態...</string>
  <string id="System Status">系統狀態</string>
  <string id="System Status 1">系統狀態 1</string>
  <string id="Task Id">作業 ID</string>
  <string id="Task Id:">½業 ID：</string>
  <string id="Task Name">作業名稱</string>
  <string id="Task Name:">作業名稱：</string>
  <string id="Task Summary Report">作業摘要報告</string>
  <string id="Test Progress">測試進度</string>
  <string id="Test Results">測試結果</string>
  <string id="Test Settings">測試設定</string>
  <string id="Testing LDAP Settings...">正在測試 LDAP 設定...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">第一個畫面上的按鈕可按自訂方式排列。</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">已成功產生下列報告：REPORT_NAME。請檢視附加的報告。</string>
  <string id="The password provided is incorrect.">所提供的密碼不正確。</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">正在從群組中的所有裝置取消部署此群組的策略。</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">報告現在已經備妥可供下載。請按一下「確定」以繼續作業。</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">報告期間的「結束日期」比「起始日期」早。系統會在產生報告時自動切換這些日期。您要繼續作業嗎？</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">­¤軟體用戶端群組目前沒有用戶端¯¯設定檔。請填妥以上欄位，以新增用戶端設­定檔。</string>
  <string id="There are currently no cSF Apps associated with this device group."> 此裝置群組目前沒有關聯的 cSF 應用程式。</string>
  <string id="There are currently no cSF Apps to add to this device group."> 目前沒有要新增至此裝置群組的 cSF 應用程式。</string>
  <string id="There are currently no device groups to perform discovery.">There are currently no device groups to perform discovery.</string>
  <string id='There are currently no device groups to perform policy update.'>目前沒有要執行策略更新的裝置群組。</string> 
  <string id="There are currently no device groups to schedule.">目前沒有要執行尋找的裝置群組。</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>目前沒有裝置群組。請按一下左邊的「新增」按鈕，以新增裝置群組。</string>
  <string id="There are currently no devices discovered for this device group.">目前找不到此裝置群組的裝置。</string>
  <string id="There are currently no devices in this device group.">此裝置群組中目前沒有裝置。</string>
  <string id="There are currently no discovered devices.">目前沒有找到的裝置。</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">此裝置群組目前沒有尋找設定檔。請填妥以上適當的欄位，以新增尋找設定檔。</string>
  <string id="There are currently no forms printers in the system.">系統中目前沒有表單印表機。</string>
  <string id="There are currently no licenses installed.">目前沒有已安裝的授權。</string>
  <string id="There are currently no licensing changes made by this upload.">此上傳目前沒有進行授權變更。</string>
  <string id="There are currently no missing devices for this device group.">此裝置群組目前沒有找不到的裝置。</string>
  <string id="There are currently no missing devices.">目前沒有找不到的裝置。</string>
  <string id="There are currently no out of policy devices for this device group.">此裝置群組目前沒有不符策略的裝置。</string>
  <string id="There are currently no out of policy devices.">目前沒有不符策略的裝置。</string>
  <string id="There are currently no scheduled tasks">目前沒有已排程作業</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">目前沒有軟體用戶端群組。請按一下左邊的「新增」按鈕，以新增群組。</string>
  <string id="There are currently no solutions associated with this device group."> 此裝置群組目前沒有關聯的解決方案。</string>
  <string id="There are currently no solutions associated with this software client group.">此軟體用戶端群組目前沒有關聯的解決方案。</string>
  <string id="There are currently no solutions installed.">目前沒有已安裝的解決方案。</string>
  <string id='There are currently no solutions to add to this device group.'>目前沒有要新增至此裝置群組的解決方案。</string>  
  <string id="There are currently no solutions to add to this software client group.">目前沒有要新增至此軟體用戶端群組的解決方案。</string>
  <string id="There are currently no unlicensed devices for this device group.">此裝置群組目前沒有未獲授權的裝置。</string>
  <string id="There are currently no unlicensed devices in this device group.">此裝置群組中目前沒有未獲授權的裝置。</string>
  <string id="There are currently no unlicensed devices.">目前沒有未獲授權的裝置。</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">此群組的策略目前有關聯的解決方案或 cSF 應用程式和/或主畫面。您要立即取消部署此策略嗎？請注意，立即取消部署此策略並不會立即刪除裝置群組。請在策略更新完成時移除裝置群組。</string>
  <string id="There are no associated UCF Files for this Solution.">此「解決方案」沒有相關聯的「安全設定檔」。</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">此裝置群組中的「解決方案」沒有相關聯的「安全設定檔」。</string>
  <string id="There are no configuration settings for this eSF application.">此 eSF 應用程式沒有配置設定。</string>
  <string id="There are no configuration settings in this solution.">此解決方案中沒有配置設定。</string>
  <string id="There are no configuration settings in this webapp.">此 Web 應用程式中沒有配置設定。</string>
  <string id="There are no cSF Apps installed currently.">目前沒有已安裝的 cSF 應用程式。</string>
  <string id="There are no deployments setting for this solution.">此解決方案沒有部署設定。</string>
  <string id="There are no devices in the system that match the filter.">系統中目前沒有符合過濾基準的裝置。</string>
  <string id="There are no eSF Applications for this solution.">此解決方案沒有 eSF 應用程式。</string>
  <string id="There are no e-Task profiles for this device group."> 此裝置群組沒有 e-Task 設定檔。</string>
  <string id="There are no e-Task2 profiles for this device group."> 此裝置群組沒有 e-Task2 設定檔。</string>
  <string id="There are no forms for this solution.">此解決方案沒有表單。</string>
  <string id="There are no forms in the system.">系統中沒有表單。</string>
  <string id="There are no parameters in this service.">此服務中沒有參數。</string>
  <string id="There are no profiles for this software client group.">此軟體用戶端群組沒有設定檔。</string>
  <string id="There are no settings for this action.">此動作沒有設定。</string>
  <string id="There are no settings for this solution.">此解決方案沒有設定。</string>
  <string id="There is currently a Policy Update running...">目前有「策略更新」正在執行...</string>
  <string id="There is currently no Version Info.">目前沒有「版本資訊」。</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">這些 eSF 應用程式是關聯於此裝置群組的解決方案的一部分。請選取應用程式，以檢視它的設定。</string>
  <string id="These group settings are currently hidden.">這些群組設定目前為隱藏形式。</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">這些設定檔是每個型號的群組策略的一部分。請選取每個型號的設定檔，以檢視它的設定。</string>
  <string id="Third">第三</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">此連結會將您引領至 Lexmark 的「Webkit 配置使用者介面」，您要繼續作業嗎？</string>
  <string id="This Month">這個月</string>
  <string id="This name has been given to another device group. Please choose a different name.">此名稱已提供給其他裝置群組。請選擇不同的名稱。</string>
  <string id="This name has been given to another software client group. Please choose a different name.">此名稱已提供給其他軟體用戶端群組。請選擇不同的名稱。</string>
  <string id="Thread Count">執行緒計數</string>
  <string id="Thu">星期四</string>
  <string id="Time">時間</string>
  <string id="Time of Next Run">下次執行的時間</string>
  <string id="Time Policies Last Applied">最後套用策略的時間</string>
  <string id="Time:">時間：</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">若要將它們新增至主畫面，請從上述下拉式方塊中選擇「自訂版面配置」，然後新增設定檔。</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">若要自行排列它們，請從上述下拉式方塊中選擇一種版面配置。</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">若要配置一個項目，請從上述下拉式方塊中選擇一種版面配置。</string>
  <string id="To:">收件人：</string>
  <string id="Today">今天</string>
  <string id="Today date">今天日期</string>
  <string id="Tops Report">上層報告</string>
  <string id="Tue">星期二</string>
  <string id="UCF">安全設定檔</string>
  <string id="UCF:">安全設定檔:</string>    
  <string id="Unable to Change Password.">無法變更密碼。</string>
  <string id="Unable to Change Username.">無法變更使用者名稱。</string>
  <string id="Unable to validate all settings!">無法驗證所有字串！</string>
  <string id="Uncounted">不納入計數</string>
  <string id="Un-deploying all cSF Apps(s)...">正在取消部署所有 cSF 應用程式...</string>
  <string id="Un-deploying cSF App(s)...">正在取消部署 cSF 應用程式...</string>
  <string id="Unknown">不明</string>
  <string id="Unknown Error Occured! Please Check System Log">發生不明錯誤！請檢查系統日誌</string>
  <string id='Unknown Secure State'>不明的安全狀態</string>
  <string id="Unlicensed">未獲授權</string>
  <string id="Unlicensed Device">未獲授權的裝置</string>
  <string id="Unlicensed Devices">未獲授權的裝置</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">未獲授權的裝置是指先前找到，但在最近尋找時卻無法被指定授權的裝置。（例如：由於授權到期或所有的授權均在使用中）。</string>
  <string id="Unlicensed devices:">未獲授權的裝置：</string>
  <string id="Unlicensed Devices:">未獲授權的裝置：</string>
  <string id="Unlicensed:">未獲授權：</string>
  <string id="Unlimited">無限制</string>
  <string id="Up icon:">上圖示：</string>
  <string id="Update">更新</string>
  <string id="Update Policy">更新策略</string>
  <string id="Update Time">更新時間</string>
  <string id="Update Time:">更新時間：</string>
  <string id="Updating client profile...">正在更新用戶端設定檔...</string>
  <string id="Updating discovery profile..."> 正在更新尋找設定檔...</string>
  <string id="Updating e-Task home screen...">正在更新 e-Task 主畫面...</string>
  <string id="Updating e-Task2 home screen..."> 正在更新 e-Task2 主畫面...</string>
  <string id="Updating e-Task2+ home screen..."> 正在更新 e-Task2+ 主畫面...</string>
  <string id="Updating e-Task3 home screen..."> 正在更新 e-Task3 主畫面...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen..."> 正在更新 e-Tas4（4.3 英吋）主畫面...</string>
  <string id="Updating e-Task4 home screen..."> 正在更新 e-Task4 主畫面...</string>
  <string id="Updating Fax Forward settings..."> 正在更新傳真轉發設定...</string>
  <string id="Updating password...">正在更新密碼...</string>
  <string id="Updating Security setting...">正在更新安全設定...</string>
  <string id="Updating service settings...">正在更新服務設定...</string>
  <string id="Updating SFP e-Task home screen..."> 正在更新單功能印表機 e-Task 主畫面...</string>
  <string id="Updating SFP e-Task2 home screen..."> 正在更新單功能印表機 e-Task2 主畫面...</string>
  <string id="Updating SFP e-Task2+ home screen..."> 正在更新單功能印表機 e-Task2+ 主畫面...</string>
  <string id="Updating SFP e-Task3 home screen..."> 正在更新單功能印表機 e-Task3 主畫面...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen..."> 正在更新單功能印表機 e-Tas4（7 英吋）主畫面...</string>
  <string id="Updating SFP e-Task4 home screen..."> 正在更新單功能印表機 e-Task4 主畫面...</string>
  <string id="Updating solution settings...">正在更新解決方案設定...</string>
  <string id="Updating username...">正在更新使用者名稱...</string>
  <string id="Updating X642 home screen..."> 正在更新 X642 主畫面...</string>
  <string id='Updating webapp settings...'>正在更新 Web 應用程式設定...</string>
  <string id="Upgrading or deleting solutions here will require">在這裡升級或刪除解決方案需要執行</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">若要在這裡升級或取消部署 cSF 應用程式，所有受影響的「裝置群組」都需要&lt;b&gt;策略更新&lt;/b&gt;</string>
  <string id="Upload">上傳</string>
  <string id="Upload custom icons">上傳自訂圖示</string>
  <string id="Upload Report Files">上傳報告檔案</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">已完成 AP 軟體組和描述子的上傳。</string>
  <string id="Uploading AP Bundle and Descriptor...">正在上傳 AP 軟體組和描述子...</string>
  <string id="Uploading cSF Ap cert files....">正在上傳 cSF 應用程式憑證檔....</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">正在上傳 cSF 應用程式憑證檔（cacert.pem 和 key.pem）...</string>
  <string id="Uploading of cSF App cert files Completed.">已完成 cSF 應用程式憑證檔的上傳。</string>
  <string id="Uploading Report(s)...">正在上傳報告...</string>
  <string id="Uploading...">上傳中...</string>
  <string id="Usage:">使用次數：</string>
  <string id="Usb Drive">USB 儲存碟</string>
  <string id="Use default settings">使用預設值</string>
  <string id="Use Secure Connection. (SSLTLS)">使用安全連線。(SSL/TLS)</string>
  <string id="Use Solution Configuration">使用解決方案配置</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">只有當現有 LDD 系統的資料庫、中央 webdav 資料，必須與另一個作為「備份 LDD 系統」的作用中 LDD 系統進行同步化時，才使用此對話方塊。如需有關此功能的其他資訊，請參閱「管理者手冊」。</string>
  <string id="Use this home screen as part of the device groups policy.">使用此主畫面作為裝置群組策略的一部分。</string>
  <string id='Used:'>已使用：</string>
  <string id="User Name">使用者名稱</string>
  <string id="User Name:">使用者名稱：</string>
  <string id="User Report">使用者報告</string>
  <string id="User Search Base:">使用者搜尋基礎：</string>
  <string id="User Search Filter:">使用者搜尋過濾基準：</string>
  <string id="Username amp; Password">使用者名稱與密碼</string>
  <string id="Username and Password">使用者名稱和密碼</string>
  <string id="Username Changed Successfully.">已成功變更使用者名稱。</string>
  <string id="Username Password">使用者名稱密碼</string>
  <string id="Username updated.">已更新使用者名稱。</string>
  <string id="Username*">使用者名稱*</string>
  <string id="Username:">使用者名稱：</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">驗證 eSF 應用程式部署，並部署這些 eSF 設定。</string>
  <string id="Version">版本</string>
  <string id="Version Info:">版本資訊：</string>
  <string id="Version:">版本：</string>
  <string id="VersionInfo">版本資訊</string>
  <string id="Very very very long long long text">非常非常長的文字</string>
  <string id="View Details">檢視詳細資料</string>
  <string id="View Source">檢視來源</string>
  <string id="Waiting for License Upload Results ...">正在等待授權上傳結果 ...</string>
  <string id="WebApps">WebApps</string>
  <string id="WebClient Version">WebClient 版本</string>
  <string id="WebClient Version:">WebClient 版本：</string>
  <string id="Wed">星期三</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated."> 已更新 X642 主畫面。</string>
  <string id="Yes">是</string>
  <string id="You are viewing the Kranked version of the application">您正在檢視應用程式的 Kranked 版本</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">您沒有權限存取所有 cSF 應用程式中的任何作業</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">您沒有存取「所有裝置群組」中任何作業的權限</string>
  <string id="You have no privilege to this task.">您沒有權限存取此作業。</string>
  <string id="You must first select a Task to Edit">您必須先選取「要編輯的作業」</string>
  <string id="active">作用中</string>
  <string id="active:">作用中：</string>
  <string id="addition to the two events below.">新增至下列兩個事件。</string>
  <string id="avg response (ms)">平均回應（毫秒）</string>
  <string id="be set back to the default values next time.">於下次回復為預設值。</string>
  <string id="cache">快取</string>
  <string id="cc:">副本抄送：</string>
  <string id="change">變更</string>
  <string id="cSF App">cSF 應用程式</string>
  <string id="cSF App Cert File">cSF 應用程式憑證檔案</string>
  <string id="cSF App Certificates">cSF 應用程式憑證</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">cSF 應用程式憑證（cacert.pem、key.pem）上傳</string>
  <string id="cSF App Key File">cSF 應用程式金鑰檔</string>
  <string id="cSF App settings updated.">已更新 cSF 應用程式設定。</string>
  <string id="cSF App Version">cSF 應用程式版本</string>
  <string id="cSF App Version:">cSF 應用程式版本：</string>
  <string id="cSF Apps">cSF 應用程式</string>
  <string id="cSF Apps deployed to device group">已將 cSF 應用程式部署至裝置群組</string>
  <string id="cSF Apps to deploy:">要部署的 cSF 應用程式：</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF 應用程式：已刪除裝置群組部署。</string>
  <string id="day(s)">天</string>
  <string id="devices failed">裝置失敗</string>
  <string id="devices updated">已更新裝置</string>
  <string id="device(s) discovered">已找到裝置</string>
  <string id="device(s) missing">找不到裝置</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">eSF 應用程式設定：</string>
  <string id="eSF Application Version:">eSF 應用程式版本：</string>
  <string id="eSF Applications">eSF 應用程式</string>
  <string id="eSF Applications:">eSF 應用程式：</string>
  <string id="eSF Applications: (Solution)">eSF 應用程式：（解決方案）</string>
  <string id="eSF Configuration">eSF 配置</string>
  <string id="eSF Settings Saved."> 已儲存 eSF 設定。</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">已更新 e-Task 主畫面。</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated."> 已更新 e-Task2 主畫面。</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated."> 已更新 e-Task2+ 主畫面。</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated."> 已更新 e-Task3 主畫面。</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4（4.3 英吋）</string>
  <string id="e-Task4 (4.3 in.) home screen updated."> 已更新 e-Task4（4.3 英吋）主畫面。</string>
  <string id="e-Task4 home screen updated."> 已更新 e-Task4 主畫面。</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">失敗。</string>
  <string id="hide">隱藏</string>
  <string id="hour(s)">小時</string>
  <string id="in order to add a group.">以新增群組。</string>
  <string id="info">資訊</string>
  <string id="load">載入</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">分鐘</string>
  <string id="month(s)">個月</string>
  <string id="not communicating">沒有通訊</string>
  <string id="null">null</string>
  <string id="offline">離線</string>
  <string id="on">開啟</string>
  <string id="on all effected Device Groups.">（在所有受影響的「裝置群組」上）。</string>
  <string id="oncheck">在檢查時</string>
  <string id="online">線上</string>
  <string id="or home screen support for this device does not exist.">或支援此裝置的主畫面不存在。</string>
  <string id="requests">要求</string>
  <string id="requests/sec">每秒請求數量</string>
  <string id="saving report...">正在儲存報告...</string>
  <string id="server">伺服器</string>
  <string id="show">顯示</string>
  <string id="test">測試</string>
  <string id="to">至</string>
  <string id="to change them.">，以變更它們。</string>
  <string id="to take effect on the devices.">，以便在裝置上生效。</string>
  <string id="total requests:">請求總數：</string>
  <string id="total responses:">回應總數：</string>
  <string id="undo">還原</string>
  <string id="uploaded.">已上傳。</string>
  <string id="week(s)">週</string>
  <string id="{0} Groups">{0} 個群組</string>
  <string id="{0} Reports">{0} 份報告</string>
  <string id="{0} Software Client Groups">{0} 個軟體用戶端群組</string>
  <string id="{0} Solutions">{0} 個解決方案</string>
  <string id="{0} eForms">{0} 張電子表單</string>
  <string id="{0} eSF Applications">{0} 個 eSF 應用程式</string>
  <string id="Policy update required for changes to take effect on the devices">這裡的所有變更都需要「&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;策略更新&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;」，以便在裝置上生效。</string>
  <string id="Group search base must be set for adding group based Privileges">必須設定群組搜尋基礎，來新增以群組為依據的「&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;權限&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;」</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">必須在群組搜尋基礎「&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP 設定&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;」中設定，以新增群組。</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">SMB 授權安裝！多功能複合機授權最多將限制為</string>
  <string id="licenses!">份授權！</string>
</localize>
`;