export const IT = `
<localize>
  <string id="% Completed">% completato</string>
  <string id="% Completed:"> % completato:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">( Opzionale) Immettere una descrizione</string>
  <string id="( Username must be a Distinguished Name )"> (Il nome utente deve essere uno nome distinto)</string>
  <string id="(1-999)"> (1-999)</string>
  <string id="(Cron expression)">(Espressione cron)</string>
  <string id="(progress)">(avanzamento)</string>
  <string id="* Software Client License Not Found.">* Licenza client software non trovata.</string>
  <string id="[EXTERNAL]">[EXTERNAL]</string>
  <string id="[None]">[Nessuno]</string>
  <string id="1 Button">1 pulsante</string>
  <string id="1 minute load">1 minuto carico</string>
  <string id="1. cSF Apps">1. App cSF</string>
  <string id="1. Device Groups">1. Gruppi periferiche</string>
  <string id="1. Search">1. Cerca</string>
  <string id="1. Services">1. Servizi</string>
  <string id="1. Software Client Groups">1. Gruppi di client software</string>
  <string id="1. Solutions">1. Soluzioni</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button."> 1. Immettere il criterio di ricerca e fare clic sul pulsante &quot;Cerca&quot;.</string>
  <string id="1. WebApps">1. App Web</string>
  <string id="10 Buttons">10 pulsanti</string>
  <string id="15 minute load">15 minuto carico</string>
  <string id="15sec">15 sec</string>
  <string id="2 Buttons">2 pulsanti</string>
  <string id="2. Choose one or more devices if any are found."> 2. Scegliere una o più periferiche se trovate.</string>
  <string id="2. Devices">2. Periferiche</string>
  <string id="2. Tasks">2. Attività</string>
  <string id="3 Buttons">3 pulsanti</string>
  <string id="3. Choose a Task."> 3. Scegliere un'attività.</string>
  <string id="3. Tasks">3. Attività</string>
  <string id="30sec">30 sec</string>
  <string id="4 Buttons">4 pulsanti</string>
  <string id="4-16 Buttons">4-16 pulsanti</string>
  <string id="5 Buttons">5 pulsanti</string>
  <string id="5 minute load">5 minuto carico</string>
  <string id="5sec">5 sec</string>
  <string id="6 Buttons">6 pulsanti</string>
  <string id="60sec">60 sec</string>
  <string id="7 Buttons">7 pulsanti</string>
  <string id="8 Buttons">8 pulsanti</string>
  <string id="9 Buttons">9 pulsanti</string>
  <string id="A Policy Update is currently running...">Aggiornamento criterio in esecuzione...</string>
  <string id="About"> Info su</string>
  <string id="Action">Azione</string>
  <string id="Action Settings...">Impostazioni azione...</string>
  <string id="Action Settings:">Impostazioni azione:</string>
  <string id="Action:">Azione:</string>
  <string id="Add">Aggiungi</string>
  <string id="Add a cSF App to deploy:"> Aggiungi un'app cSF da distribuire:</string>
  <string id="Add a new Group to the system"> Aggiungi un nuovo gruppo al sistema</string>
  <string id="Add a new report to the system"> Aggiungi un nuovo rapporto al sistema</string>
  <string id="Add a solution to deploy: Step 1 of 2"> Aggiungere una soluzione da distribuire: Passaggio 1 di 2</string>
  <string id="Add a solution to deploy: Step 2 of 2"> Aggiungere una soluzione da distribuire: Passaggio 2 di 2</string>
  <string id="Add a solution: Step 1 of 2"> Aggiungi una soluzione: Passaggio 1 di 2</string>
  <string id="Add a solution: Step 2 of 2"> Aggiungi una soluzione: Passaggio 2 di 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Aggiungere attività da programmare: Passaggio 1 di 3</string>
  <string id="Add Device Group">Aggiungi gruppo periferiche</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Aggiungere gruppo periferiche da programmare: Passaggio 2 di 3</string>
  <string id="Add Forms Printer"> Aggiungi Forms Printer</string>
  <string id="Add License">Aggiungi licenza</string>
  <string id="Add Software Client Group">Aggi‎ungi gruppo di client software</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Aggiungere frequenza da programmare: Passaggio 3 di 3</string>
  <string id="Add...">Aggiungi...</string>
  <string id="Adding Formset(s)..."> Aggiunta formset in corso...</string>
  <string id="Adding Group Name from LDAP...">Aggiunta nome gruppo da LDAP in corso...</string>
  <string id="Adding solution to software client group..."> Aggiunta soluzione a gruppo di client software...</string>
  <string id="Additional Options">Opzioni aggiuntive</string>
  <string id="Additional Parameters">Parametri aggiuntivi</string>
  <string id="Additional Parameters...">Parametri aggiuntivi...</string>
  <string id="Additional Report Parameters"> Parametri rapporto aggiuntivo</string>
  <string id="Address">Indirizzo</string>
  <string id="Address:">Indirizzo:</string>
  <string id="Admin password:">Password amministratore:</string>
  <string id="All">Tutto</string>
  <string id="All cSF Apps"> Tutte le app cSF</string>
  <string id="All Device Groups">Tutti i gruppi di periferiche</string>
  <string id="All scheduled tasks for the system."> Tutte le attività pianificate per il sistema.</string>
  <string id="All scheduled tasks for this device group:"> Tutte le attività pianificate per questo gruppo di periferiche:</string>
  <string id="All scheduled tasks for this sftClient group"> Tutte le attività pianificate per questo gruppo sftClient</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">Tutte le periferiche selezionate saranno completamente rimosse dal sistema. Rimuovere queste periferiche?</string>
  <string id="All Servers Offline"> Tutti i server offline</string>
  <string id="All Servers Online"> Tutti i server online</string>
  <string id="All Software Client Groups">Tutti i gruppi di client software</string>
  <string id="All Solutions">Tutte le soluzioni</string>
  <string id="All Tabs"> Tutte le schede</string>
  <string id="An error occurred while attempting to connect to this device,">Errore di connessione alla periferica,</string>
  <string id="Anonymous">Anonimo</string>
  <string id="Any changes here will require">Qualsiasi modifica qui richiederà</string>
  <string id="Any Changes to the parameters are temporary and will">Qualsiasi modifica ai parametri è temporanea e</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Qualsiasi modifica ai parametri è temporanea e torneranno ai valori predefiniti la prossima volta.</string>
  <string id="AP (Advanced Prompting) Bundle Upload"> Caricamento bundle Richieste avanzate</string>
  <string id="AP Bundle">Bundle Richieste avanzate</string>
  <string id="AP Bundle Application File">File applicazione bundle AP</string>
  <string id="AP Bundle descriptor"> Descrittore bundle Richieste avanzate</string>
  <string id="AP Bundle Descriptor File">File descrittore bundle AP</string>
  <string id="App Reservation">Prenotazione app</string>
  <string id="Application"> Applicazione</string>
  <string id="Apply">Applica</string>
  <string id="Are you sure you want to change the edited profile?">Cambiare il profilo modificato?</string>
  <string id="Are you sure you want to change these profiles?"> Cambiare questi profili?</string>
  <string id="Are you sure you want to delete all the forms?">Eliminare tutti i moduli?</string>
  <string id="Are you sure you want to delete all the profiles?">Eliminare tutti i profili?</string>
  <string id="Are you sure you want to delete all the solutions?"> Eliminare tutti le soluzioni?</string>
  <string id="Are you sure you want to delete the selected forms?">Eliminare i moduli selezionati?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well."> Eliminare il gruppo selezionato?  Verranno automaticamente eliminati anche tutti i privilegi associati con questo gruppo.</string>
  <string id="Are you sure you want to delete the selected profiles?">Eliminare i profili selezionati?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well."> Eliminare il rapporto selezionato?  Verrà automaticamente eliminata qualsiasi attività di rapporto pianificata per questo rapporto.</string>
  <string id="Are you sure you want to delete the selected solutions?"> Eliminare le soluzioni selezionate?</string>
  <string id="Are you sure you want to delete these profiles?"> Eliminare questi profili?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?"> Annullare la distribuzione di tutte le app cSF?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?"> Annullare la distribuzione delle app cSF selezionate?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">Eliminare +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">Eliminare questo gruppo di periferiche?</string>
  <string id="Are you sure you would like to delete this forms printer?">Eliminare questa stampante di moduli?</string>
  <string id="Are you sure you would like to delete this scheduled task?"> Eliminare questa attività pianificata?</string>
  <string id="Are you sure you would like to delete this software client Group?"> Eliminare questo gruppo di client software?</string>
  <string id="Are you sure you would like to delete this solution?"> Eliminare questa soluzione?</string>
  <string id="Associated Device Group :">Gruppo di periferiche associato:</string>
  <string id="Associated Solution :">Soluzione associata:</string>
  <string id="Associated Solution:">Soluzione associata:</string>
  <string id="Authentication Method:"> Metodo di autenticazione:</string>
  <string id="Author"> Autore</string>
  <string id="Auto Refresh:">Aggiornamento automatico:</string>
  <string id="Available Columns">Colonne disponibili</string>
  <string id="Available Reports">Rapporti disponibili</string>
  <string id="Back">Indietro</string>
  <string id="Background Image:">Immagine di sfondo:</string>
  <string id="Backup &amp; Restore information"> Backup e ripristino informazioni</string>
  <string id="Backup amp; Restore">Backup e ripristino</string>
  <string id="Backup Jobs Logs Database">Esegui backup database registri processi</string>
  <string id="Backup Share Path"> Esegui backup percorso condivisione</string>
  <string id="Bar Chart">Grafico a barre</string>
  <string id="Binary Files"> File binari</string>
  <string id="Bookmarks">Segnalibri</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates."> I file cacert.pem e key.pem sono necessari per aggiornare i certificati delle app cSF.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">I file flash e descrittore eSF sono necessari per aggiornare il bundle AP.</string>
  <string id="Browse">Sfoglia</string>
  <string id="Browse...">Sfoglia...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen."> Per impostazione predefinita, l'MFP organizza automaticamente i pulsanti nella schermata iniziale.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder."> Per impostazione predefinita, l'SFP aggiunge i profili alla cartella dei processi in attesa.</string>
  <string id="Cancel">Annulla</string>
  <string id="Canceled">Annullato</string>
  <string id="Canceling...">Annullamento in corso...</string>
  <string id="Change Default Values">Modifica valori predefiniti</string>
  <string id="Change Language">Modifica lingua</string>
  <string id="Change Password">Cambia password</string>
  <string id="Change Username">Modifica nome utente</string>
  <string id="Changing name..."> Modifica del nome...</string>
  <string id="Choose a cSF App to deploy:"> Scegliere un'app cSF da distribuire:</string>
  <string id="Choose a solution to deploy:">Scegliere la soluzione da distribuire:</string>
  <string id="Choose a solution:">Scegliere una soluzione:</string>
  <string id="Choose Client Groups">Scegliere i gruppi di client</string>
  <string id="Choose deployment settings for"> Scegliere le impostazioni di distribuzione per</string>
  <string id="Choose Device Groups"> Scegliere i gruppi di periferiche</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen."> Scegliere ogni pulsante e impostarne l'azione. I pulsanti senza azioni non saranno visualizzati nella schermata iniziale.</string>
  <string id="Choose one...">Sceglierne uno...</string>
  <string id="Choose task"> Scegliere l'attività</string>
  <string id="Choose the frequency">Scegliere la frequenza</string>
  <string id="Choose the group type"> Scegliere il tipo di gruppo</string>
  <string id="Class">Classe</string>
  <string id="Click">Fare clic</string>
  <string id="Click Add to create a Home screen button.">Fare clic su Aggiungi per creare un pulsante della schermata principale.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Fare clic sulle caselle di controllo per selezionare o deselezionare i privilegi.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Fare clic sul quadrato, quindi rilasciare il pulsante del mouse per selezionare un nuovo colore.</string>
  <string id="Client Groups:">Gruppi di client:</string>
  <string id="Client Profile created.">Client Profile created.</string>
  <string id="Client Profiles">Profili client</string>
  <string id="Close">Chiudi</string>
  <string id="Color :">Colore:</string>
  <string id="Column Chart.">Grafico a colonne.</string>
  <string id="Compile">Compila</string>
  <string id="Compile Options:">Opzioni di compilazione:</string>
  <string id="Completed">Completato</string>
  <string id="Components">Componenti</string>
  <string id="Config Service">Configura servizio</string>
  <string id="Configuration">Configurazione</string>
  <string id="Configuration:">Configurazione:</string>
  <string id="Configurations for this discovery:">Configurazioni per questo rilevamento:</string>
  <string id="Connect To App">Connetti ad app</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Connesso al VM di destinazione, indirizzo: 127.0.0.1:61023, trasporto: socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings."> Timeout connessione. Controllare la configurazione del server comprese le impostazioni del firewall.</string>
  <string id="Contact Location">Posizione contatto</string>
  <string id="Contact Location:">Posizione contatto:</string>
  <string id="Contact Name">Nome contatto</string>
  <string id="Contact Name:">Nome contatto:</string>
  <string id="Content :">Contenuto:</string>
  <string id="Copy">Copia</string>
  <string id="Copy + Profile">Copia + Profilo</string>
  <string id="Copy Shortcuts">Copia scelte rapide</string>
  <string id="CPU Usage"> Utilizzo CPU</string>
  <string id="Creating client profile..."> Creazione profilo client in corso...</string>
  <string id="Creating device group..."> Creazione gruppo di periferiche in corso...</string>
  <string id="Creating discovery profile..."> Creazione profilo di ricerca in corso...</string>
  <string id="Creating or updating a forms printer..."> Creazione o aggiornamento di una Forms Printer...</string>
  <string id="Creating software client group..."> Creazione del gruppo di client software in corso...</string>
  <string id="Creatingupdating the scheduled task..."> Creazione/aggiornamento dell'attività pianificata in corso...</string>
  <string id="Cron expression)">(Espressione cron)</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">Colonne correnti</string>
  <string id="Current password is incorrect."> La password corrente è errata.</string>
  <string id="Current Password:">Password corrente:</string>
  <string id="Currently discovering Missing Devices...">Rilevamento periferiche mancanti in corso...</string>
  <string id="Currently discovering Unlicensed Devices...">Rilevamento periferiche senza licenza in corso...</string>
  <string id="Custom">Personalizzata</string>
  <string id="Custom icons:">Icone personalizzate:</string>
  <string id="Custom...">Personalizzato...</string>
  <string id="Customize Jobs Table"> Personalizza tabella processi</string>
  <string id="Customize Logs Table"> Personalizza tabella registri</string>
  <string id="Customize Table..."> Personalizza tabella...</string>
  <string id="Danger, Will Robinson!">Pericolo!</string>
  <string id="Darkness :">Intensità:</string>
  <string id="Database Driver:">Driver database:</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>Nome host qualificato O indirizzo IP database</string>
  <string id="Database URL:">URL database:</string>
  <string id="Datasource:">Datasource:</string>
  <string id="Datatype Filter">Filtro tipo di dati</string>
  <string id="Datatype filter:">Filtro tipo di dati:</string>
  <string id="Date">Dati</string>
  <string id="Debug">Debug</string>
  <string id="Default">Predefinito</string>
  <string id="Default Group">Gruppo predefinito</string>
  <string id="Default Group can not be deleted."> Impossibile eliminare il gruppo predefinito.</string>
  <string id="Default Output Format:">Formato di output predefinito:</string>
  <string id="Default: 389"> Predefinito: 389</string>
  <string id="Delete">Elimina</string>
  <string id="Delete file on failure?">Eliminare file su errore?</string>
  <string id="Delete file on success?">Eliminare file su riuscito?</string>
  <string id="Deleted device group. One or more devices must now be updated."> Gruppo di periferiche eliminato. Ora è necessario aggiornare una o più periferiche.</string>
  <string id="Deleted selected FormSet(s)."> Formset selezionati eliminati.</string>
  <string id="Deleted software client group."> Gruppo di client software eliminato.</string>
  <string id="Deleting All FormSet(s)..."> Eliminazione di tutti i formset in corso...</string>
  <string id="Deleting All solution(s)..."> Eliminazione di tutte le soluzioni in corso...</string>
  <string id="Deleting client profile(s)..."> Eliminazione dei profili client in corso...</string>
  <string id="Deleting device group..."> Eliminazione gruppo di periferiche in corso...</string>
  <string id="Deleting discovery profile(s)..."> Eliminazione dei profili di ricerca in corso...</string>
  <string id="Deleting forms printer..."> Eliminazione di Forms Printer in corso...</string>
  <string id="Deleting Formset(s)..."> Eliminazione di formset in corso...</string>
  <string id="Deleting scheduled task..."> Eliminazione attività pianificata in corso...</string>
  <string id="Deleting selected FormSet(s)..."> Eliminazione formset selezionati in corso...</string>
  <string id="Deleting software client group..."> Eliminazione gruppo di client software in corso...</string>
  <string id="Deleting solution(s)..."> Eliminazione di soluzioni in corso...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Distribuisci in:</string>
  <string id="Deploy:">Distribuisci:</string>
  <string id="Deploying home screen to"> Distribuzione schermata iniziale a</string>
  <string id="Deploying solution to device group..."> Distribuzione soluzione a gruppo di periferiche in corso...</string>
  <string id="Deploying WAR file:"> Distribuzione file WAR: </string>
  <string id="Description">Descrizione</string>
  <string id="Description:">Descrizione:</string>
  <string id="Descriptor"> Descrittore</string>
  <string id="Destination Folder Path">Percorso cartella di destinazione</string>
  <string id="Developer Forums">Forum sviluppatori</string>
  <string id="Developer Network">Developer Network</string>
  <string id="Device Address">Indirizzo periferica</string>
  <string id="Device Address:">Indirizzo periferica:</string>
  <string id="Device Class"> Classe periferica</string>
  <string id="Device Group">Gruppo periferiche</string>
  <string id="Device Group created"> Gruppo di periferiche creato</string>
  <string id="Device Group was successfully removed from the system.">Il gruppo di periferiche è stato rimosso correttamente dal sistema.</string>
  <string id="Device Group:">Gruppo periferiche:</string>
  <string id="Device Groups">Gruppi periferiche</string>
  <string id="Device Groups:">Gruppi periferiche:</string>
  <string id="Device Information Directions"> Direzioni informazioni periferica</string>
  <string id="Device Model">Modello periferica</string>
  <string id="Device Model:"> Modello periferica:</string>
  <string id="Device Profiles"> Profili periferica</string>
  <string id="Device Summary"> Riepilogo periferica</string>
  <string id="Device update complete.">Aggiornamento periferica completato.</string>
  <string id="Device update started...">Aggiornamento periferica avviato...</string>    
  <string id="DeviceGroup">Gruppo periferiche</string>
  <string id="Devices">Periferiche</string>
  <string id="Directory">Directory</string>
  <string id="Directory Path">Percorso directory</string>
  <string id="Directory path*">Percorso directory*</string>
  <string id="Directory Watcher">Sentinella directory</string>
  <string id='Directory Watcher information'>Immettere Watcher directory</string>
  <string id="Disabled">Disabilitato</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Disconnesso dal VM di destinazione, indirizzo: 127.0.0.1:60902, trasporto: socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Disconnesso dal VM di destinazione, indirizzo: 127.0.0.1:61015, trasporto: socket</string>
  <string id="Discover">Ricerca</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Rileva periferiche per determinati gruppi di periferiche usando i profili di rilevamento di ciascun gruppo.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Rileva periferiche per questo gruppo di periferiche usando i suoi profili di rilevamento.</string>
  <string id="Discover Missing">Rileva mancante</string>
  <string id="Discover new devices only">Rileva solo nuove periferiche</string>
  <string id="Discover Unlicensed">Rileva senza licenza</string>
  <string id="Discover...">Rileva...</string>
  <string id="Discovered">Rilevata</string>
  <string id="Discovered Devices">Periferiche rilevate</string>
  <string id="Discovered Devices:">Periferiche rilevate:</string>
  <string id="Discovery">Rilevamento</string>
  <string id="Discovery has Completed for...">Rilevamento completato per...</string>
  <string id="Discovery in Progress for...">Rilevamento in corso per...</string>
  <string id="Discovery Profile created."> Profilo di ricerca creato.</string>
  <string id="Discovery Profiles">Profili di rilevamento</string>
  <string id="Discovery Profiles:"> Profili di ricerca:</string>
  <string id="Display Text">Testo visualizzato</string>
  <string id="Display Text:">Testo visualizzato:</string>
  <string id="Documentation">Documentazione</string>
  <string id="Done">Fine</string>
  <string id="Done generating the jobs report for downloading."> Generazione rapporto dei processi per il download terminata.</string>
  <string id="Done generating the logs report for downloading."> Generazione rapporto dei registri per il download terminata.</string>
  <string id="Down icon">Icona giù</string>
  <string id="Down icon:">Icona giù:</string>
  <string id='Download Details'>Dettagli download</string>
  <string id="Duplex :">Fronte/retro:</string>
  <string id="Edit">Modifica</string>
  <string id="Edit a solution"> Modifica una soluzione</string>
  <string id="Edit a solution to deploy"> Modifica una soluzione da distribuire</string>
  <string id="Edit the information about the report :">Modifica informazioni sul rapporto:</string>
  <string id="Edit the report settings"> Modifica le impostazioni del rapporto</string>
  <string id="Edit...">Modifica...</string>
  <string id="EForms">Moduli elettronici</string>
  <string id="E-Forms">Moduli elettronici</string>
  <string id="EForms:">Moduli elettronici:</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank."> I campi di data e ora di inizio devono essere compilati o devono essere entrambi vuoti.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank."> I campi di data e ora di fine devono essere compilati o devono essere entrambi vuoti.</string>
  <string id="Email">E-Mail</string>
  <string id="Email + Profile">E-mail + Profilo</string>
  <string id="Email Shortcuts">Scelte rapide e-mail</string>
  <string id="Email the Report"> Invia tramite e-mail il rapporto</string>
  <string id="Email To">E-mail a</string>
  <string id="Enable Fax Forwarding.">Abilita inoltro di fax.</string>
  <string id="Enable LDAP Authentication.">Abilita autenticazione LDAP.</string>
  <string id="Enabled for Credentials">Abilitato per credenziali</string>
  <string id="Enabled for Session">Abilitato per sessione</string>
  <string id="End Time"> Ora di fine</string>
  <string id="End Time:">Ora di fine:</string>
  <string id="Enter a unique group name">Immettere un nome del gruppo univoco</string>
  <string id="Enter a unique name for this group">Immettere un nome univoco per questo gruppo</string>
  <string id="Enter appropriate fields and click the Add button:">Immettere i campi appropriati e fare clic sul pulsante Aggiungi:</string>
  <string id="Enter appropriate fields and click the Save button:"> Immettere i campi appropriati e fare clic sul pulsante Salva:</string>
  <string id="Enter the appropriate fields and click the Add button:"> Immettere i campi appropriati e fare clic sul pulsante Aggiungi:</string>
  <string id="Enter the information about the new report :">Immettere le informazioni sul nuovo rapporto:</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Immettere i valori di timeout in millisecondi, separati da un spazio tra ciascun tentativo.</string>
  <string id="Error"> Errore</string>
  <string id="Error importing license."> Errore nell'importazione della licenza.</string>
  <string id="Error in changing name."> Errore di modifica del nome.</string>
  <string id="Error in creating device group..."> Errore di creazione del gruppo di periferiche...</string>
  <string id="Error in creating software client group..."> Errore di creazione del gruppo di client software...</string>
  <string id="Error in deleting device group."> Errore di eliminazione del gruppo di periferiche.</string>
  <string id="Error in deleting software client group."> Errore di eliminazione del gruppo di client software.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details."> Errore di eliminazione dei formset. Verificare il registro per ulteriori dettagli.</string>
  <string id="Error in generating the report."> Errore durante la generazione del rapporto.</string>
  <string id="Error in saving Ldap settings."> Errore di salvataggio delle impostazioni LDAP.</string>
  <string id="Error in saving settings."> Errore di salvataggio delle impostazioni.</string>
  <string id="Error in updating password."> Errore di aggiornamento della password.</string>
  <string id="Error in updating security settings."> Errore di aggiornamento delle impostazioni di protezione.</string>
  <string id="Error in updating service settings."> Errore di aggiornamento delle impostazioni del servizio.</string>
  <string id="Error in updating solution settings."> Errore di aggiornamento delle impostazioni della soluzione.</string>
  <string id="Error while deploying home screen to"> Errore di distribuzione della schermata iniziale a</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Valuta in +app_url}</string>
  <string id="Evaluate in remote app">Valuta in app remota</string>
  <string id="Every">Ogni</string>
  <string id="Expiration Date">Data di scadenza</string>
  <string id="Expired Formset">Formset scaduto</string>
  <string id="Expired!"> Scaduto.</string>
  <string id="Expires on:">Scade il:</string>
  <string id="Export Report">Esporta rapporto</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">Non riuscito</string>
  <string id="FALSE">FALSO</string>
  <string id="Fax">Fax</string>
  <string id="Fax + Profile">Fax + Profilo</string>
  <string id="Fax Forward settings updated."> Impostazioni inoltro fax aggiornate.</string>
  <string id="Fax Forwarding">Inoltro fax</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax"> Scelta rapida di destinazione inoltro fax: (E-mail, FTP, Fax </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Scelta rapida di destinazione inoltro fax: (E-mail, FTP, Fax)</string>
  <string id="Fax Forwarding Destination:">Destinazione inoltro fax:</string>
  <string id="Fax Forwarding LDSS Script:"> Script LDSS inoltro fax:</string>
  <string id="Fax Forwarding Receive Mode:">Modalità ricezione inoltro fax:</string>
  <string id="Fax Shortcuts">Scelte rapide fax</string>
  <string id="Feature Id">ID funzione</string>
  <string id="Filter">Filtro</string>
  <string id="Filters..."> Filtri...</string>
  <string id="Finish">Fine</string>
  <string id="Finished AP Bundle Descriptor File"> File descrittore bundle Richieste avanzate terminato</string>
  <string id="Finished AP Bundle Flash File"> File flash bundle Richieste avanzate terminato</string>
  <string id="Finished upload of key.pem File."> Caricamento del file key.pem terminato.</string>
  <string id="First">Primo</string>
  <string id="Form field must be a single word or valid email address.">Il campo del modulo deve essere ununica parola o un indirizzo e-mail valido.</string>
  <string id="Form Printers">Stampanti per moduli</string>
  <string id="Format :">Formato:</string>
  <string id="Forms">Moduli</string>
  <string id="Forms Printer is unlicensed">Stampante per moduli senza licenza</string>
  <string id="Forms printer successfully created or updated."> Creazione o aggiornamento della Forms Printer completato.</string>
  <string id="Forms printer successfully deleted."> Eliminazione della Forms Printer completata.</string>
  <string id="Formsets">Formset</string>
  <string id="FormsetsSubforms"> Formset/Sottomoduli</string>
  <string id="Forward Only">Solo inoltro</string>
  <string id="Fourth">Quarto</string>
  <string id="FRAMEWORK">FRAMEWORK</string>
  <string id="Fri">Ven</string>
  <string id="From:">Da:</string>
  <string id="Ftp"> FTP</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + Profilo</string>
  <string id="Ftp Shortcuts">Scelte rapide FTP</string>
  <string id="Generating logs report for downloading..."> Generazione rapporto dei registri per il download in corso...</string>
  <string id="Generating Report">Generazione rapporto in corso</string>
  <string id="Generating Report..."> Generazione rapporto in corso...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">La generazione di rapporti durante il regolare orario di ufficio può influire negativamente sulle prestazioni del sistema. La generazione di rapporti è consigliata negli orari di chiusura.</string>
  <string id="Generating the jobs report for downloading..."> Generazione rapporto dei processi per il download in corso...</string>
  <string id="Graphic">Grafica</string>
  <string id="Graphic:"> Grafica:</string>
  <string id="Group Description placeholder">Segnaposto descrizione gruppo</string>
  <string id="Group Identifier:"> Identificatore gruppo:</string>
  <string id="Group Names from LDAP">Nomi gruppi da LDAP</string>
  <string id="Group Names from LDAP:"> Nomi gruppi da LDAP:</string>
  <string id="Group search base must be set for adding group based"> La base di ricerca del gruppo deve essere impostata per aggiungere gruppi basati </string>
  <string id="Group search base must be set in">La base di ricerca del gruppo deve essere impostata in</string>
  <string id="Group Search Base:"> Base di ricerca gruppo:</string>
  <string id="Group Search Filter:"> Filtro di ricerca gruppo:</string>
  <string id="Group Search Identifier:"> Identificatore di ricerca gruppo:</string>
  <string id="Groups">Gruppi</string>
  <string id="Held Jobs">Processi in attesa</string>
  <string id="Hide Settings">Nascondi impostazioni</string>
  <string id="Home">Pagina iniziale</string>
  <string id="Home Screen">Schermata iniziale</string>
  <string id="Home screen deployed to"> Schermata iniziale distribuita in</string>
  <string id="Home Screens"> Schermate principali</string>
  <string id="Home Tab"> Scheda principale</string>
  <string id="Hostname">Nome dellhost</string>
  <string id="Hostname:"> Nome host:</string>
  <string id="Id"> ID</string>
  <string id="IDR License Summary">Riepilogo licenza IDR</string>
  <string id="IDR License Summary:"> Riepilogo licenza IDR:</string>
  <string id="Images"> Immagini</string>
  <string id="Import">Importa</string>
  <string id="Import..."> Importa...</string>
  <string id="Importing AP Bundle Descriptor File..."> Importazione file descrittore bundle Richieste avanzate in corso...</string>
  <string id="Importing AP Bundle Flash File..."> Importazione file flash bundle Richieste avanzate in corso...</string>
  <string id='Importing Binary String...'>Importazione stringa binaria...</string>  
  <string id="Importing CaCert pem File..."> Importazione file pem CaCert in corso...</string>
  <string id="Importing license..."> Importazione licenza in corso...</string>
  <string id="Importing software client group profile..."> Importazione profilo del gruppo di client software in corso...</string>
  <string id="Importing Solution(s)..."> Importazione di soluzioni in corso...</string>  
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Inserisci - Questo inserisce il pulsante di taglio e spinge verso il basso i pulsanti rimanenti</string>
  <string id="Install Time">Ora installazione</string>
  <string id="Install Time:"> Ora installazione:</string>
  <string id="Install-Upgrade"> Installa/Aggiorna</string>
  <string id="It is recommended to run reports during off hours."> La generazione di rapporti è consigliata negli orari di chiusura.</string>
  <string id="Items">Elementi</string>
  <string id="Jasper Report File Name:">Nome file rapporto Jasper:</string>
  <string id="Job State">Stato processo</string>
  <string id="Job State:"> Stato processo:</string>
  <string id="Jobs">Processi</string>
  <string id="Jobs by user">Processi per utente</string>
  <string id="Jobs Filters Table"> Tabella filtri processi</string>
  <string id="Jobs Report">Rapporto dei processi</string>
  <string id="Jobs Report - CSV"> Rapporto dei processi - CSV</string>
  <string id="Keep previous backups">Conserva backup precedenti</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>Lingua:</string>
  <string id="Last">Ultimo</string>
  <string id="Last 12 Hours">Ultime 12 ore</string>
  <string id="Last 15 Minutes">Ultimi 15 minuti</string>
  <string id="Last 24 Hours">Ultime 24 ore</string>
  <string id="Last 3 Hours">Ultime 3 ore</string>
  <string id="Last 30 Days">Ultimi 30 giorni</string>
  <string id="Last 30 Minutes">Ultimi 30 minuti</string>
  <string id="Last 6 Hours">Ultime 6 ore</string>
  <string id="Last 7 Days">Ultimi 7 giorni</string>
  <string id="Last Discovered">Ultima rilevazione</string>
  <string id="Last Discovered:"> Ultima rilevazione:</string>
  <string id="Last Hour">Ultima ora</string>
  <string id="Last Kranked">Last Kranked</string>
  <string id="Last Modified"> Ultima modifica</string>
  <string id="Layout">Layout</string>
  <string id="Layout:"> Layout:</string>
  <string id="LDAP Server Settings:"> Impostazioni server LDAP:</string>
  <string id="Ldap Settings Saved."> Impostazioni LDAP salvate.</string>
  <string id="LDAP Setup">Configurazione LDAP</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Gestione della stampa Lexmark</string>
  <string id="License">Licenza</string>
  <string id="LICENSE">LICENZA</string>
  <string id="License Files"> File di licenze</string>
  <string id="License Type">Tipo licenza</string>
  <string id="License Upload Results."> Risultati caricamento licenza.</string>
  <string id="License Upload Results:"> Risultati caricamento licenza:</string>
  <string id="Licensed">Con licenza</string>
  <string id="Licenses">Licenze</string>
  <string id="Licenses in Use">Licenze in uso</string>
  <string id="Limit batch size">Limita dimensione batch</string>
  <string id="Line Chart with Time Period Slider.">Grafico a linea con scorrimento periodo di tempo.</string>
  <string id="LOADING">CARICAMENTO IN CORSO</string>
  <string id="Loading..."> Caricamento in corso...</string>
  <string id="LOADING..."> CARICAMENTO IN CORSO...</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>Nome host qualificato O indirizzo IP bilanciamento carico</string>
  <string id="Lock Device">Blocca periferica</string>
  <string id="Log">Registro</string>
  <string id="Log Report - CSV"> Rapporto registri - CSV</string>
  <string id="Log Report - Failed Jobs"> Rapporto registri - Processi non riusciti</string>
  <string id="Log State">Stato registro</string>
  <string id="Log State:"> Stato registro:</string>
  <string id="Logging In">Accesso in corso</string>
  <string id="Login">Accesso</string>
  <string id="Logout"> Disconnetti</string>
  <string id="Logs Filters Table"> Tabella filtri registri</string>
  <string id='Max:'>Max:</string>
  <string id="Member of Group(s):"> Membro dei gruppi:</string>
  <string id="Memory Usage"> Uso memoria</string>
  <string id="Message">Messaggio</string>
  <string id="Message:"> Messaggio:</string>
  <string id="Messages">Messaggi</string>
  <string id='Min:'>Min:</string>
  <string id='Minimum length:'>Lunghezza minima:</string>
  <string id='Minimum:'>Minimo:</string>  
  <string id="Missing">Mancante</string>
  <string id="Missing Device">Periferica mancante</string>
  <string id="Missing Devices">Periferiche mancanti</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Le periferiche mancanti sono periferiche precedentemente rilevate che, durante il rilevamento più recente, non sono state trovate (ad es. se disconnesse dalla rete).</string>
  <string id="Missing devices:"> Periferiche mancanti:</string>
  <string id="Missing Devices:"> Periferiche mancanti:</string>
  <string id="Model">Modello</string>
  <string id="Model:"> Modello:</string>
  <string id="Mon">Lun</string>
  <string id="MONITOR">MONITOR</string>
  <string id="Move Down">Sposta in basso</string>
  <string id="Move Up">Sposta in alto</string>
  <string id="Name">Nome</string>
  <string id="Name :"> Nome:</string>
  <string id="Name changed."> Nome modificato.</string>
  <string id="Name:"> Nome:</string>
  <string id="Network Load"> Carico di rete</string>
  <string id="Network share password">Password condivisione di rete</string>
  <string id="Network share user name">Nome utente condivisione di rete</string>
  <string id="New Password:"> Nuova password:</string>
  <string id="New Username:"> Nuovo nome utente:</string>
  <string id="Next">Avanti</string>
  <string id="No">No</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>Nessuna app cSF per questo gruppo di periferiche. Prima di poter associare questa azione al pulsante, è necessario avere almeno un'app cSF.</string>
  <string id="No devices are currently Out of Policy for the system.">Nessuna periferica attualmente fuori criterio per il sistema.</string>
  <string id="No devices are currently Out of Policy for this device group.">Nessuna periferica attualmente fuori criterio per questo gruppo di periferiche.</string>
  <string id="No home screen is configured for this device type."> Nessuna schermata iniziale configurata per questo tipo di periferica.</string>
  <string id="No matches found"> Nessun risultato trovato</string>
  <string id='No Privilege'>Nessun privilegio</string>
  <string id="No Privilege Alert"> Nessun avviso privilegi</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated."> Per questo gruppo di periferiche non esiste nessun profilo in quanto non è stato associata alcuna applicazione con profilo.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button."> Nessun profilo esistente per questo gruppo di periferiche. Prima di poter associare questa azione al pulsante, è necessario avere almeno un profilo.</string>
  <string id="No records match the selected filter criteria."> Nessun documento corrisponde ai criteri del filtro selezionati.</string>
  <string id="No records matched the filter criteria."> Nessun documento corrisponde ai criteri del filtro.</string>
  <string id="No schedulable scripts are available.">Nessuno script pianificabile disponibile.</string>
  <string id="No UCF File selected">Nessun file di configurazione protezione selezionato</string>
  <string id="None">Nessuno</string>
  <string id="None of the selected devices are missing."> Nessuna delle periferiche selezionate è mancante.</string>
  <string id="None of the selected devices are unlicensed."> Nessuna delle periferiche selezionate è senza licenza.</string>
  <string id="Number of Jobs per Page"> Numero di processi per pagina</string>
  <string id="Number of Licenses">Numero di licenze</string>
  <string id="Number of Logs per Page"> Numero di registri per pagina</string>
  <string id="Off">Disattivato</string>
  <string id="OK">OK</string>
  <string id="Once">Una volta</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">Uno o più pulsanti nella configurazione attuale non sono validi. &lt;font color="#ff0000"&gt;(mostrato in rosso)&lt;/font&gt; Verificare che tutti i pulsanti siano validi.</string>
  <string id="One or more tests did not pass.">Uno o più test con errori.</string>
  <string id="Only"> Solo</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes."> È possibile eseguire un rilevamento alla volta. Al termine di quello in corso sarà possibile eseguire un nuovo rilevamento.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">È possibile aggiornare criteri alla volta.  Al termine di quello in corso sarà possibile eseguire un nuovo aggiornamento criteri.</string>
  <string id="Only update those devices which are Out of Policy">Aggiornare queste periferiche che sono fuori criterio</string>
  <string id="Orientation :">Orientamento:</string>
  <string id="Out of Policy">Fuori criterio</string>
  <string id="Out of Policy Device">Periferica fuori criterio</string>
  <string id="Out of Policy Devices">Periferiche fuori criterio</string>
  <string id="Out of Policy Devices:">Periferiche fuori criterio:</string>
  <string id="Output Format">Formato di stampa</string>
  <string id="Overwrite if file already exists">Sovrascrive se il file esiste già</string>
  <string id="Page 1"> Pagina 1</string>
  <string id="Page 2"> Pagina 2</string>
  <string id="Page 3"> Pagina 3</string>
  <string id="Page 4"> Pagina 4</string>
  <string id="Paper Size :">Formato carta:</string>
  <string id="Parameters">Parametri</string>
  <string id="Password Changed Successfully."> Modifica password completata.</string>
  <string id="Password updated."> Password aggiornata.</string>
  <string id="Password*">Password*</string>
  <string id="Password:">Password:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Esegui aggiornamento criteri per determinati gruppi di periferiche usando i criteri di ciascun gruppo.</string>
  <string id="Perform a Policy Update for selected devices.">Esegui aggiornamento criteri per le periferiche selezionate.</string>
  <string id="Perform a Policy Update for this device group.">Esegui aggiornamento criteri per questo gruppo di periferiche.</string>
  <string id="Placeholder">Segnaposto</string>
  <string id="Please choose a filter:">Scegliere un filtro:</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Scegliere un tipo di gruppo per accedere alle impostazioni della soluzione locale nello script pianificato:</string>
  <string id="Please choose a script:">Scegliere uno script:</string>
  <string id="Please choose a task to schedule :">Selezionare unattività da pianificare:</string>
  <string id="Please choose an action:">Scegliere unazione:</string>
  <string id="Please choose client groups to schedule :">Selezionare i gruppi client da pianificare:</string>
  <string id="Please choose device groups to schedule :">Selezionare i gruppi di periferiche da pianificare:</string>
  <string id="Please choose one of the following options:">Scegliere una delle seguenti opzioni:</string>
  <string id="Please choose solution and script :">Scegliere soluzione e script:</string>
  <string id="Please choose solution and script to schedule :">Scegliere soluzione e script da pianificare:</string>
  <string id="Please choose start time and frequency :">Scegliere ora di inizio e frequenza:</string>
  <string id="Please choose the datasource for the new report."> Scegliere la datasource per il nuovo rapporto.</string>
  <string id="Please choose the jasper filename for the new report."> Scegliere il nome file jasper per il nuovo rapporto.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed."> Scegliere il nome file jasper per il nuovo rapporto.  Caricare il rapporto jasper se non è già presente nell'elenco.</string>
  <string id="Please choose the output format for the new report."> Scegliere il formato di output per il nuovo rapporto.</string>
  <string id="Please choose the report to schedule :">Selezionare il rapporto da pianificare:</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Per informazioni sulla licenza del client software, contattare Lexmark.</string>
  <string id="Please enter a non-expired date"> Immettere una data che non sia scaduta (gg/mm/aaaa).</string>
  <string id="Please enter a valid Address."> Immettere un indirizzo valido.</string>
  <string id="Please enter a valid date"> Immettere una data valida (gg/mm/aaaa).</string>
  <string id="Please enter a valid End From Time"> Immettere un'ora di fine da valida (OO.MM AM/PM).</string>
  <string id="Please enter a valid End To Time"> Immettere un'ora di fine a valida (OO.MM AM/PM).</string>
  <string id="Please enter a valid From date"> Immettere una data da valida (gg/mm/aaaa).</string>
  <string id="Please enter a valid From time"> Immettere un'ora da valida (oo.mm AM/PM).</string>
  <string id='Please enter a valid range:'>Immettere un intervallo valido:</string>
  <string id="Please enter a valid range: 1 - 12"> Immettere un intervallo valido: 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23"> Immettere un intervallo valido: 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59"> Immettere un intervallo valido: 1 - 59</string>
  <string id="Please enter a valid Start From Time"> Immettere un'ora di inizio da valida (OO.MM AM/PM).</string>
  <string id="Please enter a valid Start To Time"> Immettere un'ora di inizio a valida (OO.MM AM/PM).</string>
  <string id="Please enter a valid time"> Immettere un'ora valida (OO.MM AM/PM)</string>
  <string id="Please enter a valid To date"> Immettere una data a valida (gg/mm/aaaa).</string>
  <string id="Please enter a valid To time"> Immettere un'ora a valida (oo.mm AM/PM).</string>
  <string id="Please enter the Database driver and URL for the external database."> Immettere il driver del database e l'URL del database esterno.</string>
  <string id="Please enter the Directory information:">Immettere le informazioni della Directory:</string>
  <string id="Please enter the location where you want the report to be saved."> Immettere il percorso in cui salvare il rapporto.</string>
  <string id="Please enter the name of the new report."> Immettere il nome del nuovo rapporto.</string>
  <string id="Please enter the network share user name and password."> Immettere il nome utente e la password della condivisione di rete.</string>
  <string id="Please enter the recipients to whom the report will be emailed."> Immettere i destinatari a cui inviare tramite e-mail il rapporto.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :"> Immettere le informazioni richieste per backup e ripristino:</string>
  <string id="Please make sure that all the necessary fields are filled in."> Verificare che tutti i campi richiesti siano compilati.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces."> Assicurarsi che l'espressione cron abbia 6 o 7 opzioni separate da spazi.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both."> Assicurarsi che l'espressione cron abbia "?" nella quarta o sesta posizione ma non in entrambe.</string>
  <string id="Please select a file to upload.">Selezionare un file da caricare.</string>
  <string id="Please select a group on the left to modify its task privileges.">Selezionare un gruppo a sinistra per modificarne i privilegi di attività.</string>
  <string id="Please select a group to save privileges for."> Selezionare un gruppo per cui salvare i privilegi.</string>
  <string id="Please select a profile to view its settings.">Selezionare un profilo per visualizzarne le impostazioni.</string>
  <string id="Please select the Group to delete."> Selezionare il gruppo da eliminare.</string>
  <string id="Please select the report to delete."> Selezionare il rapporto da eliminare.</string>
  <string id="Please select the report to edit."> Selezionare il rapporto da modificare.</string>
  <string id="Please select the report to run."> Selezionare il rapporto da eseguire.</string>
  <string id="Please specify a port:">Specificare una porta:</string>
  <string id="Please Verify MinMax, Length and Required Settings."> Verificare impostazioni minime/massime, lunghezza e obbligatorie.</string>
  <string id="Policy Last Applied">Ultima applicazione criterio</string>
  <string id="Policy Update">Aggiornamento criteri</string>
  <string id="Policy Update has Completed for...">Aggiornamento criteri completato per...</string>
  <string id="Policy Update in Progress for...">Aggiornamento criteri in corso per...</string>
  <string id="Policy Update on all effected Device Groups.">Aggiornamento criteri su tutti i gruppi di periferiche affetti.</string>
  <string id="Port">Porta</string>
  <string id="Port:">Porta:</string>
  <string id="Present">Corrente</string>
  <string id="Previous">Indietro</string>
  <string id="Print (Default)">Stampa (predefinito)</string>
  <string id="Print and Forward">Stampa e inoltra</string>
  <string id="Printer Panel">Pannello stampante</string>
  <string id="Printer Report"> Rapporto stampante</string>
  <string id="Privileges">Privilegi</string>
  <string id="Process finished with exit code 0">Termine del processo con codice di uscita 0</string>
  <string id="Profile Filters"> Filtri profili</string>
  <string id="Profile:"> Profilo:</string>
  <string id="Profiles">Profili</string>
  <string id="Profiles :"> Profili:</string>
  <string id="Profiles:"> Profili:</string>
  <string id="Progress %">% avanzamento</string>
  <string id="Property Tag">Etichetta di proprietà</string>
  <string id="Property Tag:"> Etichetta proprietà:</string>
  <string id="Quality :">Qualità:</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">Ripetizione</string>
  <string id="Refresh">Aggiorna</string>
  <string id="Refresh Defaults">Aggiorna impostazioni predefinite</string>
  <string id="Regular Expression">Espressione regolare</string>
  <string id="Release Held Faxes">Rilascia fax in attesa</string>
  <string id="Remove">Rimuovi</string>
  <string id="Remove All">Rimuovi tutto</string>
  <string id="Remove from System">Rimuovi da sistema</string>
  <string id="Remove Server(s)">Rimuovi server</string>
  <string id="RemoveAll">Rimuovi tutto</string>
  <string id="Removing selected servers..."> Rimozione server selezionati in corso...</string>
  <string id="Repeat this event :">Ripeti questo evento:</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Sostituisci - Questo elimina il pulsante selezionato e lo sostituisce con quello di taglio.</string>
  <string id="Replace Me">Sostituiscimi</string>
  <string id="Report">Rapporto</string>
  <string id="Report by Time"> Rapporto per tempo</string>
  <string id="Report Files"> File rapporti</string>
  <string id="Report From">Rapporto da</string>
  <string id="Report Name:">Nome rapporto:</string>
  <string id="Report Parameters:">Parametri rapporto:</string>
  <string id="Report To">Rapporto a</string>
  <string id="REPORT_NAME successfully generated"> Creazione REPORT_NAME riuscita</string>
  <string id="Reporting Period"> Periodo creazione rapporto</string>
  <string id="Reports">Rapporti</string>
  <string id="Reports:">Rapporti:</string>
  <string id="Request timed out. Please narrow your search criteria and try again."> Timeout richiesta. Restringere i criteri di ricerca e riprovare.</string>
  <string id="Required field"> Campo richiesto</string>
  <string id="Reset">Ripristina</string>
  <string id="Reset Filter">Ripristina filtri</string>
  <string id="Reset to Default">Ripristina su predefinito</string>
  <string id="Resolution :">Risoluzione:</string>
  <string id="Return to Original">Torna a originale</string>
  <string id="Retype New Password:">Ridigitare nuova password:</string>
  <string id="Retype New Username:">Ridigitare nuovo nome utente:</string>
  <string id="Run on All Servers">Esegui su tutti i server</string>
  <string id="Run Report">Esegui rapporto</string>
  <string id="Running">In esecuzione</string>
  <string id="Running Tasks">Esecuzione attività in corso</string>
  <string id="Running...">In esecuzione...</string>
  <string id="Sat">Sab</string>
  <string id="Save">Salva</string>
  <string id="Save Privileges">Salva privilegi</string>
  <string id="Save Settings">Salva impostazioni</string>
  <string id="Save To">Salva in</string>
  <string id="Saving eSF Settings..."> Salvataggio impostazioni eSF in corso...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings..."> Salvataggio impostazioni LDAP in corso...</string>
  <string id="Schedule">Programma</string>
  <string id="Scheduled task createdupdated"> Attività pianificata creata/aggiornata</string>
  <string id="Scheduled task deleted"> Attività pianificata eliminata</string>
  <string id="Scheduled tasks for all client groups:"> Attività pianificate per tutti i gruppi di client:</string>
  <string id="Scheduled tasks for all device groups:"> Attività pianificate per tutti i gruppi di periferiche:</string>
  <string id="Script">Script</string>
  <string id="Script:"> Script:</string>
  <string id="Search">Cerca</string>
  <string id="Search Base:"> Base di ricerca:</string>
  <string id="Search Held Jobs">Cerca processi in attesa</string>
  <string id="Search LDAP for Groups:">Cerca LDAP per gruppi:</string>
  <string id="Searching...">Ricerca in corso...</string>
  <string id="Second">Secondo</string>
  <string id="Secure Server Communication">Comunicazione sicura server</string>
  <string id="Secure Server Communication:"> Comunicazione sicura server:</string>
  <string id="Security">Protezione</string>
  <string id="Security setting updated."> Impostazione di protezione aggiornata.</string>
  <string id="Security setup file updated successfully">Aggiornamento file configurazione protezione riuscito</string>
  <string id="Security setup file update failed">Aggiornamento file configurazione protezione non riuscito</string>
  <string id="Select a Group Name:">Selezionare un nome di gruppo:</string>
  <string id="Select a report"> Selezionare un rapporto</string>
  <string id="Select a script task">Selezionare unattività script</string>
  <string id="Select one...">Selezionarne uno...</string>
  <string id="Select Profile...">Selezionare un profilo...</string>
  <string id="Select the group to copy">Selezionare il gruppo da copiare</string>
  <string id="Sent when any leaf is checked or unchecked, in">Inviato quando qualsiasi leaf è selezionata o deselezionata in</string>
  <string id="Serial Number">Numero di serie</string>
  <string id="Serial Number:"> Numero di serie:</string>
  <string id="Server Address">Indirizzo server</string>
  <string id="Server Address:">Indirizzo server:</string>
  <string id="Server handling this LMC session">Server che gestisce questa sessione LMC</string>
  <string id="Server is currently offline">Server attualmente fuori linea</string>
  <string id="Server is not communicating">Il server non comunica</string>
  <string id="Server is unlicensed">Server senza licenza</string>
  <string id="Server Port:"> Porta server:</string>
  <string id="Server Report"> Rapporto server</string>
  <string id="Server(s) Error"> Errore server</string>
  <string id="Server(s) Offline"> Server offline</string>
  <string id="Servers"> Server</string>
  <string id="Service settings updated"> Impostazioni servizio aggiornate</string>
  <string id="Services">Servizi</string>
  <string id="Set Offline">Imposta su fuori linea</string>
  <string id="Set Online">Imposta su in linea</string>
  <string id="Setting selected servers offline..."> Impostazione dei server selezionati su offline in corso...</string>
  <string id="Setting selected servers online..."> Impostazione dei server selezionati su online in corso...</string>
  <string id="Settings :">Impostazioni:</string>
  <string id="Settings:">Impostazioni:</string>
  <string id="SFP e-Task">SFP e‑Task</string>
  <string id="SFP e-Task home screen updated."> Schermata iniziale e-Task SFP aggiornata.</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated."> Schermata iniziale e-Task2 SFP aggiornata.</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated."> Schermata iniziale e-Task2+ SFP aggiornata.</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated."> Schermata iniziale e-Task3 SFP aggiornata.</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4 (7 poll.)</string>
  <string id="SFP e-Task4 (7in.) home screen updated."> Schermata iniziale e-Task4 (7 poll.) SFP aggiornata.</string>
  <string id="SFP e-Task4 home screen updated."> Schermata iniziale e-Task4 SFP aggiornata.</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">Scelta rapida</string>
  <string id="Shortcut :"> Scelta rapida:</string>
  <string id="Shortcut:"> Scelta rapida:</string>
  <string id="Show Settings">Mostra impostazioni</string>
  <string id="Since Last Month">Dal mese scorso</string>
  <string id="Since Yesterday">Da ieri</string>
  <string id="Single Profile">Profilo singolo</string>
  <string id="SNMP Timeout Retries:">Tentativi timeout SNMP:</string>
  <string id="Software Client Group">Gruppo di client software</string>
  <string id="Software Client Group created"> Gruppo di client software creato</string>
  <string id="Software Client Group:">Gruppo di client software:</string>
  <string id="Software Client Groups">Gruppi di client software</string>
  <string id="Software Client Report"> Rapporto client software</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">Soluzione</string>
  <string id="Solution deleted from software client group."> Soluzione eliminata da gruppo di client software.</string>
  <string id="Solution deployed to device group"> Soluzione distribuita a gruppo di periferiche</string>
  <string id="Solution deployed to software client group"> Soluzione distribuita a gruppo di client software</string>
  <string id="Solution Name">Nome soluzione</string>
  <string id="Solution Name:">Nome soluzione:</string>
  <string id="Solution Report"> Rapporto soluzioni</string>
  <string id="Solution settings updated."> Impostazioni soluzione aggiornate.</string>
  <string id="Solution: Deleting device group deployment..."> Soluzione: Eliminazione distribuzione del gruppo di periferiche in corso...</string>
  <string id="Solution: Deleting solution from software client group..."> Soluzione: Eliminazione soluzione da gruppo di client software in corso...</string>
  <string id="Solution: device group deployment deleted."> Soluzione: Distribuzione del gruppo di periferiche eliminata.</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">Soluzioni</string>
  <string id="Solutions to deploy:">Soluzioni da distribuire:</string>
  <string id="Solutions:"> Soluzioni:</string>
  <string id='Specify Restore system information'>Specificare le informazioni del sistema di ripristino</string>
  <string id="Specify where the generated report should be saved"> Specificare dove salvare il rapporto generato</string>
  <string id="Start Button Default Action">Azione predefinita pulsante avvio</string>
  <string id="Start Date :">Data di inizio:</string>
  <string id="Start Time">Ora di inizio</string>
  <string id="Start Time:"> Ora di inizio:</string>
  <string id="State">Stato</string>
  <string id="Status">Stato</string>
  <string id="Steps for viewing device information:">Passaggi per visualizzare le informazioni della periferica:</string>
  <string id="Stop">Interrompi</string>
  <string id="Stop Task">Interrompi attività</string>
  <string id="Subform"> Sottomodulo</string>
  <string id="Subject:">Oggetto:</string>
  <string id="Success">Operazione riuscita</string>
  <string id="Successfully added the group.">Aggiunta al gruppo correttamente.</string>
  <string id="Successfully Deleted All Solution(s) from the System."> Eliminazione di tutte le soluzioni dal sistema riuscita.</string>
  <string id="Successfully Deleted Solution(s) from the System."> Eliminazione soluzioni dal sistema riuscita.</string>
  <string id="Successfully Imported Solution(s) into the System."> Importazione soluzioni nel sistema riuscita.</string>
  <string id="Summary">Riepilogo</string>
  <string id="Sun">Dom</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Scambia - Questo scambia le posizioni tra il pulsante selezionato e quello di taglio.</string>
  <string id="System">Sistema</string>
  <string id="System Health...">Stato sistema...</string>
  <string id="System Status">Stato sistema</string>
  <string id="System Status 1"> Stato sistema 1</string>
  <string id="Task Id">ID attività</string>
  <string id="Task Id:"> ID attività:</string>
  <string id="Task Name">Nome attività</string>
  <string id="Task Name:"> Nome attività:</string>
  <string id="Task Summary Report"> Rapporto riepilogo attività</string>
  <string id="Test Progress">Avanzamento prova</string>
  <string id="Test Results">Risultati prova</string>
  <string id="Test Settings">Impostazioni prova</string>
  <string id="Testing LDAP Settings..."> Verifica impostazioni LDAP in corso...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner."> I pulsanti nella prima schermata possono essere disposti in modo personalizzato.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report."> Il seguente rapporto è stato creato correttamente:  REPORT_NAME.  Esaminare il rapporto allegato.</string>
  <string id="The password provided is incorrect."> La password fornita non è corretta.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">Il criterio di questo gruppo è in fase di rimozione da tutte le periferiche nel gruppo.</string>
  <string id="The report is now ready for downloading. Please click OK to continue."> Il rapporto può essere scaricato. Fare clic su OK per continuare.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?"> La data di fine per il periodo di creazione del rapporto è precedente della data di inizio.  Il sistema le scambierà automaticamente durante la generazione del rapporto.  Continuare?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above."> Nessun profilo client per questo gruppo di client software. Aggiungerli compilando i campi sopra.</string>
  <string id="There are currently no cSF Apps associated with this device group."> Nessuna app cSF attualmente associata a questo gruppo di periferiche.</string>
  <string id="There are currently no cSF Apps to add to this device group."> Nessuna app cSF attualmente da aggiungere a questo gruppo di periferiche.</string>
  <string id="There are currently no device groups to perform discovery."> Attualmente non è presente nessun gruppo di periferiche in cui eseguire il rilevamento.</string>
  <string id='There are currently no device groups to perform policy update.'>Attualmente non è presente nessun gruppo di periferiche in cui eseguire l'aggiornamento dei criteri.</string>
  <string id="There are currently no device groups to schedule."> Attualmente non è presente nessun gruppo di periferiche da pianificare.</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>Al momento non ci sono gruppi di periferiche.  Aggiungere un gruppo di periferiche facendo clic sul pulsante Aggiungi a sinistra.</string>
  <string id="There are currently no devices discovered for this device group."> Nessuna periferica attualmente rilevata per questo gruppo di periferiche.</string>
  <string id="There are currently no devices in this device group.">Nessuna periferica attualmente in questo gruppo di periferiche.</string>
  <string id="There are currently no discovered devices.">Al momento non ci sono periferiche rilevate.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above."> Attualmente non è presente nessun profilo di rilevamento per questo gruppo di periferiche. Aggiungerli compilando i campi appropriati sopra.</string>
  <string id="There are currently no forms printers in the system."> Attualmente non è presente nessuna Forms Printer nel sistema.</string>
  <string id="There are currently no licenses installed.">Al momento non ci sono licenze installate.</string>
  <string id="There are currently no licensing changes made by this upload."> Attualmente non è presente nessuna modifica alle licenze create da questo caricamento.</string>
  <string id="There are currently no missing devices for this device group."> Nessuna periferica attualmente mancante per questo gruppo di periferiche.</string>
  <string id="There are currently no missing devices."> Al momento non ci sono periferiche mancanti.</string>
  <string id="There are currently no out of policy devices for this device group."> Nessuna periferica attualmente senza criteri per questo gruppo di periferiche.</string>
  <string id="There are currently no out of policy devices."> Al momento non ci sono periferiche senza criteri.</string>
  <string id="There are currently no scheduled tasks"> Al momento non ci sono attività pianificate</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left."> Attualmente non è presente nessun gruppo di client software.  Aggiungere un gruppo facendo clic sul pulsante Aggiungi a sinistra.</string>
  <string id="There are currently no solutions associated with this device group."> Nessuna soluzione attualmente associata a questo gruppo di periferiche.</string>
  <string id="There are currently no solutions associated with this software client group."> Nessuna soluzione attualmente associata a questo gruppo di client software.</string>
  <string id="There are currently no solutions installed."> Al momento non ci sono soluzioni installate.</string>
  <string id='There are currently no solutions to add to this device group.'>Nessuna soluzione attualmente da aggiungere a questo gruppo di periferiche.</string>
  <string id="There are currently no solutions to add to this software client group."> Nessuna soluzione attualmente da aggiungere a questo gruppo di client software.</string>
  <string id="There are currently no unlicensed devices for this device group."> Attualmente non è presente nessuna periferica senza licenza per questo gruppo di periferiche.</string>
  <string id="There are currently no unlicensed devices in this device group.">Nessuna periferica senza licenza attualmente in questo gruppo di periferiche.</string>
  <string id="There are currently no unlicensed devices.">Al momento non ci sono periferiche senza licenza.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes."> Al momento a questo criterio del gruppo sono associate soluzioni o app cSF e/o schermate iniziali. Rimuovere questo criterio ora? Notare che il gruppo di periferiche non verrà eliminato immediatamente. Rimuovere questo gruppo di periferiche al termine dell'aggiornamento dei criteri.</string>
  <string id="There are no associated UCF Files for this Solution.">Nessun file di configurazione protezione associato a questa soluzione.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">Nessun file di configurazione protezione associato per le soluzioni in questo gruppo di periferiche.</string>
  <string id="There are no configuration settings for this eSF application.">Nessuna impostazione di configurazione per questa applicazione eSF.</string>
  <string id="There are no configuration settings in this solution.">Nessuna impostazione di configurazione in questa applicazione.</string>
  <string id="There are no configuration settings in this webapp.">Nessuna impostazione di configurazione in questa webapp.</string>
  <string id="There are no cSF Apps installed currently."> Al momento non ci sono app cSF installate.</string>
  <string id="There are no deployments setting for this solution.">Nessuna impostazione di distribuzione per questa applicazione.</string>
  <string id="There are no devices in the system that match the filter."> Non sono presenti periferiche nel sistema che corrispondono al filtro.</string>
  <string id="There are no eSF Applications for this solution."> Nessuna applicazione eSF per questa soluzione.</string>
  <string id="There are no e-Task profiles for this device group."> Nessun profilo e-Task per questo gruppo di periferiche.</string>
  <string id="There are no e-Task2 profiles for this device group."> Nessun profilo e-Task2 per questo gruppo di periferiche.</string>
  <string id="There are no forms for this solution."> Nessuna modulo per questa soluzione.</string>
  <string id="There are no forms in the system."> Nessuna modulo nel sistema.</string>
  <string id="There are no parameters in this service.">Nessun parametro per questo servizio.</string>
  <string id="There are no profiles for this software client group."> Nessun profilo per questo gruppo di client software.</string>
  <string id="There are no settings for this action.">Nessuna impostazione per questa azione.</string>
  <string id="There are no settings for this solution.">Nessuna impostazione per questa soluzione.</string>
  <string id="There is currently a Policy Update running...">Aggiornamento criteri in esecuzione...</string>
  <string id="There is currently no Version Info."> Nessuna informazione sulla versione presente.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">Queste applicazioni eSF fanno parte della soluzione associata a questo gruppo di periferiche. Selezionare unapplicazione per visualizzarne le impostazioni.</string>
  <string id="These group settings are currently hidden.">Le impostazioni di questo gruppo sono attualmente nascoste.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">Questi profili fanno parte del criterio di gruppo per ciascun modello. Selezionare un profilo per ciascun modello per visualizzarne le impostazioni.</string>
  <string id="Third">Terzo</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?"> Questo collegamento porta all'interfaccia utente di Webkit Configuration Lexmark. Continuare?</string>
  <string id="This Month">Questo mese</string>
  <string id="This name has been given to another device group. Please choose a different name.">Questo nome è stato assegnato a un altro gruppo di periferiche. Scegliere un nome diverso.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">Questo nome è stato assegnato a un altro gruppo client software. Scegliere un nome diverso.</string>
  <string id="Thread Count"> Totale thread</string>
  <string id="Thu">Gio</string>
  <string id="Time">volta</string>
  <string id="Time of Next Run">Ora prossima esecuzione</string>
  <string id="Time Policies Last Applied">Ora ultima applicazione criteri</string>
  <string id="Time:">Ora:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles."> Per aggiungerli alla schermata iniziare, scegliere il layout personalizzato dalla casella a discesa sopra e aggiungere i profili.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box."> Per disporli, scegliere uno dei layout dalla casella a discesa sopra.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box."> Per configurarne uno, scegliere uno dei layout dalla casella a discesa sopra.</string>
  <string id="To:">A:</string>
  <string id="Today">Oggi</string>
  <string id="Today date"> Data odierna</string>
  <string id="Tops Report"> Rapporto principale</string>
  <string id="Tue">Mar</string>
  <string id="UCF">File di configurazione protezione</string>
  <string id="UCF:">File di configurazione protezione:</string>      
  <string id="Unable to Change Password."> Impossibile modificare la password.</string>
  <string id="Unable to Change Username."> Impossibile modificare il nome utente.</string>
  <string id="Unable to validate all settings!"> Impossibile convalidare tutte le impostazioni.</string>
  <string id="Uncounted"> Non conteggiato</string>
  <string id="Un-deploying all cSF Apps(s)..."> Annullamento distribuzione di tutte le app cSF in corso...</string>
  <string id="Un-deploying cSF App(s)..."> Annullamento distribuzione delle app cSF in corso...</string>
  <string id="Unknown"> Sconosciuto</string>
  <string id="Unknown Error Occured! Please Check System Log"> Si è verificato un errore sconosciuto. Controllare il registro di sistema</string>
  <string id='Unknown Secure State'>Stato sicuro sconosciuto</string>
  <string id="Unlicensed">Senza licenza</string>
  <string id="Unlicensed Device">Periferica senza licenza</string>
  <string id="Unlicensed Devices">Periferiche senza licenza</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Le periferiche senza licenza sono periferiche precedentemente rilevate alle quali, durante il rilevamento più recente, non è stato possibile assegnare una licenza. (es. a causa di una licenza scaduta o tutte le licenze in uso).</string>
  <string id="Unlicensed devices:">Periferiche senza licenza:</string>
  <string id="Unlicensed Devices:"> Periferiche senza licenza:</string>
  <string id="Unlicensed:">Senza licenza:</string>
  <string id="Unlimited"> Illimitata</string>
  <string id="Up icon:">Icona su:</string>
  <string id="Update"> Aggiorna</string>
  <string id="Update Policy">Aggiorna criterio</string>
  <string id="Update Time"> Ora aggiornamento</string>
  <string id="Update Time:">Ora aggiornamento:</string>
  <string id="Updating client profile..."> Aggiornamento profilo client in corso...</string>
  <string id="Updating discovery profile..."> Aggiornamento profilo di ricerca in corso...</string>
  <string id="Updating e-Task home screen..."> Aggiornamento schermata iniziale e-Task in corso...</string>
  <string id="Updating e-Task2 home screen..."> Aggiornamento schermata iniziale e-Task2 in corso...</string>
  <string id="Updating e-Task2+ home screen..."> Aggiornamento schermata iniziale e-Task2+ in corso...</string>
  <string id="Updating e-Task3 home screen..."> Aggiornamento schermata iniziale e-Task3 in corso...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen..."> Aggiornamento schermata iniziale e-Task4 (4,3 poll.) in corso...</string>
  <string id="Updating e-Task4 home screen..."> Aggiornamento schermata iniziale e-Task4 in corso...</string>
  <string id="Updating Fax Forward settings..."> Aggiornamento impostazioni inoltro fax in corso...</string>
  <string id="Updating password..."> Aggiornamento password in corso...</string>
  <string id="Updating Security setting..."> Aggiornamento impostazioni di protezione in corso...</string>
  <string id="Updating service settings..."> Aggiornamento impostazioni servizio in corso...</string>
  <string id="Updating SFP e-Task home screen..."> Aggiornamento schermata iniziale e-Task SFP in corso...</string>
  <string id="Updating SFP e-Task2 home screen..."> Aggiornamento schermata iniziale e-Task2+ SFP in corso...</string>
  <string id="Updating SFP e-Task2+ home screen..."> Aggiornamento schermata iniziale e-Task2+ SFP in corso...</string>
  <string id="Updating SFP e-Task3 home screen..."> Aggiornamento schermata iniziale e-Task3 SFP in corso...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen..."> Aggiornamento schermata iniziale e-Task4 (7 poll.) SFP in corso...</string>
  <string id="Updating SFP e-Task4 home screen..."> Aggiornamento schermata iniziale e-Task4 SFP in corso...</string>
  <string id="Updating solution settings..."> Aggiornamento impostazioni soluzione in corso...</string>
  <string id="Updating username..."> Aggiornamento nome utente in corso...</string>
  <string id="Updating X642 home screen..."> Aggiornamento schermata iniziale X642 in corso...</string>
  <string id='Updating webapp settings...'>Aggiornamento impostazioni app Web...</string>
  <string id="Upgrading or deleting solutions here will require">Laggiornamento o leliminazione di soluzioni richiederà</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups"> L'aggiornamento o la rimozione della distribuzione delle app cSF richiederà un &lt;b&gt;aggiornamento dei criteri&lt;/b&gt; per tutti i gruppi di periferiche interessati</string>
  <string id="Upload">Carica</string>
  <string id="Upload custom icons"> Carica icone personalizzate</string>
  <string id="Upload Report Files">Carica file rapporti</string>
  <string id="Uploading AP Bundle and Descriptor Completed."> Caricamento bundle Richieste avanzate e descrittore completato.</string>
  <string id="Uploading AP Bundle and Descriptor..."> Caricamento bundle Richieste avanzate e descrittore in corso...</string>
  <string id="Uploading cSF Ap cert files...."> Caricamento file certificati app cSF in corso...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ..."> Caricamento file certificati (file cacert.pem e key.pem) app cSF in corso...</string>
  <string id="Uploading of cSF App cert files Completed."> Caricamento file certificati app cSF completato.</string>
  <string id="Uploading Report(s)..."> Caricamento rapporti in corso...</string>
  <string id="Uploading...">Caricamento in corso...</string>
  <string id="Usage:">Uso:</string>
  <string id="Usb Drive">Unità USB</string>
  <string id="Use default settings">Usa impostazioni predefinite</string>
  <string id="Use Secure Connection. (SSLTLS)"> Usa connessione sicura. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Usa Configurazione soluzioni</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">Utilizzare questa finestra di dialogo solo se il database, i dati webdav centrali del sistema LDD esistente devono essere sincronizzati con un altro sistema LDD attivo da utilizzare come 'sistema LDD di backup'. Per informazioni su questa funzione, vedere la guida dell'amministratore.</string>
  <string id="Use this home screen as part of the device groups policy.">Usa questa schermata iniziale come parte del criterio del gruppo di periferiche.</string>
  <string id='Used:'>Usato:</string>
  <string id="User Name">Nome utente</string>
  <string id="User Name:">Nome utente:</string>
  <string id="User Report"> Rapporto utenti</string>
  <string id="User Search Base:"> Base di ricerca utenti:</string>
  <string id="User Search Filter:"> Filtro di ricerca utenti:</string>
  <string id="Username amp; Password">Nome utente e password</string>
  <string id="Username and Password"> Nome utente e password</string>
  <string id="Username Changed Successfully."> Modifica nome utente completata.</string>
  <string id="Username Password"> Password del nome utente</string>
  <string id="Username updated."> Nome utente aggiornato.</string>
  <string id="Username*">Nome utente*</string>
  <string id="Username:">Nome utente:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Verifica distribuzione applicazione eSF e distribuisci queste impostazioni eSF.</string>
  <string id="Version">Versione</string>
  <string id="Version Info:">Info versione:</string>
  <string id="Version:">Versione:</string>
  <string id="VersionInfo"> Info versione</string>
  <string id="Very very very long long long text">Very very very long long long text</string>
  <string id="View Details">Vis. dettagli</string>
  <string id="View Source">Visualizza origine</string>
  <string id="Waiting for License Upload Results ...">In attesa dei risultati caricamento licenza...</string>
  <string id="WebApps">App Web</string>
  <string id="WebClient Version"> Versione client Web</string>
  <string id="WebClient Version:">Versione client Web:</string>
  <string id="Wed">Mer</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated."> Schermata iniziale X642 aggiornata.</string>
  <string id="Yes">Sì</string>
  <string id="You are viewing the Kranked version of the application">Visualizzazione della versione kranked dellapplicazione</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps"> Non si dispone dei privilegi per accedere alle attività in tutte le app cSF</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">Non si dispone dei privilegi per accedere alle attività in Tutti i gruppi di periferiche</string>
  <string id="You have no privilege to this task."> Non si dispone dei privilegi per questa attività.</string>
  <string id="You must first select a Task to Edit">È prima necessario selezionare unattività da modificare</string>
  <string id="active">attivo</string>
  <string id="active:">attivo:</string>
  <string id="addition to the two events below.">oltre ai due eventi sotto.</string>
  <string id="avg response (ms)">risposta media (ms)</string>
  <string id="be set back to the default values next time.">torneranno ai valori predefiniti la prossima volta.</string>
  <string id="cache">cache</string>
  <string id="cc:">cc:</string>
  <string id="change"> modifica</string>
  <string id="cSF App"> App cSF</string>
  <string id="cSF App Cert File"> File certificato app cSF</string>
  <string id="cSF App Certificates">Certificati app cSF</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload"> Caricamento certificati (file cacert.pem, key.pem) app cSF in corso</string>
  <string id="cSF App Key File"> File chiave app cSF</string>
  <string id="cSF App settings updated."> Impostazioni app cSF aggiornate.</string>
  <string id="cSF App Version"> Versione app cSF</string>
  <string id="cSF App Version:"> Versione app cSF:</string>
  <string id="cSF Apps">App cSF</string>
  <string id="cSF Apps deployed to device group"> App cSF distribuite a gruppo di periferiche</string>
  <string id="cSF Apps to deploy:">App cSF da distribuire:</string>
  <string id="cSF Apps: Device group deployment deleted."> App cSF: Distribuzione del gruppo di periferiche eliminata.</string>
  <string id="day(s)">giorno/i</string>
  <string id="devices failed"> Periferiche con errori</string>
  <string id="devices updated"> Periferiche aggiornate</string>
  <string id="device(s) discovered"> Periferiche rilevate</string>
  <string id="device(s) missing"> Periferiche mancanti</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">Impostazioni applicazione eSF:</string>
  <string id="eSF Application Version:">Versione applicazione eSF:</string>
  <string id="eSF Applications">Applicazioni eSF</string>
  <string id="eSF Applications:">Applicazioni eSF:</string>
  <string id="eSF Applications: (Solution)">Applicazioni eSF: (soluzione)</string>
  <string id="eSF Configuration">Configurazione eSF</string>
  <string id="eSF Settings Saved."> Impostazioni eSF salvate.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e‑Task</string>
  <string id="e-Task home screen updated."> Schermata iniziale e-Task aggiornata.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated."> Schermata iniziale e-Task2 aggiornata.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated."> Schermata iniziale e-Task2+ aggiornata.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated."> Schermata iniziale e-Task3 aggiornata.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4,3 poll.)</string>
  <string id="e-Task4 (4.3 in.) home screen updated."> Schermata iniziale e-Task4 (4,3 poll.) aggiornata.</string>
  <string id="e-Task4 home screen updated."> Schermata iniziale e-Task4 aggiornata.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed."> non riuscito.</string>
  <string id="hide"> nascondi</string>
  <string id="hour(s)">ora/e</string>
  <string id="in order to add a group."> per poter aggiungere un gruppo.</string>
  <string id="info">info</string>
  <string id="load">carica</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">min</string>
  <string id="month(s)">mese/i</string>
  <string id="not communicating"> assenza comunicazione</string>
  <string id="null">nessuno</string>
  <string id="offline"> offline</string>
  <string id="on">in</string>
  <string id="on all effected Device Groups.">su tutti i gruppi di periferiche affetti.</string>
  <string id="oncheck">oncheck</string>
  <string id="online"> online</string>
  <string id="or home screen support for this device does not exist.">o se il supporto della schermata iniziale per questa periferica non è presente.</string>
  <string id="requests">richieste</string>
  <string id="requests/sec">richieste/sec</string>
  <string id="saving report..."> salvataggio rapporto in corso...</string>
  <string id="server">server</string>
  <string id="show"> mostra</string>
  <string id="test">prova</string>
  <string id="to"> a</string>
  <string id="to change them.">modificarli.</string>
  <string id="to take effect on the devices.">influire sulle periferiche.</string>
  <string id="total requests:">richieste totali:</string>
  <string id="total responses:">risposte totali:</string>
  <string id="undo">annulla</string>
  <string id="uploaded."> caricato.</string>
  <string id="week(s)">settimana/e</string>
  <string id="{0} Groups">{0} gruppi</string>
  <string id="{0} Reports">{0} rapporti</string>
  <string id="{0} Software Client Groups">{0} gruppi di client software</string>
  <string id="{0} Solutions">{0} soluzioni</string>
  <string id="{0} eForms">{0} moduli elettronici</string>
  <string id="{0} eSF Applications">{0} applicazioni eSF</string>
  <string id="Policy update required for changes to take effect on the devices">Per rendere effettive queste modifiche nelle periferiche, è necessario un &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;aggiornamento dei criteri&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;.</string>
  <string id="Group search base must be set for adding group based Privileges">La base di ricerca del gruppo deve essere impostata per aggiungere gruppi basati  su &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;privilegi&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">La base di ricerca del gruppo deve essere impostata in &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Configurazione LDAP&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; per poter aggiungere un gruppo.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">Installazione con licenza SMB. Le licenze MFP saranno limitate a un massimo di</string>
  <string id="licenses!">licenze.</string>
</localize>
`;