export const DE = `
<localize>
  <string id="% Completed">% abgeschlossen</string>
  <string id="% Completed:">% Abgeschlossen:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">(Optional) Geben Sie eine Beschreibung ein.</string>
  <string id="( Username must be a Distinguished Name )">( Benutzername muss ein definierter Name sein )</string>
  <string id="(1-999)">(1-999)</string>
  <string id="(Cron expression)">(Cron-Ausdruck)</string>
  <string id="(progress)">(Fortschritt)</string>
  <string id="* Software Client License Not Found.">* Softwareclient-Lizenz nicht gefunden.</string>
  <string id="[EXTERNAL]">[EXTERN]</string>
  <string id="[None]">[Keine]</string>
  <string id="1 Button">1 Schaltfläche</string>
  <string id="1 minute load">1 Minute laden</string>
  <string id="1. cSF Apps">1. cSF-Apps</string>
  <string id="1. Device Groups">1. Gerätegruppen</string>
  <string id="1. Search">1. Suchen</string>
  <string id="1. Services">1. Dienste</string>
  <string id="1. Software Client Groups">1. Softwareclient-Gruppen</string>
  <string id="1. Solutions">1. Lösungen</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. Geben Sie die Suchkriterien ein und klicken Sie auf die Schaltfläche &quot;Suchen&quot;.</string>
  <string id="1. WebApps">1. WebApps</string>
  <string id="10 Buttons">10 Schaltflächen</string>
  <string id="15 minute load">15 Minuten laden</string>
  <string id="15sec">15 Sek.</string>
  <string id="2 Buttons">2 Schaltflächen</string>
  <string id="2. Choose one or more devices if any are found.">2. Wählen Sie mindestens ein Gerät aus, falls Geräte gefunden werden.</string>
  <string id="2. Devices">2. Geräte</string>
  <string id="2. Tasks">2. Aufgaben</string>
  <string id="3 Buttons">3 Schaltflächen</string>
  <string id="3. Choose a Task.">3. Wählen Sie eine Aufgabe aus.</string>
  <string id="3. Tasks">3. Aufgaben</string>
  <string id="30sec">30 Sek.</string>
  <string id="4 Buttons">4 Schaltflächen</string>
  <string id="4-16 Buttons">4-16 Schaltflächen</string>
  <string id="5 Buttons">5 Schaltflächen</string>
  <string id="5 minute load">5 Minuten laden</string>
  <string id="5sec">5 Sek.</string>
  <string id="6 Buttons">6 Schaltflächen</string>
  <string id="60sec">60 Sek.</string>
  <string id="7 Buttons">7 Schaltflächen</string>
  <string id="8 Buttons">8 Schaltflächen</string>
  <string id="9 Buttons">9 Schaltflächen</string>
  <string id="A Policy Update is currently running...">Eine Richtlinie wird gerade aktualisiert...</string>
  <string id="About">Info</string>
  <string id="Action">Aktion</string>
  <string id="Action Settings...">Aktionseinstellungen...</string>
  <string id="Action Settings:">Aktionseinstellungen:</string>
  <string id="Action:">Aktion:</string>
  <string id="Add">Hinzufügen</string>
  <string id="Add a cSF App to deploy:">Bereitzustellende cSF-App hinzufügen:</string>
  <string id="Add a new Group to the system">Neue Gruppe im System hinzufügen</string>
  <string id="Add a new report to the system">Neuen Bericht im System hinzufügen</string>
  <string id="Add a solution to deploy: Step 1 of 2">Bereitzustellende Lösung hinzufügen: Schritt 1 von 2</string>
  <string id="Add a solution to deploy: Step 2 of 2">Bereitzustellende Lösung hinzufügen: Schritt 2 von 2</string>
  <string id="Add a solution: Step 1 of 2">Lösung hinzufügen: Schritt 1 von 2</string>
  <string id="Add a solution: Step 2 of 2">Lösung hinzufügen: Schritt 2 von 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Aufgabe zum Zeitplan hinzufügen: Schritt 1 von 3</string>
  <string id="Add Device Group">Gerätegruppe hinzufügen</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Gerätegruppen zum Zeitplan hinzufügen: Schritt 2 von 3</string>
  <string id="Add Forms Printer">Formulardrucker hinzufügen</string>
  <string id="Add License">Lizenz hinzufügen</string>
  <string id="Add Software Client Group">Softwareclient-Gruppe hinzufügen</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Häufigkeit zum Zeitplan hinzufügen: Schritt 3 von 3</string>
  <string id="Add...">Hinzufügen...</string>
  <string id="Adding Formset(s)...">Formsets werden hinzugefügt...</string>
  <string id="Adding Group Name from LDAP...">Gruppenname aus LDAP wird hinzugefügt...</string>
  <string id="Adding solution to software client group...">Lösung wird Softwareclientgruppe hinzugefügt...</string>
  <string id="Additional Options">Zusätzliche Optionen</string>
  <string id="Additional Parameters">Zusätzliche Parameter</string>
  <string id="Additional Parameters...">Zusätzliche Parameter...</string>
  <string id="Additional Report Parameters">Zusätzliche Berichtsparameter</string>
  <string id="Address">Adresse</string>
  <string id="Address:">Adresse:</string>
  <string id="Admin password:">Administratorkennwort:</string>
  <string id="All">Alle</string>
  <string id="All cSF Apps">Alle cSF-Apps</string>
  <string id="All Device Groups">Alle Gerätegruppen</string>
  <string id="All scheduled tasks for the system.">Alle für das System geplanten Aufgaben.</string>
  <string id="All scheduled tasks for this device group:">Alle für diese Gerätegruppe geplanten Aufgaben:</string>
  <string id="All scheduled tasks for this sftClient group">Alle für diese sftClient-Gruppe geplanten Aufgaben</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">Alle ausgewählten Geräte werden vollständig vom System entfernt. Möchten Sie diese Geräte wirklich entfernen?</string>
  <string id="All Servers Offline">Alle Server offline</string>
  <string id="All Servers Online">Alle Server online</string>
  <string id="All Software Client Groups">Alle Softwareclient-Gruppen</string>
  <string id="All Solutions">Alle Lösungen</string>
  <string id="All Tabs">Alle Registerkarten</string>
  <string id="An error occurred while attempting to connect to this device,">Fehler beim Versuch, eine Verbindung mit diesem Gerät herzustellen.</string>
  <string id="Anonymous">Anonym</string>
  <string id="Any changes here will require">Alle Änderungen hier erfordern</string>
  <string id="Any Changes to the parameters are temporary and will">Alle Änderungen an den Parametern sind temporär und</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Alle Änderungen an den Parametern sind temporär und werden das nächste Mal auf die Standardwerte zurückgesetzt.</string>
  <string id="AP (Advanced Prompting) Bundle Upload">Upload des AP-Bundles (Erweiterte Eingabeaufforderungen)</string>
  <string id="AP Bundle">AP-Bundle</string>
  <string id="AP Bundle Application File">AP-Bundle-Anwendungsdatei</string>
  <string id="AP Bundle descriptor">AP-Bundle-Deskriptor</string>
  <string id="AP Bundle Descriptor File">AP-Bundle-Deskriptordatei</string>
  <string id="App Reservation">App-Reservierung</string>
  <string id="Application">Anwendung</string>
  <string id="Apply">Anwenden</string>
  <string id="Are you sure you want to change the edited profile?">Möchten Sie das bearbeitete Profil wirklich ändern?</string>
  <string id="Are you sure you want to change these profiles?">Möchten Sie diese Profile wirklich ändern?</string>
  <string id="Are you sure you want to delete all the forms?">Möchten Sie wirklich alle Formulare löschen?</string>
  <string id="Are you sure you want to delete all the profiles?">Möchten Sie wirklich alle Profile löschen?</string>
  <string id="Are you sure you want to delete all the solutions?">Möchten Sie wirklich alle Lösungen löschen?</string>
  <string id="Are you sure you want to delete the selected forms?">Möchten Sie die ausgewählten Formulare wirklich löschen?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">Möchten Sie die ausgewählte Gruppe wirklich löschen?  Alle dieser Gruppe zugeordneten Berechtigungen werden ebenfalls automatisch gelöscht.</string>
  <string id="Are you sure you want to delete the selected profiles?">Möchten Sie die ausgewählten Profile wirklich löschen?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">Möchten Sie den ausgewählten Bericht wirklich löschen?  Alle für diesen Bericht geplanten Berichtsaufgaben werden ebenfalls automatisch gelöscht.</string>
  <string id="Are you sure you want to delete the selected solutions?">Möchten Sie die ausgewählten Lösungen wirklich löschen?</string>
  <string id="Are you sure you want to delete these profiles?">Möchten Sie diese Profile wirklich löschen?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">Möchten Sie die Bereitstellung aller cSF-Apps wirklich aufheben?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">Möchten Sie die Bereitstellung der ausgewählten cSF-App(s) wirklich aufheben?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">Möchten Sie diese +webAppsString.getWebAppString()+?} wirklich löschen?</string>
  <string id="Are you sure you would like to delete this Device Group?">Möchten Sie diese Gerätegruppe wirklich löschen?</string>
  <string id="Are you sure you would like to delete this forms printer?">Möchten Sie diesen Formulardrucker wirklich löschen?</string>
  <string id="Are you sure you would like to delete this scheduled task?">Möchten Sie diese geplante Aufgabe wirklich löschen?</string>
  <string id="Are you sure you would like to delete this software client Group?">Möchten Sie diese Softwareclientgruppe wirklich löschen?</string>
  <string id="Are you sure you would like to delete this solution?">Möchten Sie diese Lösung wirklich löschen?</string>
  <string id="Associated Device Group :">Zugeordnete Gerätegruppe:</string>
  <string id="Associated Solution :">Zugeordnete Lösung:</string>
  <string id="Associated Solution:">Zugeordnete Lösung:</string>
  <string id="Authentication Method:">Authentifizierungsmethode:</string>
  <string id="Author">Autor</string>
  <string id="Auto Refresh:">Automatische Aktualisierung:</string>
  <string id="Available Columns">Verfügbare Spalten</string>
  <string id="Available Reports">Verfügbare Berichte</string>
  <string id="Back">Zurück</string>
  <string id="Background Image:">Hintergrundbild:</string>
  <string id="Backup &amp; Restore information">Sicherungs- &amp; Wiederherstellungsinformationen</string>
  <string id="Backup amp; Restore">Sichern amp; wiederherstellen</string>
  <string id="Backup Jobs Logs Database">Protokolldatenbank für Sicherungsaufträge</string>
  <string id="Backup Share Path">Sicherungsfreigabepfad</string>
  <string id="Bar Chart">Balkendiagramm</string>
  <string id="Binary Files">Binärdateien</string>
  <string id="Bookmarks">Lesezeichen</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">Zur Aktualisierung von cSF-App-Zertifikaten ist sowohl die Datei 'cacert.pem' als auch die Datei 'key.pem' erforderlich.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">Zur Aktualisierung des AP-Bundles ist sowohl die eSF-Flash- als auch Deskriptordatei erforderlich.</string>
  <string id="Browse">Durchsuchen</string>
  <string id="Browse...">Durchsuchen...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">Standardmäßig ordnet der MFP die Schaltflächen auf dem Startbildschirm automatisch an.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">Der SFP fügt die Profile standardmäßig dem Ordner 'Angehaltene Aufträge' hinzu.</string>
  <string id="Cancel">Abbrechen</string>
  <string id="Canceled">Abgebrochen</string>
  <string id="Canceling...">Wird abgebrochen...</string>
  <string id="Change Default Values">Standardwerte ändern</string>
  <string id="Change Language">Sprache ändern</string>
  <string id="Change Password">Kennwort ändern</string>
  <string id="Change Username">Benutzernamen ändern</string>
  <string id="Changing name...">Name wird geändert...</string>
  <string id="Choose a cSF App to deploy:">Bereitzustellende cSF-App auswählen:</string>
  <string id="Choose a solution to deploy:">Bereitzustellende Lösung auswählen:</string>
  <string id="Choose a solution:">Lösung auswählen:</string>
  <string id="Choose Client Groups">Clientgruppen auswählen</string>
  <string id="Choose deployment settings for">Bereitstellungseinstellungen auswählen für</string>
  <string id="Choose Device Groups">Gerätegruppen auswählen</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">Jede Schaltfläche auswählen und zugehörige Aktion festlegen. Schaltflächen ohne Aktion werden auf dem Startbildschirm nicht angezeigt.</string>
  <string id="Choose one...">Eine auswählen...</string>
  <string id="Choose task">Aufgabe auswählen</string>
  <string id="Choose the frequency">Häufigkeit auswählen</string>
  <string id="Choose the group type">Gruppentyp auswählen</string>
  <string id="Class">Klasse</string>
  <string id="Click">Klicken</string>
  <string id="Click Add to create a Home screen button.">Klicken Sie auf Hinzufügen, um eine Startbildschirm-Schaltfläche zu erstellen.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Klicken Sie auf die Kontrollkästchen, um Rechte zu aktivieren bzw. zu deaktivieren.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Klicken Sie auf das Quadrat und lassen Sie die Maustaste los, um eine neue Farbe auszuwählen.</string>
  <string id="Client Groups:">Clientgruppen:</string>
  <string id="Client Profile created.">Clientprofil wurde erstellt.</string>
  <string id="Client Profiles">Clientprofile</string>
  <string id="Close">Schließen</string>
  <string id="Color :">Farbe:</string>
  <string id="Column Chart.">Spaltendiagramm.</string>
  <string id="Compile">Kompilieren</string>
  <string id="Compile Options:">Kompilierungsoptionen:</string>
  <string id="Completed">Abgeschlossen</string>
  <string id="Components">Komponenten</string>
  <string id="Config Service">Konfigurationsdienst</string>
  <string id="Configuration">Konfiguration</string>
  <string id="Configuration:">Konfiguration:</string>
  <string id="Configurations for this discovery:">Konfigurationen für diese Suche:</string>
  <string id="Connect To App">Mit App verbinden</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Verbunden mit Ziel-VM, Adresse: 127.0.0.1:61023, Transport: Socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">Verbindungstimeout Überprüfen Sie die Serverkonfiguration einschließlich der Firewalleinstellungen.</string>
  <string id="Contact Location">Kontaktstandort</string>
  <string id="Contact Location:">Kontaktstandort:</string>
  <string id="Contact Name">Kontaktname</string>
  <string id="Contact Name:">Kontaktname:</string>
  <string id="Content :">Inhalt:</string>
  <string id="Copy">Kopieren</string>
  <string id="Copy + Profile">Kopie + Profil</string>
  <string id="Copy Shortcuts">Kopierkurzwahlen</string>
  <string id="CPU Usage">CPU-Nutzung</string>
  <string id="Creating client profile...">Clientprofil wird erstellt...</string>
  <string id="Creating device group...">Gerätegruppe wird erstellt...</string>
  <string id="Creating discovery profile...">Suchprofil wird erstellt...</string>
  <string id="Creating or updating a forms printer...">Formulardrucker wird erstellt oder aktualisiert...</string>
  <string id="Creating software client group...">Softwareclientgruppe wird erstellt...</string>
  <string id="Creatingupdating the scheduled task...">Geplante Aufgabe wird erstellt/aktualisiert...</string>
  <string id="Cron expression)">Cron-Ausdruck)</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">Aktuelle Spalten</string>
  <string id="Current password is incorrect.">Aktuelles Kennwort ist falsch.</string>
  <string id="Current Password:">Aktuelles Kennwort:</string>
  <string id="Currently discovering Missing Devices...">Fehlende Geräte werden gerade ermittelt...</string>
  <string id="Currently discovering Unlicensed Devices...">Nicht lizenzierte Geräte werden gerade ermittelt...</string>
  <string id="Custom">Benutzerdefiniert</string>
  <string id="Custom icons:">Benutzerdefinierte Symbole:</string>
  <string id="Custom...">Benutzerdefiniert...</string>
  <string id="Customize Jobs Table">Auftragstabelle anpassen</string>
  <string id="Customize Logs Table">Protokolltabelle anpassen</string>
  <string id="Customize Table...">Tabelle anpassen...</string>
  <string id="Danger, Will Robinson!">Achtung, Will Robinson!</string>
  <string id="Darkness :">Deckung:</string>
  <string id="Database Driver:">Datenbanktreiber:</string>
  <string id="Database Fully Qualified Hostname OR IpAddress">Vollständig qualifizierte(r) Hostname ODER IP-Adresse der Datenbank</string>
  <string id="Database URL:">Datenbank-URL:</string>
  <string id="Datasource:">Datenquelle:</string>
  <string id="Datatype Filter">Datentypfilter</string>
  <string id="Datatype filter:">Datentypfilter:</string>
  <string id="Date">Datum</string>
  <string id="Debug">Debuggen</string>
  <string id="Default">Standard</string>
  <string id="Default Group">Standardgruppe</string>
  <string id="Default Group can not be deleted.">Standardgruppe kann nicht gelöscht werden.</string>
  <string id="Default Output Format:">Standardausgabeformat:</string>
  <string id="Default: 389">Standard: 389</string>
  <string id="Delete">Löschen</string>
  <string id="Delete file on failure?">Datei bei Fehler löschen?</string>
  <string id="Delete file on success?">Datei bei Erfolg löschen?</string>
  <string id="Deleted device group. One or more devices must now be updated.">Gerätegruppe wurde gelöscht. Mindestens ein Gerät muss jetzt aktualisiert werden.</string>
  <string id="Deleted selected FormSet(s).">Ausgewählte Formsets wurden gelöscht.</string>
  <string id="Deleted software client group.">Softwareclientgruppe wurde gelöscht.</string>
  <string id="Deleting All FormSet(s)...">Alle Formsets werden gelöscht...</string>
  <string id="Deleting All solution(s)...">Alle Lösungen werden gelöscht...</string>
  <string id="Deleting client profile(s)...">Clientprofile werden gelöscht...</string>
  <string id="Deleting device group...">Gerätegruppe wird gelöscht...</string>
  <string id="Deleting discovery profile(s)...">Suchprofile werden gelöscht...</string>
  <string id="Deleting forms printer...">Formulardrucker werden gelöscht...</string>
  <string id="Deleting Formset(s)...">Formsets werden gelöscht...</string>
  <string id="Deleting scheduled task...">Geplante Aufgabe wird gelöscht...</string>
  <string id="Deleting selected FormSet(s)...">Ausgewählte Formsets wurden gelöscht...</string>
  <string id="Deleting software client group...">Softwareclientgruppe wird gelöscht...</string>
  <string id="Deleting solution(s)...">Lösungen werden gelöscht...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Bereitstellen auf:</string>
  <string id="Deploy:">Bereitstellen:</string>
  <string id="Deploying home screen to">Startbildschirm bereitstellen für</string>
  <string id="Deploying solution to device group...">Lösung wird für Gerätegruppe bereitgestellt...</string>
  <string id="Deploying WAR file:">WAR-Datei wird bereitgestellt: </string>
  <string id="Description">Beschreibung</string>
  <string id="Description:">Beschreibung:</string>
  <string id="Descriptor">Deskriptor</string>
  <string id="Destination Folder Path">Zielordnerpfad</string>
  <string id="Developer Forums">Entwicklerforen</string>
  <string id="Developer Network">Entwicklernetzwerk</string>
  <string id="Device Address">Geräteadresse</string>
  <string id="Device Address:">Geräteadresse:</string>
  <string id="Device Class">Geräteklasse</string>
  <string id="Device Group">Gerätegruppe</string>
  <string id="Device Group created">Gerätegruppe wurde erstellt</string>
  <string id="Device Group was successfully removed from the system.">Die Gerätegruppe wurde erfolgreich aus dem System entfernt.</string>
  <string id="Device Group:">Gerätegruppe:</string>
  <string id="Device Groups">Gerätegruppen</string>
  <string id="Device Groups:">Gerätegruppen:</string>
  <string id="Device Information Directions">Anweisungen für Geräteinformationen</string>
  <string id="Device Model">Gerätemodell</string>
  <string id="Device Model:">Gerätemodell:</string>
  <string id="Device Profiles">Geräteprofile</string>
  <string id="Device Summary">Gerätezusammenfassung</string>
  <string id="Device update complete.">Geräteupdate abgeschlossen.</string>
  <string id="Device update started...">Geräteupdate gestartet...</string>
  <string id="DeviceGroup">DeviceGroup</string>
  <string id="Devices">Geräte</string>
  <string id="Directory">Verzeichnis</string>
  <string id="Directory Path">Verzeichnispfad</string>
  <string id="Directory path*">Verzeichnispfad*</string>
  <string id="Directory Watcher">Verzeichnis-Überwachung</string>
  <string id="Directory Watcher information">Verzeichnisüberwachungs-Informationen</string>
  <string id="Disabled">Deaktiviert</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Getrennt von Ziel-VM, Adresse: 127.0.0.1:60902, Transport: Socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Getrennt von Ziel-VM, Adresse: 127.0.0.1:61015, Transport: Socket</string>
  <string id="Discover">Suche</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Sucht Geräte für ausgewählte Gerätegruppen anhand des spezifischen Suchprofils jeder Gruppe.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Sucht Geräte für diese Gerätegruppe anhand der Suchprofile.</string>
  <string id="Discover Missing">Fehlendes Gerät suchen</string>
  <string id="Discover new devices only">Nur neue Geräte suchen</string>
  <string id="Discover Unlicensed">Nicht lizenzierte Geräte suchen</string>
  <string id="Discover...">Suchen...</string>
  <string id="Discovered">Gefunden</string>
  <string id="Discovered Devices">Gefundene Geräte</string>
  <string id="Discovered Devices:">Gefundene Geräte:</string>
  <string id="Discovery">Suche</string>
  <string id="Discovery has Completed for...">Suche abgeschlossen für...</string>
  <string id="Discovery in Progress for...">Suche wird ausgeführt für...</string>
  <string id="Discovery Profile created.">Suchprofil wurde erstellt.</string>
  <string id="Discovery Profiles">Suchprofile</string>
  <string id="Discovery Profiles:">Suchprofile:</string>
  <string id="Display Text">Anzeigetext</string>
  <string id="Display Text:">Anzeigetext:</string>
  <string id="Documentation">Dokumentation</string>
  <string id="Done">Fertig</string>
  <string id="Done generating the jobs report for downloading.">Auftragsbericht zum Herunterladen wurde generiert.</string>
  <string id="Done generating the logs report for downloading.">Protokollbericht zum Herunterladen wurde generiert.</string>
  <string id="Down icon">Gedrückt (Symbol)</string>
  <string id="Down icon:">Gedrückt (Symbol):</string>
  <string id="Download Details">Downloaddetails</string>
  <string id="Duplex :">Beidseitig:</string>
  <string id="Edit">Bearbeiten</string>
  <string id="Edit a solution">Lösung bearbeiten</string>
  <string id="Edit a solution to deploy">Bereitzustellende Lösung bearbeiten</string>
  <string id="Edit the information about the report :">Berichtsinformationen bearbeiten:</string>
  <string id="Edit the report settings">Berichtseinstellungen bearbeiten</string>
  <string id="Edit...">Bearbeiten...</string>
  <string id="EForms">EForms</string>
  <string id="E-Forms">E-Forms</string>
  <string id="EForms:">EForms:</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">Entweder müssen sowohl das Datums- als auch das Zeitfeld 'Von' ausgefüllt oder beide Felder leer gelassen werden.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">Entweder müssen sowohl das Datums- als auch das Zeitfeld 'Bis' ausgefüllt oder beide Felder leer gelassen werden.</string>
  <string id="Email">E-Mail</string>
  <string id="Email + Profile">E-Mail + Profil</string>
  <string id="Email Shortcuts">E-Mail-Kurzwahlen</string>
  <string id="Email the Report">Bericht e-mailen</string>
  <string id="Email To">E-Mail an</string>
  <string id="Enable Fax Forwarding.">Aktivieren Sie die Faxweiterleitung.</string>
  <string id="Enable LDAP Authentication.">Aktivieren Sie die LDAP-Authentifizierung.</string>
  <string id="Enabled for Credentials">Für Anmeldeinformationen aktiviert</string>
  <string id="Enabled for Session">Für Sitzung aktiviert</string>
  <string id="End Time">Beendigungszeit</string>
  <string id="End Time:">Endzeit:</string>
  <string id="Enter a unique group name">Eindeutigen Gruppennamen eingeben</string>
  <string id="Enter a unique name for this group">Eindeutigen Namen für diese Gruppe eingeben</string>
  <string id="Enter appropriate fields and click the Add button:">Entsprechende Felder ausfüllen und auf Hinzufügen klicken:</string>
  <string id="Enter appropriate fields and click the Save button:">Entsprechende Felder ausfüllen und auf 'Speichern' klicken:</string>
  <string id="Enter the appropriate fields and click the Add button:">Entsprechende Felder ausfüllen und auf 'Hinzufügen' klicken:</string>
  <string id="Enter the information about the new report :">Informationen zum neuen Bericht eingeben:</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Geben Sie die Zeitüberschreitungswerte in Millisekunden mit einem Leerzeichen zwischen den Wiederholungen ein.</string>
  <string id="Error">Fehler</string>
  <string id="Error importing license.">Fehler beim Importieren der Lizenz.</string>
  <string id="Error in changing name.">Fehler beim Ändern des Namens.</string>
  <string id="Error in creating device group...">Fehler beim Erstellen der Gerätegruppe...</string>
  <string id="Error in creating software client group...">Fehler beim Erstellen der Softwareclientgruppe...</string>
  <string id="Error in deleting device group.">Fehler beim Löschen der Gerätegruppe.</string>
  <string id="Error in deleting software client group.">Fehler beim Löschen der Softwareclientgruppe.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">Fehler beim Löschen der Formsets. Weitere Details finden Sie in den Protokollen.</string>
  <string id="Error in generating the report.">Fehler beim Generieren des Berichts.</string>
  <string id="Error in saving Ldap settings.">Fehler beim Speichern der LDAP-Einstellungen.</string>
  <string id="Error in saving settings.">Fehler beim Speichern der Einstellungen.</string>
  <string id="Error in updating password.">Fehler beim Aktualisieren des Kennworts.</string>
  <string id="Error in updating security settings.">Fehler beim Aktualisieren der Sicherheitseinstellung.</string>
  <string id="Error in updating service settings.">Fehler beim Aktualisieren der Diensteinstellungen.</string>
  <string id="Error in updating solution settings.">Fehler beim Aktualisieren der Lösungseinstellungen.</string>
  <string id="Error while deploying home screen to">Fehler beim Bereitstellen des Startbildschirms für</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Evaluieren in +app_url}</string>
  <string id="Evaluate in remote app">Evaluieren in Remote-App</string>
  <string id="Every">Alle</string>
  <string id="Expiration Date">Ablaufdatum</string>
  <string id="Expired Formset">Abgelaufener Formularsatz</string>
  <string id="Expired!">Abgelaufen</string>
  <string id="Expires on:">Gültig bis:</string>
  <string id="Export Report">Bericht exportieren</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">Fehlgeschlagen</string>
  <string id="FALSE">FALSE</string>
  <string id="Fax">Faxen</string>
  <string id="Fax + Profile">Fax + Profil</string>
  <string id="Fax Forward settings updated.">Einstellungen für die Faxweiterleitung wurden aktualisiert.</string>
  <string id="Fax Forwarding">Faxweiterleitung</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax">Verknüpfung des Faxweiterleitungsziels: (E-Mail, FTP, Fax) </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Verknüpfung des Faxweiterleitungsziels: (E-Mail, FTP, Fax)</string>
  <string id="Fax Forwarding Destination:">Faxweiterleitungsziel:</string>
  <string id="Fax Forwarding LDSS Script:">LDSS-Skript für die Faxweiterleitung:</string>
  <string id="Fax Forwarding Receive Mode:">Empfangsmodus der Faxweiterleitung:</string>
  <string id="Fax Shortcuts">Fax-Kurzwahlen</string>
  <string id="Feature Id">Funktions-ID</string>
  <string id="Filter">Filter</string>
  <string id="Filters...">Filter...</string>
  <string id="Finish">Fertig stellen</string>
  <string id="Finished AP Bundle Descriptor File">AP-Bundle-Deskriptordatei erstellt</string>
  <string id="Finished AP Bundle Flash File">AP-Bundle-Flashdatei erstellt</string>
  <string id="Finished upload of key.pem File.">Upload der Datei 'key.pem' ausgeführt.</string>
  <string id="First">Zuerst</string>
  <string id="Form field must be a single word or valid email address.">Das Feld Formular muss ein einzelnes Wort oder eine gültige E-Mail-Adresse sein.</string>
  <string id="Form Printers">Formulardrucker</string>
  <string id="Format :">Format:</string>
  <string id="Forms">Formulare</string>
  <string id="Forms Printer is unlicensed">Formulardrucker ist nicht lizenziert</string>
  <string id="Forms printer successfully created or updated.">Formulardrucker wurde erfolgreich erstellt oder aktualisiert.</string>
  <string id="Forms printer successfully deleted.">Formulardrucker wurde erfolgreich gelöscht.</string>
  <string id="Formsets">Formularsätze</string>
  <string id="FormsetsSubforms">Formsets/Teilformulare</string>
  <string id="Forward Only">Nur weiterleiten</string>
  <string id="Fourth">Vierte</string>
  <string id="FRAMEWORK">FRAMEWORK</string>
  <string id="Fri">Frei</string>
  <string id="From:">Von:</string>
  <string id="Ftp">FTP</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + Profil</string>
  <string id="Ftp Shortcuts">FTP-Kurzwahlen</string>
  <string id="Generating logs report for downloading...">Protokollbericht zum Herunterladen wird generiert...</string>
  <string id="Generating Report">Bericht wird generiert</string>
  <string id="Generating Report...">Bericht wird generiert...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">Das Generieren von Berichten während der Geschäftszeiten kann die Systemleistung beeinträchtigen. Es wird empfohlen, Berichte außerhalb der Geschäftszeiten auszuführen.</string>
  <string id="Generating the jobs report for downloading...">Auftragsbericht zum Herunterladen wird generiert...</string>
  <string id="Graphic">Grafik</string>
  <string id="Graphic:">Grafik:</string>
  <string id="Group Description placeholder">Gruppenbeschreibung (Platzhalter)</string>
  <string id="Group Identifier:">Gruppenbezeichner:</string>
  <string id="Group Names from LDAP">Gruppennamen aus LDAP</string>
  <string id="Group Names from LDAP:">Gruppennamen aus LDAP:</string>
  <string id="Group search base must be set for adding group based">Gruppen-Suchbasis muss festgelegt werden zum Hinzufügen gruppenbasierter </string>
  <string id="Group search base must be set in">Gruppen-Suchbasis muss festgelegt werden in</string>
  <string id="Group Search Base:">Gruppensuchbasis:</string>
  <string id="Group Search Filter:">Gruppensuchfilter:</string>
  <string id="Group Search Identifier:">Gruppensuchbezeichner:</string>
  <string id="Groups">Gruppen</string>
  <string id="Held Jobs">Angehaltene Aufträge</string>
  <string id="Hide Settings">Einstellungen ausblenden</string>
  <string id="Home">Startseite</string>
  <string id="Home Screen">Startbildschirm</string>
  <string id="Home screen deployed to">Startbildschirm bereitgestellt für</string>
  <string id="Home Screens">Startbildschirme</string>
  <string id="Home Tab">Home (Registerkarte)</string>
  <string id="Hostname">Hostname</string>
  <string id="Hostname:">Hostname:</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">IDR-Lizenzübersicht</string>
  <string id="IDR License Summary:">IDR-Lizenzübersicht:</string>
  <string id="Images">Bilder</string>
  <string id="Import">Importieren</string>
  <string id="Import...">Import wird ausgeführt...</string>
  <string id="Importing AP Bundle Descriptor File...">AP-Bundle-Deskriptordatei wird importiert...</string>
  <string id="Importing AP Bundle Flash File...">AP-Bundle-Flashdatei wird importiert...</string>
  <string id="Importing Binary String...">Binäre Zeichenfolge wird importiert...</string>  
  <string id="Importing CaCert pem File...">Datei 'CaCer.pem' wird importiert...</string>
  <string id="Importing license...">Lizenz wird importiert...</string>
  <string id="Importing software client group profile...">Softwareclientgruppen-Profil wird importiert...</string>
  <string id="Importing Solution(s)...">Lösungen werden importiert...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Einfügen - Fügt die Schaltfläche Ausschneiden ein und aktiviert die übrigen Schaltflächen, sodass sie gedrückt sind.</string>
  <string id="Install Time">Installationszeit</string>
  <string id="Install Time:">Installationszeit:</string>
  <string id="Install-Upgrade">Installieren/Upgrade</string>
  <string id="It is recommended to run reports during off hours.">Es wird empfohlen, Berichte außerhalb der Geschäftszeiten auszuführen.</string>
  <string id="Items">Elemente</string>
  <string id="Jasper Report File Name:">Dateiname des Jasper-Berichts:</string>
  <string id="Job State">Auftragsstatus</string>
  <string id="Job State:">Auftragsstatus:</string>
  <string id="Jobs">Aufträge</string>
  <string id="Jobs by user">Aufträge nach Benutzer</string>
  <string id="Jobs Filters Table">Auftragsfiltertabelle</string>
  <string id="Jobs Report">Auftragsbericht</string>
  <string id="Jobs Report - CSV">Auftragsbericht – CSV</string>
  <string id="Keep previous backups">Vorherige Sicherungen beibehalten</string>
  <string id="Krank">Krank</string>
  <string id="Language:">Sprache:</string>
  <string id="Last">Letzte</string>
  <string id="Last 12 Hours">Letzte 12 Stunden</string>
  <string id="Last 15 Minutes">Letzte 15 Minuten</string>
  <string id="Last 24 Hours">Letzte 24 Stunden</string>
  <string id="Last 3 Hours">Letzte 3 Stunden</string>
  <string id="Last 30 Days">Letzte 30 Tage</string>
  <string id="Last 30 Minutes">Letzte 30 Minuten</string>
  <string id="Last 6 Hours">Letzte 6 Stunden</string>
  <string id="Last 7 Days">Letzte 7 Tage</string>
  <string id="Last Discovered">Zuletzt gesucht</string>
  <string id="Last Discovered:">Zuletzt gesucht:</string>
  <string id="Last Hour">Letzte Stunde</string>
  <string id="Last Kranked">Letzte Kranked-Version</string>
  <string id="Last Modified">Letzte Änderung</string>
  <string id="Layout">Layout</string>
  <string id="Layout:">Layout:</string>
  <string id="LDAP Server Settings:">LDAP-Servereinstellungen:</string>
  <string id="Ldap Settings Saved.">LDAP-Einstellungen wurden gespeichert.</string>
  <string id="LDAP Setup">LDAP-Einrichtung</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark Druckmanagement</string>
  <string id="License">Lizenz</string>
  <string id="LICENSE">LIZENZ</string>
  <string id="License Files">Lizenzdateien</string>
  <string id="License Type">Lizenztyp</string>
  <string id="License Upload Results.">Ergebnisse des Lizenz-Uploads.</string>
  <string id="License Upload Results:">Ergebnisse des Lizenz-Uploads:</string>
  <string id="Licensed">Lizenziert</string>
  <string id="Licenses">Lizenzen</string>
  <string id="Licenses in Use">Verwendete Lizenzen</string>
  <string id="Limit batch size">Batchgröße einschränken</string>
  <string id="Line Chart with Time Period Slider.">Liniendiagramm mit Zeitschieberegler.</string>
  <string id="LOADING">WIRD GELADEN</string>
  <string id="Loading...">Wird geladen...</string>
  <string id="LOADING...">WIRD GELADEN...</string>
  <string id="Lock Device">Gerät sperren</string>
  <string id="LoadBalancer Fully Qualified Hostname OR IpAddress">Vollständig qualifizierte(r) Hostname ODER IP-Adresse des Lastenausgleichs</string>
  <string id="Log">Protokoll</string>
  <string id="Log Report - CSV">Protokollbericht – CSV</string>
  <string id="Log Report - Failed Jobs">Protokollbericht – Fehlgeschlagene Aufträge</string>
  <string id="Log State">Protokollstatus</string>
  <string id="Log State:">Protokollstatus:</string>
  <string id="Logging In">Anmelden bei</string>
  <string id="Login">Anmelden</string>
  <string id="Logout">Abmelden</string>
  <string id="Logs Filters Table">Protokollfiltertabelle</string>
  <string id="Max:">Max.:</string>
  <string id="Member of Group(s):">Gruppenmitglied:</string>
  <string id="Memory Usage">Speichernutzung</string>
  <string id="Message">Nachricht</string>
  <string id="Message:">Nachricht:</string>
  <string id="Messages">Nachrichten</string>
  <string id="Min:">Min.:</string>
  <string id="Minimum length:">Mindestlänge:</string>
  <string id="Minimum:">Minimum:</string>  
  <string id="Missing">Fehlt</string>
  <string id="Missing Device">Fehlendes Gerät</string>
  <string id="Missing Devices">Fehlende Geräte</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Fehlende Geräte sind Geräte, die bereits einmal gefunden wurden, aber während der letzten Suche nicht ermittelt wurden (z. B., weil das Gerät nicht mit dem Netzwerk verbunden ist).</string>
  <string id="Missing devices:">Fehlende Geräte:</string>
  <string id="Missing Devices:">Fehlende Geräte:</string>
  <string id="Model">Modell</string>
  <string id="Model:">Modell:</string>
  <string id="Mon">Mon</string>
  <string id="MONITOR">MONITOR</string>
  <string id="Move Down">Nach unten</string>
  <string id="Move Up">Nach oben</string>
  <string id="Name">Name:</string>
  <string id="Name :">Name:</string>
  <string id="Name changed.">Name wurde geändert.</string>
  <string id="Name:">Name:</string>
  <string id="Network Load">Netzwerkauslastung</string>
  <string id="Network share password">Kennwort für die Netzwerkfreigabe</string>
  <string id="Network share user name">Benutzername für die Netzwerkfreigabe</string>
  <string id="New Password:">Neues Kennwort:</string>
  <string id="New Username:">Neuer Benutzername:</string>
  <string id="Next">Weiter</string>
  <string id="No">Nein</string>
  <string id="No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.">Für diese Gerätegruppe sind keine cSF-Apps vorhanden. Sie benötigen mindestens eine cSF-App, bevor Sie diese Aktion mit der Schaltfläche verknüpfen können.</string>
  <string id="No devices are currently Out of Policy for the system.">Für das System weichen derzeit keine Geräte von der Richtlinie ab.</string>
  <string id="No devices are currently Out of Policy for this device group.">Für diese Gerätegruppe weichen derzeit keine Geräte von der Richtlinie ab.</string>
  <string id="No home screen is configured for this device type.">Für diesen Gerätetyp wurde kein Startbildschirm konfiguriert.</string>
  <string id="No matches found">Keine Übereinstimmungen gefunden</string>
  <string id="No Privilege">Keine Berechtigung</string>
  <string id="No Privilege Alert">Keine Warnung über Berechtigungen</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">Für diese Gerätegruppe sind keine Profile vorhanden, da keine Lösungen mit Profilen zugeordnet wurden.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">Für diese Gerätegruppe sind keine Profile vorhanden. Sie benötigen mindestens ein Profil, bevor Sie diese Aktion mit der Schaltfläche verknüpfen können.</string>
  <string id="No records match the selected filter criteria.">Keine übereinstimmenden Datensätze für die ausgewählten Filterkriterien.</string>
  <string id="No records matched the filter criteria.">Keine übereinstimmenden Datensätze für die Filterkriterien.</string>
  <string id="No schedulable scripts are available.">Es sind keine zeitgesteuerten Skripts verfügbar.</string>
  <string id="No UCF File selected">Es wurde keine Sicherheits-Setupdatei ausgewählt</string>
  <string id="None">Keiner</string>
  <string id="None of the selected devices are missing.">Keines der ausgewählten Geräte fehlt.</string>
  <string id="None of the selected devices are unlicensed.">Keines der ausgewählten Geräte ist nicht lizenziert.</string>
  <string id="Number of Jobs per Page">Anzahl der Aufträge pro Seite</string>
  <string id="Number of Licenses">Anzahl der Lizenzen</string>
  <string id="Number of Logs per Page">Anzahl der Protokolle pro Seite</string>
  <string id="Off">Aus</string>
  <string id="OK">OK</string>
  <string id="Once">Einmal</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">Mindestens eine der Schaltflächen in der aktuellen Konfiguration ist ungültig. &lt;font color="#ff0000"&gt;(in Rot dargestellt)&lt;/font&gt; Stellen Sie sicher, dass alle Schaltflächen gültig sind.</string>
  <string id="One or more tests did not pass.">Mindestens ein Test war nicht erfolgreich.</string>
  <string id="Only">Ausschließlich</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">Es kann jeweils nur eine Suche durchgeführt werden. Nach Ende der aktuellen Suche können Sie eine neue Suche starten.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">Es kann jeweils nur eine Richtlinienaktualisierung durchgeführt werden.  Nach Ende der aktuellen Aktualisierung können Sie eine neue Richtlinienaktualisierung starten.</string>
  <string id="Only update those devices which are Out of Policy">Nur von der Richtlinie abweichende Geräte aktualisieren</string>
  <string id="Orientation :">Ausrichtung:</string>
  <string id="Out of Policy">Außerhalb der Richtlinie</string>
  <string id="Out of Policy Device">Von der Richtlinie abweichendes Gerät</string>
  <string id="Out of Policy Devices">Von der Richtlinie abweichende Geräte</string>
  <string id="Out of Policy Devices:">Von der Richtlinie abweichende Geräte:</string>
  <string id="Output Format">Ausgabeformat</string>
  <string id="Overwrite if file already exists">Überschreiben, wenn die Datei bereits vorhanden ist</string>
  <string id="Page 1">Seite 1</string>
  <string id="Page 2">Seite 2</string>
  <string id="Page 3">Seite 3</string>
  <string id="Page 4">Seite 4</string>
  <string id="Paper Size :">Papierformat:</string>
  <string id="Parameters">Parameter</string>
  <string id="Password Changed Successfully.">Kennwort erfolgreich geändert.</string>
  <string id="Password updated.">Kennwort aktualisiert.</string>
  <string id="Password*">Kennwort*</string>
  <string id="Password:">Kennwort:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Führt mithilfe der Richtlinie jeder einzelnen Gruppe eine Richtlinienaktualisierung für ausgewählte Gerätegruppen durch.</string>
  <string id="Perform a Policy Update for selected devices.">Führen Sie eine Richtlinienaktualisierung für ausgewählte Geräte durch.</string>
  <string id="Perform a Policy Update for this device group.">Führen Sie eine Richtlinienaktualisierung für diese Gerätegruppe durch.</string>
  <string id="Placeholder">Platzhalter</string>  
  <string id="Please choose a filter:">Filter auswählen:</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Wählen Sie einen Gruppentyp aus, um auf die lokalen Einstellungen einer Lösung im zeitgesteuerten Skript zuzugreifen:</string>
  <string id="Please choose a script:">Skript auswählen:</string>
  <string id="Please choose a task to schedule :">Zu planende Aufgabe auswählen:</string>
  <string id="Please choose an action:">Aktion auswählen:</string>
  <string id="Please choose client groups to schedule :">Zu planende Clientgruppen auswählen:</string>
  <string id="Please choose device groups to schedule :">Zu planende Gerätegruppen auswählen:</string>
  <string id="Please choose one of the following options:">Eine der folgenden Optionen auswählen:</string>
  <string id="Please choose solution and script :">Lösung und Skript auswählen:</string>
  <string id="Please choose solution and script to schedule :">Zu planende Lösung/Skript auswählen:</string>
  <string id="Please choose start time and frequency :">Startzeit und Häufigkeit auswählen:</string>
  <string id="Please choose the datasource for the new report.">Wählen Sie die Datenquelle für den neuen Bericht.</string>
  <string id="Please choose the jasper filename for the new report.">Wählen Sie den Jasper-Dateinamen für den neuen Bericht.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">Wählen Sie den Jasper-Dateinamen für den neuen Bericht.  Laden Sie den Jasper-Bericht hoch, falls er noch nicht aufgeführt wird.</string>
  <string id="Please choose the output format for the new report.">Wählen Sie das Ausgabeformat für den neuen Bericht.</string>
  <string id="Please choose the report to schedule :">Zu planenden Bericht auswählen:</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Informationen zur Softwareclient-Lizenz erhalten Sie bei Lexmark.</string>
  <string id="Please enter a non-expired date">Geben Sie ein nicht abgelaufenes Datum ein (tt.mm.jjjj).</string>
  <string id="Please enter a valid Address.">Geben Sie eine gültige Adresse ein.</string>
  <string id="Please enter a valid date">Geben Sie ein gültiges Datum ein (tt.mm.jjjj).</string>
  <string id="Please enter a valid End From Time">Geben Sie eine gültige Beendigungszeit für 'Von' ein (HH:MM).</string>
  <string id="Please enter a valid End To Time">Geben Sie eine gültige Beendigungszeit für 'Bis' ein (HH:MM).</string>
  <string id="Please enter a valid From date">Geben Sie ein gültiges Datum für 'Von' ein (tt.mm.jjjj).</string>
  <string id="Please enter a valid From time">Geben Sie eine gültige Uhrzeit für 'Von' ein (HH:MM).</string>
  <string id="Please enter a valid range:">Gültigen Bereich eingeben:</string>
  <string id="Please enter a valid range: 1 - 12">Geben Sie einen gültigen Bereich ein: 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">Geben Sie einen gültigen Bereich ein: 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">Geben Sie einen gültigen Bereich ein: 1 - 59</string>
  <string id="Please enter a valid Start From Time">Geben Sie eine gültige Startzeit für 'Von' ein (HH:MM).</string>
  <string id="Please enter a valid Start To Time">Geben Sie eine gültige Startzeit für 'Bis' ein (HH:MM).</string>
  <string id="Please enter a valid time">Geben Sie eine gültige Uhrzeit ein (HH:MM).</string>
  <string id="Please enter a valid To date">Geben Sie ein gültiges Datum für 'Bis' ein (tt.mm.jjjj).</string>
  <string id="Please enter a valid To time">Geben Sie eine gültige Uhrzeit für 'Bis' ein (HH:MM).</string>
  <string id="Please enter the Database driver and URL for the external database.">Geben Sie den Datenbanktreiber und die URL für die externe Datenbank ein.</string>
  <string id="Please enter the Directory information:">Verzeichnisinformationen eingeben:</string>
  <string id="Please enter the location where you want the report to be saved.">Geben Sie den Speicherort ein, an dem der Bericht gespeichert werden soll.</string>
  <string id="Please enter the name of the new report.">Geben Sie den Namen des neuen Berichts ein:</string>
  <string id="Please enter the network share user name and password.">Geben Sie den Benutzernamen und das Kennwort der Netzwerkfreigabe ein.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">Geben Sie die E-Mail-Empfänger für den Bericht ein.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">Geben Sie die erforderlichen Informationen für die Sicherung &amp; Wiederherstellung ein:</string>
  <string id="Please make sure that all the necessary fields are filled in.">Stellen Sie sicher, dass alle Pflichtfelder ausgefüllt sind.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Stellen Sie sicher, dass der Cron-Ausdruck über 6 oder 7 durch Leerzeichen getrennte Optionen verfügt.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Stellen Sie sicher, dass der Cron-Ausdruck an der 4. oder 6. Position (nicht jedoch an beiden Positionen) über ein '?' verfügt.</string>
  <string id="Please select a file to upload.">Wählen Sie eine Datei zum Upload aus.</string>
  <string id="Please select a group on the left to modify its task privileges.">Wählen Sie auf der linken Seite eine Gruppe aus, um deren Rechte für Aufgaben zu ändern.</string>
  <string id="Please select a group to save privileges for.">Wählen Sie eine Gruppe aus, für die Sie Berechtigungen speichern.</string>
  <string id="Please select a profile to view its settings.">Wählen Sie ein Profil aus, um dessen Einstellungen anzuzeigen.</string>
  <string id="Please select the Group to delete.">Wählen Sie die zu löschende Gruppe aus.</string>
  <string id="Please select the report to delete.">Wählen Sie den zu löschenden Bericht aus.</string>
  <string id="Please select the report to edit.">Wählen Sie den zu bearbeitenden Bericht aus.</string>
  <string id="Please select the report to run.">Wählen Sie den auszuführenden Bericht aus.</string>
  <string id="Please specify a port:">Anschluss angeben:</string>
  <string id="Please Verify MinMax, Length and Required Settings.">Überprüfen Sie Min/Max, Länge und erforderliche Einstellungen.</string>
  <string id="Policy Last Applied">Zuletzt angewendete Richtlinie</string>
  <string id="Policy Update">Richtlinienaktualisierung</string>
  <string id="Policy Update has Completed for...">Richtlinienaktualisierung abgeschlossen für...</string>
  <string id="Policy Update in Progress for...">Richtlinienaktualisierung wird ausgeführt für...</string>
  <string id="Policy Update on all effected Device Groups.">Richtlinienaktualisierung für alle gültigen Gerätegruppen.</string>
  <string id="Port">Anschluss</string>
  <string id="Port:">Anschluss:</string>
  <string id="Present">Aktuell</string>
  <string id="Previous">Zurück</string>
  <string id="Print (Default)">Drucken (Standard)</string>
  <string id="Print and Forward">Drucken  Weiterleiten</string>
  <string id="Printer Panel">Druckerbedienfeld</string>
  <string id="Printer Report">Druckerbericht</string>
  <string id="Privileges">Rechte</string>
  <string id="Process finished with exit code 0">Prozess mit Beendigungscode 0 beendet</string>
  <string id="Profile Filters">Profilfilter</string>
  <string id="Profile:">Profil:</string>
  <string id="Profiles">Profil</string>
  <string id="Profiles :">Profile:</string>
  <string id="Profiles:">Profile:</string>
  <string id="Progress %">Fortschritt %</string>
  <string id="Property Tag">Kennzeichnung</string>
  <string id="Property Tag:">Kennzeichnung:</string>
  <string id="Quality :">Qualität:</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">Wiederholung</string>
  <string id="Refresh">Aktualisieren</string>
  <string id="Refresh Defaults">Standardwerte aktualisieren</string>
  <string id="Regular Expression">Regulärer Ausdruck</string>
  <string id="Release Held Faxes">Zurückgehaltene Faxe freigeben</string>
  <string id="Remove">Entfernen</string>
  <string id="Remove All">Alle entfernen</string>
  <string id="Remove from System">Aus System entfernen</string>
  <string id="Remove Server(s)">Server entfernen</string>
  <string id="RemoveAll">RemoveAll</string>
  <string id="Removing selected servers...">Ausgewählte Server werden entfernt...</string>
  <string id="Repeat this event :">Dieses Ereignis wiederholen:</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Ersetzen - Löscht die ausgewählte Schaltfläche und ersetzt sie durch die Schaltfläche Ausschneiden.</string>
  <string id="Replace Me">Mich ersetzen</string>
  <string id="Report">Bericht</string>
  <string id="Report by Time">Berichte nach Zeit</string>
  <string id="Report Files">Berichtsdateien</string>
  <string id="Report From">Bericht von</string>
  <string id="Report Name:">Berichtsname:</string>
  <string id="Report Parameters:">Berichtsparameter:</string>
  <string id="Report To">Bericht an</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME erfolgreich generiert</string>
  <string id="Reporting Period">Berichtszeitraum</string>
  <string id="Reports">Berichte</string>
  <string id="Reports:">Berichte:</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">Anforderung abgelaufen. Grenzen Sie die Suchkriterien ein und wiederholen Sie den Vorgang.</string>
  <string id="Required field">Pflichtfeld</string>
  <string id="Reset">Zurücksetzen</string>
  <string id="Reset Filter">Filter zurücksetzen</string>
  <string id="Reset to Default">Auf Standard zurücksetzen</string>
  <string id="Resolution :">Auflösung:</string>
  <string id="Return to Original">Zurück zum Original</string>
  <string id="Retype New Password:">Neues Kennwort erneut eingeben:</string>
  <string id="Retype New Username:">Neuen Benutzernamen erneut eingeben:</string>
  <string id="Run on All Servers">Auf allen Servern ausführen</string>
  <string id="Run Report">Bericht ausführen</string>
  <string id="Running">Wird ausgeführt</string>
  <string id="Running Tasks">Aufgaben werden ausgeführt</string>
  <string id="Running...">Wird ausgeführt...</string>
  <string id="Sat">Sam</string>
  <string id="Save">Speichern</string>
  <string id="Save Privileges">Rechte speichern</string>
  <string id="Save Settings">Einstellungen speichern</string>
  <string id="Save To">Speichern in</string>
  <string id="Saving eSF Settings...">eSF-Einstellungen werden gespeichert...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>  
  <string id="Saving LDAP Settings...">LDAP-Einstellungen werden gespeichert...</string>
  <string id="Schedule">Planen</string>
  <string id="Scheduled task createdupdated">Geplante Aufgabe wurde erstellt/aktualisiert</string>
  <string id="Scheduled task deleted">Geplante Aufgabe wurde gelöscht</string>
  <string id="Scheduled tasks for all client groups:">Geplante Aufgaben für alle Clientgruppen:</string>
  <string id="Scheduled tasks for all device groups:">Geplante Aufgaben für alle Gerätegruppen:</string>
  <string id="Script">Skript</string>
  <string id="Script:">Skript:</string>
  <string id="Search">Suchen</string>
  <string id="Search Base:">Suchbasis:</string>
  <string id="Search Held Jobs">Angehaltene Jobs suchen</string>
  <string id="Search LDAP for Groups:">LDAP für Gruppen suchen:</string>
  <string id="Searching...">Wird gesucht...</string>
  <string id="Second">Sekunde</string>
  <string id="Secure Server Communication">Sichere Serverkommunikation</string>
  <string id="Secure Server Communication:">Sichere Serverkommunikation:</string>
  <string id="Security">Sicherheit</string>
  <string id="Security setting updated.">Sicherheitseinstellung wurde aktualisiert.</string>
  <string id="Security setup file updated successfully">Sicherheits-Setupdatei wurde erfolgreich aktualisiert</string>
  <string id="Security setup file update failed">Fehler beim Aktualisieren der Sicherheits-Setupdatei</string>
  <string id="Select a Group Name:">Gruppennamen auswählen:</string>
  <string id="Select a report">Bericht auswählen</string>
  <string id="Select a script task">Skriptaufgabe auswählen</string>
  <string id="Select one...">Eines auswählen...</string>
  <string id="Select Profile...">Profil auswählen...</string>
  <string id="Select the group to copy">Zu kopierende Gruppe auswählen</string>
  <string id="Sent when any leaf is checked or unchecked, in">Bei Aktivierung/Deaktivierung eines beliebigen Blatts gesendet in</string>
  <string id="Serial Number">Seriennummer</string>
  <string id="Serial Number:">Seriennummer:</string>
  <string id="Server Address">Serveradresse</string>
  <string id="Server Address:">Serveradresse:</string>
  <string id="Server handling this LMC session">Server, der diese LMC-Sitzung behandelt</string>
  <string id="Server is currently offline">Server ist gerade offline</string>
  <string id="Server is not communicating">Server kommuniziert nicht</string>
  <string id="Server is unlicensed">Server ist nicht lizenziert</string>
  <string id="Server Port:">Serveranschluss:</string>
  <string id="Server Report">Serverbericht</string>
  <string id="Server(s) Error">Serverfehler</string>
  <string id="Server(s) Offline">Server offline</string>
  <string id="Servers">Server</string>
  <string id="Service settings updated">Diensteinstellungen aktualisiert</string>
  <string id="Services">Dienste</string>
  <string id="Set Offline">Offline schalten</string>
  <string id="Set Online">Online schalten</string>
  <string id="Setting selected servers offline...">Ausgewählte Server werden offline geschaltet...</string>
  <string id="Setting selected servers online...">Ausgewählte Server werden online geschaltet...</string>
  <string id="Settings :">Einstellungen:</string>
  <string id="Settings:">Einstellungen:</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task home screen updated.">SFP e-Task-Startbildschirm wurde aktualisiert.</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated.">SFP e-Task2-Startbildschirm wurde aktualisiert.</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated.">SFP e-Task2+-Startbildschirm wurde aktualisiert.</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated.">SFP e-Task3-Startbildschirm wurde aktualisiert.</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4 (7 Zoll)</string>
  <string id="SFP e-Task4 (7in.) home screen updated.">SFP e-Task4 (7 Zoll)-Startbildschirm wurde aktualisiert.</string>
  <string id="SFP e-Task4 home screen updated.">SFP e-Task4-Startbildschirm wurde aktualisiert.</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">Verknüpfung</string>
  <string id="Shortcut :">Verknüpfung:</string>
  <string id="Shortcut:">Verknüpfung:</string>
  <string id="Show Settings">Einstellungen anzeigen</string>
  <string id="Since Last Month">Seit letztem Monat</string>
  <string id="Since Yesterday">Seit gestern</string>
  <string id="Single Profile">Einzelprofil</string>
  <string id="SNMP Timeout Retries:">SNMP Wiederholungen nach Zeitüberschreitung:</string>
  <string id="Software Client Group">Softwareclient-Gruppe</string>
  <string id="Software Client Group created">Softwareclientgruppe erstellt</string>
  <string id="Software Client Group:">Softwareclient-Gruppe:</string>
  <string id="Software Client Groups">Softwareclient-Gruppen</string>
  <string id="Software Client Report">Softwareclientbericht</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">Lösung</string>
  <string id="Solution deleted from software client group.">Lösung aus Softwareclientgruppe gelöscht.</string>
  <string id="Solution deployed to device group">Lösung für Gerätegruppe bereitgestellt</string>
  <string id="Solution deployed to software client group">Lösung für Softwareclientgruppe bereitgestellt</string>
  <string id="Solution Name">Name der Lösung</string>
  <string id="Solution Name:">Name der Lösung:</string>
  <string id="Solution Report">Lösungsbericht</string>
  <string id="Solution settings updated.">Lösungseinstellungen aktualisiert.</string>
  <string id="Solution: Deleting device group deployment...">Lösung: Bereitstellung der Gerätegruppe wird gelöscht...</string>
  <string id="Solution: Deleting solution from software client group...">Lösung: Lösung wird aus Softwareclientgruppe gelöscht...</string>
  <string id="Solution: device group deployment deleted.">Lösung: Bereitstellung der Gerätegruppe gelöscht.</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">Lösungen</string>
  <string id="Solutions to deploy:">Bereitzustellende Lösungen:</string>
  <string id="Solutions:">Lösungen:</string>
  <string id="Specify Restore system information">Informationen zur Systemwiederherstellung angeben</string>
  <string id="Specify where the generated report should be saved">Speicherort für den generierten Bericht angeben</string>
  <string id="Start Button Default Action">Standardaktion der Start-Schaltfläche</string>
  <string id="Start Date :">Startdatum:</string>
  <string id="Start Time">Startzeit</string>
  <string id="Start Time:">Startzeit:</string>
  <string id="State">Zustand</string>
  <string id="Status">Status</string>
  <string id="Steps for viewing device information:">Schritte zum Anzeigen von Geräteinformationen:</string>
  <string id="Stop">Beenden</string>
  <string id="Stop Task">Aufgabe anhalten</string>
  <string id="Subform">Teilformular</string>
  <string id="Subject:">Betreff:</string>
  <string id="Success">Erfolgreich</string>
  <string id="Successfully added the group.">Gruppe erfolgreich hinzugefügt.</string>
  <string id="Successfully Deleted All Solution(s) from the System.">Alle Lösungen erfolgreich aus dem System gelöscht.</string>
  <string id="Successfully Deleted Solution(s) from the System.">Lösungen erfolgreich aus dem System gelöscht.</string>
  <string id="Successfully Imported Solution(s) into the System.">Lösungen erfolgreich in das System importiert.</string>
  <string id="Summary">Zusammenfassung</string>
  <string id="Sun">So</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Umschalten - Wechselt die Position zwischen der ausgewählten Schaltfläche und der Schaltfläche Ausschneiden.</string>
  <string id="System">System</string>
  <string id="System Health...">Systemzustand...</string>
  <string id="System Status">Systemstatus</string>
  <string id="System Status 1">Systemstatus 1</string>
  <string id="Task Id">Aufgaben-ID</string>
  <string id="Task Id:">Aufgaben-ID:</string>
  <string id="Task Name">Aufgabenname</string>
  <string id="Task Name:">Aufgabenname:</string>
  <string id="Task Summary Report">Aufgabenzusammenfassungsbericht</string>
  <string id="Test Progress">Testfortschritt</string>
  <string id="Test Results">Testergebnisse</string>
  <string id="Test Settings">Testeinstellungen</string>
  <string id="Testing LDAP Settings...">LDAP-Einstellungen werden getestet...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">Die Schaltflächen auf dem ersten Bildschirm können individuell angeordnet werden.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">Der folgende Bericht wurde erfolgreich generiert:  REPORT_NAME.  Zeigen Sie den angehängten Bericht an.</string>
  <string id="The password provided is incorrect.">Das eingegebene Kennwort ist falsch.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">Die Bereitstellung dieser Gruppenrichtlinie wird jetzt auf allen Geräten in der Gruppe aufgehoben.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">Der Bericht ist jetzt bereit zum Herunterladen. Klicken Sie zum Fortfahren auf 'OK'.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">Das 'Bis'-Datum des Berichtszeitraums liegt vor dem 'Von'-Datum.  Die Angaben werden beim Generieren des Berichts automatisch umgekehrt.  Möchten Sie fortfahren?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">Für diese Softwareclientgruppe sind derzeit keine Clientprofile vorhanden. Fügen Sie sie hinzu, indem Sie die Felder oben ausfüllen.</string>
  <string id="There are currently no cSF Apps associated with this device group.">Derzeit sind dieser Gerätegruppe keine cSF-Apps zugeordnet.</string>
  <string id="There are currently no cSF Apps to add to this device group.">Derzeit sind keine cSF-Apps verfügbar, die dieser Gerätegruppe hinzugefügt werden können.</string>  
  <string id="There are currently no device groups to perform discovery.">Derzeit sind keine Gerätegruppen verfügbar, für die eine Suche ausgeführt werden kann.</string>
  <string id="There are currently no device groups to perform policy update.">Derzeit sind keine Gerätegruppen verfügbar, um die Richtlinienaktualisierung auszuführen.</string>
  <string id="There are currently no device groups to schedule.">Derzeit sind keine Gerätegruppen zur Planung verfügbar.</string>
  <string id="There are currently no device groups.  Please add a device group by clicking on the Add button on the left.">Derzeit sind keine Gerätegruppen vorhanden.  Fügen Sie eine Gerätegruppe hinzu, indem Sie auf die Schaltfläche 'Hinzufügen' links klicken.</string>
  <string id="There are currently no devices discovered for this device group.">Aktuell wurden keine Geräte für diese Gerätegruppe gefunden.</string>
  <string id="There are currently no devices in this device group.">Derzeit befinden sich keine Geräte in dieser Gerätegruppe.</string>
  <string id="There are currently no discovered devices.">Derzeit wurden noch keine Geräte gefunden.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">Derzeit sind keine Suchprofile für diese Gerätegruppe vorhanden. Fügen Sie sie hinzu, indem Sie die entsprechenden Felder oben ausfüllen.</string>
  <string id="There are currently no forms printers in the system.">Derzeit befinden sich keine Formulardrucker im System.</string>
  <string id="There are currently no licenses installed.">Derzeit sind keine Lizenzen installiert.</string>
  <string id="There are currently no licensing changes made by this upload.">Aktuell wurden keine Lizenzänderungen durch dieses Upload vorgenommen.</string>
  <string id="There are currently no missing devices for this device group.">Derzeit gibt es keine fehlenden Geräte für diese Gerätegruppe.</string>
  <string id="There are currently no missing devices.">Derzeit gibt es keine fehlenden Geräte.</string>
  <string id="There are currently no out of policy devices for this device group.">Derzeit weichen keine Geräte dieser Gerätegruppe von Richtlinien ab.</string>
  <string id="There are currently no out of policy devices.">Derzeit weichen keine Geräte von Richtlinien ab.</string>
  <string id="There are currently no scheduled tasks">Derzeit sind keine geplanten Aufgaben verfügbar</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">Derzeit sind keine Softwareclientgruppen verfügbar.  Fügen Sie eine Gruppe hinzu, indem Sie auf die Schaltfläche 'Hinzufügen' links klicken.</string>
  <string id="There are currently no solutions associated with this device group.">Derzeit sind dieser Gerätegruppe keine Lösungen zugeordnet.</string>
  <string id="There are currently no solutions associated with this software client group.">Derzeit sind dieser Softwareclientgruppe keine Lösungen zugeordnet.</string>
  <string id="There are currently no solutions installed.">Derzeit sind keine Lösungen installiert.</string>
  <string id="There are currently no solutions to add to this device group.">Derzeit sind keine Lösungen verfügbar, die dieser Gerätegruppe hinzugefügt werden können.</string>
  <string id="There are currently no solutions to add to this software client group.">Derzeit sind keine Lösungen verfügbar, die dieser Softwareclientgruppe hinzugefügt werden können.</string>
  <string id="There are currently no unlicensed devices for this device group.">Aktuell wurden keine nicht lizenzierten Geräte für diese Gerätegruppe gefunden.</string>
  <string id="There are currently no unlicensed devices in this device group.">Derzeit befinden sich keine nicht lizenzierten Geräte in dieser Gerätegruppe.</string>
  <string id="There are currently no unlicensed devices.">Derzeit wurden noch keine nicht lizenzierten Geräte gefunden.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">Derzeit sind Lösungen oder cSF-Apps und/oder Startbildschirme mit der Richtlinie dieser Gruppe verknüpft. Möchten Sie die Bereitstellung dieser Richtlinie jetzt aufheben? Beachten Sie, dass die Gerätegruppe dadurch nicht sofort gelöscht wird. Entfernen Sie die Gerätegruppe, nachdem die Richtlinienaktualisierung beendet wurde.</string>
  <string id="There are no associated UCF Files for this Solution.">Dieser Lösung wurden keine Sicherheits-Setupdateien zugeordnet.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">Den Lösungen in dieser Gerätegruppe sind derzeit keine Sicherheits-Setupdateien zugeordnet.</string>
  <string id="There are no configuration settings for this eSF application.">Für diese eSF-Anwendung sind keine Konfigurationseinstellungen vorhanden.</string>
  <string id="There are no configuration settings in this solution.">In dieser Lösung sind keine Konfigurationseinstellungen vorhanden.</string>
  <string id="There are no configuration settings in this webapp.">In dieser Web-App sind keine Konfigurationseinstellungen vorhanden.</string>
  <string id="There are no cSF Apps installed currently.">Derzeit sind keine cSF-Apps installiert.</string>
  <string id="There are no deployments setting for this solution.">Für diese Lösung ist keine Bereitstellungseinstellung vorhanden.</string>
  <string id="There are no devices in the system that match the filter.">Im System sind keine Geräte vorhanden, die die Filterkriterien erfüllen.</string>
  <string id="There are no eSF Applications for this solution.">Es sind keine eSF-Anwendungen für diese Lösung verfügbar.</string>
  <string id="There are no e-Task profiles for this device group.">Es sind keine e-Task-Profile für diese Gerätegruppe verfügbar.</string>
  <string id="There are no e-Task2 profiles for this device group.">Es sind keine e-Task2-Profile für diese Gerätegruppe verfügbar.</string>
  <string id="There are no forms for this solution.">Es sind keine Formulare für diese Lösung verfügbar.</string>
  <string id="There are no forms in the system.">Es sind keine Formulare im System vorhanden.</string>
  <string id="There are no parameters in this service.">In diesem Dienst sind keine Parameter vorhanden.</string>
  <string id="There are no profiles for this software client group.">Es sind keine Profile für diese Softwareclientgruppe verfügbar.</string>
  <string id="There are no settings for this action.">Für diese Aktion sind keine Einstellungen vorhanden.</string>
  <string id="There are no settings for this solution.">Für diese Lösung sind keine Einstellungen vorhanden.</string>
  <string id="There is currently a Policy Update running...">Richtlinienaktualisierung wird gerade ausgeführt...</string>
  <string id="There is currently no Version Info.">Derzeit sind keine Versionsinformationen verfügbar.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">Diese eSF-Anwendungen sind Teil der Lösungen, die dieser Gerätegruppe zugewiesen sind. Wählen Sie eine Anwendung aus, um die Einstellungen anzuzeigen.</string>
  <string id="These group settings are currently hidden.">Diese Gruppeneinstellungen sind derzeit ausgeblendet.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">Diese Profile sind Teil der Gruppenrichtlinie für jedes Modell. Wählen Sie ein Profil für jedes Modell aus, um dessen Einstellungen anzuzeigen.</string>
  <string id="Third">Dritte</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">Über diesen Link werden Sie zur Benutzeroberfläche der Lexmark Webkit-Konfiguration weitergeleitet. Möchten Sie fortfahren?</string>
  <string id="This Month">Dieser Monat</string>
  <string id="This name has been given to another device group. Please choose a different name.">Dieser Name wurde einer anderen Gerätegruppe zugewiesen. Wählen Sie einen anderen Namen.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">Dieser Name wurde einer anderen Softwareclientgruppe zugewiesen. Wählen Sie einen anderen Namen.</string>
  <string id="Thread Count">Threadanzahl</string>
  <string id="Thu">Do</string>
  <string id="Time">Uhrzeit</string>
  <string id="Time of Next Run">Letzte Ausführung</string>
  <string id="Time Policies Last Applied">Zuletzt angewendete Zeitrichtlinien</string>
  <string id="Time:">Uhrzeit:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">Um sie dem Startbildschirm hinzuzufügen, wählen Sie aus dem Dropdown-Feld oben ein benutzerdefiniertes Layout aus und fügen die Profile hinzu.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">Um sie selbst anzuordnen, wählen Sie aus dem Dropdown-Feld oben eines der Layouts aus.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">Um selbst eins zu konfigurieren, wählen Sie aus dem Dropdown-Feld oben eines der Layouts aus.</string>
  <string id="To:">An:</string>
  <string id="Today">Heute</string>
  <string id="Today date">Heutiges Datum</string>
  <string id="Tops Report">Hauptnutzungsbericht</string>
  <string id="Tue">Die</string>
  <string id="UCF">Sicherheits-Setupdateien</string>
  <string id="UCF:">Sicherheits-Setupdateien:</string>  
  <string id="Unable to Change Password.">Kennwort kann nicht geändert werden.</string>
  <string id="Unable to Change Username.">Benutzername kann nicht geändert werden.</string>
  <string id="Unable to validate all settings!">Es können keine Einstellungen überprüft werden.</string>
  <string id="Uncounted">Ungezählt</string>
  <string id="Un-deploying all cSF Apps(s)...">Bereitstellung aller cSF-Apps wird aufgehoben...</string>
  <string id="Un-deploying cSF App(s)...">Bereitstellung von cSF-App(s) wird aufgehoben...</string>
  <string id="Unknown">Unbekannt</string>
  <string id="Unknown Error Occured! Please Check System Log">Unbekannter Fehler. Überprüfen Sie das Systemprotokoll</string>
  <string id="Unknown Secure State">Unbekannter Sicherheitsstatus</string>
  <string id="Unlicensed">Nicht lizenziert</string>
  <string id="Unlicensed Device">Nicht lizenziertes Gerät</string>
  <string id="Unlicensed Devices">Nicht lizenzierte Geräte</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Nicht lizenzierte Geräte sind Geräte, die bereits einmal gefunden wurden, aber während der letzten Suche nicht ermittelt wurden; ihnen konnte keine Lizenz zugewiesen werden. (Da die Lizenz beispielsweise abgelaufen ist oder alle Lizenzen in Gebrauch sind.)</string>
  <string id="Unlicensed devices:">Nicht lizenzierte Geräte:</string>
  <string id="Unlicensed Devices:">Nicht lizenzierte Geräte:</string>
  <string id="Unlicensed:">Nicht lizenziert:</string>
  <string id="Unlimited">Unbegrenzt</string>
  <string id="Up icon:">Nicht gedrückt (Symbol):</string>
  <string id="Update">Aktualisieren</string>
  <string id="Update Policy">Richtlinie aktualisieren</string>
  <string id="Update Time">Aktualisierungszeit</string>
  <string id="Update Time:">Aktualisierungszeit:</string>
  <string id="Updating client profile...">Clientprofil wird aktualisiert...</string>
  <string id="Updating discovery profile...">Suchprofil wird aktualisiert...</string>
  <string id="Updating e-Task home screen...">e-Task-Startbildschirm wird aktualisiert...</string>
  <string id="Updating e-Task2 home screen...">e-Task2-Startbildschirm wird aktualisiert...</string>
  <string id="Updating e-Task2+ home screen...">e-Task2+-Startbildschirm wird aktualisiert...</string>
  <string id="Updating e-Task3 home screen...">e-Task3-Startbildschirm wird aktualisiert...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">e-Task4 (4,3 Zoll)-Startbildschirm wird aktualisiert...</string>
  <string id="Updating e-Task4 home screen...">e-Task4-Startbildschirm wird aktualisiert...</string>
  <string id="Updating Fax Forward settings...">Einstellungen für die Faxweiterleitung werden aktualisiert...</string>
  <string id="Updating password...">Kennwort wird aktualisiert...</string>
  <string id="Updating Security setting...">Sicherheitseinstellung wird aktualisiert...</string>
  <string id="Updating service settings...">Diensteinstellungen werden aktualisiert...</string>
  <string id="Updating SFP e-Task home screen...">SFP e-Task-Startbildschirm wird aktualisiert...</string>
  <string id="Updating SFP e-Task2 home screen...">SFP e-Task2-Startbildschirm wird aktualisiert...</string>
  <string id="Updating SFP e-Task2+ home screen...">SFP e-Task2+-Startbildschirm wird aktualisiert...</string>
  <string id="Updating SFP e-Task3 home screen...">SFP e-Task3-Startbildschirm wird aktualisiert...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen...">SFP e-Task4 (7 Zoll)-Startbildschirm wird aktualisiert...</string>
  <string id="Updating SFP e-Task4 home screen...">SFP e-Task4-Startbildschirm wird aktualisiert...</string>
  <string id="Updating solution settings...">Lösungseinstellungen werden aktualisiert...</string>
  <string id="Updating username...">Benutzername wird aktualisiert...</string>
  <string id="Updating X642 home screen...">X642-Startbildschirm wird aktualisiert...</string>
  <string id="Updating webapp settings...">WebApp-Einstellungen werden aktualisiert...</string>
  <string id="Upgrading or deleting solutions here will require">Die Aktualisierung oder das Löschen von Lösungen an dieser Stelle erfordert</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">Das Upgrade oder Aufheben der Bereitstellung von cSF-Apps erfordert eine &lt;b&gt;Richtlinienaktualisierung&lt;/b&gt; für alle betroffenen Gerätegruppen</string>
  <string id="Upload">Hochladen</string>
  <string id="Upload custom icons">Benutzerdefinierte Symbole hochladen</string>
  <string id="Upload Report Files">Berichtsdateien hochladen</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">Upload von AP-Bundle- und Deskriptordatei abgeschlossen.</string>
  <string id="Uploading AP Bundle and Descriptor...">Upload von AP-Bundle- und Deskriptordatei wird ausgeführt...</string>
  <string id="Uploading cSF Ap cert files....">cSF-App-Zertifikatdateien werden hochgeladen...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">cSF-App-Zertifikatdateien ('cacert.pem' und 'key.pem') werden hochgeladen...</string>
  <string id="Uploading of cSF App cert files Completed.">Upload von cSF-App-Zertifikatdateien abgeschlossen.</string>
  <string id="Uploading Report(s)...">Berichte werden hochgeladen...</string>
  <string id="Uploading...">Wird hochgeladen...</string>
  <string id="Usage:">Verbrauch:</string>
  <string id="Usb Drive">USB-Laufwerk</string>
  <string id="Use default settings">Standardeinstellungen verwenden</string>
  <string id="Use Secure Connection. (SSLTLS)">Sichere Verbindung verwenden. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Lösungskonfiguration verwenden</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">Verwenden Sie dieses Dialogfeld nur für die Datenbank, wenn zentrale webdav-Daten des vorhandenen LDD-Systems mit einem anderen aktiven LDD-System synchronisiert werden müssen, das als LDD-Backupsystem fungiert. Informationen zu dieser Funktion finden Sie im Administratorhandbuch.</string>
  <string id="Use this home screen as part of the device groups policy.">Verwenden Sie diesen Startbildschirm als Teil der Gerätegruppen-Richtlinie.</string>  
  <string id="Used:">Verwendet:</string>
  <string id="User Name">Benutzername</string>
  <string id="User Name:">Benutzername:</string>
  <string id="User Report">Benutzerbericht</string>
  <string id="User Search Base:">Benutzersuchbasis:</string>
  <string id="User Search Filter:">Benutzersuchfilter:</string>
  <string id="Username amp; Password">Benutzername &amp;amp; Kennwort</string>
  <string id="Username and Password">Benutzername und Kennwort</string>
  <string id="Username Changed Successfully.">Benutzername erfolgreich geändert.</string>
  <string id="Username Password">Benutzername Kennwort</string>
  <string id="Username updated.">Benutzername aktualisiert.</string>
  <string id="Username*">Benutzername*</string>
  <string id="Username:">Benutzername:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Überprüfen Sie die Bereitstellung der eSF-Anwendung und stellen Sie diese eSF-Einstellungen bereit.</string>
  <string id="Version">Version</string>
  <string id="Version Info:">Versionsinfo:</string>
  <string id="Version:">Version:</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">Sehr sehr sehr langer langer langer Text</string>
  <string id="View Details">Details anzeigen</string>
  <string id="View Source">Quelle anzeigen</string>
  <string id="Waiting for License Upload Results ...">Auf Ergebnisse des Lizenz-Uploads wird gewartet...</string>
  <string id="WebApps">WebApps</string>
  <string id="WebClient Version">WebClient-Version</string>
  <string id="WebClient Version:">WebClient-Version:</string>
  <string id="Wed">Mi</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated.">X642-Startbildschirm aktualisiert.</string>
  <string id="Yes">Ja</string>
  <string id="You are viewing the Kranked version of the application">Sie zeigen die Kranked-Version der Anwendung an</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">Sie sind nicht berechtigt, auf eine der Aufgaben in 'Alle cSF-Apps' zuzugreifen.</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">Sie sind nicht berechtigt, auf eine der Aufgaben in Alle Gerätegruppen zuzugreifen.</string>
  <string id="You have no privilege to this task.">Sie haben keine Berechtigung für diese Aufgabe.</string>
  <string id="You must first select a Task to Edit">Sie müssen erst eine Aufgabe zur Bearbeitung auswählen.</string>
  <string id="active">aktiv</string>
  <string id="active:">aktiv:</string>
  <string id="addition to the two events below.">zusätzlich zu den beiden Ereignissen unten.</string>
  <string id="avg response (ms)">durchschnittl. Antwort (ms)</string>
  <string id="be set back to the default values next time.">werden nächstes Mal auf die Standardwerte zurückgesetzt.</string>
  <string id="cache">Cache</string>
  <string id="cc:">Cc:</string>
  <string id="change">ändern</string>
  <string id="cSF App">cSF-App</string>
  <string id="cSF App Cert File">cSF-App-Zertifikatdatei</string>
  <string id="cSF App Certificates">cSF-App-Zertifikate</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">Upload der cSF-App-Zertifikate ('cacert.pem', 'key.pem')</string>
  <string id="cSF App Key File">cSF-App-Schlüsseldatei</string>
  <string id="cSF App settings updated.">cSF-App-Einstellungen aktualisiert.</string>
  <string id="cSF App Version">cSF-App-Version</string>
  <string id="cSF App Version:">cSF-App-Version:</string>
  <string id="cSF Apps">cSF-Apps</string>
  <string id="cSF Apps deployed to device group">cSF-Apps für Gerätegruppe bereitgestellt</string>
  <string id="cSF Apps to deploy:">Bereitzustellende cSF-Apps:</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF-Apps: Bereitstellung der Gerätegruppe gelöscht.</string>
  <string id="day(s)">Tag(e)</string>
  <string id="devices failed">Geräte fehlerhaft</string>
  <string id="devices updated">Geräte aktualisiert</string>
  <string id="device(s) discovered">Gerät(e) gefunden</string>
  <string id="device(s) missing">Geräte fehlen</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">eSF-Anwendungseinstellungen:</string>
  <string id="eSF Application Version:">eSF-Anwendungsversion:</string>
  <string id="eSF Applications">eSF-Anwendungen</string>
  <string id="eSF Applications:">eSF-Anwendungen:</string>
  <string id="eSF Applications: (Solution)">eSF-Anwendungen: (Lösung)</string>
  <string id="eSF Configuration">eSF-Konfiguration</string>
  <string id="eSF Settings Saved.">eSF-Einstellungen gespeichert.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">e-Task-Startbildschirm aktualisiert.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated.">e-Task2-Startbildschirm aktualisiert.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated.">e-Task2+-Startbildschirm aktualisiert.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated.">e-Task3-Startbildschirm aktualisiert.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4,3 Zoll)</string>
  <string id="e-Task4 (4.3 in.) home screen updated.">e-Task4 (4,3 Zoll)-Startbildschirm aktualisiert.</string>
  <string id="e-Task4 home screen updated.">e-Task4-Startbildschirm aktualisiert.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">fehlerhaft.</string>
  <string id="hide">ausblenden</string>
  <string id="hour(s)">Stunde(n)</string>
  <string id="in order to add a group.">um eine Gruppe hinzuzufügen.</string>
  <string id="info">Info</string>
  <string id="load">laden</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">Minute(n)</string>
  <string id="month(s)">Monat(e)</string>
  <string id="not communicating">Keine Kommunikation</string>
  <string id="null">NULL</string>
  <string id="offline">offline</string>
  <string id="on">Ein</string>
  <string id="on all effected Device Groups.">für alle gültigen Gerätegruppen.</string>
  <string id="oncheck">oncheck</string>
  <string id="online">online</string>
  <string id="or home screen support for this device does not exist.">oder Startbildschirm-Unterstützung für dieses Gerät ist nicht vorhanden.</string>
  <string id="requests">Anforderungen</string>
  <string id="requests/sec">Anforderungen/s</string>
  <string id="saving report...">Bericht wird gespeichert...</string>
  <string id="server">Server</string>
  <string id="show">anzeigen</string>
  <string id="test">Testen</string>
  <string id="to">zu</string>
  <string id="to change them.">um sie zu ändern.</string>
  <string id="to take effect on the devices.">um sie für Geräte durchzusetzen.</string>
  <string id="total requests:">Gesamtanforderungen:</string>
  <string id="total responses:">Gesamtantworten:</string>
  <string id="undo">Rückgängig</string>
  <string id="uploaded.">hochgeladen.</string>
  <string id="week(s)">Woche(n)</string>
  <string id="{0} Groups">{0} Gruppen</string>
  <string id="{0} Reports">{0} Berichte</string>
  <string id="{0} Software Client Groups">{0} Softwareclientgruppen</string>
  <string id="{0} Solutions">{0} Lösungen</string>
  <string id="{0} eForms">{0} eForms</string>
  <string id="{0} eSF Applications">{0} eSF-Anwendungen</string>
  <string id="Policy update required for changes to take effect on the devices">Damit die hier vorgenommenen Änderungen auf den Geräten wirksam werden, ist eine &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Richtlinienänderung&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; erforderlich.</string>
  <string id="Group search base must be set for adding group based Privileges">Zum Hinzufügen gruppenbasierter &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Rechte&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; muss eine Gruppen-Suchbasis festgelegt werden</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">Um eine Gruppe hinzuzufügen, muss die Gruppen-Suchbasis in der &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP-Einrichtung&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; festgelegt werden.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">Für SMB-lizenzierte Installation! MFP-Lizenzen sind auf eine maximale Anzahl von</string>
  <string id="licenses!">Lizenzen beschränkt!</string>
</localize>
`;