export const KO = `
<localize>
  <string id="% Completed">% 완료됨</string>
  <string id="% Completed:">% 완료됨:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">(선택 사항) 설명을 입력하십시오.</string>
  <string id="( Username must be a Distinguished Name )">(사용자 이름은 고유 이름이어야 함)</string>
  <string id="(1-999)">(1-999)</string>
  <string id="(Cron expression)">(Cron 표현식)</string>
  <string id="(progress)">(진행률)</string>
  <string id="* Software Client License Not Found.">* 소프트웨어 클라이언트 라이센스를 찾을 수 없습니다.</string>
  <string id="[EXTERNAL]">[내부]</string>
  <string id="[None]">[없음]</string>
  <string id="1 Button">1개 단추</string>
  <string id="1 minute load">1분 로드</string>
  <string id="1. cSF Apps">1. cSF 앱</string>
  <string id="1. Device Groups">1. 장치 그룹</string>
  <string id="1. Search">1. 검색</string>
  <string id="1. Services">1. 서비스</string>
  <string id="1. Software Client Groups">1. 소프트웨어 클라이언트 그룹</string>
  <string id="1. Solutions">1. 솔루션</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. 검색 조건을 입력하고 &quot;검색&quot; 단추를 누르십시오.</string>
  <string id="1. WebApps">1. 웹 앱</string>
  <string id="10 Buttons">10개 단추</string>
  <string id="15 minute load">15분 로드</string>
  <string id="15sec">15초</string>
  <string id="2 Buttons">2개 단추</string>
  <string id="2. Choose one or more devices if any are found.">2. 검색된 장치를 하나 이상 선택하십시오.</string>
  <string id="2. Devices">2. 장치</string>
  <string id="2. Tasks">2. 작업</string>
  <string id="3 Buttons">3개 단추</string>
  <string id="3. Choose a Task.">3. 작업을 선택하십시오.</string>
  <string id="3. Tasks">3. 작업</string>
  <string id="30sec">30초</string>
  <string id="4 Buttons">4개 단추</string>
  <string id="4-16 Buttons">4-16개 단추</string>
  <string id="5 Buttons">5개 단추</string>
  <string id="5 minute load">5분 로드</string>
  <string id="5sec">5초</string>
  <string id="6 Buttons">6개 단추</string>
  <string id="60sec">60초</string>
  <string id="7 Buttons">7개 단추</string>
  <string id="8 Buttons">8개 단추</string>
  <string id="9 Buttons">9개 단추</string>
  <string id="A Policy Update is currently running...">정책 업데이트 실행 중...</string>
  <string id="About">정보</string>
  <string id="Action">작업</string>
  <string id="Action Settings...">작업 설정...</string>
  <string id="Action Settings:">작업 설정:</string>
  <string id="Action:">작업:</string>
  <string id="Add">추가</string>
  <string id="Add a cSF App to deploy:"> 배포할 cSF 앱 추가:</string>
  <string id="Add a new Group to the system">새 그룹을 시스템에 추가</string>
  <string id="Add a new report to the system">새 보고서를 시스템에 추가</string>
  <string id="Add a solution to deploy: Step 1 of 2"> 배포할 솔루션 추가: 단계 1/2</string>
  <string id="Add a solution to deploy: Step 2 of 2"> 배포할 솔루션 추가: 단계 2/2</string>
  <string id="Add a solution: Step 1 of 2">솔루션 추가: 단계 1/2</string>
  <string id="Add a solution: Step 2 of 2">솔루션 추가: 단계 2/2</string>
  <string id="Add a task to Schedule : Step 1 of 3">예약할 작업 추가: 1/3단계</string>
  <string id="Add Device Group">장치 그룹 추가</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">예약할 장치 그룹 추가: 2/3단계</string>
  <string id="Add Forms Printer">양식 프린터 추가</string>
  <string id="Add License">라이센스 추가</string>
  <string id="Add Software Client Group">소프트웨어 클라이언트 그룹 추가</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">예약할 빈도 추가: 3/3 단계</string>
  <string id="Add...">추가...</string>
  <string id="Adding Formset(s)...">양식 집합 추가 중...</string>
  <string id="Adding Group Name from LDAP...">LDAP에서 그룹 이름 추가 중...</string>
  <string id="Adding solution to software client group...">소프트웨어 클라이언트 그룹에 솔루션 추가 중...</string>
  <string id="Additional Options">추가 옵션</string>
  <string id="Additional Parameters">추가 매개변수</string>
  <string id="Additional Parameters...">추가 매개변수...</string>
  <string id="Additional Report Parameters">추가 보고서 매개변수</string>
  <string id="Address">주소</string>
  <string id="Address:">주소:</string>
  <string id="Admin password:">관리자 암호:</string>
  <string id="All">모두</string>
  <string id="All cSF Apps">모든 cSF 앱</string>
  <string id="All Device Groups">모든 장치 그룹</string>
  <string id="All scheduled tasks for the system.">시스템에 대해 예약된 모든 작업.</string>
  <string id="All scheduled tasks for this device group:">이 장치 그룹에 대해 예약된 모든 작업:</string>
  <string id="All scheduled tasks for this sftClient group">이 sftClient 그룹에 대해 예약된 모든 작업</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">선택한 모든 장치가 시스템에서 완전히 제거됩니다. 이 장치들을 제거하시겠습니까?</string>
  <string id="All Servers Offline">모든 오프라인 서버</string>
  <string id="All Servers Online">모든 온라인 서버</string>
  <string id="All Software Client Groups">모든 소프트웨어 클라이언트 그룹</string>
  <string id="All Solutions">모든 솔루션</string>
  <string id="All Tabs">모든 탭</string>
  <string id="An error occurred while attempting to connect to this device,">이 장치에 연결하는 동안 오류가 발생했습니다.</string>
  <string id="Anonymous">익명</string>
  <string id="Any changes here will require">여기서 모든 변경 사항에는 다음이 필요함</string>
  <string id="Any Changes to the parameters are temporary and will">매개변수에 대한 모든 변경 사항은 임시로 적용되며</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">매개변수에 대한 모든 변경 사항은 임시로 적용되며 다음에 다시 기본값으로 설정됩니다.</string>
  <string id="AP (Advanced Prompting) Bundle Upload">AP(Advanced Prompting) 번들 업로드</string>
  <string id="AP Bundle">AP 번들</string>
  <string id="AP Bundle Application File">AP 번들 응용 프로그램 파일</string>
  <string id="AP Bundle descriptor">AP 번들 설명자</string>
  <string id="AP Bundle Descriptor File">AP 번들 설명자 파일</string>
  <string id="App Reservation">앱 보유</string>
  <string id="Application">응용 프로그램</string>
  <string id="Apply">적용</string>
  <string id="Are you sure you want to change the edited profile?">편집한 프로필을 변경하시겠습니까?</string>
  <string id="Are you sure you want to change these profiles?">이러한 프로파일을 변경하시겠습니까?</string>
  <string id="Are you sure you want to delete all the forms?">모든 양식을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete all the profiles?">모든 프로필을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete all the solutions?">모든 솔루션을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete the selected forms?">선택된 양식을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">선택한 그룹을 삭제하시겠습니까?  이 그룹과 연관된 모든 권한도 자동으로 함께 삭제됩니다.</string>
  <string id="Are you sure you want to delete the selected profiles?">선택된 프로필을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">선택한 보고서를 삭제하시겠습니까?  이 보고서에 대해 예약된 보고서 작업도 자동으로 함께 삭제됩니다.</string>
  <string id="Are you sure you want to delete the selected solutions?">선택한 솔루션을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to delete these profiles?">이러한 프로파일을 삭제하시겠습니까?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">모든 cSF 앱을 배포 해제하시겠습니까?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">선택한 cSF 앱을 배포 해제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">이 +webAppsString.getWebAppString()+?}을(를) 삭제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this Device Group?">이 장치 그룹을 삭제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this forms printer?">이 양식 프린터를 삭제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this scheduled task?">이 예약된 작업을 삭제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this software client Group?">이 소프트웨어 클라이언트 그룹을 삭제하시겠습니까?</string>
  <string id="Are you sure you would like to delete this solution?">이 솔루션을 삭제하시겠습니까?</string>
  <string id="Associated Device Group :">연결된 장치 그룹:</string>
  <string id="Associated Solution :">연결된 솔루션:</string>
  <string id="Associated Solution:">연결된 솔루션:</string>
  <string id="Authentication Method:">인증 방법:</string>
  <string id="Author">작성자</string>
  <string id="Auto Refresh:">자동 새로 고침:</string>
  <string id="Available Columns">사용 가능한 열</string>
  <string id="Available Reports">사용 가능한 보고서</string>
  <string id="Back">뒤로</string>
  <string id="Background Image:">배경 이미지:</string>
  <string id="Backup &amp; Restore information">백업 및 복원 정보</string>
  <string id="Backup amp; Restore">백업 및 복원</string>
  <string id="Backup Jobs Logs Database">백업 작업 로그 데이터베이스</string>
  <string id="Backup Share Path">백업 공유 경로</string>
  <string id="Bar Chart">막대 차트</string>
  <string id="Binary Files">바이너리 파일</string>
  <string id="Bookmarks">책갈피</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">cSF 앱 인증서를 업데이트하려면 cacert.pem 및 key.pem 파일이 모두 필요합니다.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">AP 번들을 업데이트하려면 eSF 플래시 및 설명자 파일이 필요합니다.</string>
  <string id="Browse">찾아보기</string>
  <string id="Browse...">찾아보기...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">기본적으로 MFP는 홈 스크린에서 단추를 자동으로 배열합니다.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">기본적으로 SFP는 프로파일을 보류 작업 폴더에 추가합니다.</string>
  <string id="Cancel">취소</string>
  <string id="Canceled">취소됨</string>
  <string id="Canceling...">취소 중...</string>
  <string id="Change Default Values">기본값 변경</string>
  <string id="Change Language">언어 변경</string>
  <string id="Change Password">암호 변경</string>
  <string id="Change Username">사용자 이름 변경</string>
  <string id="Changing name...">이름 변경 중...</string>
  <string id="Choose a cSF App to deploy:"> 배포할 cSF 앱 선택:</string>
  <string id="Choose a solution to deploy:">배포할 솔루션 선택:</string>
  <string id="Choose a solution:">솔루션 선택:</string>
  <string id="Choose Client Groups">클라이언트 그룹 선택</string>
  <string id="Choose deployment settings for">배포 설정 선택</string>
  <string id="Choose Device Groups">장치 그룹 선택</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">각 단추를 선택하고 해당 작업을 설정합니다. 작업이 없는 단추는 홈 스크린에 표시되지 않습니다.</string>
  <string id="Choose one...">항목 하나 선택...</string>
  <string id="Choose task">작업 선택</string>
  <string id="Choose the frequency">빈도 선택</string>
  <string id="Choose the group type">그룹 유형 선택</string>
  <string id="Class">클래스</string>
  <string id="Click">누르기</string>
  <string id="Click Add to create a Home screen button.">홈 스크린 단추를 만들려면 추가를 누르십시오.</string>
  <string id="Click on checkboxes to select or deselect privileges.">권한을 선택 또는 선택 해제하려면 확인란을 누르십시오.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">사각형을 누르고 마우스 단추를 놓아 새 색상을 선택합니다.</string>
  <string id="Client Groups:">클라이언트 그룹:</string>
  <string id="Client Profile created.">클라이언트 프로파일을 만들었습니다.</string>
  <string id="Client Profiles">클라이언트 프로필</string>
  <string id="Close">닫기</string>
  <string id="Color :">컬러:</string>
  <string id="Column Chart.">막대형 차트.</string>
  <string id="Compile">컴파일</string>
  <string id="Compile Options:">컴파일 옵션:</string>
  <string id="Completed">완료됨</string>
  <string id="Components">구성 요소</string>
  <string id="Config Service">구성 서비스</string>
  <string id="Configuration">구성</string>
  <string id="Configuration:">구성:</string>
  <string id="Configurations for this discovery:">이 검색 구성:</string>
  <string id="Connect To App">앱에 연결</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">대상 VM에 연결됨, 주소: 127.0.0.1:61023, 전송: socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">연결 시간이 초과되었습니다. 방화벽 설정을 포함하여 서버 구성을 확인하십시오.</string>
  <string id="Contact Location">연락처 위치</string>
  <string id="Contact Location:">연락처 위치:</string>
  <string id="Contact Name">연락처 이름</string>
  <string id="Contact Name:">연락처 이름:</string>
  <string id="Content :">콘텐츠:</string>
  <string id="Copy">복사</string>
  <string id="Copy + Profile">복사 + 프로필</string>
  <string id="Copy Shortcuts">복사 단축번호</string>
  <string id="CPU Usage">CPU 사용</string>
  <string id="Creating client profile...">클라이언트 프로파일을 만드는 중...</string>
  <string id="Creating device group...">장치 그룹을 만드는 중...</string>
  <string id="Creating discovery profile...">검색 프로파일을 만드는 중...</string>
  <string id="Creating or updating a forms printer...">양식 프린터를 만들거나 업데이트하는 중...</string>
  <string id="Creating software client group...">소프트웨어 클라이언트 그룹을 만드는 중...</string>
  <string id="Creatingupdating the scheduled task...">예약된 작업을 만드는/업데이트하는 중...</string>
  <string id="Cron expression)">Cron 표현식</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">현재 열</string>
  <string id="Current password is incorrect.">현재 암호가 잘못되었습니다.</string>
  <string id="Current Password:">현재 암호:</string>
  <string id="Currently discovering Missing Devices...">현재 누락된 장치 검색 중...</string>
  <string id="Currently discovering Unlicensed Devices...">현재 라이선스가 없는 장치 검색 중...</string>
  <string id="Custom">사용자 정의</string>
  <string id="Custom icons:">사용자 정의 아이콘:</string>
  <string id="Custom...">사용자 지정...</string>
  <string id="Customize Jobs Table">작업 테이블 사용자 정의</string>
  <string id="Customize Logs Table">로그 테이블 사용자 정의</string>
  <string id="Customize Table...">테이블 사용자 정의...</string>
  <string id="Danger, Will Robinson!">위험, Will Robinson!</string>
  <string id="Darkness :">농도:</string>
  <string id="Database Driver:">데이터베이스 드라이버:</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>데이터베이스 정규화된 호스트 이름 또는 IP 주소</string>
  <string id="Database URL:">데이터베이스 URL:</string>
  <string id="Datasource:">데이터 소스</string>
  <string id="Datatype Filter">데이터 형식 필터</string>
  <string id="Datatype filter:">데이터 형식 필터:</string>
  <string id="Date">날짜</string>
  <string id="Debug">디버그</string>
  <string id="Default">기본값</string>
  <string id="Default Group">기본 그룹</string>
  <string id="Default Group can not be deleted.">기본 그룹을 삭제할 수 없습니다.</string>
  <string id="Default Output Format:">기본 출력 형식:</string>
  <string id="Default: 389">기본값: 389</string>
  <string id="Delete">삭제</string>
  <string id="Delete file on failure?">실패 시 파일을 삭제하겠습니까?</string>
  <string id="Delete file on success?">성공 시 파일을 삭제하겠습니까?</string>
  <string id="Deleted device group. One or more devices must now be updated.">장치 그룹을 삭제했습니다. 이제 하나 이상의 장치를 업데이트해야 합니다.</string>
  <string id="Deleted selected FormSet(s).">선택한 양식 집합을 삭제했습니다.</string>
  <string id="Deleted software client group.">소프트웨어 클라이언트 그룹을 삭제했습니다.</string>
  <string id="Deleting All FormSet(s)...">모든 양식 집합을 삭제하는 중...</string>
  <string id="Deleting All solution(s)...">모든 솔루션을 삭제하는 중...</string>
  <string id="Deleting client profile(s)...">클라이언트 프로파일을 삭제하는 중...</string>
  <string id="Deleting device group...">장치 그룹을 삭제하는 중...</string>
  <string id="Deleting discovery profile(s)...">검색 프로파일을 삭제하는 중...</string>
  <string id="Deleting forms printer...">양식 프린터를 삭제하는 중...</string>
  <string id="Deleting Formset(s)...">양식 집합을 삭제하는 중...</string>
  <string id="Deleting scheduled task...">예약된 작업을 삭제하는 중...</string>
  <string id="Deleting selected FormSet(s)...">선택한 양식 집합을 삭제하는 중...</string>
  <string id="Deleting software client group...">소프트웨어 클라이언트 그룹을 삭제하는 중...</string>
  <string id="Deleting solution(s)...">솔루션을 삭제하는 중...</string>
  <string id="Delta">델타</string>
  <string id="Deploy to:">배포 대상:</string>
  <string id="Deploy:">배포:</string>
  <string id="Deploying home screen to"> 홈 스크린 배포 중</string>
  <string id="Deploying solution to device group..."> 장치 그룹에 솔루션을 배포하는 중...</string>
  <string id="Deploying WAR file:">WAR 파일 배포: </string>
  <string id="Description">설명</string>
  <string id="Description:">설명:</string>
  <string id="Descriptor">설명자</string>
  <string id="Destination Folder Path">대상 폴더 경로</string>
  <string id="Developer Forums">개발자 포럼</string>
  <string id="Developer Network">개발자 네트워크</string>
  <string id="Device Address">장치 주소</string>
  <string id="Device Address:">장치 주소:</string>
  <string id="Device Class">장치 클래스</string>
  <string id="Device Group">장치 그룹</string>
  <string id="Device Group created">장치 그룹을 만듦</string>
  <string id="Device Group was successfully removed from the system.">장치 그룹이 시스템에서 성공적으로 제거되었습니다.</string>
  <string id="Device Group:">장치 그룹:</string>
  <string id="Device Groups">장치 그룹</string>
  <string id="Device Groups:">장치 그룹:</string>
  <string id="Device Information Directions">장치 정보 지침</string>
  <string id="Device Model">장치 모델</string>
  <string id="Device Model:">장치 모델:</string>
  <string id="Device Profiles">장치 프로파일</string>
  <string id="Device Summary">장치 요약</string>
  <string id="Device update complete.">장치 업데이트가 완료되었습니다.</string>
  <string id="Device update started...">장치 업데이트 시작됨...</string>    
  <string id="DeviceGroup">장치 그룹</string>
  <string id="Devices">장치</string>
  <string id="Directory">디렉터리</string>
  <string id="Directory Path">디렉토리 경로</string>
  <string id="Directory path*">디렉토리 경로*</string>
  <string id="Directory Watcher">디렉토리 감시자</string>
  <string id='Directory Watcher information'>디렉토리 감시자 정보</string>  
  <string id="Disabled">사용 안 함</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">대상 VM에서 연결 해제, 주소: 127.0.0.1:60902, 전송: socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">대상 VM에서 연결 해제, 주소: 127.0.0.1:61015, 전송: socket</string>
  <string id="Discover">검색</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">각 그룹의 고유한 검색 프로필을 사용해서 선택한 장치 그룹에 대한 장치를 검색합니다.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">검색 프로필을 사용하여 이 장치 그룹에 대한 장치를 검색합니다.</string>
  <string id="Discover Missing">누락 항목 검색</string>
  <string id="Discover new devices only">새 장치만 검색</string>
  <string id="Discover Unlicensed">라이센스가 없는 항목 검색</string>
  <string id="Discover...">검색...</string>
  <string id="Discovered">검색됨</string>
  <string id="Discovered Devices">검색된 장치</string>
  <string id="Discovered Devices:">검색된 장치:</string>
  <string id="Discovery">검색</string>
  <string id="Discovery has Completed for...">검색이 완료됨...</string>
  <string id="Discovery in Progress for...">검색 진행 중...</string>
  <string id="Discovery Profile created.">검색 프로파일을 만들었습니다.</string>
  <string id="Discovery Profiles">검색 프로파일</string>
  <string id="Discovery Profiles:">검색 프로파일:</string>
  <string id="Display Text">표시 텍스트</string>
  <string id="Display Text:">표시 텍스트:</string>
  <string id="Documentation">설명서</string>
  <string id="Done">완료</string>
  <string id="Done generating the jobs report for downloading.">다운로드할 작업 보고서 생성을 완료했습니다.</string>
  <string id="Done generating the logs report for downloading.">다운로드할 로그 보고서 생성을 완료했습니다.</string>
  <string id="Down icon">아래로 아이콘</string>
  <string id="Down icon:">아래로 아이콘:</string>
  <string id='Download Details'>다운로드 세부 정보</string>
  <string id="Duplex :">양면 장치:</string>
  <string id="Edit">편집</string>
  <string id="Edit a solution">솔루션 편집</string>
  <string id="Edit a solution to deploy">배포할 솔루션 편집</string>
  <string id="Edit the information about the report :">보고서에 대한 정보 편집:</string>
  <string id="Edit the report settings">보고서 설정 편집</string>
  <string id="Edit...">편집...</string>
  <string id="EForms">EForms</string>
  <string id="E-Forms">E-Forms</string>
  <string id="EForms:">EForms:</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">시작 날짜 및 시간 필드를 모두 채우거나 모두 비워 두어야 합니다.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">종료 날짜 및 시간 필드를 모두 채우거나 모두 비워 두어야 합니다.</string>
  <string id="Email">이메일</string>
  <string id="Email + Profile">이메일 + 프로필</string>
  <string id="Email Shortcuts">이메일 단축번호</string>
  <string id="Email the Report">보고서 이메일 전송</string>
  <string id="Email To">이메일 대상</string>
  <string id="Enable Fax Forwarding.">팩스 전송을 활성화합니다.</string>
  <string id="Enable LDAP Authentication.">LDAP 인증을 활성화합니다.</string>
  <string id="Enabled for Credentials">자격 증명에 대해 활성화됨</string>
  <string id="Enabled for Session">세션에 대해 활성화됨</string>
  <string id="End Time">종료 시간</string>
  <string id="End Time:">종료 시간:</string>
  <string id="Enter a unique group name">고유한 그룹 이름을 입력합니다.</string>
  <string id="Enter a unique name for this group">이 그룹에 대한 고유한 이름 입력</string>
  <string id="Enter appropriate fields and click the Add button:">적합한 필드를 입력하고 추가 단추 누름:</string>
  <string id="Enter appropriate fields and click the Save button:">적합한 필드를 입력하고 저장 단추 누름:</string>
  <string id="Enter the appropriate fields and click the Add button:">적합한 필드를 입력하고 추가 단추 누름:</string>
  <string id="Enter the information about the new report :">새 보고서에 대한 정보 편집:</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">각 재시도 간격 사이를 공백으로 구분하여 시간 초과 값(밀리초)을 입력합니다.</string>
  <string id="Error">오류</string>
  <string id="Error importing license.">라이센스를 가져오는 중 오류가 발생했습니다.</string>
  <string id="Error in changing name.">이름을 변경하는 중 오류가 발생했습니다.</string>
  <string id="Error in creating device group...">장치 그룹을 만드는 중 오류 발생...</string>
  <string id="Error in creating software client group...">소프트웨어 클라이언트 그룹을 만드는 중 오류 발생...</string>
  <string id="Error in deleting device group.">장치 그룹을 삭제하는 중 오류 발생...</string>
  <string id="Error in deleting software client group.">소프트웨어 클라이언트 그룹을 삭제하는 중 오류 발생...</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">양식 집합을 삭제하는 중 오류가 발생했습니다. 자세한 내용은 로그를 확인하십시오.</string>
  <string id="Error in generating the report.">보고서를 생성하는 중 오류가 발생했습니다.</string>
  <string id="Error in saving Ldap settings.">LDAP 설정을 저장하는 중 오류가 발생했습니다.</string>
  <string id="Error in saving settings.">설정을 저장하는 중 오류가 발생했습니다.</string>
  <string id="Error in updating password.">암호를 업데이트하는 중 오류가 발생했습니다.</string>
  <string id="Error in updating security settings.">보안 설정을 업데이트하는 중 오류가 발생했습니다.</string>
  <string id="Error in updating service settings.">서비스 설정을 업데이트하는 중 오류가 발생했습니다.</string>
  <string id="Error in updating solution settings.">솔루션 설정을 업데이트하는 중 오류가 발생했습니다.</string>
  <string id="Error while deploying home screen to">홈 스크린을 배포하는 중 오류 발생</string>
  <string id="Eval">평가</string>
  <string id="Evaluate in +app_url}">+app_url}에서 평가</string>
  <string id="Evaluate in remote app">원격 앱에서 평가</string>
  <string id="Every">매</string>
  <string id="Expiration Date">만료 날짜</string>
  <string id="Expired Formset">만료된 양식 집합</string>
  <string id="Expired!">만료되었습니다!</string>
  <string id="Expires on:">만료일:</string>
  <string id="Export Report">보고서 내보내기</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">실패함</string>
  <string id="FALSE">FALSE</string>
  <string id="Fax">팩스</string>
  <string id="Fax + Profile">팩스 + 프로필</string>
  <string id="Fax Forward settings updated."> 팩스 전달 설정이 업데이트되었습니다.</string>
  <string id="Fax Forwarding">팩스 전달</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax"> 팩스 전달 대상 단축번호: (이메일, FTP, 팩스 </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">팩스 전달 대상 단축번호: (이메일, FTP, 팩스)</string>
  <string id="Fax Forwarding Destination:">팩스 전달 대상:</string>
  <string id="Fax Forwarding LDSS Script:"> 팩스 전달 LDSS 스크립트:</string>
  <string id="Fax Forwarding Receive Mode:">팩스 전달 수신 모드:</string>
  <string id="Fax Shortcuts">팩스 단축번호</string>
  <string id="Feature Id">기능 ID</string>
  <string id="Filter">필터</string>
  <string id="Filters...">필터...</string>
  <string id="Finish">마침</string>
  <string id="Finished AP Bundle Descriptor File">완료된 AP 번들 설명자 파일</string>
  <string id="Finished AP Bundle Flash File">완료된 AP 번들 플래시 파일</string>
  <string id="Finished upload of key.pem File.">key.pem 파일의 업로드를 완료했습니다.</string>
  <string id="First">첫 번째</string>
  <string id="Form field must be a single word or valid email address.">양식 필드는 단일 단어 또는 올바른 이메일 주소여야 합니다.</string>
  <string id="Form Printers">양식 프린터</string>
  <string id="Format :">형식:</string>
  <string id="Forms">양식</string>
  <string id="Forms Printer is unlicensed">양식 프린터에 라이센스가 제공되지 않음</string>
  <string id="Forms printer successfully created or updated.">양식 프린터를 성공적으로 만들거나 업데이트했습니다.</string>
  <string id="Forms printer successfully deleted.">양식 프린터를 성공적으로 삭제했습니다.</string>
  <string id="Formsets">양식 집합</string>
  <string id="FormsetsSubforms">양식 집합/하위 양식</string>
  <string id="Forward Only">전달 전용</string>
  <string id="Fourth">네 번째</string>
  <string id="FRAMEWORK">프레임워크</string>
  <string id="Fri">금</string>
  <string id="From:">보낸 사람:</string>
  <string id="Ftp">Ftp</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + 프로필</string>
  <string id="Ftp Shortcuts">FTP 단축번호</string>
  <string id="Generating logs report for downloading...">다운로드할 로그 보고서를 생성하는 중...</string>
  <string id="Generating Report">보고서 생성</string>
  <string id="Generating Report...">보고서 생성 중...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">정규 업무 시간 중 보고서를 생성하면 시스템 성능에 부정적인 영향을 줄 수 있습니다. 근무 외 시간에 보고서를 생성하는 것이 좋습니다.</string>
  <string id="Generating the jobs report for downloading...">다운로드할 작업 보고서를 생성하는 중...</string>
  <string id="Graphic">그래픽</string>
  <string id="Graphic:">그래픽:</string>
  <string id="Group Description placeholder">그룹 설명 위치 표시자</string>
  <string id="Group Identifier:">그룹 식별자:</string>
  <string id="Group Names from LDAP">LDAP의 그룹 이름</string>
  <string id="Group Names from LDAP:">LDAP의 그룹 이름:</string>
  <string id="Group search base must be set for adding group based">그룹 기반을 추가하려면 그룹 검색 기반을 설정해야 합니다. </string>
  <string id="Group search base must be set in">그룹 검색 기반을 다음 위치에서 설정해야 함:</string>
  <string id="Group Search Base:">그룹 검색 기반:</string>
  <string id="Group Search Filter:">그룹 검색 필터:</string>
  <string id="Group Search Identifier:">그룹 검색 식별자:</string>
  <string id="Groups">그룹</string>
  <string id="Held Jobs">보류 작업</string>
  <string id="Hide Settings">설정 숨기기</string>
  <string id="Home">홈</string>
  <string id="Home Screen">홈 스크린</string>
  <string id="Home screen deployed to">홈 스크린 배포</string>
  <string id="Home Screens">홈 스크린</string>
  <string id="Home Tab">홈 탭</string>
  <string id="Hostname">호스트 이름</string>
  <string id="Hostname:">호스트 이름:</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">IDR 라이센스 요약</string>
  <string id="IDR License Summary:">IDR 라이센스 요약:</string>
  <string id="Images">이미지</string>
  <string id="Import">가져오기</string>
  <string id="Import...">가져오기...</string>
  <string id="Importing AP Bundle Descriptor File...">AP 번들 설명자 파일을 가져오는 중...</string>
  <string id="Importing AP Bundle Flash File...">AP 번들 플래시 파일을 가져오는 중...</string>
  <string id='Importing Binary String...'>바이너리 문자열을 가져오는 중...</string>  
  <string id="Importing CaCert pem File...">CaCert pem 파일을 가져오는 중...</string>
  <string id="Importing license...">라이센스를 가져오는 중...</string>
  <string id="Importing software client group profile...">소프트웨어 클라이언트 그룹 프로필을 가져오는 중...</string>
  <string id="Importing Solution(s)...">솔루션을 가져오는 중...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">삽입 - 이 작업은 잘라내기 단추를 삽입하고 남은 단추를 아래로 푸시합니다.</string>
  <string id="Install Time">설치 시간</string>
  <string id="Install Time:">설치 시간:</string>
  <string id="Install-Upgrade">설치/업데이트</string>
  <string id="It is recommended to run reports during off hours.">근무 외 시간에 보고서를 생성하는 것이 좋습니다.</string>
  <string id="Items">항목</string>
  <string id="Jasper Report File Name:">Jasper 보고서 파일 이름:</string>
  <string id="Job State">작업 상태</string>
  <string id="Job State:">작업 상태:</string>
  <string id="Jobs">작업</string>
  <string id="Jobs by user">사용자별 작업</string>
  <string id="Jobs Filters Table">작업 필터 테이블</string>
  <string id="Jobs Report">작업 보고서</string>
  <string id="Jobs Report - CSV">작업 보고서 - CSV</string>
  <string id="Keep previous backups">이전 백업 보관</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>언어:</string>
  <string id="Last">마지막</string>
  <string id="Last 12 Hours">마지막 12시간</string>
  <string id="Last 15 Minutes">마지막 15분</string>
  <string id="Last 24 Hours">마지막 24시간</string>
  <string id="Last 3 Hours">마지막 3시간</string>
  <string id="Last 30 Days">마지막 30일</string>
  <string id="Last 30 Minutes">마지막 30분</string>
  <string id="Last 6 Hours">마지막 6시간</string>
  <string id="Last 7 Days">마지막 7일</string>
  <string id="Last Discovered">마지막 검색</string>
  <string id="Last Discovered:">마지막 검색:</string>
  <string id="Last Hour">마지막 시간</string>
  <string id="Last Kranked">마지막 Kranked</string>
  <string id="Last Modified">마지막 수정</string>
  <string id="Layout">레이아웃</string>
  <string id="Layout:">레이아웃:</string>
  <string id="LDAP Server Settings:">LDAP 서버 설정:</string>
  <string id="Ldap Settings Saved.">LDAP 설정이 저장되었습니다.</string>
  <string id="LDAP Setup">LDAP 설정</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark 인쇄 관리</string>
  <string id="License">라이센스</string>
  <string id="LICENSE">라이센스</string>
  <string id="License Files">라이센스 파일</string>
  <string id="License Type">라이센스 종류</string>
  <string id="License Upload Results.">라이센스 업로드 결과.</string>
  <string id="License Upload Results:">라이센스 업로드 결과:</string>
  <string id="Licensed">라이센스가 부여됨</string>
  <string id="Licenses">라이센스</string>
  <string id="Licenses in Use">사용 중인 라이센스</string>
  <string id="Limit batch size">배치 크기 제한</string>
  <string id="Line Chart with Time Period Slider.">시계열 슬라이더를 포함하는 꺾은선형 차트입니다.</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>부하 분산 장치 정규화된 호스트 이름 또는 IP 주소</string>
  <string id="LOADING">넣기</string>
  <string id="Loading...">로드 중...</string>
  <string id="LOADING...">로드 중...</string>
  <string id="Lock Device">장치 잠금</string>
  <string id="Log">로그</string>
  <string id="Log Report - CSV">로그 보고서 - CSV</string>
  <string id="Log Report - Failed Jobs">로그 보고서 - 실패한 작업</string>
  <string id="Log State">로그 상태</string>
  <string id="Log State:">로그 상태:</string>
  <string id="Logging In">로그인</string>
  <string id="Login">로그인</string>
  <string id="Logout">로그아웃</string>
  <string id="Logs Filters Table">로그 필터 테이블</string>
  <string id='Max:'>최대:</string>
  <string id="Member of Group(s):">그룹 구성원:</string>
  <string id="Memory Usage">메모리 사용</string>
  <string id="Message">메시지</string>
  <string id="Message:">메시지:</string>
  <string id="Messages">메시지</string>
  <string id='Min:'>분:</string>
  <string id='Minimum length:'>최소 길이:</string>
  <string id='Minimum:'>최소:</string>
  <string id="Missing">없음</string>
  <string id="Missing Device">누락된 장치</string>
  <string id="Missing Devices">누락된 장치</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">누락된 장치는 한 번 검색되었지만 최근 검색 중에 찾을 수 없었던 장치입니다(예: 장치의 네트워크 연결이 해제됨).</string>
  <string id="Missing devices:">누락된 장치:</string>
  <string id="Missing Devices:">누락된 장치:</string>
  <string id="Model">모델</string>
  <string id="Model:">모델:</string>
  <string id="Mon">월</string>
  <string id="MONITOR">모니터</string>
  <string id="Move Down">아래로 이동</string>
  <string id="Move Up">위로 이동</string>
  <string id="Name">이름</string>
  <string id="Name :">이름:</string>
  <string id="Name changed.">이름이 변경되었습니다.</string>
  <string id="Name:">이름:</string>
  <string id="Network Load">네트워크 로드</string>
  <string id="Network share password">네트워크 공유 암호</string>
  <string id="Network share user name">네트워크 공유 사용자 이름</string>
  <string id="New Password:">새 암호:</string>
  <string id="New Username:">새 사용자 이름:</string>
  <string id="Next">다음</string>
  <string id="No">아니오</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>이 장치 그룹에 대한 cSF 앱이 없습니다. 이 작업을 단추와 연관시키려면 먼저 cSF 앱을 하나 지정해야 합니다.</string>
  <string id="No devices are currently Out of Policy for the system.">현재 시스템의 장치가 최신 상태입니다.</string>
  <string id="No devices are currently Out of Policy for this device group.">이 장치 그룹의 정책 외부 장치가 없습니다.</string>
  <string id="No home screen is configured for this device type.">이 장치에 대한 홈 스크린 지원이 구성되지 않았습니다.</string>
  <string id="No matches found">일치하는 항목을 찾을 수 없음</string>
  <string id='No Privilege'>권한 없음</string>
  <string id="No Privilege Alert">권한 없음 경고</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">프로파일과 연관된 솔루션이 없기 때문에 이 장치 그룹에 대한 프로파일이 없습니다.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">이 장치 그룹에 대한 프로파일이 없습니다. 이 작업을 단추와 연관시키려면 먼저 프로파일을 하나 지정해야 합니다.</string>
  <string id="No records match the selected filter criteria.">선택한 필터 조건과 일치하는 레코드가 없습니다.</string>
  <string id="No records matched the filter criteria.">필터 조건과 일치하는 레코드가 없습니다.</string>
  <string id="No schedulable scripts are available.">사용할 수 있는 예약 가능한 스크립트가 없습니다.</string>
  <string id="No UCF File selected">선택한 보안 설정 파일 없음</string>
  <string id="None">없음</string>
  <string id="None of the selected devices are missing.">선택한 장치 중 누락된 장치가 없습니다.</string>
  <string id="None of the selected devices are unlicensed.">선택한 장치 중 라이센스가 해제된 장치가 없습니다.</string>
  <string id="Number of Jobs per Page">페이지별 작업 수</string>
  <string id="Number of Licenses">라이센스 수</string>
  <string id="Number of Logs per Page">페이지별 로그 수</string>
  <string id="Off">끄기</string>
  <string id="OK">확인</string>
  <string id="Once">한 번</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">현재 구성에서 하나 이상의 단추가 잘못되었습니다. &lt;font color="#ff0000"&gt;(빨간색으로 표시)&lt;/font&gt; 모든 단추가 올바른지 확인하십시오.</string>
  <string id="One or more tests did not pass.">하나 이상의 테스트에 실패했습니다.</string>
  <string id="Only"> 전용</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">한 번에 하나의 검색만 수행할 수 있습니다. 현재 검색이 완료된 후에 새 검색을 시작할 수 있습니다.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">한 번에 하나의 정책 업데이트만 수행할 수 있습니다.  현재 업데이트가 완료된 후 새 정책 업데이트를 시작할 수 있습니다.</string>
  <string id="Only update those devices which are Out of Policy">정책 외부 장치만 업데이트</string>
  <string id="Orientation :">용지 방향:</string>
  <string id="Out of Policy">정책 외부</string>
  <string id="Out of Policy Device">정책 외부 장치</string>
  <string id="Out of Policy Devices">정책 외부 장치</string>
  <string id="Out of Policy Devices:">정책 외부 장치:</string>
  <string id="Output Format">출력 형식</string>
  <string id="Overwrite if file already exists">파일이 존재하는 경우 덮어씀</string>
  <string id="Page 1">페이지 1</string>
  <string id="Page 2">페이지 2</string>
  <string id="Page 3">페이지 3</string>
  <string id="Page 4">페이지 4</string>
  <string id="Paper Size :">용지 크기:</string>
  <string id="Parameters">매개변수</string>
  <string id="Password Changed Successfully.">암호를 성공적으로 변경했습니다.</string>
  <string id="Password updated.">암호를 업데이트했습니다.</string>
  <string id="Password*">암호*</string>
  <string id="Password:">암호:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">각 그룹의 정책을 사용해서 선택한 장치 그룹에 대한 정책 업데이트를 수행합니다.</string>
  <string id="Perform a Policy Update for selected devices.">선택한 장치에 대한 정책 업데이트를 수행합니다.</string>
  <string id="Perform a Policy Update for this device group.">선택한 장치에 대한 정책 업데이트를 수행합니다.</string>
  <string id="Placeholder">자리 표시자</string>
  <string id="Please choose a filter:">필터를 선택하십시오.</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">예약된 스크립트에서 솔루션의 로컬 솔루션 설정에 액세스할 수 있는 그룹 종류를 선택하십시오.</string>
  <string id="Please choose a script:">스크립트를 선택하십시오.</string>
  <string id="Please choose a task to schedule :">예약할 작업을 선택하십시오.</string>
  <string id="Please choose an action:">작업을 선택하십시오.</string>
  <string id="Please choose client groups to schedule :">예약할 클라이언트 그룹을 선택하십시오.</string>
  <string id="Please choose device groups to schedule :">예약할 장치 그룹을 선택하십시오.</string>
  <string id="Please choose one of the following options:">다음 옵션 중 하나를 선택하십시오.</string>
  <string id="Please choose solution and script :">솔루션 및 스크립트를 선택하십시오.</string>
  <string id="Please choose solution and script to schedule :">예약할 솔루션 및 스크립트를 선택하십시오.</string>
  <string id="Please choose start time and frequency :">시작 시간 및 빈도를 선택하십시오.</string>
  <string id="Please choose the datasource for the new report.">새 보고서에 대한 데이터 소스를 선택하십시오.</string>
  <string id="Please choose the jasper filename for the new report.">새 보고서에 대한 Jasper 파일 이름을 선택하십시오.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">새 보고서에 대한 Jasper 파일 이름을 선택하십시오.  아직 나열되지 않았으면 Jasper 보고서를 업로드하십시오.</string>
  <string id="Please choose the output format for the new report.">새 보고서에 대한 결과 형식을 선택하십시오.</string>
  <string id="Please choose the report to schedule :">예약할 보고서를 선택하십시오.</string>
  <string id="Please Contact Lexmark for Software Client License Information.">소프트웨어 클라이언트 라이센스 정보는 Lexmark에 문의하십시오.</string>
  <string id="Please enter a non-expired date">만료되지 않은 날짜(mm/dd/yyyy)를 입력하십시오.</string>
  <string id="Please enter a valid Address.">올바른 주소를 입력하십시오.</string>
  <string id="Please enter a valid date">올바른 날짜(mm/dd/yyyy)를 입력하십시오.</string>
  <string id="Please enter a valid End From Time">올바른 종료 시간(시작)(HH:MM AM/PM)을 입력하십시오.</string>
  <string id="Please enter a valid End To Time">올바른 종료 시간(끝)(HH:MM AM/PM)을 입력하십시오.</string>
  <string id="Please enter a valid From date">올바른 시작 날짜(mm/dd/yyyy)를 입력하십시오.</string>
  <string id="Please enter a valid From time">올바른 시작 시간(hh:mm AM/PM)을 입력하십시오.</string>
  <string id='Please enter a valid range:'>올바른 범위를 입력하십시오.</string>
  <string id="Please enter a valid range: 1 - 12">올바른 범위를 입력하십시오. 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">올바른 범위를 입력하십시오. 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">올바른 범위를 입력하십시오. 1 - 59</string>
  <string id="Please enter a valid Start From Time">올바른 시작 시간(시작)(HH:MM AM/PM)을 입력하십시오.</string>
  <string id="Please enter a valid Start To Time">올바른 시작 시간(끝)(HH:MM AM/PM)을 입력하십시오.</string>
  <string id="Please enter a valid time">올바른 시간(HH:MM AM/PM)을 입력하십시오.</string>
  <string id="Please enter a valid To date">올바른 종료 날짜(mm/dd/yyyy)를 입력하십시오.</string>
  <string id="Please enter a valid To time">올바른 종료 시간(hh:mm AM/PM)을 입력하십시오.</string>
  <string id="Please enter the Database driver and URL for the external database.">외부 데이터베이스에 대한 데이터베이스 드라이버 및 URL을 입력하십시오.</string>
  <string id="Please enter the Directory information:">디렉토리 정보를 입력하십시오.</string>
  <string id="Please enter the location where you want the report to be saved.">보고서를 저장하려는 위치를 입력하십시오.</string>
  <string id="Please enter the name of the new report.">새 보고서의 이름을 입력하십시오.</string>
  <string id="Please enter the network share user name and password.">네트워크 공유 사용자 이름 및 암호를 입력하십시오.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">이메일로 보내려는 보고서의 받는 사람을 입력하십시오.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">백업 및 복원에 대한 요청된 정보를 입력하십시오.</string>
  <string id="Please make sure that all the necessary fields are filled in.">모든 필수 필드가 채워졌는지 확인하십시오.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">cron 표현식에 공백으로 구분된 6 또는 7개 옵션이 포함되었는지 확인하십시오.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">cron표현식에 4 또는 6번째 위치에 "?"가 있지만 두 위치에 모두 있지는 않은지 확인하십시오.</string>
  <string id="Please select a file to upload.">업로드할 파일을 선택하십시오.</string>
  <string id="Please select a group on the left to modify its task privileges.">작업 권한을 수정하려면 왼쪽에서 해당 그룹을 선택하십시오.</string>
  <string id="Please select a group to save privileges for.">권한을 저장할 그룹을 선택하십시오.</string>
  <string id="Please select a profile to view its settings.">해당 설정을 보려면 프로필을 선택하십시오.</string>
  <string id="Please select the Group to delete.">삭제할 그룹을 선택하십시오.</string>
  <string id="Please select the report to delete.">삭제할 보고서를 선택하십시오.</string>
  <string id="Please select the report to edit.">편집할 보고서를 선택하십시오.</string>
  <string id="Please select the report to run.">실행할 보고서를 선택하십시오.</string>
  <string id="Please specify a port:">포트를 지정하십시오.</string>
  <string id="Please Verify MinMax, Length and Required Settings.">최소/최대 길이 및 필요한 설정을 확인하십시오.</string>
  <string id="Policy Last Applied">마지막으로 적용된 정책</string>
  <string id="Policy Update">정책 업데이트</string>
  <string id="Policy Update has Completed for...">정책 업데이트 완료...</string>
  <string id="Policy Update in Progress for...">정책 업데이트 진행 중...</string>
  <string id="Policy Update on all effected Device Groups.">영향을 받는 모든 장치 그룹에 대한 정책 업데이트입니다.</string>
  <string id="Port">포트</string>
  <string id="Port:">포트:</string>
  <string id="Present">제공</string>
  <string id="Previous">이전</string>
  <string id="Print (Default)">인쇄(기본값)</string>
  <string id="Print and Forward">인쇄 및 전달</string>
  <string id="Printer Panel">프린터 패널</string>
  <string id="Printer Report">프린터 보고서</string>
  <string id="Privileges">권한</string>
  <string id="Process finished with exit code 0">종료 코드 0으로 종료된 프로세스</string>
  <string id="Profile Filters">프로파일 필터</string>
  <string id="Profile:">프로파일:</string>
  <string id="Profiles">프로필</string>
  <string id="Profiles :">프로파일:</string>
  <string id="Profiles:"> 프로파일:</string>
  <string id="Progress %">진행률 %</string>
  <string id="Property Tag">속성 태그</string>
  <string id="Property Tag:">속성 태그:</string>
  <string id="Quality :">품질:</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">되풀이</string>
  <string id="Refresh">새로 고침</string>
  <string id="Refresh Defaults">기본값 새로 고침</string>
  <string id="Regular Expression">정규 표현식</string>
  <string id="Release Held Faxes">팩스 보류 해제</string>
  <string id="Remove">제거</string>
  <string id="Remove All">모두 제거</string>
  <string id="Remove from System">시스템에서 제거</string>
  <string id="Remove Server(s)">서버 제거</string>
  <string id="RemoveAll">모두 제거</string>
  <string id="Removing selected servers...">선택한 서버를 제거하는 중...</string>
  <string id="Repeat this event :">이 이벤트 반복:</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">바꾸기 - 이 작업은 선택한 단추를 삭제하고 이를 잘라내기 단추로 바꿉니다.</string>
  <string id="Replace Me">교체</string>
  <string id="Report">보고서</string>
  <string id="Report by Time">시간별 보고서</string>
  <string id="Report Files">보고서 파일</string>
  <string id="Report From">보고 원본</string>
  <string id="Report Name:">보고서 이름:</string>
  <string id="Report Parameters:">보고서 매개변수:</string>
  <string id="Report To">보고 대상</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME이 성공적으로 생성됨</string>
  <string id="Reporting Period">보고 기간</string>
  <string id="Reports">보고서</string>
  <string id="Reports:">보고서:</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">요청 시간이 초과되었습니다. 검색 조건을 좁히고 다시 시도하십시오.</string>
  <string id="Required field">필수 필드</string>
  <string id="Reset">재설정</string>
  <string id="Reset Filter">필터 재설정</string>
  <string id="Reset to Default">기본값으로 재설정</string>
  <string id="Resolution :">해상도:</string>
  <string id="Return to Original">원래 값으로 돌아가기</string>
  <string id="Retype New Password:">새 암호 다시 입력:</string>
  <string id="Retype New Username:">새 사용자 이름 다시 입력:</string>
  <string id="Run on All Servers">모든 서버에서 실행</string>
  <string id="Run Report">보고서 실행</string>
  <string id="Running">실행 중</string>
  <string id="Running Tasks">작업 실행 중</string>
  <string id="Running...">실행 중...</string>
  <string id="Sat">토</string>
  <string id="Save">저장</string>
  <string id="Save Privileges">저장 권한</string>
  <string id="Save Settings">설정 저장</string>
  <string id="Save To">저장 위치</string>
  <string id="Saving eSF Settings..."> eSF 설정 저장 중...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">LDAP 설정 저장 중...</string>
  <string id="Schedule">일정</string>
  <string id="Scheduled task createdupdated">예약된 작업이 생성/업데이트됨</string>
  <string id="Scheduled task deleted">예약된 작업이 삭제됨</string>
  <string id="Scheduled tasks for all client groups:">모든 클라이언트 그룹에 대해 예약된 작업:</string>
  <string id="Scheduled tasks for all device groups:">모든 장치 그룹에 대해 예약된 작업:</string>
  <string id="Script">스크립트</string>
  <string id="Script:">스크립트:</string>
  <string id="Search">검색</string>
  <string id="Search Base:">검색 기반:</string>
  <string id="Search Held Jobs">보류 작업 검색</string>
  <string id="Search LDAP for Groups:">그룹 LDAP 검색:</string>
  <string id="Searching...">검색 중...</string>
  <string id="Second">두 번째</string>
  <string id="Secure Server Communication">보안 서버 통신</string>
  <string id="Secure Server Communication:">보안 서버 통신:</string>
  <string id="Security">보안</string>
  <string id="Security setting updated.">보안 설정을 업데이트했습니다.</string>
  <string id="Security setup file updated successfully">보안 설정 파일이 성공적으로 업데이트되었습니다.</string>
  <string id="Security setup file update failed">보안 설정 파일 업데이트 실패</string>
  <string id="Select a Group Name:">그룹 이름 선택:</string>
  <string id="Select a report">보고서 선택</string>
  <string id="Select a script task">스크립트 작업 선택</string>
  <string id="Select one...">항목 하나 선택...</string>
  <string id="Select Profile...">프로필 선택...</string>
  <string id="Select the group to copy">복사할 그룹 선택</string>
  <string id="Sent when any leaf is checked or unchecked, in">아래 두 이벤트 외에도 리프를 선택 또는 선택 해제할 때 전송</string>
  <string id="Serial Number">일련 번호</string>
  <string id="Serial Number:">일련 번호:</string>
  <string id="Server Address">서버 주소</string>
  <string id="Server Address:">서버 주소:</string>
  <string id="Server handling this LMC session">이 LMC 세션을 처리하는 서버</string>
  <string id="Server is currently offline">서버가 현재 오프라인입니다.</string>
  <string id="Server is not communicating">서버가 통신 중이 아닙니다.</string>
  <string id="Server is unlicensed">서버에 라이센스가 없습니다.</string>
  <string id="Server Port:">서버 포트:</string>
  <string id="Server Report">서버 보고서</string>
  <string id="Server(s) Error">서버 오류</string>
  <string id="Server(s) Offline">서버 오프라인</string>
  <string id="Servers">서버</string>
  <string id="Service settings updated">서비스 설정 업데이트됨</string>
  <string id="Services">서비스</string>
  <string id="Set Offline">오프라인 설정</string>
  <string id="Set Online">온라인 설정</string>
  <string id="Setting selected servers offline...">선택한 서버를 오프라인으로 설정하는 중...</string>
  <string id="Setting selected servers online...">선택한 서버를 온라인으로 설정하는 중...</string>
  <string id="Settings :">설정:</string>
  <string id="Settings:">설정:</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task home screen updated."> SFP e-Task 홈 스크린이 업데이트되었습니다.</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated."> SFP e-Task2 홈 스크린이 업데이트되었습니다.</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated."> SFP e-Task2+ 홈 스크린이 업데이트되었습니다.</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated."> SFP e-Task3 홈 스크린이 업데이트되었습니다.</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4(7인치)</string>
  <string id="SFP e-Task4 (7in.) home screen updated."> SFP e-Task4(7인치) 홈 스크린이 업데이트되었습니다.</string>
  <string id="SFP e-Task4 home screen updated."> SFP e-Task4 홈 스크린이 업데이트되었습니다.</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">단축키</string>
  <string id="Shortcut :">단축키:</string>
  <string id="Shortcut:">단축키:</string>
  <string id="Show Settings">설정 표시</string>
  <string id="Since Last Month">지난 달 이후</string>
  <string id="Since Yesterday">어제 이후</string>
  <string id="Single Profile">단일 프로필</string>
  <string id="SNMP Timeout Retries:">SNMP 시간 초과 재시도:</string>
  <string id="Software Client Group">소프트웨어 클라이언트 그룹</string>
  <string id="Software Client Group created">소프트웨어 클라이언트 그룹 생성됨</string>
  <string id="Software Client Group:">소프트웨어 클라이언트 그룹:</string>
  <string id="Software Client Groups">소프트웨어 클라이언트 그룹</string>
  <string id="Software Client Report">소프트웨어 클라이언트 보고서</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">솔루션</string>
  <string id="Solution deleted from software client group.">소프트웨어 클라이언트 그룹에서 솔루션이 삭제되었습니다.</string>
  <string id="Solution deployed to device group"> 장치 그룹에 배포된 솔루션</string>
  <string id="Solution deployed to software client group">소프트웨어 클라이언트 그룹에 배포된 솔루션</string>
  <string id="Solution Name">솔루션 이름</string>
  <string id="Solution Name:">솔루션 이름:</string>
  <string id="Solution Report">솔루션 보고서</string>
  <string id="Solution settings updated.">솔루션 설정이 업데이트되었습니다.</string>
  <string id="Solution: Deleting device group deployment..."> 솔루션: 장치 그룹 배포를 삭제하는 중...</string>
  <string id="Solution: Deleting solution from software client group...">솔루션: 소프트웨어 클라이언트 그룹에서 솔루션을 삭제하는 중...</string>
  <string id="Solution: device group deployment deleted."> 솔루션: 장치 그룹 배포가 삭제되었습니다.</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">솔루션</string>
  <string id="Solutions to deploy:">배포할 솔루션:</string>
  <string id="Solutions:">솔루션:</string>
  <string id='Specify Restore system information'>시스템 복원 정보 지정</string>
  <string id="Specify where the generated report should be saved">생성된 보고서가 저장되는 위치 지정</string>
  <string id="Start Button Default Action">시작 단추 기본 동작</string>
  <string id="Start Date :">시작 날짜:</string>
  <string id="Start Time">시작 시간</string>
  <string id="Start Time:">시작 시간:</string>
  <string id="State">시/도</string>
  <string id="Status">상태</string>
  <string id="Steps for viewing device information:">장치 정보 보기 단계:</string>
  <string id="Stop">중지</string>
  <string id="Stop Task">작업 중지</string>
  <string id="Subform">하위 양식</string>
  <string id="Subject:">제목:</string>
  <string id="Success">성공</string>
  <string id="Successfully added the group.">그룹을 성공적으로 추가했습니다.</string>
  <string id="Successfully Deleted All Solution(s) from the System.">시스템에서 모든 솔루션을 성공적으로 삭제했습니다.</string>
  <string id="Successfully Deleted Solution(s) from the System.">시스템에서 솔루션을 성공적으로 삭제했습니다.</string>
  <string id="Successfully Imported Solution(s) into the System.">시스템에 솔루션을 성공적으로 가져왔습니다.</string>
  <string id="Summary">요약</string>
  <string id="Sun">일</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">전환 - 선택한 항목과 잘라내기 단추 사이의 위치를 전환합니다.</string>
  <string id="System">시스템</string>
  <string id="System Health...">시스템 상태...</string>
  <string id="System Status">시스템 상태</string>
  <string id="System Status 1">시스템 상태 1</string>
  <string id="Task Id">작업 ID</string>
  <string id="Task Id:">작업 ID:</string>
  <string id="Task Name">작업 이름</string>
  <string id="Task Name:">작업 이름:</string>
  <string id="Task Summary Report">작업 요약 보고서</string>
  <string id="Test Progress">테스트 진행률</string>
  <string id="Test Results">테스트 결과</string>
  <string id="Test Settings">테스트 설정</string>
  <string id="Testing LDAP Settings...">LDAP 설정 테스트 중...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">첫 번째 화면의 단추는 사용자 정의 방식으로 배열할 수 있습니다.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">다음 보고서가 성공적으로 생성됨:  REPORT_NAME.  첨부된 보고서를 확인하십시오.</string>
  <string id="The password provided is incorrect.">제공한 암호가 잘못되었습니다.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">이제 이 그룹의 정책을 그룹의 모든 장치에서 배포 해제하는 중입니다.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">이제 보고서를 다운로드할 준비가 되었습니다. 계속하려면 [확인]을 누르십시오.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">보고 기간의 종료 날짜가 시작 날짜보다 이전입니다.  보고서를 생성할 때 시스템이 이를 자동으로 전환합니다.  계속하시겠습니까?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">현재 이 소프트웨어 클라이언트 그룹에 대한 클라이언트 프로파일이 없습니다. 위 필드를 채워서 추가하십시오.</string>
  <string id="There are currently no cSF Apps associated with this device group."> 현재 이 장치 그룹과 연관된 cSF 앱이 없습니다.</string>
  <string id="There are currently no cSF Apps to add to this device group."> 현재 이 장치 그룹에 추가할 cSF 앱이 없습니다.</string>
  <string id="There are currently no device groups to perform discovery.">현재 검색을 수행할 장치 그룹이 없습니다.</string>
  <string id='There are currently no device groups to perform policy update.'>현재 정책 업데이트를 수행할 장치 그룹이 없습니다.</string>  
  <string id="There are currently no device groups to schedule.">현재 예약할 장치 그룹이 없습니다.</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>현재 장치 그룹이 없습니다.  왼쪽의 추가 단추를 클릭하여 장치 그룹을 추가하십시오.</string>
  <string id="There are currently no devices discovered for this device group.">현재 이 장치 그룹에 대해 검색된 장치가 없습니다.</string>
  <string id="There are currently no devices in this device group.">현재 이 장치 그룹에 장치가 없습니다.</string>
  <string id="There are currently no discovered devices.">현재 검색된 장치가 없습니다.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">현재 이 장치 그룹에 대한 검색 프로파일이 없습니다. 위에서 적합한 필드를 채워서 추가하십시오.</string>
  <string id="There are currently no forms printers in the system.">현재 시스템에 양식 프린터가 없습니다.</string>
  <string id="There are currently no licenses installed.">현재 설치된 라이센스가 없습니다.</string>
  <string id="There are currently no licensing changes made by this upload.">현재 이 업로드로 수행된 라이센스 변경 사항이 없습니다.</string>
  <string id="There are currently no missing devices for this device group.">현재 이 장치 그룹에 대해 누락된 장치가 없습니다.</string>
  <string id="There are currently no missing devices.">현재 누락된 장치가 없습니다.</string>
  <string id="There are currently no out of policy devices for this device group.">현재 이 장치 그룹에 대해 정책을 위반하는 장치가 없습니다.</string>
  <string id="There are currently no out of policy devices.">현재 정책 위반 장치가 없습니다.</string>
  <string id="There are currently no scheduled tasks">현재 예약된 작업이 없습니다.</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">소프트웨어 클라이언트 그룹이 없습니다.  왼쪽의 추가 단추를 클릭하여 그룹을 추가하십시오.</string>
  <string id="There are currently no solutions associated with this device group."> 현재 이 장치 그룹과 연관된 솔루션이 없습니다.</string>
  <string id="There are currently no solutions associated with this software client group.">현재 이 소프트웨어 클라이언트 그룹과 연관된 솔루션이 없습니다.</string>
  <string id="There are currently no solutions installed.">현재 설치된 솔루션이 없습니다.</string>
  <string id='There are currently no solutions to add to this device group.'>현재 이 장치 그룹에 추가할 솔루션이 없습니다.</string>
  <string id="There are currently no solutions to add to this software client group.">현재 이 소프트웨어 클라이언트 그룹에 추가할 솔루션이 없습니다.</string>
  <string id="There are currently no unlicensed devices for this device group.">현재 이 장치 그룹에 대해 라이센스가 해제된 장치가 없습니다.</string>
  <string id="There are currently no unlicensed devices in this device group.">현재 이 장치 그룹에 라이센스가 없는 장치가 없습니다.</string>
  <string id="There are currently no unlicensed devices.">현재 라이센스가 없는 장치가 없습니다.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">현재 이 그룹의 정책과 연관된 솔루션 또는 cSF 앱 및/또는 홈 스크린이 있습니다. 지금 이 정책을 배포 해제하시겠습니까? 이렇게 하면 장치 그룹이 즉시 삭제되지 않습니다. 정책 업데이트가 완료되면 장치 그룹을 제거하십시오.</string>
  <string id="There are no associated UCF Files for this Solution.">이 솔루션에 대해 연관된 보안 설정 파일이 없습니다.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">이 장치 그룹의 솔루션에 대해 연관된 보안 설정 파일이 없습니다.</string>
  <string id="There are no configuration settings for this eSF application.">이 eSF 응용 프로그램에 대한 구성 설정이 없습니다.</string>
  <string id="There are no configuration settings in this solution.">이 솔루션에 구성 설정이 없습니다.</string>
  <string id="There are no configuration settings in this webapp.">이 웹 앱에 구성 설정이 없습니다.</string>
  <string id="There are no cSF Apps installed currently.">현재 설치된 cSF 앱이 없습니다.</string>
  <string id="There are no deployments setting for this solution.">이 솔루션에 대한 배포 설정이 없습니다.</string>
  <string id="There are no devices in the system that match the filter.">필터와 일치하는 장치가 시스템에 없습니다.</string>
  <string id="There are no eSF Applications for this solution.">이 솔루션에 대한 eSF 응용 프로그램이 없습니다.</string>
  <string id="There are no e-Task profiles for this device group."> 이 장치 그룹에 대한 e-Task 프로파일이 없습니다.</string>
  <string id="There are no e-Task2 profiles for this device group."> 이 장치 그룹에 대한 e-Task2 프로파일이 없습니다.</string>
  <string id="There are no forms for this solution.">이 솔루션에 대한 양식이 없습니다.</string>
  <string id="There are no forms in the system.">시스템에 양식이 없습니다.</string>
  <string id="There are no parameters in this service.">이 서비스에 매개변수가 없습니다.</string>
  <string id="There are no profiles for this software client group.">이 소프트웨어 클라이언트 그룹에 대한 프로파일이 없습니다.</string>
  <string id="There are no settings for this action.">이 작업에 대한 설정이 없습니다.</string>
  <string id="There are no settings for this solution.">이 솔루션에 대한 설정이 없습니다.</string>
  <string id="There is currently a Policy Update running...">현재 실행 중인 정책 업데이트가 있습니다.</string>
  <string id="There is currently no Version Info.">현재 버전 정보가 없습니다.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">이러한 eSF 응용 프로그램은 이 장치 그룹과 연관된 솔루션에 포함됩니다. 해당 설정을 보려면 응용 프로그램을 선택하십시오.</string>
  <string id="These group settings are currently hidden.">이러한 그룹 설정은 현재 숨겨져 있습니다.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">이러한 프로필은 각 모델의 정책 그룹에 포함됩니다. 해당 설정을 보려면 각 모델의 프로필을 선택하십시오.</string>
  <string id="Third">세 번째</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">이 링크는 Lexmark의 웹 키트 구성 UI로 연결됩니다. 계속하시겠습니까?</string>
  <string id="This Month">이번 달</string>
  <string id="This name has been given to another device group. Please choose a different name.">이 이름은 다른 장치 그룹에 이미 지정되었습니다. 다른 이름을 선택하십시오.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">이 이름은 다른 소프트웨어 클라이언트 그룹에 이미 지정되었습니다. 다른 이름을 선택하십시오.</string>
  <string id="Thread Count">스레드 수</string>
  <string id="Thu">목</string>
  <string id="Time">시간</string>
  <string id="Time of Next Run">다음 실행 시간</string>
  <string id="Time Policies Last Applied">마지막으로 적용된 시간 정책</string>
  <string id="Time:">시간:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">홈 스크린에 추가하려면 위에 있는 드롭다운 상자에서 사용자 정의 레이아웃을 선택하고 프로파일을 추가하십시오.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">직접 배열하려면 위에 있는 드롭다운 상자에서 레이아웃 중 하나를 선택합니다.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">레이아웃을 구성하려면 위에 있는 드롭다운 상자에서 레이아웃 중 하나를 선택하십시오.</string>
  <string id="To:">받는 사람:</string>
  <string id="Today">오늘</string>
  <string id="Today date">오늘 날짜</string>
  <string id="Tops Report">최상위 보고서</string>
  <string id="Tue">화</string>
  <string id="UCF">보안 설정 파일</string>
  <string id="UCF:">보안 설정 파일:</string>    
  <string id="Unable to Change Password.">암호를 변경할 수 없습니다.</string>
  <string id="Unable to Change Username.">사용자 이름을 변경할 수 없습니다.</string>
  <string id="Unable to validate all settings!">모든 설정을 검증할 수 없습니다!</string>
  <string id="Uncounted">계산되지 않음</string>
  <string id="Un-deploying all cSF Apps(s)...">모든 cSF 앱을 배치 해제하는 중...</string>
  <string id="Un-deploying cSF App(s)...">cSF 앱을 배치 해제하는 중...</string>
  <string id="Unknown">알 수 없음</string>
  <string id="Unknown Error Occured! Please Check System Log">알 수 없는 오류가 발생했습니다! 시스템 로그를 확인하십시오.</string>
  <string id='Unknown Secure State'>알 수 없는 보안 상태</string>
  <string id="Unlicensed">라이센스가 해제됨</string>
  <string id="Unlicensed Device">라이센스가 해제된 장치</string>
  <string id="Unlicensed Devices">라이센스가 해제된 장치</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">라이센스가 해제된 장치는 검색되었지만 최근 검색 중에 라이센스를 지정할 수 없었던 장치입니다. (예: 라이센스 만료 또는 모든 라이센스가 사용 중인 경우)</string>
  <string id="Unlicensed devices:">라이센스가 해제된 장치:</string>
  <string id="Unlicensed Devices:">라이센스가 해제된 장치:</string>
  <string id="Unlicensed:">라이센스가 해제됨:</string>
  <string id="Unlimited">무제한</string>
  <string id="Up icon:">위로 아이콘:</string>
  <string id="Update">업데이트</string>
  <string id="Update Policy">정책 업데이트</string>
  <string id="Update Time">업데이트 시간</string>
  <string id="Update Time:">업데이트 시간:</string>
  <string id="Updating client profile...">클라이언트 프로파일을 업데이트하는 중...</string>
  <string id="Updating discovery profile..."> 검색 프로파일을 업데이트하는 중...</string>
  <string id="Updating e-Task home screen...">e-Task 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating e-Task2 home screen..."> e-Task2 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating e-Task2+ home screen..."> e-Task2+ 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating e-Task3 home screen..."> e-Task3 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">e-Task4(4.3인치) 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating e-Task4 home screen..."> e-Task4 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating Fax Forward settings..."> 팩스 전달 설정을 업데이트하는 중...</string>
  <string id="Updating password...">암호를 업데이트하는 중...</string>
  <string id="Updating Security setting...">보안 설정을 업데이트하는 중...</string>
  <string id="Updating service settings...">서비스 설정을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task home screen..."> SFP e-Task 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task2 home screen..."> SFP e-Task2 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task2+ home screen..."> SFP e-Task2+ 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task3 home screen..."> SFP e-Task3 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen..."> SFP e-Task4(7인치) 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating SFP e-Task4 home screen..."> SFP e-Task4 홈 스크린을 업데이트하는 중...</string>
  <string id="Updating solution settings...">솔루션 설정을 업데이트하는 중...</string>
  <string id="Updating username...">사용자 이름을 업데이트하는 중...</string>
  <string id="Updating X642 home screen..."> X642 홈 스크린을 업데이트하는 중...</string>
  <string id='Updating webapp settings...'>웹 앱 설정 업데이트 중...</string>
  <string id="Upgrading or deleting solutions here will require">여기서 솔루션을 업그레이드 또는 삭제하려면 다음이 필요함:</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">cSF 앱을 여기에서 업그레이드 또는 배포 해제하려면 영향을 받는 모든 장치 그룹에 &lt;b&gt;정책 업데이트&lt;/b&gt;가 필요합니다.</string>
  <string id="Upload">업로드</string>
  <string id="Upload custom icons">사용자 정의 아이콘 업로드</string>
  <string id="Upload Report Files">보고서 파일 업로드</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">AP 번들 및 설명자 업로드를 완료했습니다.</string>
  <string id="Uploading AP Bundle and Descriptor...">AP 번들 및 설명자를 업로드하는 중...</string>
  <string id="Uploading cSF Ap cert files....">cSF 앱 인증서 파일을 업로드하는 중...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">cSF 앱 인증서 파일(cacert.pem 및 key.pem)을 업로드하는 중...</string>
  <string id="Uploading of cSF App cert files Completed.">cSF 앱 인증서 파일 업로드를 완료했습니다.</string>
  <string id="Uploading Report(s)...">보고서 업로드 중...</string>
  <string id="Uploading...">업로드 중...</string>
  <string id="Usage:">사용:</string>
  <string id="Usb Drive">USB 드라이브</string>
  <string id="Use default settings">기본 설정 사용</string>
  <string id="Use Secure Connection. (SSLTLS)">보안 연결을 사용합니다. (SSL/TLS)</string>
  <string id="Use Solution Configuration">솔루션 구성 사용</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">기존 LDD 시스템의 중앙 webdav 데이터인 데이터베이스를 '백업 LDD 시스템'으로 작동하는 다른 활성 LDD 시스템과 동기화해야 하는 경우에만 이 대화 상자를 사용하십시오. 이 기능에 대한 자세한 내용은 관리 설명서를 참조하십시오.</string>
  <string id="Use this home screen as part of the device groups policy.">장치 그룹의 정책의 일부로 이 홈 스크린을 사용합니다.</string>
  <string id='Used:'>사용됨:</string>
  <string id="User Name">사용자 이름</string>
  <string id="User Name:">사용자 이름:</string>
  <string id="User Report">사용자 보고서</string>
  <string id="User Search Base:">사용자 검색 기반:</string>
  <string id="User Search Filter:">사용자 검색 필터:</string>
  <string id="Username amp; Password">사용자 이름 및 암호</string>
  <string id="Username and Password">사용자 이름 및 암호</string>
  <string id="Username Changed Successfully.">사용자 이름을 성공적으로 변경했습니다.</string>
  <string id="Username Password">사용자 이름 암호</string>
  <string id="Username updated.">사용자 이름을 업데이트했습니다.</string>
  <string id="Username*">사용자 이름*</string>
  <string id="Username:">사용자 이름:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">eSF 응용 프로그램 배포를 확인하고 이러한 eSF 설정을 배포합니다.</string>
  <string id="Version">버전</string>
  <string id="Version Info:">버전 정보:</string>
  <string id="Version:">버전:</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">텍스트가 너무 깁니다.</string>
  <string id="View Details">세부 사항 보기</string>
  <string id="View Source">원본 보기</string>
  <string id="Waiting for License Upload Results ...">라이센스 업로드 결과를 기다리는 중...</string>
  <string id="WebApps">웹 앱</string>
  <string id="WebClient Version">웹 클라이언트 버전</string>
  <string id="WebClient Version:">웹 클라이언트 버전:</string>
  <string id="Wed">수</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated."> X642 홈 스크린을 업데이트했습니다.</string>
  <string id="Yes">예</string>
  <string id="You are viewing the Kranked version of the application">Kranked 버전의 응용 프로그램을 보는 중입니다.</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">모든 cSF 앱의 작업에 액세스할 수 있는 권한이 없습니다.</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">모든 장치 그룹의 작업에 액세스할 수 있는 권한이 없습니다.</string>
  <string id="You have no privilege to this task.">이 작업에 대한 권한이 없습니다.</string>
  <string id="You must first select a Task to Edit">먼저 편집할 작업을 선택해야 합니다.</string>
  <string id="active">활성</string>
  <string id="active:">활성:</string>
  <string id="addition to the two events below.">아래의 두 이벤트에 추가합니다.</string>
  <string id="avg response (ms)">평균 응답(밀리초)</string>
  <string id="be set back to the default values next time.">다음에 기본값으로 다시 설정됩니다.</string>
  <string id="cache">캐시</string>
  <string id="cc:">참조:</string>
  <string id="change">변경</string>
  <string id="cSF App">cSF 앱</string>
  <string id="cSF App Cert File">cSF 앱 인증서 파일</string>
  <string id="cSF App Certificates">cSF 앱 인증서</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">cSF 앱 인증서(cacert.pem, key.pem ) 업로드</string>
  <string id="cSF App Key File">cSF 앱 키 파일</string>
  <string id="cSF App settings updated.">cSF 앱 설정을 업데이트했습니다.</string>
  <string id="cSF App Version">cSF 앱 버전</string>
  <string id="cSF App Version:">cSF 앱 버전:</string>
  <string id="cSF Apps">cSF 앱</string>
  <string id="cSF Apps deployed to device group">장치 그룹에 배포된 cSF 앱</string>
  <string id="cSF Apps to deploy:">배포할 cSF 앱:</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF 앱: 장치 그룹 배포가 삭제되었습니다.</string>
  <string id="day(s)">일</string>
  <string id="devices failed">장치 실패</string>
  <string id="devices updated">장치 업데이트</string>
  <string id="device(s) missing">장치 누락</string>
  <string id="device(s) discovered">장치 검색</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">eSF 응용 프로그램 설정:</string>
  <string id="eSF Application Version:">eSF 응용 프로그램 버전:</string>
  <string id="eSF Applications">eSF 응용 프로그램</string>
  <string id="eSF Applications:">eSF 응용 프로그램:</string>
  <string id="eSF Applications: (Solution)">eSF 응용 프로그램: (솔루션)</string>
  <string id="eSF Configuration">eSF 구성</string>
  <string id="eSF Settings Saved."> eSF 설정을 저장했습니다.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">e-Task 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated."> e-Task2 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated."> e-Task2+ 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated."> e-Task3 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4(4.3인치)</string>
  <string id="e-Task4 (4.3 in.) home screen updated."> e-Task4(4.3인치) 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task4 home screen updated."> e-Task4 홈 스크린이 업데이트되었습니다.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">실패했습니다.</string>
  <string id="hide">숨기기</string>
  <string id="hour(s)">시간</string>
  <string id="in order to add a group.">그룹을 추가하려면</string>
  <string id="info">정보</string>
  <string id="load">넣기</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">분</string>
  <string id="month(s)">월</string>
  <string id="not communicating">통신 중이 아님</string>
  <string id="null">널</string>
  <string id="offline">오프라인</string>
  <string id="on">켜기</string>
  <string id="on all effected Device Groups.">영향을 받는 모든 장치 그룹에</string>
  <string id="oncheck">oncheck</string>
  <string id="online">온라인</string>
  <string id="or home screen support for this device does not exist.">또는 이 장치에 대한 홈 스크린 지원이 존재하지 않습니다.</string>
  <string id="requests">요청</string>
  <string id="requests/sec">요청/초</string>
  <string id="saving report...">보고서 저장 중...</string>
  <string id="server">서버</string>
  <string id="show">표시</string>
  <string id="test">테스트</string>
  <string id="to">대상</string>
  <string id="to change them.">변경합니다.</string>
  <string id="to take effect on the devices.">장치에 적용합니다.</string>
  <string id="total requests:">총 요청:</string>
  <string id="total responses:">총 응답:</string>
  <string id="undo">실행 취소</string>
  <string id="uploaded.">업로드되었습니다.</string>
  <string id="week(s)">주</string>
  <string id="{0} Groups">{0} 그룹</string>
  <string id="{0} Reports">{0} 보고서</string>
  <string id="{0} Software Client Groups">{0} 소프트웨어 클라이언트 그룹</string>
  <string id="{0} Solutions">{0} 솔루션</string>
  <string id="{0} eForms">{0} eForms</string>
  <string id="{0} eSF Applications">{0} eSF 응용 프로그램</string>
  <string id="Policy update required for changes to take effect on the devices">항목 변경 시에는 &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;정책 업데이트&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;를 통해 해당 장치에 적용해야 합니다.</string>
  <string id="Group search base must be set for adding group based Privileges">그룹 기반 &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;권한&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;을 추가하려면 그룹 검색 기반을 설정해야 합니다.</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">그룹을 추가하려면 &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP 설정&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;에서 그룹 검색 기반을 설정해야 합니다.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">SMB 라이센스가 부여된 설치입니다. MFP 라이센스는 최대</string>
  <string id="licenses!">개로 제한됩니다.</string>
</localize>
`;