export const FR = `
<localize>
  <string id="% Completed">% terminé</string>
  <string id="% Completed:">% Terminé :</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">(Facultatif) Veuillez saisir une description</string>
  <string id="( Username must be a Distinguished Name )">( Le nom d'utilisateur doit être un nom unique )</string>
  <string id="(1-999)"> (1-999)</string>
  <string id="(Cron expression)">(Expression Cron)</string>
  <string id="(progress)">(progression)</string>
  <string id="* Software Client License Not Found.">* Licence client du logiciel introuvable.</string>
  <string id="[EXTERNAL]">[EXTERNE]</string>
  <string id="[None]">[Aucun(e)]</string>
  <string id="1 Button">1 bouton</string>
  <string id="1 minute load">Charge de 1 minute</string>
  <string id="1. cSF Apps">1. Applications cSF</string>
  <string id="1. Device Groups">1. Groupes de périphériques</string>
  <string id="1. Search">1. Rechercher</string>
  <string id="1. Services">1. Services</string>
  <string id="1. Software Client Groups">1. Groupes client du logiciel</string>
  <string id="1. Solutions">1. Solutions</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. Saisissez les critères de recherche et cliquez sur le bouton « Rechercher ».</string>
  <string id="1. WebApps">1. Applications Web</string>
  <string id="10 Buttons">10 boutons</string>
  <string id="15 minute load">Charge de 15 minutes</string>
  <string id="15sec">15 sec</string>
  <string id="2 Buttons">2 boutons</string>
  <string id="2. Choose one or more devices if any are found.">2. Choisissez un ou plusieurs périphériques parmi ceux éventuellement trouvés.</string>
  <string id="2. Devices">2. Périphériques</string>
  <string id="2. Tasks">2. Tâches</string>
  <string id="3 Buttons">3 boutons</string>
  <string id="3. Choose a Task.">3. Choisissez une tâche.</string>
  <string id="3. Tasks">3. Tâches</string>
  <string id="30sec">30 sec</string>
  <string id="4 Buttons">4 boutons</string>
  <string id="4-16 Buttons">4-16 boutons</string>
  <string id="5 Buttons">5 boutons</string>
  <string id="5 minute load">Charge de 5 minutes</string>
  <string id="5sec">5 sec</string>
  <string id="6 Buttons">6 boutons</string>
  <string id="60sec">60 sec</string>
  <string id="7 Buttons">7 boutons</string>
  <string id="8 Buttons">8 boutons</string>
  <string id="9 Buttons">9 boutons</string>
  <string id="A Policy Update is currently running...">Une mise à jour de la stratégie est actuellement en cours...</string>
  <string id="About">A propos</string>
  <string id="Action">Action</string>
  <string id="Action Settings...">Paramètres de laction...</string>
  <string id="Action Settings:">Paramètres de laction :</string>
  <string id="Action:">Action :</string>
  <string id="Add">Ajouter</string>
  <string id="Add a cSF App to deploy:"> Ajoutez une application cSF à déployer :</string>
  <string id="Add a new Group to the system">Ajouter un nouveau groupe au système</string>
  <string id="Add a new report to the system">Ajouter un nouveau rapport au système</string>
  <string id="Add a solution to deploy: Step 1 of 2"> Ajoutez une solution à déployer : Etape 1 de 2</string>
  <string id="Add a solution to deploy: Step 2 of 2"> Ajoutez une solution à déployer : Etape 2 de 2</string>
  <string id="Add a solution: Step 1 of 2">Ajoutez une solution : Etape 1 de 2</string>
  <string id="Add a solution: Step 2 of 2">Ajoutez une solution : Etape 2 de 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Ajouter une tâche au planning : Etape 1 sur 3</string>
  <string id="Add Device Group">Ajouter un groupe de périphériques</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Ajouter des groupes de périphériques au planning : Etape 2 sur 3</string>
  <string id="Add Forms Printer">Ajouter une imprimante Forms</string>
  <string id="Add License">Ajouter une licence</string>
  <string id="Add Software Client Group">Ajouter le groupe client du logiciel</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Ajouter la fréquence au planning : Etape 3 sur 3</string>
  <string id="Add...">Ajouter...</string>
  <string id="Adding Formset(s)...">Ajout de Formset(s)...</string>
  <string id="Adding Group Name from LDAP...">Ajout d'un nom de groupe provenant de LDAP...</string>
  <string id="Adding solution to software client group...">Ajout d'une solution au groupe client du logiciel...</string>
  <string id="Additional Options">Options supplémentaires</string>
  <string id="Additional Parameters">Paramètres supplémentaires</string>
  <string id="Additional Parameters...">Paramètres supplémentaires...</string>
  <string id="Additional Report Parameters">Paramètres de rapport supplémentaires</string>
  <string id="Address">Adresse</string>
  <string id="Address:">Adresse :</string>
  <string id="Admin password:">Mot de passe administrateur :</string>
  <string id="All">Tous</string>
  <string id="All cSF Apps">Toutes les applications cSF</string>
  <string id="All Device Groups">Tous les groupes de périphériques</string>
  <string id="All scheduled tasks for the system.">Toutes les tâches planifiées pour le système.</string>
  <string id="All scheduled tasks for this device group:"> Toutes les tâches planifiées pour ce groupe de périphériques :</string>
  <string id="All scheduled tasks for this sftClient group">Toutes les tâches planifiées pour ce groupe sftClient</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">Tous les périphériques sélectionnés seront complètement supprimés du système. Voulez-vous vraiment supprimer ces périphériques ?</string>
  <string id="All Servers Offline">Tous les serveurs hors ligne</string>
  <string id="All Servers Online">Tous les serveurs en ligne</string>
  <string id="All Software Client Groups">Tous les groupes client du logiciel</string>
  <string id="All Solutions">Toutes les solutions</string>
  <string id="All Tabs">Tous les onglets</string>
  <string id="An error occurred while attempting to connect to this device,">Une erreur s’est produite pendant la tentative de connexion à ce périphérique.</string>
  <string id="Anonymous">Anonyme</string>
  <string id="Any changes here will require">Toute modification ici nécessitera</string>
  <string id="Any Changes to the parameters are temporary and will">Toute modification des paramètres est temporaire et</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Toute modification des paramètres est temporaire et les valeurs par défaut seront rétablies la prochaine fois.</string>
  <string id="AP (Advanced Prompting) Bundle Upload">Téléchargement de l'ensemble AP (Advanced Prompting)</string>
  <string id="AP Bundle">Ensemble AP</string>
  <string id="AP Bundle Application File">Fichier dapplication de lensemble AP</string>
  <string id="AP Bundle descriptor">Descripteur de l'ensemble AP</string>
  <string id="AP Bundle Descriptor File">Fichier descripteur de lensemble AP</string>
  <string id="App Reservation">Réservation dapplication</string>
  <string id="Application">Application</string>
  <string id="Apply">Appliquer</string>
  <string id="Are you sure you want to change the edited profile?">Voulez-vous vraiment changer le profil modifié ?</string>
  <string id="Are you sure you want to change these profiles?">Voulez-vous vraiment modifier ces profils ?</string>
  <string id="Are you sure you want to delete all the forms?">Voulez-vous vraiment supprimer tous les formulaires ?</string>
  <string id="Are you sure you want to delete all the profiles?">Voulez-vous vraiment supprimer tous les profils ?</string>
  <string id="Are you sure you want to delete all the solutions?">Voulez-vous vraiment supprimer toutes les solutions ?</string>
  <string id="Are you sure you want to delete the selected forms?">Voulez-vous vraiment supprimer les formulaires sélectionnés ?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">Voulez-vous vraiment supprimer le groupe sélectionné ?  Tout privilège associé à ce groupe sera lui aussi automatiquement supprimé.</string>
  <string id="Are you sure you want to delete the selected profiles?">Voulez-vous vraiment supprimer les profils sélectionnés ?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">Voulez-vous vraiment supprimer le rapport sélectionné ?  Toutes les tâches des rapports planifiés pour ce rapport seront automatiquement supprimées elles aussi.</string>
  <string id="Are you sure you want to delete the selected solutions?">Voulez-vous vraiment supprimer les solutions sélectionnées ?</string>
  <string id="Are you sure you want to delete these profiles?">Voulez-vous vraiment supprimer ces profils ?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">Voulez-vous vraiment annuler le déploiement de toutes les applications cSF ?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">Voulez-vous vraiment annuler le déploiement de la (les) application(s) cSF sélectionnée(s) ?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">Etes-vous sûr de vouloir supprimer ce(tte) +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">Etes-vous sûr de vouloir supprimer ce groupe de périphérique ?</string>
  <string id="Are you sure you would like to delete this forms printer?">Etes-vous sûr de vouloir supprimer cette imprimante Forms ?</string>
  <string id="Are you sure you would like to delete this scheduled task?">Voulez-vous vraiment supprimer cette tâche planifiée ?</string>
  <string id="Are you sure you would like to delete this software client Group?">Voulez-vous vraiment supprimer ce groupe client du logiciel ?</string>
  <string id="Are you sure you would like to delete this solution?">Voulez-vous vraiment supprimer cette solution ?</string>
  <string id="Associated Device Group :">Groupe de périphériques associés :</string>
  <string id="Associated Solution :">Solution associée :</string>
  <string id="Associated Solution:">Solution associée :</string>
  <string id="Authentication Method:">Méthode d'authentification :</string>
  <string id="Author">Auteur</string>
  <string id="Auto Refresh:">Actualiser automatiquement :</string>
  <string id="Available Columns">Colonnes disponibles</string>
  <string id="Available Reports">Rapports disponibles</string>
  <string id="Back">Retour</string>
  <string id="Background Image:">Image darrière-plan :</string>
  <string id="Backup &amp; Restore information">Sauvegarder et restaurer des informations</string>
  <string id="Backup amp; Restore">Sauvegarder amp; Restaurer</string>
  <string id="Backup Jobs Logs Database">Sauvegarder la base de données des journaux de travaux</string>
  <string id="Backup Share Path">Chemin de partage de la sauvegarde</string>
  <string id="Bar Chart">Diagramme à barres</string>
  <string id="Binary Files">Fichiers binaires</string>
  <string id="Bookmarks">Signets</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">Les fichiers cacert.pem et key.pem sont requis pour mettre à jour les certificats des applications cSF.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">Le fichier eSF et le fichier de description sont requis pour mettre à jour lensemble AP.</string>
  <string id="Browse">Parcourir</string>
  <string id="Browse...">Parcourir...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">Par défaut, l'IMF dispose automatiquement les boutons sur l'écran d'accueil.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">Par défaut, le SFP ajoute les profils au dossier des travaux suspendus.</string>
  <string id="Cancel">Annuler</string>
  <string id="Canceled">Annulé</string>
  <string id="Canceling...">Annulation...</string>
  <string id="Change Default Values">Modifier les valeurs par défaut</string>
  <string id="Change Language">Changer de langue</string>
  <string id="Change Password">Modifier le mot de passe</string>
  <string id="Change Username">Modifier le nom d’utilisateur</string>
  <string id="Changing name...">Modification du nom...</string>
  <string id="Choose a cSF App to deploy:"> Choisissez une application cSF à déployer :</string>
  <string id="Choose a solution to deploy:">Choisissez une solution à déployer :</string>
  <string id="Choose a solution:">Choisissez une solution :</string>
  <string id="Choose Client Groups">Choisir des groupes client</string>
  <string id="Choose deployment settings for">Choisissez les paramètres de déploiement de</string>
  <string id="Choose Device Groups">Choisir les groupes de périphériques</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">Choisissez chaque bouton et définissez son action. Les boutons sans action n'apparaîtront pas dans l'écran d'accueil.</string>
  <string id="Choose one...">Choisissez une...</string>
  <string id="Choose task">Choisir une tâche</string>
  <string id="Choose the frequency">Choisir la fréquence</string>
  <string id="Choose the group type">Choisir un type de groupe</string>
  <string id="Class">Classe</string>
  <string id="Click">Cliquer</string>
  <string id="Click Add to create a Home screen button.">Cliquez sur Ajouter pour créer un bouton décran daccueil.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Cliquez sur les cases à cocher pour sélectionner ou désélectionner des privilèges.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Cliquez sur le carré, puis relâchez le bouton de la souris pour sélectionner une nouvelle couleur.</string>
  <string id="Client Groups:">Groupes client :</string>
  <string id="Client Profile created.">Profil du client créé.</string>
  <string id="Client Profiles">Profils client</string>
  <string id="Close">Fermer</string>
  <string id="Color :">Couleur :</string>
  <string id="Column Chart.">Diagramme à barres</string>
  <string id="Compile">Compiler</string>
  <string id="Compile Options:">Options de compilation :</string>
  <string id="Completed">Terminé</string>
  <string id="Components">Composants</string>
  <string id="Config Service">Configurer le service</string>
  <string id="Configuration">Configuration</string>
  <string id="Configuration:">Configuration :</string>
  <string id="Configurations for this discovery:">Configurations pour cette recherche :</string>
  <string id="Connect To App">Connexion à lapplication</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Connexion à la machine virtuelle cible établie, adresse : « 127.0.0.1:61023 », transport : « socket »</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">Délai de connexion dépassé Vérifiez la configuration du serveur, y compris les paramètres du pare-feu.</string>
  <string id="Contact Location">Emplacement du contact</string>
  <string id="Contact Location:">Emplacement du contact :</string>
  <string id="Contact Name">Nom du contact</string>
  <string id="Contact Name:">Nom du contact :</string>
  <string id="Content :">Contenu :</string>
  <string id="Copy">Copie</string>
  <string id="Copy + Profile">Copie + Profil</string>
  <string id="Copy Shortcuts">Raccourcis de copie</string>
  <string id="CPU Usage">Utilisation du processeur</string>
  <string id="Creating client profile...">Création d'un profil de client...</string>
  <string id="Creating device group...">Création d'un groupe de périphériques...</string>
  <string id="Creating discovery profile...">Création d'un profil de recherche...</string>
  <string id="Creating or updating a forms printer...">Création ou mise à jour d'une imprimante Forms...</string>
  <string id="Creating software client group...">Création d'un groupe client du logiciel...</string>
  <string id="Creatingupdating the scheduled task...">Création/mise à jour de la tâche planifiée...</string>
  <string id="Cron expression)">(Expression Cron)</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">Colonnes actuelles</string>
  <string id="Current password is incorrect.">Le mot de passe actuel est incorrect.</string>
  <string id="Current Password:">Mot de passe actuel :</string>
  <string id="Currently discovering Missing Devices...">Recherche en cours des périphériques manquants...</string>
  <string id="Currently discovering Unlicensed Devices...">Recherche en cours des périphériques sans licence...</string>
  <string id="Custom">Personnalisé</string>
  <string id="Custom icons:">Icônes personnalisées :</string>
  <string id="Custom...">Personnalisé...</string>
  <string id="Customize Jobs Table">Personnaliser le tableau des travaux</string>
  <string id="Customize Logs Table">Personnaliser le tableau des journaux</string>
  <string id="Customize Table...">Personnaliser le tableau...</string>
  <string id="Danger, Will Robinson!">Danger, Will Robinson !</string>
  <string id="Darkness :">Intensité :</string>
  <string id="Database Driver:">Pilote de base de données :</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>Nom d'hôte de base de données qualifié complet OU adresse IP</string>
  <string id="Database URL:">URL de base de données :</string>
  <string id="Datasource:">Source de données :</string>
  <string id="Datatype Filter">Filtre Type de données</string>
  <string id="Datatype filter:">Filtre Type de données :</string>
  <string id="Date">Date</string>
  <string id="Debug">Débogage</string>
  <string id="Default">Par défaut</string>
  <string id="Default Group">Groupe par défaut</string>
  <string id="Default Group can not be deleted.">Il n'est pas possible de supprimer le groupe par défaut.</string>
  <string id="Default Output Format:">Format de sortie par défaut :</string>
  <string id="Default: 389">Par défaut : 389</string>
  <string id="Delete">Supprimer</string>
  <string id="Delete file on failure?">Supprimer le fichier en cas déchec ?</string>
  <string id="Delete file on success?">Supprimer le fichier en cas de réussite ?</string>
  <string id="Deleted device group. One or more devices must now be updated.">Groupe de périphériques supprimé. Un ou plusieurs périphériques doivent maintenant être mis à jour.</string>
  <string id="Deleted selected FormSet(s).">FormSet(s) sélectionné(s) supprimé(s).</string>
  <string id="Deleted software client group.">Groupe client du logiciel supprimé.</string>
  <string id="Deleting All FormSet(s)...">Suppression de tous les FormSet(s)...</string>
  <string id="Deleting All solution(s)...">Suppression de toutes les solutions...</string>
  <string id="Deleting client profile(s)...">Suppression de(s) profil(s) de clients...</string>
  <string id="Deleting device group...">Suppression d'un groupe de périphériques...</string>
  <string id="Deleting discovery profile(s)...">Suppression de(s) profil(s) de recherche...</string>
  <string id="Deleting forms printer...">Suppression de l'imprimante Forms...</string>
  <string id="Deleting Formset(s)...">Suppression de(s) Formset(s)...</string>
  <string id="Deleting scheduled task...">Suppression d'une tâche planifiée...</string>
  <string id="Deleting selected FormSet(s)...">Suppression de(s) FormSet(s) sélectionné(s)...</string>
  <string id="Deleting software client group...">Suppression du groupe client du logiciel...</string>
  <string id="Deleting solution(s)...">Suppression de(s) solution(s)...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Déployer sur :</string>
  <string id="Deploy:">Déployer :</string>
  <string id="Deploying home screen to"> Déploiement de l'écran d'accueil sur</string>
  <string id="Deploying solution to device group..."> Déploiement de la solution sur un groupe de périphériques...</string>
  <string id="Deploying WAR file:">Déploiement du fichier WAR : </string>
  <string id="Description">Description</string>
  <string id="Description:">Description :</string>
  <string id="Descriptor">Descripteur</string>
  <string id="Destination Folder Path">Chemin du dossier de destination</string>
  <string id="Developer Forums">Forums du développeur</string>
  <string id="Developer Network">Réseau du développeur</string>
  <string id="Device Address">Adresse du périphérique</string>
  <string id="Device Address:">Adresse du périphérique :</string>
  <string id="Device Class">Classe de périphérique</string>
  <string id="Device Group">Groupe de périphériques</string>
  <string id="Device Group created">Groupe de périphériques créé</string>
  <string id="Device Group was successfully removed from the system.">Le groupe de périphériques a été retiré du système avec succès.</string>
  <string id="Device Group:">Groupe de périphériques :</string>
  <string id="Device Groups">Groupes de périphériques</string>
  <string id="Device Groups:">Groupes de périphériques :</string>
  <string id="Device Information Directions">Instructions relatives aux informations des périphérique</string>
  <string id="Device Model">Modèle de périphérique</string>
  <string id="Device Model:">Modèle de périphérique :</string>
  <string id="Device Profiles">Profils de périphérique</string>
  <string id="Device Summary">Résumé des périphériques</string>
  <string id="Device update complete.">Mise à jour des périphériques terminée.</string>
  <string id="Device update started...">Mise à jour des périphériques lancée...</string>    
  <string id="DeviceGroup">DeviceGroup</string>
  <string id="Devices">Périphériques</string>
  <string id="Directory">Répertoire</string>
  <string id="Directory Path">Chemin d’accès du répertoire</string>
  <string id="Directory path*">Chemin d’accès du répertoire*</string>
  <string id="Directory Watcher">Directory Watcher</string>
  <string id='Directory Watcher information'>Informations Directory Watcher</string>
  <string id="Disabled">Désactivé(e)</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Déconnexion de la machine virtuelle cible établie, adresse : « 127.0.0.1:60902 », transport : « socket »</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Déconnexion de la machine virtuelle cible établie, adresse : « 127.0.0.1:61015 », transport : « socket »</string>
  <string id="Discover">Détecter</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Détecter des périphériques pour les groupes de périphériques sélectionnés à laide des profils de détection propres à chaque groupe.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Détecter des périphériques pour ce groupe de périphériques à laide de ses profils de détection.</string>
  <string id="Discover Missing">Détecter les périphériques absents</string>
  <string id="Discover new devices only">Détecter uniquement les nouveaux périphériques</string>
  <string id="Discover Unlicensed">Détecter les périphériques sans licence</string>
  <string id="Discover...">Détecter...</string>
  <string id="Discovered">Détecté</string>
  <string id="Discovered Devices">Périphériques détectés</string>
  <string id="Discovered Devices:">Périphériques détectés :</string>
  <string id="Discovery">Détection</string>
  <string id="Discovery has Completed for...">Détection terminée pour...</string>
  <string id="Discovery in Progress for...">Détection en cours pour...</string>
  <string id="Discovery Profile created.">Profil de recherche créé.</string>
  <string id="Discovery Profiles">Profils de détection</string>
  <string id="Discovery Profiles:">Profils de recherche :</string>
  <string id="Display Text">Afficher le texte</string>
  <string id="Display Text:">Afficher le texte :</string>
  <string id="Documentation">Documentation</string>
  <string id="Done">Terminé</string>
  <string id="Done generating the jobs report for downloading.">Création du rapport des travaux terminée en vue du téléchargement.</string>
  <string id="Done generating the logs report for downloading.">Création du rapport des journaux terminée en vue du téléchargement.</string>
  <string id="Down icon">Icône Bas</string>
  <string id="Down icon:">Icône Bas :</string>
  <string id='Download Details'>Télécharger les détails</string>
  <string id="Duplex :">Recto verso :</string>
  <string id="Edit">Modifier</string>
  <string id="Edit a solution">Modifier une solution</string>
  <string id="Edit a solution to deploy">Modifier une solution à déployer</string>
  <string id="Edit the information about the report :">Modifier les informations relatives au rapport :</string>
  <string id="Edit the report settings">Modifier les paramètres de rapport</string>
  <string id="Edit...">Modifier...</string>
  <string id="EForms">Formulaires électroniques</string>
  <string id="E-Forms">Formulaires électroniques</string>
  <string id="EForms:">Formulaires électroniques :</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">Les champs date et heure De doivent être remplis ou être laissés tous deux vierges.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">Les champs date et heure A doivent être remplis ou être laissés tous deux vierges.</string>
  <string id="Email">Email</string>
  <string id="Email + Profile">Email + Profil</string>
  <string id="Email Shortcuts">Raccourcis demail</string>
  <string id="Email the Report">Envoyer le rapport par email</string>
  <string id="Email To">Envoyer à</string>
  <string id="Enable Fax Forwarding.">Activer le transfert de télécopies.</string>
  <string id="Enable LDAP Authentication.">Activer lauthentification LDAP.</string>
  <string id="Enabled for Credentials">Activée pour les informations dauthentification</string>
  <string id="Enabled for Session">Activée pour la session</string>
  <string id="End Time">Heure de fin</string>
  <string id="End Time:">Heure de fin :</string>
  <string id="Enter a unique group name">Entrez un nom de groupe unique</string>
  <string id="Enter a unique name for this group">Entrez un nom unique pour ce groupe</string>
  <string id="Enter appropriate fields and click the Add button:">Complétez les champs appropriés et cliquez sur le bouton Ajouter :</string>
  <string id="Enter appropriate fields and click the Save button:">Complétez les champs appropriés et cliquez sur le bouton Enregistrer :</string>
  <string id="Enter the appropriate fields and click the Add button:">Complétez les champs appropriés et cliquez sur le bouton Ajouter :</string>
  <string id="Enter the information about the new report :">Entrez les informations relatives au nouveau rapport :</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Entrez les valeurs de temporisation en millisecondes, en séparant chaque entrée par un espace.</string>
  <string id="Error">Erreur</string>
  <string id="Error importing license.">Erreur d'importation de la licence.</string>
  <string id="Error in changing name.">Erreur de changement de nom.</string>
  <string id="Error in creating device group...">Erreur de création du groupe de périphériques...</string>
  <string id="Error in creating software client group...">Erreur de création du groupe client du logiciel...</string>
  <string id="Error in deleting device group.">Erreur de suppression du groupe de périphériques.</string>
  <string id="Error in deleting software client group.">Erreur de suppression du groupe client du logiciel.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">Erreur de suppression de(s) FormSet(s). Consultez les journaux pour plus de détails.</string>
  <string id="Error in generating the report.">Erreur de création du rapport.</string>
  <string id="Error in saving Ldap settings.">Erreur d'enregistrement des paramètres Ldap.</string>
  <string id="Error in saving settings.">Erreur d'enregistrement des paramètres.</string>
  <string id="Error in updating password.">Erreur de mise à jour du mot de passe.</string>
  <string id="Error in updating security settings.">Erreur de mise à jour du paramètre de sécurité.</string>
  <string id="Error in updating service settings.">Erreur de mise à jour des paramètres du service.</string>
  <string id="Error in updating solution settings.">Erreur de mise à jour des paramètres de solution.</string>
  <string id="Error while deploying home screen to">Erreur de déploiement de l'écran d'accueil sur</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Evaluer dans +app_url}</string>
  <string id="Evaluate in remote app">Evaluer dans lapplication distante</string>
  <string id="Every">Tou(te)s</string>
  <string id="Expiration Date">Date dexpiration</string>
  <string id="Expired Formset">Formset expiré</string>
  <string id="Expired!">Expiré !</string>
  <string id="Expires on:">Expire le :</string>
  <string id="Export Report">Exporter le rapport</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">Echec</string>
  <string id="FALSE">FAUX</string>
  <string id="Fax">Télécopie</string>
  <string id="Fax + Profile">Télécopie + Profil</string>
  <string id="Fax Forward settings updated."> Paramètres de transfert des télécopies mis à jour.</string>
  <string id="Fax Forwarding">Transfert télécopie</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax"> Raccourci de destination du transfert de télécopie : (Email, FTP, télécopie </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Raccourci de destination du transfert de télécopie : (Email, FTP, télécopie)</string>
  <string id="Fax Forwarding Destination:">Destination du transfert de télécopie :</string>
  <string id="Fax Forwarding LDSS Script:"> Script LDSS de transfert de télécopie :</string>
  <string id="Fax Forwarding Receive Mode:">Mode de réception du transfert de télécopie :</string>
  <string id="Fax Shortcuts">Raccourcis des télécopies</string>
  <string id="Feature Id">ID de fonction</string>
  <string id="Filter">Filtre</string>
  <string id="Filters...">Filtres...</string>
  <string id="Finish">Terminer</string>
  <string id="Finished AP Bundle Descriptor File">Fichier de descripteur d'ensemble AP terminé</string>
  <string id="Finished AP Bundle Flash File">Fichier Flash de l'ensemble AP terminé</string>
  <string id="Finished upload of key.pem File.">Téléchargement du fichier key.pem terminé.</string>
  <string id="First">Premier</string>
  <string id="Form field must be a single word or valid email address.">Le champ de formulaire doit contenir un mot unique ou une adresse email valide.</string>
  <string id="Form Printers">Imprimantes Form</string>
  <string id="Format :">Format :</string>
  <string id="Forms">Formulaires</string>
  <string id="Forms Printer is unlicensed">Limprimante Forms nest pas sous licence</string>
  <string id="Forms printer successfully created or updated.">Imprimante Forms correctement créée ou mise à jour.</string>
  <string id="Forms printer successfully deleted.">Imprimante Forms correctement supprimée.</string>
  <string id="Formsets">Formsets</string>
  <string id="FormsetsSubforms">Formsets/Sous-formulaires</string>
  <string id="Forward Only">Transférer seulement</string>
  <string id="Fourth">Quatrième</string>
  <string id="FRAMEWORK">STRUCTURE</string>
  <string id="Fri">Ven</string>
  <string id="From:">De :</string>
  <string id="Ftp">Ftp</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">Ftp + Profil</string>
  <string id="Ftp Shortcuts">Raccourcis Ftp</string>
  <string id="Generating logs report for downloading...">Création du rapport des journaux à télécharger...</string>
  <string id="Generating Report">Génération de rapport</string>
  <string id="Generating Report...">Création du rapport...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">La génération de rapports pendant les heures de bureau ordinaires peut influencer négativement les performances du système. Il est recommandé dexécuter les rapports en dehors des heures de bureau.</string>
  <string id="Generating the jobs report for downloading...">Création du rapport des travaux à télécharger...</string>
  <string id="Graphic">Graphique</string>
  <string id="Graphic:">Graphique :</string>
  <string id="Group Description placeholder">Marque de réservation de la description de groupe</string>
  <string id="Group Identifier:">Identifiant de groupe :</string>
  <string id="Group Names from LDAP">Noms de groupes de LDAP</string>
  <string id="Group Names from LDAP:">Noms de groupes de LDAP :</string>
  <string id="Group search base must be set for adding group based">La base de recherche de groupe doit être définie pour ajouter un groupe basé </string>
  <string id="Group search base must be set in">La base de recherche du groupe doit être définie dans</string>
  <string id="Group Search Base:">Base de recherche de groupe :</string>
  <string id="Group Search Filter:">Filtre de recherche de groupe :</string>
  <string id="Group Search Identifier:">Identifiant de recherche de groupe :</string>
  <string id="Groups">Groupes</string>
  <string id="Held Jobs">Travaux suspendus</string>
  <string id="Hide Settings">Masquer les paramètres</string>
  <string id="Home">Accueil</string>
  <string id="Home Screen">Ecran d’accueil</string>
  <string id="Home screen deployed to">Ecran d'accueil déployé sur</string>
  <string id="Home Screens">Ecrans d'accueil</string>
  <string id="Home Tab">Onglet Accueil</string>
  <string id="Hostname">Nom dhôte</string>
  <string id="Hostname:">Nom d'hôte :</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">Résumé de la licence IDR</string>
  <string id="IDR License Summary:">Résumé de la licence IDR :</string>
  <string id="Images">Images</string>
  <string id="Import">Importer</string>
  <string id="Import...">Importation...</string>
  <string id="Importing AP Bundle Descriptor File...">Importation du fichier du descripteur de l'ensemble AP...</string>
  <string id="Importing AP Bundle Flash File...">Importation du fichier Flash de l'ensemble AP...</string>
  <string id='Importing Binary String...'>Importation de la chaîne binaire...</string>  
  <string id="Importing CaCert pem File...">Importation du fichier CaCert pem...</string>
  <string id="Importing license...">Importation de la licence...</string>
  <string id="Importing software client group profile...">Importation du profil du groupe client du logiciel...</string>
  <string id="Importing Solution(s)...">Importation de(s) solution(s)...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Insérer - Insère le bouton Couper et descend les autres boutons vers le bas</string>
  <string id="Install Time">Heure dinstallation</string>
  <string id="Install Time:">Heure d'installation :</string>
  <string id="Install-Upgrade">Installer/Mettre à jour</string>
  <string id="It is recommended to run reports during off hours.">Il est recommandé d'exécuter les rapports en dehors des heures de bureau.</string>
  <string id="Items">Eléments</string>
  <string id="Jasper Report File Name:">Nom de fichier du rapport Jasper :</string>
  <string id="Job State">Etat du travail</string>
  <string id="Job State:">Etat du travail :</string>
  <string id="Jobs">Travaux</string>
  <string id="Jobs by user">Travaux par utilisateur</string>
  <string id="Jobs Filters Table">Tableau des filtres des travaux</string>
  <string id="Jobs Report">Rapport des travaux</string>
  <string id="Jobs Report - CSV">Rapport des travaux - CSV</string>
  <string id="Keep previous backups">Conserver les sauvegardes précédentes</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>Langue :</string>
  <string id="Last">Dernier(ère)</string>
  <string id="Last 12 Hours">Dernières 12 heures</string>
  <string id="Last 15 Minutes">Dernières 15 minutes</string>
  <string id="Last 24 Hours">Dernières 24 heures</string>
  <string id="Last 3 Hours">Dernières 3 heures</string>
  <string id="Last 30 Days">30 derniers jours</string>
  <string id="Last 30 Minutes">Dernières 30 minutes</string>
  <string id="Last 6 Hours">Dernières 6 heures</string>
  <string id="Last 7 Days">7 derniers jours</string>
  <string id="Last Discovered">Dernière recherche</string>
  <string id="Last Discovered:">Dernière recherche :</string>
  <string id="Last Hour">Dernières heure</string>
  <string id="Last Kranked">Dernier Krank</string>
  <string id="Last Modified">Dernière modification :</string>
  <string id="Layout">Mise en page</string>
  <string id="Layout:">Disposition :</string>
  <string id="LDAP Server Settings:">Paramètres du serveur LDAP :</string>
  <string id="Ldap Settings Saved.">Paramètres Ldap enregistrés.</string>
  <string id="LDAP Setup">Configuration LDAP</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Infogérance d'impression Lexmark</string>
  <string id="License">Licence</string>
  <string id="LICENSE">LICENCE</string>
  <string id="License Files">Fichiers de licence</string>
  <string id="License Type">Type de licence</string>
  <string id="License Upload Results.">Résultats du téléchargement de licence.</string>
  <string id="License Upload Results:">Résultats du téléchargement de licence :</string>
  <string id="Licensed">Avec licence</string>
  <string id="Licenses">Licences</string>
  <string id="Licenses in Use">Licences utilisées</string>
  <string id="Limit batch size">Taille de lot limite</string>
  <string id="Line Chart with Time Period Slider.">Graphique linéaire avec curseur de période de temps.</string>
  <string id="LOADING">CHARGEMENT</string>
  <string id="Loading...">Chargement...</string>
  <string id="LOADING...">CHARGEMENT...</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>Nom d'hôte d'équilibreur de charge qualifié complet. OU adresse IP</string>
  <string id="Lock Device">Verrouiller le dispositif</string>
  <string id="Log">Journal</string>
  <string id="Log Report - CSV">Rapport de journal - CSV</string>
  <string id="Log Report - Failed Jobs">Rapport de journal - Travaux échoués</string>
  <string id="Log State">Etat du journal</string>
  <string id="Log State:">Etat du journal :</string>
  <string id="Logging In">Connexion</string>
  <string id="Login">Connexion</string>
  <string id="Logout">Déconnexion</string>
  <string id="Logs Filters Table">Tableau des filtres des journaux</string>
  <string id='Max:'>Max :</string>
  <string id="Member of Group(s):">Membre des groupes :</string>
  <string id="Memory Usage">Utilisation de la mémoire</string>
  <string id="Message">Message</string>
  <string id="Message:">Message :</string>
  <string id="Messages">Messages</string>
  <string id='Min:'>Min :</string>
  <string id='Minimum length:'>Longueur minimale :</string>
  <string id='Minimum:'>Minimum :</string>
  <string id="Missing">Manquant</string>
  <string id="Missing Device">Périphérique manquant</string>
  <string id="Missing Devices">Périphériques manquants</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Les périphériques manquants sont des périphériques qui ont été détectés une fois, mais qui sont demeurés introuvables lors de la dernière détection (parce quils étaient hors de la couverture réseau, par exemple).</string>
  <string id="Missing devices:">Périphériques manquants :</string>
  <string id="Missing Devices:">Périphériques manquants :</string>
  <string id="Model">Modèle</string>
  <string id="Model:">Modèle :</string>
  <string id="Mon">Lun</string>
  <string id="MONITOR">MONITEUR</string>
  <string id="Move Down">Déplacer vers le bas</string>
  <string id="Move Up">Déplacer vers le haut</string>
  <string id="Name">Nom</string>
  <string id="Name :">Nom :</string>
  <string id="Name changed.">Nom modifié.</string>
  <string id="Name:">Nom :</string>
  <string id="Network Load">Charge du réseau</string>
  <string id="Network share password">Mot de passe du partage réseau</string>
  <string id="Network share user name">Nom dutilisateur du partage réseau</string>
  <string id="New Password:">Nouveau mot de passe :</string>
  <string id="New Username:">Nouveau nom d’utilisateur :</string>
  <string id="Next">Suivant</string>
  <string id="No">Non</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>Il n'existe pas d'application eSF pour ce groupe de périphériques. Vous avez besoin d'une application eSF au moins pour associer cette action au bouton.</string>
  <string id="No devices are currently Out of Policy for the system.">Aucun périphérique ne possède actuellement une stratégie insuffisante pour le système.</string>
  <string id="No devices are currently Out of Policy for this device group.">Aucun périphérique ne possède actuellement une stratégie insuffisante pour ce groupe de périphériques.</string>
  <string id="No home screen is configured for this device type.">Aucun écran d'accueil n'est configuré pour ce type de périphérique.</string>
  <string id="No matches found">Aucune correspondance trouvée</string>
  <string id='No Privilege'>Sans privilège</string>
  <string id="No Privilege Alert">Aucune alerte de privilège</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">Il n'existe pas de profil pour ce groupe de périphériques, car aucune solution avec profils ne lui a été associé.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">Il n'existe aucun profil pour ce groupe de périphériques. Vous avez besoin d'un profil au moins avant de pouvoir associer cette action au bouton.</string>
  <string id="No records match the selected filter criteria.">Aucun enregistrement ne correspond aux critères de filtrage sélectionnés.</string>
  <string id="No records matched the filter criteria.">Aucun enregistrement ne correspond aux critères du filtre.</string>
  <string id="No schedulable scripts are available.">Aucun script planifiable nest disponible.</string>
  <string id="No UCF File selected">Aucun fichier de configuration de la sécurité n'est sélectionné</string>
  <string id="None">Aucun</string>
  <string id="None of the selected devices are missing.">Il ne manque aucun des périphériques sélectionnés.</string>
  <string id="None of the selected devices are unlicensed.">Aucun des des périphériques sélectionnés n'est dépourvu de licence.</string>
  <string id="Number of Jobs per Page">Nombre de travaux par page</string>
  <string id="Number of Licenses">Nombre de licences</string>
  <string id="Number of Logs per Page">Nombre de journaux par page</string>
  <string id="Off">Désactivé</string>
  <string id="OK">OK</string>
  <string id="Once">Lorsque</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">Un ou plusieurs boutons de la configuration actuelle ne sont pas valides. &lt;font color="#ff0000"&gt;(affiché en rouge)&lt;/font&gt; Vérifiez que tous les boutons sont valides.</string>
  <string id="One or more tests did not pass.">Un ou plusieurs tests a échoué.</string>
  <string id="Only"> Uniquement</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">Vous ne pouvez effectuer qu'une seule recherche à la fois. Vous pouvez démarrer une nouvelle recherche dès que celle en cours est terminée.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">Vous ne pouvez effectuer quune seule mise à jour de stratégie à la fois.  Vous pouvez démarrer une nouvelle mise à jour de stratégie dès que celle en cours est terminée.</string>
  <string id="Only update those devices which are Out of Policy">Ne mettez à jour que les périphériques dont la stratégie est insuffisante.</string>
  <string id="Orientation :">Orientation :</string>
  <string id="Out of Policy">Stratégie insuffisante</string>
  <string id="Out of Policy Device">Périphérique à stratégie insuffisante</string>
  <string id="Out of Policy Devices">Périphériques à stratégie insuffisante</string>
  <string id="Out of Policy Devices:">Périphériques à stratégie insuffisante :</string>
  <string id="Output Format">Format de sortie</string>
  <string id="Overwrite if file already exists">Remplacer si le fichier existe déjà</string>
  <string id="Page 1">Page 1</string>
  <string id="Page 2">Page 2</string>
  <string id="Page 3">Page 3</string>
  <string id="Page 4">Page 4</string>
  <string id="Paper Size :">Format de papier :</string>
  <string id="Parameters">Paramètres</string>
  <string id="Password Changed Successfully.">Mot de passe correctement modifié.</string>
  <string id="Password updated.">Mot de passe mis à jour.</string>
  <string id="Password*">Mot de passe*</string>
  <string id="Password:">Mot de passe :</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Effectuez une mise à jour de stratégie pour les groupes de périphériques sélectionnés à laide de la stratégie de chaque groupe.</string>
  <string id="Perform a Policy Update for selected devices.">Effectuez une mise à jour de stratégie pour les périphériques sélectionnés.</string>
  <string id="Perform a Policy Update for this device group.">Effectuez une mise à jour de stratégie pour ce groupe de périphériques.</string>
  <string id="Placeholder">Marque de réservation</string>
  <string id="Please choose a filter:">Veuillez choisir un filtre :</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Veuillez choisir un type de groupe capable daccéder aux paramètres de solution locaux dune solution dans le script planifié :</string>
  <string id="Please choose a script:">Veuillez choisir un script :</string>
  <string id="Please choose a task to schedule :">Veuillez choisir une tâche à planifier :</string>
  <string id="Please choose an action:">Veuillez choisir une action :</string>
  <string id="Please choose client groups to schedule :">Veuillez choisir des groupes client à planifier :</string>
  <string id="Please choose device groups to schedule :">Veuillez choisir des groupes de périphériques à planifier :</string>
  <string id="Please choose one of the following options:">Veuillez choisir lune des options suivantes :</string>
  <string id="Please choose solution and script :">Veuillez choisir la solution et le script :</string>
  <string id="Please choose solution and script to schedule :">Veuillez choisir la solution et le script à planifier :</string>
  <string id="Please choose start time and frequency :">Veuillez choisir lheure de début et la fréquence :</string>
  <string id="Please choose the datasource for the new report.">Choisissez la source de données du nouveau rapport.</string>
  <string id="Please choose the jasper filename for the new report.">Choisissez le nom de fichier jasper du nouveau rapport.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">Choisissez le nom de fichier jasper du nouveau rapport.  Téléchargez le rapport jasper s'il ne figure pas encore dans la liste.</string>
  <string id="Please choose the output format for the new report.">Choisissez le format de sortie du nouveau rapport.</string>
  <string id="Please choose the report to schedule :">Veuillez choisir le rapport à planifier :</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Veuillez contacter Lexmark pour obtenir des informations sur la licence client du logiciel.</string>
  <string id="Please enter a non-expired date">Entrez une date non encore échue (mm/jj/aaaa).</string>
  <string id="Please enter a valid Address.">Entrez une adresse valide.</string>
  <string id="Please enter a valid date">Entrez une date valide (mm/jj/aaaa).</string>
  <string id="Please enter a valid End From Time">Entrez une heure de fin à partir de valide (HH:MM AM/PM).</string>
  <string id="Please enter a valid End To Time">Entrez une heure Fin jusqu'à valide (HH:MM AM/PM).</string>
  <string id="Please enter a valid From date">Entrez une date De valide (mm/jj/aaaa).</string>
  <string id="Please enter a valid From time">Entrez une heure De valide (hh:mm AM/PM).</string>
  <string id='Please enter a valid range:'>Entrez une plage valide :</string>
  <string id="Please enter a valid range: 1 - 12">Entrez une plage valide : 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">Entrez une plage valide : 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">Entrez une plage valide : 1 - 59</string>
  <string id="Please enter a valid Start From Time">Entrez une heure de début à partir de valide (HH:MM AM/PM).</string>
  <string id="Please enter a valid Start To Time">Entrez une heure Début jusqu'à valide (HH:MM AM/PM).</string>
  <string id="Please enter a valid time">Entrez une heure valide (HH:MM AM/PM)</string>
  <string id="Please enter a valid To date">Entrez une date A valide (mm/jj/aaaa).</string>
  <string id="Please enter a valid To time">Entrez une heure A valide (hh:mm AM/PM).</string>
  <string id="Please enter the Database driver and URL for the external database.">Entrez le pilote de base de données et l'URL de la base de données externe.</string>
  <string id="Please enter the Directory information:">Veuillez entrer les informations de répertoire :</string>
  <string id="Please enter the location where you want the report to be saved.">Entrez l'emplacement où vous voulez enregistrer le rapport.</string>
  <string id="Please enter the name of the new report.">Entrer le nom du nouveau rapport.</string>
  <string id="Please enter the network share user name and password.">Entrez le nom d’utilisateur et le mot de passe du partage réseau.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">Entrez les destinataires auxquels le rapport sera envoyé par email.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">Entrez les informations demandées pour Sauvegarder et restaurer :</string>
  <string id="Please make sure that all the necessary fields are filled in.">Vérifiez que tous les champs requis sont remplis.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Assurez-vous que votre expression cron compte 6 ou 7 options séparées par des espaces.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Assurez-vous que votre expression cron compte un « ? » en 4ème ou 6ème position, mais pas dans les deux.</string>
  <string id="Please select a file to upload.">Veuillez sélectionner un fichier à télécharger.</string>
  <string id="Please select a group on the left to modify its task privileges.">Veuillez sélectionner un groupe sur la gauche pour modifier ses privilèges de tâche.</string>
  <string id="Please select a group to save privileges for.">Sélectionnez un groupe pour lequel enregistrer des privilèges.</string>
  <string id="Please select a profile to view its settings.">Veuillez sélectionner un profil pour afficher ses paramètres.</string>
  <string id="Please select the Group to delete.">Sélectionnez le groupe à supprimer.</string>
  <string id="Please select the report to delete.">Sélectionnez le rapport à supprimer.</string>
  <string id="Please select the report to edit.">Sélectionnez le rapport à modifier.</string>
  <string id="Please select the report to run.">Sélectionnez le rapport à exécuter.</string>
  <string id="Please specify a port:">Veuillez spécifier un port :</string>
  <string id="Please Verify MinMax, Length and Required Settings.">Vérifiez les min/max, la longueur et les paramètres requis.</string>
  <string id="Policy Last Applied">Dernière stratégie appliquée</string>
  <string id="Policy Update">Mise à jour de stratégie</string>
  <string id="Policy Update has Completed for...">La mise à jour de stratégie est terminée pour...</string>
  <string id="Policy Update in Progress for...">Mise à jour de stratégie en cours pour...</string>
  <string id="Policy Update on all effected Device Groups.">Mise à jour de stratégie pour tous les groupes de périphériques concernés.</string>
  <string id="Port">Port</string>
  <string id="Port:">Port :</string>
  <string id="Present">Présent</string>
  <string id="Previous">Précédent</string>
  <string id="Print (Default)">Imprimer (par défaut)</string>
  <string id="Print and Forward">Imprimer et transférer</string>
  <string id="Printer Panel">Panneau de limprimante</string>
  <string id="Printer Report">Rapport d'imprimante</string>
  <string id="Privileges">Privilèges</string>
  <string id="Process finished with exit code 0">Opération terminée avec le code de sortie 0</string>
  <string id="Profile Filters">Filtres de profils</string>
  <string id="Profile:">Profil :</string>
  <string id="Profiles">Profils</string>
  <string id="Profiles :">Profils :</string>
  <string id="Profiles:"> Profils :</string>
  <string id="Progress %">% de progression</string>
  <string id="Property Tag">Identifiant de propriété</string>
  <string id="Property Tag:">Identifiant de l'imprimante :</string>
  <string id="Quality :">Qualité :</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">Récurrence</string>
  <string id="Refresh">Actualiser</string>
  <string id="Refresh Defaults">Actualiser les valeurs par défaut</string>
  <string id="Regular Expression">Expression ordinaire</string>
  <string id="Release Held Faxes">Libérer les télécopies suspendues</string>
  <string id="Remove">Supprimer</string>
  <string id="Remove All">Tout supprimer</string>
  <string id="Remove from System">Supprimer du système</string>
  <string id="Remove Server(s)">Retirer serveur</string>
  <string id="RemoveAll">RemoveAll</string>
  <string id="Removing selected servers...">Suppression des serveurs sélectionnés...</string>
  <string id="Repeat this event :">Répéter cet événement :</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Remplacer - Supprime le bouton sélectionné et le remplace par le bouton Couper.</string>
  <string id="Replace Me">Remplacez-moi</string>
  <string id="Report">Rapport</string>
  <string id="Report by Time">Rapport par heure</string>
  <string id="Report Files">Fichiers de rapport</string>
  <string id="Report From">Rapport de</string>
  <string id="Report Name:">Nom du rapport :</string>
  <string id="Report Parameters:">Paramètres du rapport :</string>
  <string id="Report To">Rapport à</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME correctement créé</string>
  <string id="Reporting Period">Période de rapport</string>
  <string id="Reports">Rapports</string>
  <string id="Reports:">Rapports :</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">Le délai de traitement de la demande a expiré. Précisez vos critères de recherche et réessayez.</string>
  <string id="Required field">Champ obligatoire</string>
  <string id="Reset">Réinitialiser</string>
  <string id="Reset Filter">Réinitialiser le filtre</string>
  <string id="Reset to Default">Rétablir les paramètres par défaut</string>
  <string id="Resolution :">Résolution :</string>
  <string id="Return to Original">Retour à loriginal</string>
  <string id="Retype New Password:">Ressaisissez le nouveau mot de passe :</string>
  <string id="Retype New Username:">Ressaisissez le nouveau nom d’utilisateur :</string>
  <string id="Run on All Servers">Exécuter sur tous les serveurs</string>
  <string id="Run Report">Exécuter le rapport</string>
  <string id="Running">En cours dexécution</string>
  <string id="Running Tasks">Tâches en cours dexécution</string>
  <string id="Running...">Exécution...</string>
  <string id="Sat">Sam</string>
  <string id="Save">Enregistrer</string>
  <string id="Save Privileges">Enregistrer les privilèges</string>
  <string id="Save Settings">Enregistrer les paramètres</string>
  <string id="Save To">Enregistrer sous</string>
  <string id="Saving eSF Settings...">Enregistrement des paramètres eSF...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">Enregistrement des paramètres LDAP...</string>
  <string id="Schedule">Planifier</string>
  <string id="Scheduled task createdupdated">Tâche planifiée créée/mise à jour</string>
  <string id="Scheduled task deleted">Tâche planifiée supprimée</string>
  <string id="Scheduled tasks for all client groups:">Tâches planifiées pour tous les groupes de clients :</string>
  <string id="Scheduled tasks for all device groups:">Tâches planifiées pour tous les groupes de périphériques :</string>
  <string id="Script">Script</string>
  <string id="Script:">Script :</string>
  <string id="Search">Rechercher</string>
  <string id="Search Base:">Base de recherche :</string>
  <string id="Search Held Jobs">Rechercher dans les travaux suspendus</string>
  <string id="Search LDAP for Groups:">Rechercher LDAP pour les groupes :</string>
  <string id="Searching...">Recherche...</string>
  <string id="Second">Deuxième</string>
  <string id="Secure Server Communication">Sécuriser la communication du serveur</string>
  <string id="Secure Server Communication:">Communication par serveur sécurisé :</string>
  <string id="Security">Sécurité</string>
  <string id="Security setting updated.">Paramètre de sécurité mis à jour.</string>
  <string id="Security setup file updated successfully">Mise à jour réussie du fichier de configuration de la sécurité</string>
  <string id="Security setup file update failed">Echec de la mise à jour du fichier de configuration de la sécurité</string>
  <string id="Select a Group Name:">Sélectionnez un nom de groupe :</string>
  <string id="Select a report">Sélectionner un rapport</string>
  <string id="Select a script task">Sélectionner une tâche de script</string>
  <string id="Select one...">Sélectionner un(e)...</string>
  <string id="Select Profile...">Sélectionner le profil...</string>
  <string id="Select the group to copy">Sélectionner le groupe à copier</string>
  <string id="Sent when any leaf is checked or unchecked, in">Envoyé quand une feuille est activée ou désactivée, en</string>
  <string id="Serial Number">Numéro de série</string>
  <string id="Serial Number:">Numéro de série :</string>
  <string id="Server Address">Adresse du serveur</string>
  <string id="Server Address:">Adresse du serveur :</string>
  <string id="Server handling this LMC session">Serveur traitant cette session LMC</string>
  <string id="Server is currently offline">Le serveur est actuellement hors ligne</string>
  <string id="Server is not communicating">Le serveur ne communique pas</string>
  <string id="Server is unlicensed">Le serveur nest pas sous licence</string>
  <string id="Server Port:">Port du serveur :</string>
  <string id="Server Report">Rapport de serveur :</string>
  <string id="Server(s) Error">Erreur de serveur(s)</string>
  <string id="Server(s) Offline">Serveur(s) hors ligne</string>
  <string id="Servers">Serveurs</string>
  <string id="Service settings updated">Paramètre de service mis à jour</string>
  <string id="Services">Services</string>
  <string id="Set Offline">Mettre hors ligne</string>
  <string id="Set Online">Mettre en ligne</string>
  <string id="Setting selected servers offline...">Mise hors ligne des serveurs sélectionnés...</string>
  <string id="Setting selected servers online...">Mise en ligne des serveurs sélectionnés...</string>
  <string id="Settings :">Paramètres :</string>
  <string id="Settings:">Paramètres :</string>
  <string id="SFP e-Task">e-Task SFP</string>
  <string id="SFP e-Task home screen updated."> Ecran d'accueil e-Task SFP mis à jour.</string>
  <string id="SFP e-Task2">e-Task2 SFP</string>
  <string id="SFP e-Task2 home screen updated."> Ecran d'accueil e-Task2 SFP mis à jour.</string>
  <string id="SFP e-Task2+">e-Task2+ SFP</string>
  <string id="SFP e-Task2+ home screen updated."> Ecran d'accueil e-Task2+ SFP mis à jour.</string>
  <string id="SFP e-Task3">e-Task3 SFP</string>
  <string id="SFP e-Task3 home screen updated."> Ecran d'accueil e-Task3 SFP mis à jour.</string>
  <string id="SFP e-Task4">e-Task4 SFP</string>
  <string id="SFP e-Task4 (7in.)">e-Task4 SFP (7 po.)</string>
  <string id="SFP e-Task4 (7in.) home screen updated."> Ecran d'accueil e-Task4 SFP (7 po.) mis à jour.</string>
  <string id="SFP e-Task4 home screen updated."> Ecran d'accueil e-Task4 SFP mis à jour.</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">Raccourci</string>
  <string id="Shortcut :">Raccourci :</string>
  <string id="Shortcut:">Raccourci :</string>
  <string id="Show Settings">Afficher les paramètres</string>
  <string id="Since Last Month">Depuis le mois dernier</string>
  <string id="Since Yesterday">Depuis hier</string>
  <string id="Single Profile">Profil unique</string>
  <string id="SNMP Timeout Retries:">Tentatives de temporisation SNMP :</string>
  <string id="Software Client Group">Groupe client du logiciel</string>
  <string id="Software Client Group created">Groupe client du logiciel créé</string>
  <string id="Software Client Group:">Groupe client du logiciel :</string>
  <string id="Software Client Groups">Groupes clients du logiciel</string>
  <string id="Software Client Report">Rapport de groupe client du logiciel</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">Solution</string>
  <string id="Solution deleted from software client group.">Solution supprimée du groupe client du logiciel.</string>
  <string id="Solution deployed to device group"> Solution déployée sur un groupe de périphériques</string>
  <string id="Solution deployed to software client group">Solution déployée dans un groupe client du logiciel</string>
  <string id="Solution Name">Nom de la solution</string>
  <string id="Solution Name:">Nom de la solution :</string>
  <string id="Solution Report">Rapport de solution</string>
  <string id="Solution settings updated.">Paramètres de solution mis à jour.</string>
  <string id="Solution: Deleting device group deployment..."> Solution : Suppression du déploiement du groupe de périphériques...</string>
  <string id="Solution: Deleting solution from software client group...">Solution : Suppression de la solution du groupe client du logiciel...</string>
  <string id="Solution: device group deployment deleted."> Solution : déploiement du groupe de périphériques supprimé.</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">Solutions</string>
  <string id="Solutions to deploy:">Solutions à déployer :</string>
  <string id="Solutions:">Solutions :</string>
  <string id='Specify Restore system information'>Définir les informations de restauration du système</string>
  <string id="Specify where the generated report should be saved">Spécifier l'emplacement d'enregistrement du rapport créé</string>
  <string id="Start Button Default Action">Action par défaut du bouton Démarrer</string>
  <string id="Start Date :">Date de début:</string>
  <string id="Start Time">Heure de début</string>
  <string id="Start Time:">Heure de début:</string>
  <string id="State">Etat</string>
  <string id="Status">Etat</string>
  <string id="Steps for viewing device information:">Etapes daffichage des informations du périphérique :</string>
  <string id="Stop">Arrêter</string>
  <string id="Stop Task">Arrêter la tâche</string>
  <string id="Subform">Sous-formulaire</string>
  <string id="Subject:">Objet :</string>
  <string id="Success">Réussite</string>
  <string id="Successfully added the group.">Ajout réussi au groupe.</string>
  <string id="Successfully Deleted All Solution(s) from the System.">Toutes les solutions ont été correctement supprimées du système.</string>
  <string id="Successfully Deleted Solution(s) from the System.">Solution(s) correctement supprimée(s) du système.</string>
  <string id="Successfully Imported Solution(s) into the System.">Solution(s) correctement importée(s) dans le système.</string>
  <string id="Summary">Résumé</string>
  <string id="Sun">Dim</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Permuter - Permute la position du bouton sélectionné avec celle du bouton Couper.</string>
  <string id="System">Système</string>
  <string id="System Health...">Santé du système...</string>
  <string id="System Status">Etat du système</string>
  <string id="System Status 1">Etat du système 1</string>
  <string id="Task Id">ID de la tâche</string>
  <string id="Task Id:">ID de tâche :</string>
  <string id="Task Name">Nom de la tâche</string>
  <string id="Task Name:">Nom de tâche :</string>
  <string id="Task Summary Report">Rapport de résumé de tâche</string>
  <string id="Test Progress">Progression du test</string>
  <string id="Test Results">Résultats du test</string>
  <string id="Test Settings">Paramètres de test</string>
  <string id="Testing LDAP Settings...">Test des paramètres LDAP...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">Les boutons du premier écran peuvent être disposés de manière personnalisée.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">Le rapport suivant a été correctement créé :  REPORT_NAME.  Consultez le rapport joint.</string>
  <string id="The password provided is incorrect.">Le mot de passe fourni est incorrect.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">Le déploiement de la stratégie de ce groupe est actuellement arrêté à partir de tous les périphériques du groupe.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">Le rapport est à présent prêt à être téléchargé. Cliquez sur OK pour continuer.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">La date A de la période du rapport est antérieure à la date De.  Le système les permutera automatiquement lorsque vous créerez le rapport.  Voulez-vous continuer ?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">Il n'y a actuellement aucun profil de client pour ce groupe client du logiciel. Ajoutez-les en remplissant le champ ci-dessous.</string>
  <string id="There are currently no cSF Apps associated with this device group."> Il n'y a actuellement aucune application cSF associée à ce groupe de périphériques.</string>
  <string id="There are currently no cSF Apps to add to this device group."> Il n'y a actuellement aucune application cSF à ajouter à ce groupe de périphériques.</string>
  <string id="There are currently no device groups to perform discovery."> Il n'y a actuellement aucun groupe de périphériques pour exécuter la recherche.</string>
  <string id='There are currently no device groups to perform policy update.'>Il n'y a actuellement aucun groupe de périphériques pour exécuter la mise à jour de la stratégie.</string>
  <string id="There are currently no device groups to schedule.">Il n'y a actuellement aucun groupe de périphériques à planifier.</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>Il n'y a actuellement aucun groupe de périphériques.  Ajoutez un groupe de périphériques en cliquant sur le bouton Ajouter, sur la gauche.</string>
  <string id="There are currently no devices discovered for this device group.">Il n'y a actuellement aucun périphérique détecté pour ce groupe de périphériques.</string>
  <string id="There are currently no devices in this device group.">Il ny a actuellement aucun périphérique dans ce groupe de périphériques.</string>
  <string id="There are currently no discovered devices.">Il ny a actuellement aucun périphérique détecté.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">Il n'y a actuellement aucun profil de recherché pour ce groupe de périphériques. Ajoutez-les en remplissant le champ approprié ci-dessous.</string>
  <string id="There are currently no forms printers in the system.">Il n'y a actuellement aucune imprimante Forms dans le système.</string>
  <string id="There are currently no licenses installed.">Il n'y a actuellement aucune licence installée.</string>
  <string id="There are currently no licensing changes made by this upload.">Il n'y a actuellement aucune modification de licence opérée par ce téléchargement.</string>
  <string id="There are currently no missing devices for this device group.">Il n'y a actuellement aucun périphérique manquant pour ce groupe de périphériques.</string>
  <string id="There are currently no missing devices.">Il n'y a actuellement aucun périphérique manquant.</string>
  <string id="There are currently no out of policy devices for this device group.">Il n'y a actuellement aucun périphérique dépourvu de stratégie pour ce groupe de périphériques.</string>
  <string id="There are currently no out of policy devices.">Il n'y a actuellement aucun périphérique dépourvu de stratégie.</string>
  <string id="There are currently no scheduled tasks">Il n'y a actuellement aucune tâche planifiée</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">Il n'y a actuellement aucun groupe client du logiciel.  Ajoutez un groupe en cliquant sur le bouton Ajouter, sur la gauche.</string>
  <string id="There are currently no solutions associated with this device group."> Il n'y a actuellement aucune solution associée à ce groupe de périphériques.</string>
  <string id="There are currently no solutions associated with this software client group.">Il n'y a actuellement aucune solution associée à ce groupe client du logiciel.</string>
  <string id="There are currently no solutions installed.">Il n'y a actuellement aucune solution installée.</string>
  <string id='There are currently no solutions to add to this device group.'>Il n'y a actuellement aucune solution à ajouter à ce groupe de périphériques.</string>
  <string id="There are currently no solutions to add to this software client group.">Il n'y a actuellement aucune solution à ajouter à ce groupe client du logiciel.</string>
  <string id="There are currently no unlicensed devices for this device group.">Il n'y a actuellement aucun périphérique sans licence pour ce groupe de périphériques.</string>
  <string id="There are currently no unlicensed devices in this device group.">Il ny a actuellement aucun périphérique sans licence dans ce groupe de périphériques.</string>
  <string id="There are currently no unlicensed devices.">Il ny a actuellement aucun périphérique sans licence.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">Il y a actuellement des solutions ou des applications cSF et/ou des écrans d'accueil associés à la stratégie de ce groupe. Voulez-vous annuler le déploiement de cette stratégie maintenant ? Notez que cette opération ne supprimera pas immédiatement le groupe de périphériques. Supprimez le groupe de périphériques lorsque la mise à jour de la stratégie est terminée.</string>
  <string id="There are no associated UCF Files for this Solution.">Aucun n'y a pas de fichier de configuration de la sécurité associé pour cette Solution.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">Aucun n'y a pas de fichier de configuration de la sécurité associé pour les Solutions dans ce groupe de périphériques.</string>
  <string id="There are no configuration settings for this eSF application.">Il ny a pas de paramètres de configuration pour cette application eSF.</string>
  <string id="There are no configuration settings in this solution.">Il ny a pas de paramètres de configuration dans cette solution.</string>
  <string id="There are no configuration settings in this webapp.">Il ny a pas de paramètres de configuration dans cette application Web.</string>
  <string id="There are no cSF Apps installed currently.">Il n'y a actuellement aucune application cSF installée.</string>
  <string id="There are no deployments setting for this solution.">Il ny a pas de paramètre de déploiement pour cette solution.</string>
  <string id="There are no devices in the system that match the filter.">Il n'y a pas de périphérique correspondant au filtre dans le système.</string>
  <string id="There are no eSF Applications for this solution.">Il n'y a pas d'application eSF pour cette solution.</string>
  <string id="There are no e-Task profiles for this device group."> Il n'y a pas de profil e-Task pour ce groupe de périphériques.</string>
  <string id="There are no e-Task2 profiles for this device group."> Il n'y a pas de profil e-Task2 pour ce groupe de périphériques.</string>
  <string id="There are no forms for this solution.">Il n'y a pas de formulaire pour cette solution.</string>
  <string id="There are no forms in the system.">Il n'y a pas de formulaire dans le système.</string>
  <string id="There are no parameters in this service.">Il ny a pas de paramètre dans ce service.</string>
  <string id="There are no profiles for this software client group.">Il n'y a pas de profil pour ce groupe client du logiciel.</string>
  <string id="There are no settings for this action.">Il ny a pas de paramètre pour cette action.</string>
  <string id="There are no settings for this solution.">Il ny a pas de paramètre pour cette solution.</string>
  <string id="There is currently a Policy Update running...">Un mise à jour de la stratégie est actuellement en cours dexécution...</string>
  <string id="There is currently no Version Info.">Il n'y a actuellement aucune information de version.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">Ces applications eSF font partie des solutions associées à ce groupe de périphériques. Veuillez sélectionner une application pour afficher ses paramètres.</string>
  <string id="These group settings are currently hidden.">Les paramètres de ce groupe sont actuellement masqués.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">Ces profils font partie de la stratégie de groupe pour chaque modèle. Veuillez sélectionner un profil pour chaque modèle afin dafficher ses paramètres.</string>
  <string id="Third">Troisième</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">Ce lient vous renvoie à l'interface utilisateur de configuration du Webkit de Lexmark, voulez-vous continuer ?</string>
  <string id="This Month">Ce mois-ci</string>
  <string id="This name has been given to another device group. Please choose a different name.">Ce nom a été attribué à un autre groupe de périphériques. Veuillez choisir un autre nom.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">Ce nom a été attribué à un autre groupe client du logiciel. Veuillez choisir un autre nom.</string>
  <string id="Thread Count">Nombre de threads</string>
  <string id="Thu">Jeu</string>
  <string id="Time">Heure</string>
  <string id="Time of Next Run">Heure de la prochaine exécution</string>
  <string id="Time Policies Last Applied">Heure de la dernière application des stratégies</string>
  <string id="Time:">Heure :</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">Pour les ajouter à l'écran d'accueil, choisissez la Mise en page personnalisée dans la zone de liste déroulante ci-dessus et ajoutez les profils.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">Pour les disposer vous-même, choisissez une des mises en page dans la zone de liste déroulante ci-dessus.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">Pour en configurer un, choisissez une des mises en page dans la zone de liste déroulante ci-dessus.</string>
  <string id="To:">A :</string>
  <string id="Today">Aujourdhui</string>
  <string id="Today date">Date d'aujourd'hui</string>
  <string id="Tops Report">Rapport Tops</string>
  <string id="Tue">Mar</string>
  <string id="UCF">Fichiers de configuration de la sécurité</string>
  <string id="UCF:">Fichiers de configuration de la sécurité :</string>  
  <string id="Unable to Change Password.">Impossible de modifier le mot de passe.</string>
  <string id="Unable to Change Username.">Impossible de modifier le nom d'utilisateur.</string>
  <string id="Unable to validate all settings!">Impossible de valider tous les paramètres !</string>
  <string id="Uncounted">Non pris en compte</string>
  <string id="Un-deploying all cSF Apps(s)...">Annuler le déploiement de toutes les applications cSF...</string>
  <string id="Un-deploying cSF App(s)...">Annulation du déploiement des applications cSF...</string>
  <string id="Unknown">Inconnu</string>
  <string id="Unknown Error Occured! Please Check System Log">Une erreur inconnue s'est produite ! Vérifiez le journal système</string>
  <string id='Unknown Secure State'>Etat de sécurisation inconnu</string>
  <string id="Unlicensed">Sans licence</string>
  <string id="Unlicensed Device">Périphérique sans licence</string>
  <string id="Unlicensed Devices">Périphériques sans licence</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Les périphériques sans licence sont des périphériques qui ont été détectés, mais auxquels une licence na pas pu être attribuée lors de la dernière détection (parce que la licence a expiré ou que toutes les licences sont utilisées, par exemple).</string>
  <string id="Unlicensed devices:">Périphériques sans licence :</string>
  <string id="Unlicensed Devices:">Périphériques sans licence :</string>
  <string id="Unlicensed:">Sans licence :</string>
  <string id="Unlimited">Illimité</string>
  <string id="Up icon:">Icône Haut :</string>
  <string id="Update">Mettre à jour</string>
  <string id="Update Policy">Mettre à jour la stratégie</string>
  <string id="Update Time">Heure de mise à jour</string>
  <string id="Update Time:">Heure de mise à jour :</string>
  <string id="Updating client profile...">Mise à jour du profil de client...</string>
  <string id="Updating discovery profile..."> Mise à jour du profil de recherche...</string>
  <string id="Updating e-Task home screen...">Mise à jour de l'écran d'accueil e-Task...</string>
  <string id="Updating e-Task2 home screen..."> Mise à jour de l'écran d'accueil e-Task2...</string>
  <string id="Updating e-Task2+ home screen..."> Mise à jour de l'écran d'accueil e-Task2+...</string>
  <string id="Updating e-Task3 home screen..."> Mise à jour de l'écran d'accueil e-Task3...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen..."> Mise à jour de l'écran d'accueil e-Task4 (4,3 po.)...</string>
  <string id="Updating e-Task4 home screen..."> Mise à jour de l'écran d'accueil e-Task4...</string>
  <string id="Updating Fax Forward settings..."> Mise à jour des paramètres de transfert des télécopies...</string>
  <string id="Updating password...">Mise à jour du mot de passe...</string>
  <string id="Updating Security setting...">Mise à jour du paramètre de sécurité...</string>
  <string id="Updating service settings...">Mise à jour des paramètres de service...</string>
  <string id="Updating SFP e-Task home screen..."> Mise à jour de l'écran d'accueil e-Task SFP...</string>
  <string id="Updating SFP e-Task2 home screen..."> Mise à jour de l'écran d'accueil e-Task2 SFP...</string>
  <string id="Updating SFP e-Task2+ home screen..."> Mise à jour de l'écran d'accueil e-Task2+ SFP...</string>
  <string id="Updating SFP e-Task3 home screen..."> Mise à jour de l'écran d'accueil e-Task3 SFP...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen..."> Mise à jour de l'écran d'accueil e-Task4 SFP (7 po.)...</string>
  <string id="Updating SFP e-Task4 home screen..."> Mise à jour de l'écran d'accueil e-Task4 SFP...</string>
  <string id="Updating solution settings...">Mise à jour des paramètres de solution...</string>
  <string id="Updating username...">Mise à jour du nom d'utilisateur...</string>
  <string id="Updating X642 home screen..."> Mise à jour de l'écran d'accueil X642...</string>
  <string id='Updating webapp settings...'>Mise à jour des paramètres webapp...</string>
  <string id="Upgrading or deleting solutions here will require">La mise à niveau ou la suppression de solutions ici nécessitera</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">La mise à niveau ou l'annulation ici du déploiement des applications cSF nécessite la &lt;b&gt;Mise à jour de la stratégie&lt;/b&gt; dans tous les groupes de périphériques concernés</string>
  <string id="Upload">Télécharger</string>
  <string id="Upload custom icons">Télécharger les icônes personnalisées</string>
  <string id="Upload Report Files">Télécharger les fichiers de rapport</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">Téléchargement du descripteur et de l'ensemble AP terminé.</string>
  <string id="Uploading AP Bundle and Descriptor...">Téléchargement du descripteur et de l'ensemble AP...</string>
  <string id="Uploading cSF Ap cert files....">Téléchargement des fichiers de certification des applications cSF....</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">Téléchargement des fichiers de certification des applications cSF (cacert.pem et key.pem ...</string>
  <string id="Uploading of cSF App cert files Completed.">Téléchargement des fichiers de certification des applications cSF terminé.</string>
  <string id="Uploading Report(s)...">Téléchargement du (des) rapport(s)...</string>
  <string id="Uploading...">Téléchargement...</string>
  <string id="Usage:">Consommation :</string>
  <string id="Usb Drive">Lecteur USB</string>
  <string id="Use default settings">Utiliser les paramètres par défaut</string>
  <string id="Use Secure Connection. (SSLTLS)">Utilisez une connexion sécurisée. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Utiliser la configuration de la solution</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">N'utilisez cette boîte de dialogue que si la base de données, les données webdav centrales du système LDD existant, doit être synchronisée avec un autre système LDD actif qui jouera le rôle de « système LDD de secours ». Pour plus d'informations sur cette fonction, reportez-vous au Guide de l'administrateur.</string>
  <string id="Use this home screen as part of the device groups policy.">Utilisez cet écran daccueil dans le cadre de la stratégie du groupe de périphériques.</string>
  <string id='Used:'>Utilisé :</string>
  <string id="User Name">Nom dutilisateur</string>
  <string id="User Name:">Nom dutilisateur :</string>
  <string id="User Report">Rapport utilisateur</string>
  <string id="User Search Base:">Base de recherche d'utilisateurs :</string>
  <string id="User Search Filter:">Filtre de recherche d'utilisateurs :</string>
  <string id="Username amp; Password">Nom dutilisateur &amp;amp; Mot de passe</string>
  <string id="Username and Password">Nom d'utilisateur et mot de passe</string>
  <string id="Username Changed Successfully.">Nom d'utilisateur correctement modifié.</string>
  <string id="Username Password">Mot de passe du nom d'utilisateur</string>
  <string id="Username updated.">Nom d'utilisateur mis à jour.</string>
  <string id="Username*">Nom d’utilisateur*</string>
  <string id="Username:">Nom dutilisateur :</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Vérifiez le déploiement de lapplication eSF et déployez ces paramètres eSF.</string>
  <string id="Version">Version</string>
  <string id="Version Info:">Infos de version :</string>
  <string id="Version:">Version :</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">Très très très long long long texte</string>
  <string id="View Details">Afficher les détails</string>
  <string id="View Source">Afficher la source</string>
  <string id="Waiting for License Upload Results ...">En attente des résultats du téléchargement de licence...</string>
  <string id="WebApps">Applications Web</string>
  <string id="WebClient Version">Version de WebClient</string>
  <string id="WebClient Version:">Version du client Web :</string>
  <string id="Wed">Mer</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated."> Ecran d'accueil X642 mis à jour.</string>
  <string id="Yes">Oui</string>
  <string id="You are viewing the Kranked version of the application">Vous consultez la version Kranked de lapplication</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">Vous ne possédez aucun privilège pour accéder à des tâches quelconques dans toutes les applications cSF</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">Vous ne possédez aucun privilège pour accéder à des tâches quelconques dans tous les groupes de périphériques</string>
  <string id="You have no privilege to this task.">Vous n'avez aucun privilège pour cette tâche.</string>
  <string id="You must first select a Task to Edit">Vous devez dabord sélectionner une tâche à modifier</string>
  <string id="active">actif</string>
  <string id="active:">actif :</string>
  <string id="addition to the two events below.">ajout aux deux événements ci-dessous.</string>
  <string id="avg response (ms)">réponse moyenne (ms)</string>
  <string id="be set back to the default values next time.">les valeurs par défaut seront rétablies la prochaine fois.</string>
  <string id="cache">cache</string>
  <string id="cc:">cc :</string>
  <string id="change">modifier</string>
  <string id="cSF App">Application cSF</string>
  <string id="cSF App Cert File">Fichier de certification d'application cSF</string>
  <string id="cSF App Certificates">Certificats d'applications cSF</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">Téléchargement des certificats d'applications cSF (cacert.pem, key.pem )</string>
  <string id="cSF App Key File">Fichier de clé d'application cSF</string>
  <string id="cSF App settings updated.">Paramètres d'application cSF mis à jour.</string>
  <string id="cSF App Version">Version de l'application cSF</string>
  <string id="cSF App Version:">Version de l'application cSF :</string>
  <string id="cSF Apps">Applications cSF</string>
  <string id="cSF Apps deployed to device group">Applications cSF déployées sur un groupe de périphériques</string>
  <string id="cSF Apps to deploy:">Applications csF à déployer :</string>
  <string id="cSF Apps: Device group deployment deleted.">Applications cSF : Déploiement du groupe de périphériques supprimé.</string>
  <string id="day(s)">jour(s)</string>
  <string id="devices failed">périphériques défaillants</string>
  <string id="devices updated">périphériques mis à jour</string>
  <string id="device(s) discovered">périphérique(s) détecté(s)</string>
  <string id="device(s) missing">périphérique(s) manquant(s)</string>
  <string id="disk-in-use=">disque utilisé=</string>
  <string id="disk-total=">total du disque=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">Paramètres de l’application eSF :</string>
  <string id="eSF Application Version:">Version de lapplication eSF :</string>
  <string id="eSF Applications">Applications eSF</string>
  <string id="eSF Applications:">Applications eSF :</string>
  <string id="eSF Applications: (Solution)">Applications eSF : (Solution)</string>
  <string id="eSF Configuration">Configuration eSF</string>
  <string id="eSF Settings Saved."> Paramètres eSF enregistrés.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">Ecran d'accueil e-Task mis à jour.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated."> Ecran d'accueil e-Task2 mis à jour.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated."> Ecran d'accueil e-Task2+ mis à jour.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated."> Ecran d'accueil e-Task3 mis à jour.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4,3 po.)</string>
  <string id="e-Task4 (4.3 in.) home screen updated."> Ecran d'accueil e-Task4 (4,3 po.) mis à jour.</string>
  <string id="e-Task4 home screen updated."> Ecran d'accueil e-Task4 mis à jour.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">échec.</string>
  <string id="hide">masquer</string>
  <string id="hour(s)">heure(s)</string>
  <string id="in order to add a group.">pour pouvoir ajouter un groupe.</string>
  <string id="info">info</string>
  <string id="load">frais</string>
  <string id="mem-in-use=">mémoire utilisé=</string>
  <string id="mem-total=">mémoire totale=</string>
  <string id="min(s)">min</string>
  <string id="month(s)">mois</string>
  <string id="not communicating">non communicant</string>
  <string id="null">nul</string>
  <string id="offline">hors ligne</string>
  <string id="on">allumé</string>
  <string id="on all effected Device Groups.">sur tous les groupes de périphériques concernés.</string>
  <string id="oncheck">oncheck</string>
  <string id="online">en ligne</string>
  <string id="or home screen support for this device does not exist.">ou la prise en charge décran daccueil pour ce périphérique nexiste pas.</string>
  <string id="requests">demandes</string>
  <string id="requests/sec">demandes/sec</string>
  <string id="saving report...">enregistrement du rapport...</string>
  <string id="server">serveur</string>
  <string id="show">afficher</string>
  <string id="test">test</string>
  <string id="to">à</string>
  <string id="to change them.">pour les modifier.</string>
  <string id="to take effect on the devices.">pour prendre effet sur les périphériques.</string>
  <string id="total requests:">total des demandes :</string>
  <string id="total responses:">total des réponses :</string>
  <string id="undo">annuler</string>
  <string id="uploaded.">téléchargé.</string>
  <string id="week(s)">semaine(s)</string>
  <string id="{0} Groups">{0} Groupes</string>
  <string id="{0} Reports">{0} Rapports</string>
  <string id="{0} Software Client Groups">{0} Groupes client du logiciel</string>
  <string id="{0} Solutions">{0} Solutions</string>
  <string id="{0} eForms">{0} Formulaires électroniques</string>
  <string id="{0} eSF Applications">{0} Applications eSF</string>
  <string id="Policy update required for changes to take effect on the devices">Toute modification effectuée ici  nécessitera la &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;mise à jour de la stratégie&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; pour être appliquée sur les périphériques.</string>
  <string id="Group search base must be set for adding group based Privileges">La base de recherche de groupe doit être définie pour ajouter un groupe basé sur les &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;privilèges&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">La base de recherche du groupe doit être définie dans la &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;configuration LDAP&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; pour pouvoir ajouter un groupe.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">Installation d'une licence PME. Pour les produits multifonction, le nombre est limité à</string>
  <string id="licenses!">licences.</string>
</localize>
`;