export const EN = `
<localize>
  <string id="% Completed">% Completed</string>
  <string id="% Completed:">% Completed:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">( Optional ) Please type in a description</string>
  <string id="( Username must be a Distinguished Name )">( Username must be a Distinguished Name )</string>
  <string id="(1-999)">(1-999)</string>
  <string id="(Cron expression)">(Cron expression)</string>
  <string id="(progress)">(progress)</string>
  <string id="* Software Client License Not Found.">* Software Client License Not Found.</string>
  <string id="1 Button">1 Button</string>
  <string id="1 minute load">1 minute load</string>
  <string id="1. Device Groups">1. Device Groups</string>
  <string id="1. Search">1. Search</string>
  <string id="1. Services">1. Services</string>
  <string id="1. Software Client Groups">1. Software Client Groups</string>
  <string id="1. Solutions">1. Solutions</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. Type in the search criteria and click the &quot;Search&quot; button.</string>
  <string id="1. WebApps">1. WebApps</string>
  <string id="1. cSF Apps">1. cSF Apps</string>
  <string id="10 Buttons">10 Buttons</string>
  <string id="15 minute load">15 minute load</string>
  <string id="15sec">15sec</string>
  <string id="2 Buttons">2 Buttons</string>
  <string id="2. Choose one or more devices if any are found.">2. Choose one or more devices if any are found.</string>
  <string id="2. Devices">2. Devices</string>
  <string id="2. Tasks">2. Tasks</string>
  <string id="3 Buttons">3 Buttons</string>
  <string id="3. Choose a Task.">3. Choose a Task.</string>
  <string id="3. Tasks">3. Tasks</string>
  <string id="30sec">30sec</string>
  <string id="4 Buttons">4 Buttons</string>
  <string id="4-16 Buttons">4-16 Buttons</string>
  <string id="5 Buttons">5 Buttons</string>
  <string id="5 minute load">5 minute load</string>
  <string id="5sec">5sec</string>
  <string id="6 Buttons">6 Buttons</string>
  <string id="60sec">60sec</string>
  <string id="7 Buttons">7 Buttons</string>
  <string id="8 Buttons">8 Buttons</string>
  <string id="9 Buttons">9 Buttons</string>
  <string id="A Policy Update is currently running...">A Policy Update is currently running...</string>
  <string id="AP (Advanced Prompting) Bundle Upload">AP (Advanced Prompting) Bundle Upload</string>
  <string id="AP Bundle Application File">AP Bundle Application File</string>
  <string id="AP Bundle Descriptor File">AP Bundle Descriptor File</string>
  <string id="AP Bundle descriptor">AP Bundle descriptor</string>
  <string id="AP Bundle">AP Bundle</string>
  <string id="About">About</string>
  <string id="Action Settings...">Action Settings...</string>
  <string id="Action Settings:">Action Settings:</string>
  <string id="Action">Action</string>
  <string id="Action:">Action:</string>
  <string id="Add Device Group">Add Device Group</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Add Device Groups to Schedule : Step 2 of 3</string>
  <string id="Add Forms Printer">Add Forms Printer</string>
  <string id="Add License">Add License</string>
  <string id="Add Software Client Group">Add Software Client Group</string>
  <string id="Add a cSF App to deploy:">Add a cSF App to deploy:</string>
  <string id="Add a new Group to the system">Add a new Group to the system</string>
  <string id="Add a new report to the system">Add a new report to the system</string>
  <string id="Add a solution to deploy: Step 1 of 2">Add a solution to deploy: Step 1 of 2</string>
  <string id="Add a solution to deploy: Step 2 of 2">Add a solution to deploy: Step 2 of 2</string>
  <string id="Add a solution: Step 1 of 2">Add a solution: Step 1 of 2</string>
  <string id="Add a solution: Step 2 of 2">Add a solution: Step 2 of 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Add a task to Schedule : Step 1 of 3</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Add the frequency to Schedule : Step 3 of 3</string>
  <string id="Add">Add</string>
  <string id="Add...">Add...</string>
  <string id="Adding Formset(s)...">Adding Formset(s)...</string>
  <string id="Adding Group Name from LDAP...">Adding Group Name from LDAP...</string>
  <string id="Adding solution to software client group...">Adding solution to software client group...</string>
  <string id="Additional Options">Additional Options</string>
  <string id="Additional Parameters">Additional Parameters</string>
  <string id="Additional Parameters...">Additional Parameters...</string>
  <string id="Additional Report Parameters">Additional Report Parameters</string>
  <string id="Address">Address</string>
  <string id="Address:">Address:</string>
  <string id="Admin password:">Admin password:</string>
  <string id="All Device Groups">All Device Groups</string>
  <string id="All Servers Offline">All Servers Offline</string>
  <string id="All Servers Online">All Servers Online</string>
  <string id="All Software Client Groups">All Software Client Groups</string>
  <string id="All Solutions">All Solutions</string>
  <string id="All Tabs">All Tabs</string>
  <string id="All cSF Apps">All cSF Apps</string>
  <string id="All scheduled tasks for the system.">All scheduled tasks for the system.</string>
  <string id="All scheduled tasks for this device group:">All scheduled tasks for this device group:</string>
  <string id="All scheduled tasks for this sftClient group">All scheduled tasks for this sftClient group</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">All selected devices will be completely removed from the system. Are you sure you want to remove these devices?</string>
  <string id="All">All</string>
  <string id="An error occurred while attempting to connect to this device,">An error occurred while attempting to connect to this device,</string>
  <string id="Anonymous">Anonymous</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Any Changes to the parameters are temporary and will be set back to the default values next time.</string>
  <string id="Any Changes to the parameters are temporary and will">Any Changes to the parameters are temporary and will</string>
  <string id="Any changes here will require">Any changes here will require</string>
  <string id="App Reservation">App Reservation</string>
  <string id="Application">Application</string>
  <string id="Apply">Apply</string>
  <string id="Are you sure you want to change the edited profile?">Are you sure you want to change the edited profile?</string>
  <string id="Are you sure you want to change these profiles?">Are you sure you want to change these profiles?</string>
  <string id="Are you sure you want to delete all the forms?">Are you sure you want to delete all the forms?</string>
  <string id="Are you sure you want to delete all the profiles?">Are you sure you want to delete all the profiles?</string>
  <string id="Are you sure you want to delete all the solutions?">Are you sure you want to delete all the solutions?</string>
  <string id="Are you sure you want to delete the selected forms?">Are you sure you want to delete the selected forms?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.</string>
  <string id="Are you sure you want to delete the selected profiles?">Are you sure you want to delete the selected profiles?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.</string>
  <string id="Are you sure you want to delete the selected solutions?">Are you sure you want to delete the selected solutions?</string>
  <string id="Are you sure you want to delete these profiles?">Are you sure you want to delete these profiles?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">Are you sure you want to un-deploy all cSF Apps?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">Are you sure you want to un-deploy the selected cSF App(s)?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">Are you sure you would like to delete this +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">Are you sure you would like to delete this Device Group?</string>
  <string id="Are you sure you would like to delete this forms printer?">Are you sure you would like to delete this forms printer?</string>
  <string id="Are you sure you would like to delete this scheduled task?">Are you sure you would like to delete this scheduled task?</string>
  <string id="Are you sure you would like to delete this software client Group?">Are you sure you would like to delete this software client Group?</string>
  <string id="Are you sure you would like to delete this solution?">Are you sure you would like to delete this solution?</string>
  <string id="Associated Device Group :">Associated Device Group :</string>
  <string id="Associated Solution :">Associated Solution :</string>
  <string id="Associated Solution:">Associated Solution:</string>
  <string id="Authentication Method:">Authentication Method:</string>
  <string id="Author">Author</string>
  <string id="Auto Refresh:">Auto Refresh:</string>
  <string id="Available Columns">Available Columns</string>
  <string id="Available Reports">Available Reports</string>
  <string id="Back">Back</string>
  <string id="Background Image:">Background Image:</string>
  <string id="Backup &amp; Restore information">Backup &amp; Restore information</string>
  <string id="Backup Jobs Logs Database">Backup Jobs Logs Database</string>
  <string id="Backup Share Path">Backup Share Path</string>
  <string id="Backup amp; Restore">Backup &amp; Restore</string>
  <string id="Bar Chart">Bar Chart</string>
  <string id="Binary Files">Binary Files</string>
  <string id="Bookmarks">Bookmarks</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">Both the cacert.pem and key.pem files are required to update cSF App certificates.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">Both the eSF flash and descriptor files are required to update the AP bundle.</string>
  <string id="Browse">Browse</string>
  <string id="Browse...">Browse...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">By default, the MFP automatically arranges the buttons on the Home Screen.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">By default, the SFP adds the profiles to the Held jobs folder.</string>
  <string id="CPU Usage">CPU Usage</string>
  <string id="CSV">CSV</string>
  <string id="Cancel">Cancel</string>
  <string id="Canceled">Canceled</string>
  <string id="Canceling...">Canceling...</string>
  <string id="Change Default Values">Change Default Values</string>
  <string id="Change Language">Change Language</string>
  <string id="Change Password">Change Password</string>
  <string id="Change Username">Change Username</string>
  <string id="Changing name...">Changing name...</string>
  <string id="Choose Client Groups">Choose Client Groups</string>
  <string id="Choose Device Groups">Choose Device Groups</string>
  <string id="Choose a cSF App to deploy:">Choose a cSF App to deploy:</string>
  <string id="Choose a solution to deploy:">Choose a solution to deploy:</string>
  <string id="Choose a solution:">Choose a solution:</string>
  <string id="Choose deployment settings for">Choose deployment settings for</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.</string>
  <string id="Choose one...">Choose one...</string>
  <string id="Choose task">Choose task</string>
  <string id="Choose the frequency">Choose the frequency</string>
  <string id="Choose the group type">Choose the group type</string>
  <string id="Class">Class</string>
  <string id="Click Add to create a Home screen button.">Click Add to create a Home screen button.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Click on checkboxes to select or deselect privileges.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Click on the square, then release the mouse button to select a new color.</string>
  <string id="Click">Click</string>
  <string id="Client Groups:">Client Groups:</string>
  <string id="Client Profile created.">Client Profile created.</string>
  <string id="Client Profiles">Client Profiles</string>
  <string id="Close">Close</string>
  <string id="Color :">Color :</string>
  <string id="Column Chart.">Column Chart.</string>
  <string id="Compile Options:">Compile Options:</string>
  <string id="Compile">Compile</string>
  <string id="Completed">Completed</string>
  <string id="Components">Components</string>
  <string id="Config Service">Config Service</string>
  <string id="Configuration">Configuration</string>
  <string id="Configuration:">Configuration:</string>
  <string id="Configurations for this discovery:">Configurations for this discovery:</string>
  <string id="Connect To App">Connect To App</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Connected to the target VM, address: 127.0.0.1:61023, transport: socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">Connection Timed Out. Please check the server configuration, including firewall settings.</string>
  <string id="Contact Location">Contact Location</string>
  <string id="Contact Location:">Contact Location:</string>
  <string id="Contact Name">Contact Name</string>
  <string id="Contact Name:">Contact Name:</string>
  <string id="Content :">Content :</string>
  <string id="Copy + Profile">Copy + Profile</string>
  <string id="Copy Shortcuts">Copy Shortcuts</string>
  <string id="Copy">Copy</string>
  <string id="Creating client profile...">Creating client profile...</string>
  <string id="Creating device group...">Creating device group...</string>
  <string id="Creating discovery profile...">Creating discovery profile...</string>
  <string id="Creating or updating a forms printer...">Creating or updating a forms printer...</string>
  <string id="Creating software client group...">Creating software client group...</string>
  <string id="Creatingupdating the scheduled task...">Creating/updating the scheduled task...</string>
  <string id="Cron expression)">Cron expression)</string>
  <string id="Current Columns">Current Columns</string>
  <string id="Current Password:">Current Password:</string>
  <string id="Current password is incorrect.">Current password is incorrect.</string>
  <string id="Currently discovering Missing Devices...">Currently discovering Missing Devices...</string>
  <string id="Currently discovering Unlicensed Devices...">Currently discovering Unlicensed Devices...</string>
  <string id="Custom icons:">Custom icons:</string>
  <string id="Custom">Custom</string>
  <string id="Custom...">Custom...</string>
  <string id="Customize Jobs Table">Customize Jobs Table</string>
  <string id="Customize Logs Table">Customize Logs Table</string>
  <string id="Customize Table...">Customize Table...</string>
  <string id="Danger, Will Robinson!">Danger, Will Robinson!</string>
  <string id="Darkness :">Darkness :</string>
  <string id="Database Driver:">Database Driver:</string>
  <string id="Database Fully Qualified Hostname OR IpAddress">Database Fully Qualified Hostname OR IpAddress</string>
  <string id="Database URL:">Database URL:</string>
  <string id="Datasource:">Datasource:</string>
  <string id="Datatype Filter">Datatype Filter</string>
  <string id="Datatype filter:">Datatype filter:</string>
  <string id="Date">Date</string>
  <string id="Debug">Debug</string>
  <string id="Default Group can not be deleted.">Default Group can not be deleted.</string>
  <string id="Default Group">Default Group</string>
  <string id="Default Output Format:">Default Output Format:</string>
  <string id="Default">Default</string>
  <string id="Default: 389">Default: 389</string>
  <string id="Delete file on failure?">Delete file on failure?</string>
  <string id="Delete file on success?">Delete file on success?</string>
  <string id="Delete">Delete</string>
  <string id="Deleted device group. One or more devices must now be updated.">Deleted device group. One or more devices must now be updated.</string>
  <string id="Deleted selected FormSet(s).">Deleted selected FormSet(s).</string>
  <string id="Deleted software client group.">Deleted software client group.</string>
  <string id="Deleting All FormSet(s)...">Deleting All FormSet(s)...</string>
  <string id="Deleting All solution(s)...">Deleting All solution(s)...</string>
  <string id="Deleting Formset(s)...">Deleting Formset(s)...</string>
  <string id="Deleting client profile(s)...">Deleting client profile(s)...</string>
  <string id="Deleting device group...">Deleting device group...</string>
  <string id="Deleting discovery profile(s)...">Deleting discovery profile(s)...</string>
  <string id="Deleting forms printer...">Deleting forms printer...</string>
  <string id="Deleting scheduled task...">Deleting scheduled task...</string>
  <string id="Deleting selected FormSet(s)...">Deleting selected FormSet(s)...</string>
  <string id="Deleting software client group...">Deleting software client group...</string>
  <string id="Deleting solution(s)...">Deleting solution(s)...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Deploy to:</string>
  <string id="Deploy:">Deploy:</string>
  <string id="Deploying WAR file:">Deploying WAR file : </string>
  <string id="Deploying home screen to">Deploying home screen to</string>
  <string id="Deploying solution to device group...">Deploying solution to device group...</string>
  <string id="Description">Description</string>
  <string id="Description:">Description:</string>
  <string id="Descriptor">Descriptor</string>
  <string id="Destination Folder Path">Destination Folder Path</string>
  <string id="Developer Forums">Developer Forums</string>
  <string id="Developer Network">Developer Network</string>
  <string id="Device Address">Device Address</string>
  <string id="Device Address:">Device Address:</string>
  <string id="Device Class">Device Class</string>
  <string id="Device Group created">Device Group created</string>
  <string id="Device Group was successfully removed from the system.">Device Group was successfully removed from the system.</string>
  <string id="Device Group">Device Group</string>
  <string id="Device Group:">Device Group:</string>
  <string id="Device Groups">Device Groups</string>
  <string id="Device Groups:">Device Groups:</string>
  <string id="Device Information Directions">Device Information Directions</string>
  <string id="Device Model">Device Model</string>
  <string id="Device Model:">Device Model:</string>
  <string id="Device Profiles">Device Profiles</string>
  <string id="Device Summary">Device Summary</string>
  <string id="Device update complete.">Device update complete.</string>
  <string id="Device update started...">Device update started...</string>
  <string id="DeviceGroup">DeviceGroup</string>
  <string id="Devices">Devices</string>
  <string id="Directory">Directory</string>
  <string id="Directory Path">Directory Path</string>
  <string id="Directory Watcher information">Directory Watcher information</string>
  <string id="Directory Watcher">Directory Watcher</string>
  <string id="Directory path*">Directory path*</string>
  <string id="Disabled">Disabled</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket</string>
  <string id="Discover Missing">Discover Missing</string>
  <string id="Discover Unlicensed">Discover Unlicensed</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Discover devices for selected device groups using each group's own Discovery Profiles.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Discover devices for this device group using its Discovery Profiles.</string>
  <string id="Discover new devices only">Discover new devices only</string>
  <string id="Discover">Discover</string>
  <string id="Discover...">Discover...</string>
  <string id="Discovered Devices">Discovered Devices</string>
  <string id="Discovered Devices:">Discovered Devices:</string>
  <string id="Discovered">Discovered</string>
  <string id="Discovery Profile created.">Discovery Profile created.</string>
  <string id="Discovery Profiles">Discovery Profiles</string>
  <string id="Discovery Profiles:">Discovery Profiles:</string>
  <string id="Discovery has Completed for...">Discovery has Completed for...</string>
  <string id="Discovery in Progress for...">Discovery in Progress for...</string>
  <string id="Discovery">Discovery</string>
  <string id="Display Text">Display Text</string>
  <string id="Display Text:">Display Text:</string>
  <string id="Documentation">Documentation</string>
  <string id="Done generating the jobs report for downloading.">Done generating the jobs report for downloading.</string>
  <string id="Done generating the logs report for downloading.">Done generating the logs report for downloading.</string>
  <string id="Done">Done</string>
  <string id="Down icon">Down icon</string>
  <string id="Down icon:">Down icon:</string>
  <string id="Download Details">Download Details</string>
  <string id="Duplex :">Duplex :</string>
  <string id="E-Forms">E-Forms</string>
  <string id="EForms">EForms</string>
  <string id="EForms:">EForms:</string>
  <string id="Edit a solution to deploy">Edit a solution to deploy</string>
  <string id="Edit a solution">Edit a solution</string>
  <string id="Edit the information about the report :">Edit the information about the report :</string>
  <string id="Edit the report settings">Edit the report settings</string>
  <string id="Edit">Edit</string>
  <string id="Edit...">Edit...</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">Either both the From date and time fields must be filled, or they must both be left blank.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">Either both the To date and time fields must be filled, or they must both be left blank.</string>
  <string id="Email + Profile">Email + Profile</string>
  <string id="Email Shortcuts">Email Shortcuts</string>
  <string id="Email To">Email To</string>
  <string id="Email the Report">Email the Report</string>
  <string id="Email">Email</string>
  <string id="Enable Fax Forwarding.">Enable Fax Forwarding.</string>
  <string id="Enable LDAP Authentication.">Enable LDAP Authentication.</string>
  <string id="Enabled for Credentials">Enabled for Credentials</string>
  <string id="Enabled for Session">Enabled for Session</string>
  <string id="End Time">End Time</string>
  <string id="End Time:">End Time:</string>
  <string id="Enter a unique group name">Enter a unique group name</string>
  <string id="Enter a unique name for this group">Enter a unique name for this group</string>
  <string id="Enter appropriate fields and click the Add button:">Enter appropriate fields and click the Add button:</string>
  <string id="Enter appropriate fields and click the Save button:">Enter appropriate fields and click the Save button:</string>
  <string id="Enter the appropriate fields and click the Add button:">Enter the appropriate fields and click the Add button:</string>
  <string id="Enter the information about the new report :">Enter the information about the new report :</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Enter the timeout values in milliseconds, separated by a space in between each retry.</string>
  <string id="Error importing license.">Error importing license.</string>
  <string id="Error in changing name.">Error in changing name.</string>
  <string id="Error in creating device group...">Error in creating device group...</string>
  <string id="Error in creating software client group...">Error in creating software client group...</string>
  <string id="Error in deleting device group.">Error in deleting device group.</string>
  <string id="Error in deleting software client group.">Error in deleting software client group.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">Error deleting the FormSet(s). Please check the logs for more details.</string>
  <string id="Error in generating the report.">Error in generating the report.</string>
  <string id="Error in saving Ldap settings.">Error saving Ldap settings.</string>
  <string id="Error in saving settings.">Error in saving settings.</string>
  <string id="Error in updating password.">Error in updating password.</string>
  <string id="Error in updating security settings.">Error updating Security setting.</string>
  <string id="Error in updating service settings.">Error in updating service settings.</string>
  <string id="Error in updating solution settings.">Error in updating solution settings.</string>
  <string id="Error while deploying home screen to">Error while deploying home screen to</string>
  <string id="Error">Error</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Evaluate in +app_url}</string>
  <string id="Evaluate in remote app">Evaluate in remote app</string>
  <string id="Every">Every</string>
  <string id="Expiration Date">Expiration Date</string>
  <string id="Expired Formset">Expired Formset</string>
  <string id="Expired!">Expired!</string>
  <string id="Expires on:">Expires on:</string>
  <string id="Export Report">Export Report</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="FALSE">FALSE</string>
  <string id="FRAMEWORK">FRAMEWORK</string>
  <string id="FTP">FTP</string>
  <string id="Failed">Failed</string>
  <string id="Fax + Profile">Fax + Profile</string>
  <string id="Fax Forward settings updated.">Fax Forward settings updated.</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax">Fax Forwarding Destination Shortcut: (Email, FTP, Fax </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Fax Forwarding Destination Shortcut: (Email, FTP, Fax)</string>
  <string id="Fax Forwarding Destination:">Fax Forwarding Destination:</string>
  <string id="Fax Forwarding LDSS Script:">Fax Forwarding LDSS Script:</string>
  <string id="Fax Forwarding Receive Mode:">Fax Forwarding Receive Mode:</string>
  <string id="Fax Forwarding">Fax Forwarding</string>
  <string id="Fax Shortcuts">Fax Shortcuts</string>
  <string id="Fax">Fax</string>
  <string id="Feature Id">Feature Id</string>
  <string id="Filter">Filter</string>
  <string id="Filters...">Filters...</string>
  <string id="Finish">Finish</string>
  <string id="Finished AP Bundle Descriptor File">Finished AP Bundle Descriptor File</string>
  <string id="Finished AP Bundle Flash File">Finished AP Bundle Flash File</string>
  <string id="Finished upload of key.pem File.">Finished upload of key.pem File.</string>
  <string id="First">First</string>
  <string id="Form Printers">Form Printers</string>
  <string id="Form field must be a single word or valid email address.">Form field must be a single word or valid email address.</string>
  <string id="Format :">Format :</string>
  <string id="Forms Printer is unlicensed">Forms Printer is unlicensed</string>
  <string id="Forms printer successfully created or updated.">Forms printer successfully created or updated.</string>
  <string id="Forms printer successfully deleted.">Forms printer successfully deleted.</string>
  <string id="Forms">Forms</string>
  <string id="Formsets">Formsets</string>
  <string id="FormsetsSubforms">Formsets/Subforms</string>
  <string id="Forward Only">Forward Only</string>
  <string id="Fourth">Fourth</string>
  <string id="Fri">Fri</string>
  <string id="From:">From:</string>
  <string id="Ftp + Profile">Ftp + Profile</string>
  <string id="Ftp Shortcuts">Ftp Shortcuts</string>
  <string id="Ftp">Ftp</string>
  <string id="Generating Report">Generating Report</string>
  <string id="Generating Report...">Generating Report...</string>
  <string id="Generating logs report for downloading...">Generating logs report for downloading...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.</string>
  <string id="Generating the jobs report for downloading...">Generating the jobs report for downloading...</string>
  <string id="Graphic">Graphic</string>
  <string id="Graphic:">Graphic:</string>
  <string id="Group Description placeholder">Group Description placeholder</string>
  <string id="Group Identifier:">Group Identifier:</string>
  <string id="Group Names from LDAP">Group Names from LDAP</string>
  <string id="Group Names from LDAP:">Group Names from LDAP:</string>
  <string id="Group Search Base:">Group Search Base:</string>
  <string id="Group Search Filter:">Group Search Filter:</string>
  <string id="Group Search Identifier:">Group Search Identifier:</string>
  <string id="Group search base must be set for adding group based">Group search base must be set for adding group based </string>
  <string id="Group search base must be set in">Group search base must be set in</string>
  <string id="Groups">Groups</string>
  <string id="Held Jobs">Held Jobs</string>
  <string id="Hide Settings">Hide Settings</string>
  <string id="Home Screen">Home Screen</string>
  <string id="Home Screens">Home Screens</string>
  <string id="Home Tab">Home Tab</string>
  <string id="Home screen deployed to">Home screen deployed to</string>
  <string id="Home">Home</string>
  <string id="Hostname">Hostname</string>
  <string id="Hostname:">Hostname:</string>
  <string id="IDR License Summary">IDR License Summary</string>
  <string id="IDR License Summary:">IDR License Summary:</string>
  <string id="Id">Id</string>
  <string id="Images">Images</string>
  <string id="Import">Import</string>
  <string id="Import...">Import...</string>
  <string id="Importing AP Bundle Descriptor File...">Importing AP Bundle Descriptor File...</string>
  <string id="Importing AP Bundle Flash File...">Importing AP Bundle Flash File...</string>
  <string id="Importing Binary String...">Importing Binary String...</string>
  <string id="Importing CaCert pem File...">Importing CaCert pem File...</string>
  <string id="Importing Solution(s)...">Importing Solution(s)...</string>
  <string id="Importing license...">Importing license...</string>
  <string id="Importing software client group profile...">Importing software client group profile...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Insert - This will insert the cut button and push the remaining buttons down</string>
  <string id="Install Time">Install Time</string>
  <string id="Install Time:">Install Time:</string>
  <string id="Install-Upgrade">Install/Upgrade</string>
  <string id="It is recommended to run reports during off hours.">It is recommended to run reports during off hours.</string>
  <string id="Items">Items</string>
  <string id="Jasper Report File Name:">Jasper Report File Name:</string>
  <string id="Job State">Job State</string>
  <string id="Job State:">Job State:</string>
  <string id="Jobs Filters Table">Jobs Filters Table</string>
  <string id="Jobs Report - CSV">Jobs Report - CSV</string>
  <string id="Jobs Report">Jobs Report</string>
  <string id="Jobs by user">Jobs by user</string>
  <string id="Jobs">Jobs</string>
  <string id="Keep previous backups">Keep previous backups</string>
  <string id="Krank">Krank</string>
  <string id="LDAP Server Settings:">LDAP Server Settings:</string>
  <string id="LDAP Setup">LDAP Setup</string>
  <string id="LDSS">LDSS</string>
  <string id="LICENSE">LICENSE</string>
  <string id="LOADING">LOADING</string>
  <string id="LOADING...">LOADING...</string>
  <string id="Language:">Language:</string>
  <string id="Last">Last</string>
  <string id="Last 12 Hours">Last 12 Hours</string>
  <string id="Last 15 Minutes">Last 15 Minutes</string>
  <string id="Last 24 Hours">Last 24 Hours</string>
  <string id="Last 3 Hours">Last 3 Hours</string>
  <string id="Last 30 Days">Last 30 Days</string>
  <string id="Last 30 Minutes">Last 30 Minutes</string>
  <string id="Last 6 Hours">Last 6 Hours</string>
  <string id="Last 7 Days">Last 7 Days</string>
  <string id="Last Discovered">Last Discovered</string>
  <string id="Last Discovered:">Last Discovered:</string>
  <string id="Last Hour">Last Hour</string>
  <string id="Last Kranked">Last Kranked</string>
  <string id="Last Modified">Last Modified</string>  
  <string id="Layout">Layout</string>
  <string id="Layout:">Layout:</string>
  <string id="Ldap Settings Saved.">Ldap Settings Saved.</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark�MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark Print Management</string>
  <string id="License Files">License Files</string>
  <string id="License Type">License Type</string>
  <string id="License Upload Results.">License Upload Results.</string>
  <string id="License Upload Results:">License Upload Results:</string>
  <string id="License">License</string>
  <string id="Licensed">Licensed</string>
  <string id="Licenses in Use">Licenses in Use</string>
  <string id="Licenses">Licenses</string>
  <string id="Limit batch size">Limit batch size</string>
  <string id="Line Chart with Time Period Slider.">Line Chart with Time Period Slider.</string>
  <string id="LoadBalancer Fully Qualified Hostname OR IpAddress">LoadBalancer Fully Qualified Hostname OR IpAddress</string>
  <string id="Loading...">Loading...</string>
  <string id="Lock Device">Lock Device</string>
  <string id="Log Report - CSV">Log Report - CSV</string>
  <string id="Log Report - Failed Jobs">Log Report - Failed Jobs</string>
  <string id="Log State">Log State</string>
  <string id="Log State:">Log State:</string>
  <string id="Log">Log</string>
  <string id="Logging In">Logging In</string>
  <string id="Login">Login</string>
  <string id="Logout">Logout</string>
  <string id="Logs Filters Table">Logs Filters Table</string>
  <string id="MONITOR">MONITOR</string>
  <string id="Max:">Max:</string>
  <string id="Member of Group(s):">Member of Groups:</string>
  <string id="Memory Usage">Memory Usage</string>
  <string id="Message">Message</string>
  <string id="Message:">Message:</string>
  <string id="Messages">Messages</string>
  <string id="Min:">Min:</string>
  <string id="Minimum length:">Minimum length:</string>
  <string id="Minimum:">Minimum:</string>
  <string id="Missing Device">Missing Device</string>
  <string id="Missing Devices">Missing Devices</string>
  <string id="Missing Devices:">Missing Devices:</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).</string>
  <string id="Missing devices:">Missing devices:</string>
  <string id="Missing">Missing</string>
  <string id="Model">Model</string>
  <string id="Model:">Model:</string>
  <string id="Mon">Mon</string>
  <string id="Move Down">Move Down</string>
  <string id="Move Up">Move Up</string>
  <string id="Name :">Name :</string>
  <string id="Name changed.">Name changed.</string>
  <string id="Name">Name</string>
  <string id="Name:">Name:</string>
  <string id="Network Load">Network Load</string>
  <string id="Network share password">Network share password</string>
  <string id="Network share user name">Network share user name</string>
  <string id="New Password:">New Password:</string>
  <string id="New Username:">New Username:</string>
  <string id="Next">Next</string>
  <string id="No Privilege Alert">No Privilege Alert</string>
  <string id="No Privilege">No Privilege</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">No Profiles exist for this device group because no solutions with profiles have been associated.</string>
  <string id="Unable to fetch data for this device or No eSF application is installed in this device.">Unable to fetch data for this device or No eSF application is installed in this device.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.</string>
  <string id="No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.">No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.</string>
  <string id="No devices are currently Out of Policy for the system.">No devices are currently Out of Policy for the system.</string>
  <string id="No devices are currently Out of Policy for this device group.">No devices are currently Out of Policy for this device group.</string>
  <string id="No home screen is configured for this device type.">No home screen is configured for this device type.</string>
  <string id="No matches found">No matches found</string>
  <string id="No records match the selected filter criteria.">No records match the selected filter criteria.</string>
  <string id="No records matched the filter criteria.">No records matched the filter criteria.</string>
  <string id="No schedulable scripts are available.">No schedulable scripts are available.</string>
  <string id="No UCF File selected">No Security Setup File selected</string>
  <string id="No">No</string>
  <string id="None of the selected devices are missing.">None of the selected devices are missing.</string>
  <string id="None of the selected devices are unlicensed.">None of the selected devices are unlicensed.</string>
  <string id="None">None</string>
  <string id="Number of Jobs per Page">Number of Jobs per Page</string>
  <string id="Number of Licenses">Number of Licenses</string>
  <string id="Number of Logs per Page">Number of Logs per Page</string>
  <string id="OK">OK</string>
  <string id="Off">Off</string>
  <string id="Once">Once</string>  
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">One or more buttons in the current configuration are not valid. &lt;font color="#ff0000"&gt;(shown in red)&lt;/font&gt; Please make sure that all the buttons are valid.</string>
  <string id="One or more tests did not pass.">One or more tests did not pass.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">Only one Policy Update can occur at a time. You can start a new Policy Update after the current one finishes.</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.</string>
  <string id="Only update those devices which are Out of Policy">Only update those devices which are Out of Policy</string>
  <string id="Only">Only</string>
  <string id="Orientation :">Orientation :</string>
  <string id="Out of Policy Device">Out of Policy Device</string>
  <string id="Out of Policy Devices">Out of Policy Devices</string>
  <string id="Out of Policy Devices:">Out of Policy Devices:</string>
  <string id="Out of Policy">Out of Policy</string>
  <string id="Output Format">Output Format</string>
  <string id="Overwrite if file already exists">Overwrite if file already exists</string>
  <string id="PDF">PDF</string>
  <string id="Page 1">Page 1</string>
  <string id="Page 2">Page 2</string>
  <string id="Page 3">Page 3</string>
  <string id="Page 4">Page 4</string>
  <string id="Paper Size :">Paper Size :</string>
  <string id="Parameters">Parameters</string>
  <string id="Password Changed Successfully.">Password Changed Successfully.</string>
  <string id="Password updated.">Password updated.</string>
  <string id="Password*">Password*</string>
  <string id="Password:">Password:</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Perform a Policy Update for selected device groups using each group's Policy.</string>
  <string id="Perform a Policy Update for selected devices.">Perform a Policy Update for selected devices.</string>
  <string id="Perform a Policy Update for this device group.">Perform a Policy Update for this device group.</string>
  <string id="Placeholder">Placeholder</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Please Contact Lexmark for Software Client License Information.</string>
  <string id="Please Verify MinMax, Length and Required Settings.">Please Verify Min/Max, Length and Required Settings.</string>
  <string id="Please choose a filter:">Please choose a filter:</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Please choose a group type to be able to access a solutions local solution settings in the scheduled script:</string>
  <string id="Please choose a script:">Please choose a script:</string>
  <string id="Please choose a task to schedule :">Please choose a task to schedule :</string>
  <string id="Please choose an action:">Please choose an action:</string>
  <string id="Please choose client groups to schedule :">Please choose client groups to schedule :</string>
  <string id="Please choose device groups to schedule :">Please choose device groups to schedule :</string>
  <string id="Please choose one of the following options:">Please choose one of the following options:</string>
  <string id="Please choose solution and script :">Please choose solution and script :</string>
  <string id="Please choose solution and script to schedule :">Please choose solution and script to schedule :</string>
  <string id="Please choose start time and frequency :">Please choose start time and frequency :</string>
  <string id="Please choose the datasource for the new report.">Please choose the datasource for the new report.</string>
  <string id="The report name already exists. Please choose a different name.">The report name already exists. Please choose a different name.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.</string>
  <string id="Please choose the jasper filename for the new report.">Please choose the jasper filename for the new report.</string>
  <string id="Please choose the output format for the new report.">Please choose the output format for the new report.</string>
  <string id="Please choose the report to schedule :">Please choose the report to schedule :</string>
  <string id="Please enter a non-expired date">Please enter a non-expired date (mm/dd/yyyy).</string>
  <string id="Please enter a valid Address.">Please enter a valid Address.</string>
  <string id="Please enter a valid End From Time">Please enter a valid End From Time (HH:MM AM/PM).</string>
  <string id="Please enter a valid End To Time">Please enter a valid End To Time (HH:MM AM/PM).</string>
  <string id="Please enter a valid From date">Please enter a valid From date (mm/dd/yyyy).</string>
  <string id="Please enter a valid From time">Please enter a valid From time (hh:mm AM/PM).</string>
  <string id="Please enter a valid Start From Time">Please enter a valid Start From Time (HH:MM AM/PM).</string>
  <string id="Please enter a valid Start To Time">Please enter a valid Start To Time (HH:MM AM/PM).</string>
  <string id="Please enter a valid To date">Please enter a valid To date (mm/dd/yyyy).</string>
  <string id="Please enter a valid To time">Please enter a valid To time (hh:mm AM/PM).</string>
  <string id="Please enter a valid date">Please enter a valid date (mm/dd/yyyy).</string>
  <string id="Please enter a valid range:">Please enter a valid range:</string>
  <string id="Please enter a valid range: 1 - 12">Please enter a valid range:： 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">Please enter a valid range:： 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">Please enter a valid range:： 1 - 59</string>  
  <string id="Please enter a valid time">Please enter a valid time(HH:MM AM/PM)</string>
  <string id="Please enter the Database driver and URL for the external database.">Please enter the Database driver and URL for the external database.</string>
  <string id="Please enter the Directory information:">Please enter the Directory information:</string>
  <string id="Please enter the location where you want the report to be saved.">Please enter the location where you want the report to be saved.</string>
  <string id="Please enter the name of the new report.">Please enter the name of the new report.</string>
  <string id="Please enter the network share user name and password.">Please enter the network share user name and password.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">Please enter the recipients to whom the report will be emailed.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">Please enter the requested information for Backup &amp; Restore :</string>
  <string id="Please make sure that all the necessary fields are filled in.">Please make sure that all the necessary fields are filled in.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Please make sure the your cron expression has 6 or 7 options seperated by spaces.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Please make sure the your cron expression has a "?" in either the 4th or 6th position, but not in both.</string>
  <string id="Please select a file to upload.">Please select a file to upload.</string>
  <string id="Please select a group on the left to modify its task privileges.">Please select a group on the left to modify its task privileges.</string>
  <string id="Please select a group to save privileges for.">Please select a group to save privileges for.</string>
  <string id="Please select a profile to view its settings.">Please select a profile to view its settings.</string>
  <string id="Please select the Group to delete.">Please select the Group to delete.</string>
  <string id="Please select the report to delete.">Please select the report to delete.</string>
  <string id="Please select the report to edit.">Please select the report to edit.</string>
  <string id="Please select the report to run.">Please select the report to run.</string>
  <string id="Please specify a port:">Please specify a port:</string>
  <string id="Policy Last Applied">Policy Last Applied</string>
  <string id="Policy Update has Completed for...">Policy Update has Completed for...</string>
  <string id="Policy Update in Progress for...">Policy Update in Progress for...</string>
  <string id="Policy Update on all effected Device Groups.">Policy Update on all effected Device Groups.</string>
  <string id="Policy Update">Policy Update</string>
  <string id="Port">Port</string>
  <string id="Port:">Port:</string>
  <string id="Present">Present</string>
  <string id="Previous">Previous</string>
  <string id="Print (Default)">Print (Default)</string>
  <string id="Print and Forward">Print and Forward</string>
  <string id="Printer Panel">Printer Panel</string>
  <string id="Printer Report">Printer Report</string>
  <string id="Privileges">Privileges</string>
  <string id="Process finished with exit code 0">Process finished with exit code 0</string>
  <string id="Profile Filters">Profile Filters</string>
  <string id="Profile:">Profile:</string>
  <string id="Profiles :">Profiles :</string>
  <string id="Profiles">Profiles</string>
  <string id="Profiles:">Profiles:</string>
  <string id="Progress %">Progress %</string>
  <string id="Property Tag">Property Tag</string>
  <string id="Property Tag:">Property Tag:</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Quality :">Quality :</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME successfully generated</string>
  <string id="Recurrence">Recurrence</string>
  <string id="Refresh Defaults">Refresh Defaults</string>
  <string id="Refresh">Refresh</string>
  <string id="Regular Expression">Regular Expression</string>
  <string id="Release Held Faxes">Release Held Faxes</string>
  <string id="Remove All">Remove All</string>
  <string id="Remove Server(s)">Remove Server(s)</string>
  <string id="Remove from System">Remove from System</string>
  <string id="Remove">Remove</string>
  <string id="RemoveAll">RemoveAll</string>
  <string id="Removing selected servers...">Removing selected servers...</string>
  <string id="Repeat this event :">Repeat this event :</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Replace - This will delete the selected button and replace it with the cut button.</string>
  <string id="Replace Me">Replace Me</string>
  <string id="Report Files">Report Files</string>
  <string id="Report From">Report From</string>
  <string id="Report Name:">Report Name:</string>
  <string id="Report Parameters:">Report Parameters:</string>
  <string id="Report To">Report To</string>
  <string id="Report by Time">Report by Time</string>
  <string id="Report">Report</string>
  <string id="Reporting Period">Reporting Period</string>
  <string id="Reports">Reports</string>
  <string id="Reports:">Reports:</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">Request timed out. Please narrow your search criteria and try again.</string>
  <string id="Required field">Required field</string>
  <string id="Reset Filter">Reset Filter</string>
  <string id="Reset to Default">Reset to Default</string>
  <string id="Reset">Reset</string>
  <string id="Resolution :">Resolution :</string>
  <string id="Return to Original">Return to Original</string>
  <string id="Retype New Password:">Retype New Password:</string>
  <string id="Retype New Username:">Retype New Username:</string>
  <string id="Run Report">Run Report</string>
  <string id="Run on All Servers">Run on All Servers</string>
  <string id="Running Tasks">Running Tasks</string>
  <string id="Running">Running</string>
  <string id="Running...">Running...</string>
  <string id="SFP e-Task home screen updated.">SFP e-Task home screen updated.</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task2 home screen updated.">SFP e-Task2 home screen updated.</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2+ home screen updated.">SFP e-Task2+ home screen updated.</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task3 home screen updated.">SFP e-Task3 home screen updated.</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task4 (7in.) home screen updated.">SFP e-Task4 (7in.) home screen updated.</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4 (7in.)</string>
  <string id="SFP e-Task4 home screen updated.">SFP e-Task4 home screen updated.</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SNMP Timeout Retries:">SNMP Timeout Retries:</string>
  <string id="SOLO">SOLO</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Sat">Sat</string>
  <string id="Save Privileges">Save Privileges</string>
  <string id="Save Settings">Save Settings</string>
  <string id="Save To">Save To</string>
  <string id="Save">Save</string>
  <string id="Saving LDAP Settings...">Saving LDAP Settings...</string>
  <string id="Saving eSF Settings...">Saving eSF Settings...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Schedule">Schedule</string>
  <string id="Scheduled task createdupdated">Scheduled task created/updated</string>
  <string id="Scheduled task deleted">Scheduled task deleted</string>
  <string id="Scheduled tasks for all client groups:">Scheduled tasks for all client groups:</string>
  <string id="Scheduled tasks for all device groups:">Scheduled tasks for all device groups:</string>
  <string id="Script">Script</string>
  <string id="Script:">Script:</string>
  <string id="Search Base:">Search Base:</string>
  <string id="Search Held Jobs">Search Held Jobs</string>
  <string id="Search LDAP for Groups:">Search LDAP for Groups:</string>
  <string id="Search">Search</string>
  <string id="Searching...">Searching...</string>
  <string id="Second">Second</string>
  <string id="Secure Server Communication">Secure Server Communication</string>
  <string id="Secure Server Communication:">Secure Server communication:</string>
  <string id="Security setting updated.">Security setting updated.</string>
  <string id="Security">Security</string>
  <string id="Security setup file updated successfully">Security setup file updated successfully</string>
  <string id="Security setup file update failed">Security setup file update failed</string>
  <string id="Select Profile...">Select Profile...</string>
  <string id="Select a Group Name:">Select a Group Name:</string>
  <string id="Select a report">Select a report</string>
  <string id="Select a script task">Select a script task</string>
  <string id="Select one...">Select one...</string>
  <string id="Select the group to copy">Select the group to copy</string>
  <string id="Sent when any leaf is checked or unchecked, in">Sent when any leaf is checked or unchecked, in</string>
  <string id="Serial Number">Serial Number</string>
  <string id="Serial Number:">Serial Number:</string>
  <string id="Server Address">Server Address</string>
  <string id="Server Address:">Server Address:</string>
  <string id="Server Port:">Server Port:</string>
  <string id="Server Report">Server Report</string>
  <string id="Server handling this LMC session">Server handling this LMC session</string>
  <string id="Server is currently offline">Server is currently offline</string>
  <string id="Server is not communicating">Server is not communicating</string>
  <string id="Server is unlicensed">Server is unlicensed</string>
  <string id="Server(s) Error">Server(s) Error</string>
  <string id="Server(s) Offline">Server(s) Offline</string>
  <string id="Servers">Servers</string>
  <string id="Service settings updated">Service settings updated</string>
  <string id="Services">Services</string>
  <string id="Set Offline">Set Offline</string>
  <string id="Set Online">Set Online</string>
  <string id="Setting selected servers offline...">Setting selected servers offline...</string>
  <string id="Setting selected servers online...">Setting selected servers online...</string>
  <string id="Settings :">Settings :</string>
  <string id="Settings:">Settings:</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut :">Shortcut :</string>
  <string id="Shortcut">Shortcut</string>
  <string id="Shortcut:">Shortcut:</string>
  <string id="Show Settings">Show Settings</string>
  <string id="Since Last Month">Since Last Month</string>
  <string id="Since Yesterday">Since Yesterday</string>
  <string id="Single Profile">Single Profile</string>
  <string id="Software Client Group created">Software Client Group created</string>
  <string id="Software Client Group">Software Client Group</string>
  <string id="Software Client Group:">Software Client Group:</string>
  <string id="Software Client Groups">Software Client Groups</string>
  <string id="Software Client Report">Software Client Report</string>
  <string id="Solution Name">Solution Name</string>
  <string id="Solution Name:">Solution Name:</string>
  <string id="Solution Report">Solution Report</string>
  <string id="Solution deleted from software client group.">Solution deleted from software client group.</string>
  <string id="Solution deployed to device group">Solution deployed to device group</string>
  <string id="Solution deployed to software client group">Solution deployed to software client group</string>
  <string id="Solution settings updated.">Solution settings updated.</string>
  <string id="Solution">Solution</string>
  <string id="Solution: Deleting device group deployment...">Solution: Deleting device group deployment...</string>
  <string id="Solution: Deleting solution from software client group...">Solution: Deleting solution from software client group...</string>
  <string id="Solution: device group deployment deleted.">Solution: device group deployment deleted.</string>
  <string id="Solutions to deploy:">Solutions to deploy:</string>
  <string id="Solutions">Solutions</string>
  <string id="Solutions:">Solutions:</string>
  <string id="Specify Restore system information">Specify Restore system information</string>
  <string id="Specify where the generated report should be saved">Specify where the generated report should be saved</string>
  <string id="Start Button Default Action">Start Button Default Action</string>
  <string id="Start Date :">Start Date:</string>
  <string id="Start Time">Start Time</string>
  <string id="Start Time:">Start Time:</string>
  <string id="State">State</string>
  <string id="Status">Status</string>
  <string id="Steps for viewing device information:">Steps for viewing device information:</string>
  <string id="Stop Task">Stop Task</string>
  <string id="Stop">Stop</string>
  <string id="Subform">Subform</string>
  <string id="Subject:">Subject:</string>
  <string id="Success">Success</string>
  <string id="Successfully Deleted All Solution(s) from the System.">Successfully Deleted All Solution(s) from the System.</string>
  <string id="Successfully Deleted Solution(s) from the System.">Successfully Deleted Solution(s) from the System.</string>
  <string id="Successfully Imported Solution(s) into the System.">Successfully Imported Solution(s) into the System.</string>
  <string id="Successfully added the group.">Successfully added the group.</string>
  <string id="Summary">Summary</string>
  <string id="Sun">Sun</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Switch - This will switch the positions between the selected and cut buttons.</string>
  <string id="System Health...">System Health...</string>
  <string id="System Status 1">System Status 1</string>
  <string id="System Status">System Status</string>
  <string id="System">System</string>
  <string id="Task Id">Task Id</string>
  <string id="Task Id:">Task Id:</string>
  <string id="Task Name">Task Name</string>
  <string id="Task Name:">Task Name:</string>
  <string id="Task Summary Report">Task Summary Report</string>
  <string id="Test Progress">Test Progress</string>
  <string id="Test Results">Test Results</string>
  <string id="Test Settings">Test Settings</string>
  <string id="Testing LDAP Settings...">Testing LDAP Settings...</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">The buttons on the first screen can be arranged in a custom manner.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.</string>
  <string id="The password provided is incorrect.">The password provided is incorrect.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">The policy of this group is now being undeployed from all devices in the group.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">The report is now ready for downloading. Please click OK to continue.</string>
  <string id="There are currently no cSF Apps associated with this device group.">There are currently no cSF Apps associated with this device group.</string>
  <string id="There are currently no cSF Apps to add to this device group.">There are currently no cSF Apps to add to this device group.</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">There are currently no client profiles for this software client group. Please add them by filling out the fields above.</string>
  <string id="There are currently no device groups to perform discovery.">There are currently no device groups to perform discovery.</string>
  <string id="There are currently no device groups to perform policy update.">There are currently no device groups to perform policy update.</string>
  <string id="There are currently no device groups to schedule.">There are currently no device groups to schedule.</string>
  <string id="There are currently no device groups.  Please add a device group by clicking on the Add button on the left.">There are currently no device groups.  Please add a device group by clicking on the Add button on the left.</string>
  <string id="There are currently no devices discovered for this device group.">There are currently no devices discovered for this device group.</string>
  <string id="There are currently no devices in this device group.">There are currently no devices in this device group.</string>
  <string id="There are currently no discovered devices.">There are currently no discovered devices.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.</string>
  <string id="There are currently no forms printers in the system.">There are currently no forms printers in the system.</string>
  <string id="There are currently no licenses installed.">There are currently no licenses installed.</string>
  <string id="There are currently no licensing changes made by this upload.">There are currently no licensing changes made by this upload.</string>
  <string id="There are currently no missing devices for this device group.">There are currently no missing devices for this device group.</string>
  <string id="There are currently no missing devices.">There are currently no missing devices.</string>
  <string id="There are currently no out of policy devices for this device group.">There are currently no out of policy devices for this device group.</string>
  <string id="There are currently no out of policy devices.">There are currently no out of policy devices.</string>
  <string id="There are currently no scheduled tasks">There are currently no scheduled tasks</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">There are currently no software client groups.  Please add a group by clicking on the Add button on the left.</string>
  <string id="There are currently no solutions associated with this device group.">There are currently no solutions associated with this device group.</string>
  <string id="There are currently no solutions associated with this software client group.">There are currently no solutions associated with this software client group.</string>
  <string id="There are currently no solutions installed.">There are currently no solutions installed.</string>
  <string id="There are currently no solutions to add to this device group.">There are currently no solutions to add to this device group.</string>
  <string id="There are currently no solutions to add to this software client group.">There are currently no solutions to add to this software client group.</string>
  <string id="There are currently no unlicensed devices for this device group.">There are currently no unlicensed devices for this device group.</string>
  <string id="There are currently no unlicensed devices in this device group.">There are currently no unlicensed devices in this device group.</string>
  <string id="There are currently no unlicensed devices.">There are currently no unlicensed devices.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">There are currently solutions or cSF Apps and/or home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.</string>
  <string id="There are no associated UCF Files for this Solution.">There are no associated Security Setup Files for this Solution.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">There are no associated Security Setup Files for the Solutions in this device group.</string>
  <string id="There are no cSF Apps installed currently.">There are no cSF Apps installed currently.</string>
  <string id="There are no configuration settings for this eSF application.">There are no configuration settings for this eSF application.</string>
  <string id="There are no configuration settings in this solution.">There are no configuration settings in this solution.</string>
  <string id="There are no configuration settings in this webapp.">There are no configuration settings in this webapp.</string>
  <string id="There are no deployments setting for this solution.">There are no deployments setting for this solution.</string>
  <string id="There are no devices in the system that match the filter.">There are no devices in the system that match the filter.</string>
  <string id="There are no e-Task profiles for this device group.">There are no e-Task profiles for this device group.</string>
  <string id="There are no e-Task2 profiles for this device group.">There are no e-Task2 profiles for this device group.</string>
  <string id="There are no eSF Applications for this solution.">There are no eSF Applications for this solution.</string>
  <string id="There are no forms for this solution.">There are no forms for this solution.</string>
  <string id="There are no forms in the system.">There are no forms in the system.</string>
  <string id="There are no parameters in this service.">There are no parameters in this service.</string>
  <string id="There are no profiles for this software client group.">There are no profiles for this software client group.</string>
  <string id="There are no settings for this action.">There are no settings for this action.</string>
  <string id="There are no settings for this solution.">There are no settings for this solution.</string>
  <string id="There is currently a Policy Update running...">There is currently a Policy Update running...</string>
  <string id="There is currently no Version Info.">There is currently no Version Info.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.</string>
  <string id="These group settings are currently hidden.">These group settings are currently hidden.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.</string>
  <string id="Third">Third</string>
  <string id="This Month">This Month</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?</string>
  <string id="This name has been given to another device group. Please choose a different name.">This name has been given to another device group. Please choose a different name.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">This name has been given to another software client group. Please choose a different name.</string>
  <string id="Thread Count">Thread Count</string>
  <string id="Thu">Thu</string>
  <string id="Time Policies Last Applied">Time Policies Last Applied</string>
  <string id="Time of Next Run">Time of Next Run</string>
  <string id="Time">Time</string>
  <string id="Time:">Time:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">To arrange them yourself, choose one of the layouts from the above drop down box.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">To configure one, please choose one of the layouts from the above drop down box.</string>
  <string id="To:">To:</string>
  <string id="Today date">Today date</string>
  <string id="Today">Today</string>
  <string id="Tops Report">Tops Report</string>
  <string id="Tue">Tue</string>
  <string id="UCF">Security Setup Files</string>
  <string id="UCF:">Security Setup Files:</string>
  <string id="Un-deploying all cSF Apps(s)...">Un-deploying all cSF Apps(s)...</string>
  <string id="Un-deploying cSF App(s)...">Un-deploying cSF App(s)...</string>
  <string id="Unable to Change Password.">Unable to Change Password.</string>
  <string id="Unable to Change Username.">Unable to Change Username.</string>
  <string id="Unable to validate all settings!">Unable to validate all settings!</string>
  <string id="Uncounted">Uncounted</string>
  <string id="Unknown Error Occured! Please Check System Log">Unknown Error Occured! Please Check System Log</string>
  <string id="Unknown Secure State">Unknown Secure State</string>
  <string id="Unknown">Unknown</string>
  <string id="Unlicensed Device">Unlicensed Device</string>
  <string id="Unlicensed Devices">Unlicensed Devices</string>
  <string id="Unlicensed Devices:">Unlicensed Devices:</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).</string>
  <string id="Unlicensed devices:">Unlicensed devices:</string>
  <string id="Unlicensed">Unlicensed</string>
  <string id="Unlicensed:">Unlicensed:</string>
  <string id="Unlimited">Unlimited</string>
  <string id="Up icon:">Up icon:</string>
  <string id="Update Policy">Update Policy</string>
  <string id="Update Time">Update Time</string>
  <string id="Update Time:">Update Time:</string>
  <string id="Update">Update</string>
  <string id="Updating Fax Forward settings...">Updating Fax Forward settings...</string>
  <string id="Updating SFP e-Task home screen...">Updating SFP e-Task home screen...</string>
  <string id="Updating SFP e-Task2 home screen...">Updating SFP e-Task2 home screen...</string>
  <string id="Updating SFP e-Task2+ home screen...">Updating SFP e-Task2+ home screen...</string>
  <string id="Updating SFP e-Task3 home screen...">Updating SFP e-Task3 home screen...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen...">Updating SFP e-Task4 (7in.) home screen...</string>
  <string id="Updating SFP e-Task4 home screen...">Updating SFP e-Task4 home screen...</string>
  <string id="Updating Security setting...">Updating Security setting...</string>
  <string id="Updating X642 home screen...">Updating X642 home screen...</string>
  <string id="Updating client profile...">Updating client profile...</string>
  <string id="Updating discovery profile...">Updating discovery profile...</string>
  <string id="Updating e-Task home screen...">Updating e-Task home screen...</string>
  <string id="Updating e-Task2 home screen...">Updating e-Task2 home screen...</string>
  <string id="Updating e-Task2+ home screen...">Updating e-Task2+ home screen...</string>
  <string id="Updating e-Task3 home screen...">Updating e-Task3 home screen...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">Updating e-Task4 (4.3 in.) home screen...</string>
  <string id="Updating e-Task4 home screen...">Updating e-Task4 home screen...</string>
  <string id="Updating password...">Updating password...</string>
  <string id="Updating service settings...">Updating service settings...</string>
  <string id="Updating solution settings...">Updating solution settings...</string>
  <string id="Updating username...">Updating username...</string>
  <string id="Updating webapp settings...">Updating webapp settings...</string>
  <string id="Upgrading or deleting solutions here will require">Upgrading or deleting solutions here will require</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">Upgrading or un-deploying cSF App(s) here will require &lt;b&gt;Policy Update&lt;/b&gt; on all effected Device Groups</string>
  <string id="Upload Report Files">Upload Report Files</string>
  <string id="Upload custom icons">Upload custom icons</string>
  <string id="Upload">Upload</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">Uploading AP Bundle and Descriptor Completed.</string>
  <string id="Uploading AP Bundle and Descriptor...">Uploading AP Bundle and Descriptor...</string>
  <string id="Uploading Report(s)...">Uploading Report(s)...</string>
  <string id="Uploading cSF Ap cert files....">Uploading cSF Ap cert files....</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">Uploading cSF App Cert files(cacert.pem and key.pem ...</string>
  <string id="Uploading of cSF App cert files Completed.">Uploading of cSF App cert files Completed.</string>
  <string id="Uploading...">Uploading...</string>
  <string id="Usage:">Usage:</string>
  <string id="Usb Drive">Usb Drive</string>  
  <string id="Use Secure Connection. (SSLTLS)">Use Secure Connection. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Use Solution Configuration</string>
  <string id="Use default settings">Use default settings</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.</string>
  <string id="Use this home screen as part of the device groups policy.">Use this home screen as part of the device groups policy.</string>
  <string id="Used:">Used:</string>
  <string id="User Name">User Name</string>
  <string id="User Name:">User Name:</string>
  <string id="User Report">User Report</string>
  <string id="User Search Base:">User Search Base:</string>
  <string id="User Search Filter:">User Search Filter:</string>
  <string id="Username Changed Successfully.">Username Changed Successfully.</string>
  <string id="Username Password">Username Password</string>
  <string id="Username amp; Password">Username &amp;amp; Password</string>
  <string id="Username and Password">Username and Password</string>
  <string id="Username updated.">Username updated.</string>
  <string id="Username*">Username*</string>
  <string id="Username:">Username:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Verify eSF application deployment and deploy these eSF settings.</string>
  <string id="Version Info:">Version Info:</string>
  <string id="Version">Version</string>
  <string id="Version:">Version:</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">Very very very long long long text</string>
  <string id="View Details">View Details</string>
  <string id="View Source">View Source</string>
  <string id="Waiting for License Upload Results ...">Waiting for License Upload Results ...</string>
  <string id="WebApps">WebApps</string>
  <string id="WebClient Version">WebClient Version</string>
  <string id="WebClient Version:">WebClient Version:</string>
  <string id="Wed">Wed</string>
  <string id="X642 home screen updated.">X642 home screen updated.</string>
  <string id="X642">X642</string>
  <string id="Yes">Yes</string>
  <string id="You are viewing the Kranked version of the application">You are viewing the Kranked version of the application</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">You have no privilege to access any of the tasks in All Device Groups</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">You have no privilege to access any of the tasks in All cSF Apps</string>
  <string id="You have no privilege to this task.">You have no privilege to this task.</string>
  <string id="You must first select a Task to Edit">You must first select a Task to Edit</string>
  <string id="[EXTERNAL]">[EXTERNAL]</string>
  <string id="[None]">[None]</string>
  <string id="active">active</string>
  <string id="active:">active:</string>
  <string id="addition to the two events below.">addition to the two events below.</string>
  <string id="avg response (ms)">avg response (ms)</string>
  <string id="be set back to the default values next time.">be set back to the default values next time.</string>
  <string id="cSF App Cert File">cSF App Cert File</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">cSF App Certificates (cacert.pem, key.pem ) Upload</string>
  <string id="cSF App Certificates">cSF App Certificates</string>
  <string id="cSF App Key File">cSF App Key File</string>
  <string id="cSF App Version">cSF App Version</string>
  <string id="cSF App Version:">cSF App Version:</string>
  <string id="cSF App settings updated.">cSF App settings updated.</string>
  <string id="cSF App">cSF App</string>
  <string id="cSF Apps deployed to device group">cSF Apps deployed to device group</string>
  <string id="cSF Apps to deploy:">cSF Apps to deploy:</string>
  <string id="cSF Apps">cSF Apps</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF Apps: Device group deployment deleted.</string>
  <string id="cache">cache</string>
  <string id="cc:">cc:</string>
  <string id="change">change</string>
  <string id="day(s)">day(s)</string>
  <string id="device(s) discovered">device(s) discovered</string>
  <string id="device(s) missing">device(s) missing</string>
  <string id="devices failed">devices failed</string>
  <string id="devices updated">devices updated</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="e-Task home screen updated.">e-Task home screen updated.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task2 home screen updated.">e-Task2 home screen updated.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2+ home screen updated.">e-Task2+ home screen updated.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task3 home screen updated.">e-Task3 home screen updated.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task4 (4.3 in.) home screen updated.">e-Task4 (4.3 in.) home screen updated.</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4.3 in.)</string>
  <string id="e-Task4 home screen updated.">e-Task4 home screen updated.</string>
  <string id="e-Task5 home screen updated.">e-Task5 home screen updated.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task5">e-Task5</string>
  <string id="eSF Application Settings:">eSF Application Settings:</string>
  <string id="eSF Application Version:">eSF Application Version:</string>
  <string id="eSF Applications">eSF Applications</string>
  <string id="eSF Applications: (Solution)">eSF Applications: (Solution)</string>
  <string id="eSF Applications:">eSF Applications:</string>
  <string id="eSF Configuration">eSF Configuration</string>
  <string id="eSF Settings Saved.">eSF Settings Saved.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="eSF">eSF</string>
  <string id="failed.">failed.</string>
  <string id="hide">hide</string>
  <string id="hour(s)">hour(s)</string>
  <string id="in order to add a group.">in order to add a group.</string>
  <string id="info">info</string>
  <string id="load">load</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">min(s)</string>
  <string id="month(s)">month(s)</string>
  <string id="not communicating">not communicating</string>
  <string id="null">null</string>
  <string id="offline">offline</string>
  <string id="on all effected Device Groups.">on all effected Device Groups.</string>
  <string id="on">on</string>
  <string id="oncheck">oncheck</string>
  <string id="online">online</string>
  <string id="or home screen support for this device does not exist.">or home screen support for this device does not exist.</string>
  <string id="requests">requests</string>
  <string id="requests/sec">requests/sec</string>
  <string id="saving report...">saving report...</string>
  <string id="server">server</string>
  <string id="show">show</string>
  <string id="test">test</string>
  <string id="to change them.">to change them.</string>
  <string id="to take effect on the devices.">to take effect on the devices.</string>
  <string id="to">to</string>
  <string id="total requests:">total requests:</string>
  <string id="total responses:">total responses:</string>
  <string id="undo">undo</string>
  <string id="uploaded.">uploaded.</string>
  <string id="week(s)">week(s)</string>
  <string id="{0} Groups">{0} Groups</string>
  <string id="{0} Reports">{0} Reports</string>
  <string id="{0} Software Client Groups">{0} Software Client Groups</string>
  <string id="{0} Solutions">{0} Solutions</string>
  <string id="{0} eForms">{0} eForms</string>
  <string id="{0} eSF Applications">{0} eSF Applications</string>
  <string id="Policy update required for changes to take effect on the devices">Any changes here will require &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Policy Update&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; to take effect on the devices.</string>
  <string id="Group search base must be set for adding group based Privileges">Group search base must be set for adding group based &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Privileges&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">Group search base must be set in &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP Setup&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;  in order to add a group.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">SMB licensed installation! MFP Licenses will be limited to a maximum of</string>
  <string id="licenses!">licenses!</string>
  <string id="Job Queue">Job Queue</string>
  <string id="Settings">Settings</string>
  <string id="Shortcut Center">Shortcut Center</string>
  <string id="Shortcuts">Shortcuts</string>
  <string id="Address Book">Address Book</string>
  <string id="Scan Profiles">Scan Profiles</string>
  <string id="Status/Supplies">Status/Supplies</string>
  <string id="App Profiles">App Profiles</string>
</localize>
`;