export const ZH = `
<localize>
  <string id="% Completed">% 已完成</string>
  <string id="% Completed:">% 已完成：</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;版本信息&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">（可选）请键入描述</string>
  <string id="( Username must be a Distinguished Name )">（用户名必须是一个可分辨名称）</string>
  <string id="(1-999)"> ）（1-999）</string>
  <string id="(Cron expression)">（Cron 表达式）</string>
  <string id="(progress)">（进度）</string>
  <string id="* Software Client License Not Found.">* 软件客户端许可证未发现。</string>
  <string id="[EXTERNAL]">[外部]</string>
  <string id="EXTERNAL">[外部]</string>
  <string id="[None]">[无]</string>
  <string id="1 Button">1 个按钮</string>
  <string id="1 minute load">1 分钟加载</string>
  <string id="1. cSF Apps">1.  cSF 应用程序</string>
  <string id="1. Device Groups">1. 设备组</string>
  <string id="1. Search">1. 搜索</string>
  <string id="1. Services">1. 服务</string>
  <string id="1. Software Client Groups">1. 软件客户组</string>
  <string id="1. Solutions">1. 解决方案</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. 键入搜索标准并单击&quot;搜索&quot;按钮。</string>
  <string id="1. WebApps">1. WebApps</string>
  <string id="10 Buttons">10 个按钮</string>
  <string id="15 minute load">15 分钟加载</string>
  <string id="15sec">15 秒</string>
  <string id="2 Buttons">2 个按钮</string>
  <string id="2. Choose one or more devices if any are found.">2. 如果发现，请选择一个或多个设备。</string>
  <string id="2. Devices">2. 设备</string>
  <string id="2. Tasks">2. 任务</string>
  <string id="3 Buttons">3 个按钮</string>
  <string id="3. Choose a Task.">3. 选择任务。</string>
  <string id="3. Tasks">3. 任务</string>
  <string id="30sec">30 秒</string>
  <string id="4 Buttons">4 个按钮</string>
  <string id="4-16 Buttons">4-16 个按钮</string>
  <string id="5 Buttons">5 个按钮</string>
  <string id="5 minute load">5 分钟加载</string>
  <string id="5sec">5 秒</string>
  <string id="6 Buttons">6 个按钮</string>
  <string id="60sec">60 秒</string>
  <string id="7 Buttons">7 个按钮</string>
  <string id="8 Buttons">8 个按钮</string>
  <string id="9 Buttons">9 个按钮</string>
  <string id="A Policy Update is currently running...">策略更新当前正在运行...</string>
  <string id="About">关于</string>
  <string id="Action">操作</string>
  <string id="Action Settings...">操作设置...</string>
  <string id="Action Settings:">操作设置：</string>
  <string id="Action:">操作：</string>
  <string id="Add">添加</string>
  <string id="Add a cSF App to deploy:"> 添加 cSF 应用程序以部署：</string>
  <string id="Add a new Group to the system">添加新组到系统</string>
  <string id="Add a new report to the system">添加新报告到系统</string>
  <string id="Add a solution to deploy: Step 1 of 2"> 添加解决方案以部署：2 步之 1</string>
  <string id="Add a solution to deploy: Step 2 of 2"> 添加解决方案以部署：2 步之 2</string>
  <string id="Add a solution: Step 1 of 2">添加解决方案：2 步之 1</string>
  <string id="Add a solution: Step 2 of 2">添加解决方案：2 步之 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">添加任务到时间表：3 步之 1</string>
  <string id="Add Device Group">添加设备组</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">添加设备组到时间表：3 步之 2</string>
  <string id="Add Forms Printer">添加 表单打印机</string>
  <string id="Add License">添加许可证</string>
  <string id="Add Software Client Group">添加软件客户组</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">添加频率到时间表：3 步之 3</string>
  <string id="Add...">添加...</string>
  <string id="Adding Formset(s)...">正在添加表单集...</string>
  <string id="Adding Group Name from LDAP...">从 LDAP 添加组名...</string>
  <string id="Adding solution to software client group...">正在添加解决方案到软件客户组...</string>
  <string id="Additional Options">其他选项</string>
  <string id="Additional Parameters">其他参数</string>
  <string id="Additional Parameters...">其他参数...</string>
  <string id="Additional Report Parameters">其他报告参数</string>
  <string id="Address">地址</string>
  <string id="Address:">地址：</string>
  <string id="Admin password:">管理员密码：</string>
  <string id="All">全部</string>
  <string id="All cSF Apps">所有 cSF 应用程序</string>
  <string id="All Device Groups">所有设备组</string>
  <string id="All scheduled tasks for the system.">系统的所有预定任务。</string>
  <string id="All scheduled tasks for this device group:"> 此设备组的所有预定任务：</string>
  <string id="All scheduled tasks for this sftClient group">此 sftClient 组的所有预定任务</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">所有选定设备将从系统被完全移除。您确认要移除这些设备吗？</string>
  <string id="All Servers Offline">所有服务器脱机</string>
  <string id="All Servers Online">所有服务器联机</string>
  <string id="All Software Client Groups">所有软件客户组</string>
  <string id="All Solutions">所有解决方案</string>
  <string id="All Tabs">所有选项卡</string>
  <string id="An error occurred while attempting to connect to this device,">当试图连接到此设备时出现错误，</string>
  <string id="Anonymous">匿名</string>
  <string id="Any changes here will require">此处任何更改将需要</string>
  <string id="Any Changes to the parameters are temporary and will">参数的任何更改是暂时的，并将</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">参数的任何更改是暂时的，并将在下次设置回默认值。</string>
  <string id="AP (Advanced Prompting) Bundle Upload">AP（高级提示）Bundle 上载</string>
  <string id="AP Bundle">AP Bundle</string>
  <string id="AP Bundle Application File">AP Bundle 应用程序文件</string>
  <string id="AP Bundle descriptor">AP Bundle 描述符</string>
  <string id="AP Bundle Descriptor File">AP Bundle 描述符文件</string>
  <string id="App Reservation">应用程序保留</string>
  <string id="Application">应用程序</string>
  <string id="Apply">应用</string>
  <string id="Are you sure you want to change the edited profile?">您确认要更改已编辑的配置文件吗？</string>
  <string id="Are you sure you want to change these profiles?">您确认要更改这些配置文件吗？</string>
  <string id="Are you sure you want to delete all the forms?">您确认要删除所有表单吗？</string>
  <string id="Are you sure you want to delete all the profiles?">您确认要删除所有配置文件吗？</string>
  <string id="Are you sure you want to delete all the solutions?">您确认要删除所有解决方案吗？</string>
  <string id="Are you sure you want to delete the selected forms?">您确认要删除选定的表单吗？</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">您确认要删除选定的组吗？与此组相关联的任何权限也将被自动删除。</string>
  <string id="Are you sure you want to delete the selected profiles?">您确认要删除选定的配置文件吗？</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">您确认要删除选定的报告吗？此报告的任何预定报告任务也将被自动删除。</string>
  <string id="Are you sure you want to delete the selected solutions?">您确认要删除选定的解决方案吗？</string>
  <string id="Are you sure you want to delete these profiles?">您确认要删除这些配置文件吗？</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">您确认要撤销部署所有 cSF 应用程序吗？</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">您确认要撤销部署选定的 cSF 应用程序吗？</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">您确认想删除此 +webAppsString.getWebAppString()+?} 吗？</string>
  <string id="Are you sure you would like to delete this Device Group?">您确认想删除此设备组吗？</string>
  <string id="Are you sure you would like to delete this forms printer?">您确认想删除此 表单打印机 吗？</string>
  <string id="Are you sure you would like to delete this scheduled task?">您确认想删除此预定任务吗？</string>
  <string id="Are you sure you would like to delete this software client Group?">您确认想删除此软件客户组吗？</string>
  <string id="Are you sure you would like to delete this solution?">您确认想删除此解决方案吗？</string>
  <string id="Associated Device Group :">已关联的设备组：</string>
  <string id="Associated Solution :">已关联的解决方案：</string>
  <string id="Associated Solution:">已关联的解决方案：</string>
  <string id="Authentication Method:">验证方法：</string>
  <string id="Author">作者</string>
  <string id="Auto Refresh:">自动刷新：</string>
  <string id="Available Columns">可用列</string>
  <string id="Available Reports">可用报告</string>
  <string id="Back">返回</string>
  <string id="Background Image:">背景图像：</string>
  <string id="Backup &amp; Restore information">备份和还原信息</string>
  <string id="Backup amp; Restore">备份和还原</string>
  <string id="Backup Jobs Logs Database">备份作业日志数据库</string>
  <string id="Backup Share Path">备份共享路径</string>
  <string id="Bar Chart">条形图</string>
  <string id="Binary Files">二进制文件</string>
  <string id="Bookmarks">书签</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">更新 cSF 应用程序证书同时需要 cacert.pem 和 key.pem 文件。</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">更新 AP Bundle 同时需要 eSF 刷新和描述符文件。</string>
  <string id="Browse">浏览</string>
  <string id="Browse...">浏览...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">默认地，MFP 自动排列主屏幕上的按钮。</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">默认地，SFP 将配置文件添加到挂起作业文件夹中。</string>
  <string id="Cancel">取消</string>
  <string id="Canceled">已取消</string>
  <string id="Canceling...">正在取消...</string>
  <string id="Change Default Values">更改默认值</string>
  <string id="Change Language">更改语言</string>
  <string id="Change Password">更改密码</string>
  <string id="Change Username">更改用户名</string>
  <string id="Changing name...">正在更改名称...</string>
  <string id="Choose a cSF App to deploy:"> 选择 cSF 应用程序以部署：</string>
  <string id="Choose a solution to deploy:">选择解决方案以部署：</string>
  <string id="Choose a solution:">选择解决方案：</string>
  <string id="Choose Client Groups">选择客户组</string>
  <string id="Choose deployment settings for">选择部署设置</string>
  <string id="Choose Device Groups">选择设备组</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">选择每一个按钮并设置其操作。没有操作的按钮将不会出现在主屏幕上。</string>
  <string id="Choose one...">选择一项...</string>
  <string id="Choose task">选择任务</string>
  <string id="Choose the frequency">选择频率</string>
  <string id="Choose the group type">选择组类型</string>
  <string id="Class">类</string>
  <string id="Click">单击</string>
  <string id="Click Add to create a Home screen button.">单击“添加”来创建主屏幕按钮。</string>
  <string id="Click on checkboxes to select or deselect privileges.">单击复选框来选择或取消选择权限。</string>
  <string id="Click on the square, then release the mouse button to select a new color.">单击方块，然后松开鼠标按钮来选择新的颜色</string>
  <string id="Client Groups:">客户组：</string>
  <string id="Client Profile created.">客户配置文件已创建。</string>
  <string id="Client Profiles">客户端配置文件</string>
  <string id="Close">关闭</string>
  <string id="Color :">颜色：</string>
  <string id="Column Chart.">柱形图。</string>
  <string id="Compile">编译</string>
  <string id="Compile Options:">编译选项：</string>
  <string id="Completed">已完成</string>
  <string id="Components">组件</string>
  <string id="Config Service">配置服务</string>
  <string id="Configuration">配置</string>
  <string id="Configuration:">配置：</string>
  <string id="Configurations for this discovery:">用于此寻找的配置：</string>
  <string id="Connect To App">连接到应用程序</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">已连接到目标 VM，地址：“127.0.0.1:61023”，传输：“套接字”</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">连接超时。请检查服务器配置，包括防火墙设置。</string>
  <string id="Contact Location">联系人位置</string>
  <string id="Contact Location:">联系人位置：</string>
  <string id="Contact Name">联系人名称</string>
  <string id="Contact Name:">联系人名称：</string>
  <string id="Content :">内容：</string>
  <string id="Copy">复印</string>
  <string id="Copy + Profile">复印 + 配置文件</string>
  <string id="Copy Shortcuts">复印快捷方式</string>
  <string id="CPU Usage">CPU 使用情况</string>
  <string id="Creating client profile...">正在创建客户端配置文件...</string>
  <string id="Creating device group...">正在创建设备组...</string>
  <string id="Creating discovery profile...">正在创建寻找配置文件...</string>
  <string id="Creating or updating a forms printer...">正在创建或更新 表单打印机...</string>
  <string id="Creating software client group...">正在创建软件客户组...</string>
  <string id="Creatingupdating the scheduled task...">正在创建/更新预定任务...</string>
  <string id="Cron expression)">（Cron 表达式）</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">当前列</string>
  <string id="Current password is incorrect.">当前密码不正确。</string>
  <string id="Current Password:">当前密码：</string>
  <string id="Currently discovering Missing Devices...">当前正在寻找缺少的设备...</string>
  <string id="Currently discovering Unlicensed Devices...">当前正在寻找未许可的设备...</string>
  <string id="Custom">自定义</string>
  <string id="Custom icons:">自定义图标：</string>
  <string id="Custom...">自定义...</string>
  <string id="Customize Jobs Table">定制作业表格</string>
  <string id="Customize Logs Table">定制日志表格</string>
  <string id="Customize Table...">定制表格...</string>
  <string id="Danger, Will Robinson!">危险！</string>
  <string id="Darkness :">浓度：</string>
  <string id="Database Driver:">数据库驱动程序：</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>数据库完全合格主机名或 IP 地址</string>
  <string id="Database URL:">数据库 URL：</string>
  <string id="Datasource:">数据来源：</string>
  <string id="Datatype Filter">数据类型过滤器</string>
  <string id="Datatype filter:">数据类型过滤器：</string>
  <string id="Date">日期</string>
  <string id="Debug">调试</string>
  <string id="Default">默认</string>
  <string id="Default Group">默认组</string>
  <string id="Default Group can not be deleted.">默认组不能被删除。</string>
  <string id="Default Output Format:">默认输出格式：</string>
  <string id="Default: 389">默认：389</string>
  <string id="Delete">删除</string>
  <string id="Delete file on failure?">失败时删除文件？</string>
  <string id="Delete file on success?">成功时删除文件？</string>
  <string id="Deleted device group. One or more devices must now be updated.">已删除设备组。一个或多个设备必须立即更新。</string>
  <string id="Deleted selected FormSet(s).">已删除选定的表单集。</string>
  <string id="Deleted software client group.">已删除软件客户组。</string>
  <string id="Deleting All FormSet(s)...">正在删除所有表单集...</string>
  <string id="Deleting All solution(s)...">正在删除所有解决方案...</string>
  <string id="Deleting client profile(s)...">正在删除客户配置文件...</string>
  <string id="Deleting device group...">正在删除设备组...</string>
  <string id="Deleting discovery profile(s)...">正在删除寻找配置文件...</string>
  <string id="Deleting forms printer...">正在删除 表单打印机...</string>
  <string id="Deleting Formset(s)...">正在删除表单集...</string>
  <string id="Deleting scheduled task...">正在删除预定任务...</string>
  <string id="Deleting selected FormSet(s)...">正在删除选定表单集...</string>
  <string id="Deleting software client group...">正在删除软件客户组...</string>
  <string id="Deleting solution(s)...">正在删除解决方案...</string>
  <string id="Delta">Delta</string>
  <string id="demo">演示  </string>  
  <string id="Deploy to:">部署到：</string>
  <string id="Deploy:">部署：</string>
  <string id="Deploying home screen to"> 正在部署主屏幕到</string>
  <string id="Deploying solution to device group..."> 正在部署解决方案到设备组...</string>
  <string id="Deploying WAR file:">正在部署 WAR 文件：</string>
  <string id="Description">描述</string>
  <string id="Description:">描述：</string>
  <string id="Descriptor">描述符</string>
  <string id="Destination Folder Path">目标文件夹路径</string>
  <string id="Developer Forums">开发者论坛</string>
  <string id="Developer Network">开发者网络</string>
  <string id="Device Address">设备地址</string>
  <string id="Device Address:">设备地址：</string>
  <string id="Device Class">设备类</string>
  <string id="Device Group">设备组</string>
  <string id="Device Group created">设备组已创建</string>
  <string id="Device Group was successfully removed from the system.">已成功从系统移除设备组。</string>
  <string id="Device Group:">设备组：</string>
  <string id="Device Groups">设备组</string>
  <string id="Device Groups:">设备组：</string>
  <string id="Device Information Directions">设备信息方向</string>
  <string id="Device Model">设备型号</string>
  <string id="Device Model:">设备型号：</string>
  <string id="Device Profiles">设备配置文件</string>
  <string id="Device Summary">设备摘要</string>
  <string id="Device update complete.">设备更新完成。</string>
  <string id="Device update started...">设备更新已开始...</string>    
  <string id="DeviceGroup">设备组</string>
  <string id="Devices">设备</string>
  <string id="Directory">目录</string>
  <string id="Directory access successful">目录访问成功</string>
  <string id="Directory Path">目录路径</string>
  <string id="Directory path*">目录路径*</string>
  <string id="Directory Watcher">目录观察程序</string>
  <string id='Directory Watcher information'>目录观察程序信息</string>  
  <string id="Disabled">禁用</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">已从目标 VM 断开连接，地址：“127.0.0.1:60902”，传输：“套接字”</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">已从目标 VM 断开连接，地址：“127.0.0.1:61015”，传输：“套接字”</string>
  <string id="Discover">寻找</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">使用每个组自己的寻找配置文件为选定的设备组寻找设备。</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">使用其寻找配置文件为此设备组寻找设备。</string>
  <string id="Discover Missing">寻找缺少设备</string>
  <string id="Discover new devices only">仅寻找新设备</string>
  <string id="Discover Unlicensed">寻找未许可设备</string>
  <string id="Discover...">寻找...</string>
  <string id="Discovered">已发现</string>
  <string id="Discovered Devices">已发现设备</string>
  <string id="Discovered Devices:">已发现设备：</string>
  <string id="Discovery">寻找</string>
  <string id="Discovery has Completed for...">寻找已完成...</string>
  <string id="Discovery in Progress for...">寻找正在进行中...</string>
  <string id="Discovery Profile created.">寻找配置文件已创建。</string>
  <string id="Discovery Profiles">寻找配置文件</string>
  <string id="Discovery Profiles:">寻找配置文件：</string>
  <string id="Display Text">显示文本</string>
  <string id="Display Text:">显示文本：</string>
  <string id="Documentation">文档</string>
  <string id="Done">完成</string>
  <string id="Done generating the jobs report for downloading.">生成作业报告以下载已完成。</string>
  <string id="Done generating the logs report for downloading.">生成日志报告以下载已完成。</string>
  <string id="Done generating the system status report for downloading.">生成系统状态报告以下载已完成。</string>
  <string id="Down icon">“向下”图标</string>
  <string id="Down icon:">“向下”图标：</string>
  <string id='Download Details'>下载详细信息</string>
  <string id="Duplex :">双面打印：</string>
  <string id="Edit">编辑</string>
  <string id="Edit a solution">编辑解决方案</string>
  <string id="Edit a solution to deploy">编辑要部署的解决方案</string>
  <string id="Edit the information about the report :">编辑有关报告的信息：</string>
  <string id="Edit the report settings">编辑报告设置</string>
  <string id="Edit...">编辑...</string>
  <string id="EForms">电子表单</string>
  <string id="E-Forms">电子表单</string>
  <string id="EForms:">电子表单：</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">起始日期和时间字段必须同时填写，或者同时留空。</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">终止日期和时间字段必须同时填写，或者同时留空。</string>
  <string id="Email">电子邮件</string>
  <string id="Email + Profile">电子邮件 + 配置文件</string>
  <string id="Email Shortcuts">电子邮件快捷方式</string>
  <string id="Email the Report">电邮报告</string>
  <string id="Email To">发送电子邮件到</string>
  <string id="Enable Fax Forwarding.">启用传真转发。</string>
  <string id="Enable LDAP Authentication.">启用 LDAP 验证。</string>
  <string id="Enabled for Credentials">为凭证启用</string>
  <string id="Enabled for Session">为会话启用</string>
  <string id="End Time">结束时间</string>
  <string id="End Time:">结束时间：</string>
  <string id="Enter a unique group name">输入唯一的组名</string>
  <string id="Enter a unique name for this group">为此组输入唯一的名称</string>
  <string id="Enter appropriate fields and click the Add button:">输入适当的字段并单击“添加”按钮：</string>
  <string id="Enter appropriate fields and click the Save button:">输入适当的字段并单击“保存”按钮：</string>
  <string id="Enter the appropriate fields and click the Add button:">输入适当的字段并单击“添加”按钮：</string>
  <string id="Enter the information about the new report :">输入有关新报告的信息：</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">输入超时值（以毫秒为单位），在每次重试之间用空格分隔。</string>
  <string id="Error">错误</string>
  <string id="Error importing license.">导入许可证时出错。</string>
  <string id="Error in changing name.">更改名称时出错。</string>
  <string id="Error in creating device group...">创建设备组时出错...</string>
  <string id="Error in creating software client group...">创建软件客户组时出错...</string>
  <string id="Error in deleting device group.">删除设备组时出错。</string>
  <string id="Error in deleting software client group.">删除软件客户组时出错。</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">删除表单集时出错。请检查日志以获得更多详细信息。</string>
  <string id="Error in generating the report.">生成报告时出错。</string>
  <string id="Error in saving Ldap settings.">保存 LDAP 设置时出错。</string>
  <string id="Error in saving settings.">保存设置时出错。</string>
  <string id="Error in updating password.">更新密码时出错。</string>
  <string id="Error in updating security settings.">更新安全设置时出错。</string>
  <string id="Error in updating service settings.">更新服务设置时出错。</string>
  <string id="Error in updating solution settings.">更新解决方案设置时出错。</string>
  <string id="Error while deploying home screen to">部署主屏幕时出错</string>
  <string id="Eval">评估</string>
  <string id="Evaluate in +app_url}">在 +app_url} 中的评估</string>
  <string id="Evaluate in remote app">在远程应用程序中的评估</string>
  <string id="Every">每隔</string>
  <string id="Expiration Date">截止日期</string>
  <string id="Expired Formset">过期的表单集</string>
  <string id="Expired!">已过期！</string>
  <string id="Expires on:">有效期限：</string>
  <string id="Export Report">导出报告</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">失败</string>
  <string id="FALSE">假</string>
  <string id="Fax">传真</string>
  <string id="Fax + Profile">传真 + 配置文件</string>
  <string id="Fax Forward settings updated."> 传真转发设置已更新。</string>
  <string id="Fax Forwarding">传真转发</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax"> 传真转发目标快捷方式：（电子邮件、FTP、传真 </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">传真转发目标快捷方式：（电子邮件、FTP、传真）</string>
  <string id="Fax Forwarding Destination:">传真转发目标：</string>
  <string id="Fax Forwarding LDSS Script:"> 传真转发 LDSS 脚本：</string>
  <string id="Fax Forwarding Receive Mode:">传真转发接收模式：</string>
  <string id="Fax Shortcuts">传真快捷方式</string>
  <string id="Feature Id">特性 ID</string>
  <string id="Filter">过滤器</string>
  <string id="Filters...">过滤器...</string>
  <string id="Finish">完成</string>
  <string id="Finished AP Bundle Descriptor File">已完成 AP Bundle 描述符文件</string>
  <string id="Finished AP Bundle Flash File">已完成 AP Bundle 刷新文件</string>
  <string id="Finished upload of key.pem File.">已完成 key.pem 文件上载。</string>
  <string id="First">首选</string>
  <string id="Form field must be a single word or valid email address.">表单字段必须是单个词或者有效的电子邮件地址。</string>
  <string id="Form Printers">表单打印机</string>
  <string id="Format :">格式：</string>
  <string id="Forms">表单</string>
  <string id="Forms Printer is unlicensed">表单打印机</string>
  <string id="Forms printer successfully created or updated.">表单打印机 已经成功创建或更新。</string>
  <string id="Forms printer successfully deleted.">表单打印机 已经成功删除。</string>
  <string id="Formsets">表单集</string>
  <string id="FormsetsSubforms">表单集/子表单</string>
  <string id="Forward Only">仅转发</string>
  <string id="Fourth">第四</string>
  <string id="FRAMEWORK">框架</string>
  <string id="Fri">星期五</string>
  <string id="From:">发件人：</string>
  <string id="Ftp">FTP</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + 配置文件</string>
  <string id="Ftp Shortcuts">FTP 快捷方式</string>
  <string id="Generating logs report for downloading...">正在生成日志报告以下载...</string>
  <string id="Generating Report">生成报告</string>
  <string id="Generating Report...">正在生成报告...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">在正常工作时间生成报告会对系统性能产生负面影响。建议在非工作时间运行报告。</string>
  <string id="Generating the jobs report for downloading...">正在生成作业报告以下载...</string>
  <string id="Generating the system status report for downloading...">正在生成系统状态报告以下载...</string>
  <string id="Graphic">图形</string>
  <string id="Graphic:">图形：</string>
  <string id="Group Description placeholder">组描述占位符</string>
  <string id="Group Identifier:">组标识符：</string>
  <string id="Group Names from LDAP">来自 LDAP 的组名</string>
  <string id="Group Names from LDAP:">来自 LDAP 的组名：</string>
  <string id="Group search base must be set for adding group based">必须设置组搜索库以添加组，基于</string>
  <string id="Group search base must be set in">必须设置组搜索库</string>
  <string id="Group Search Base:">组搜索库：</string>
  <string id="Group Search Filter:">组搜索过滤器：</string>
  <string id="Group Search Identifier:">组搜索标识符：</string>
  <string id="Groups">组</string>
  <string id="Held Jobs">挂起作业</string>
  <string id="Hide Settings">隐藏设置</string>
  <string id="Home">主页</string>
  <string id="Home Screen">主屏幕</string>
  <string id="Home screen deployed to">主屏幕已部署到</string>
  <string id="Home Screens">主屏幕</string>
  <string id="Home Tab">“主页”选项卡</string>
  <string id="Hostname">主机名</string>
  <string id="Hostname:">主机名：</string>
  <string id="Id">IDd</string>
  <string id="IDR License Summary">IDR 许可证摘要</string>
  <string id="IDR License Summary:">IDR 许可证摘要：</string>
  <string id="Images">图像</string>
  <string id="Import">导入</string>
  <string id="Import...">导入...</string>
  <string id="Importing AP Bundle Descriptor File...">正在导入 AP Bundle 描述符文件...</string>
  <string id="Importing AP Bundle Flash File...">正在导入 AP Bundle 刷新文件...</string>
  <string id='Importing Binary String...'>正在导入二进制字符串...</string>      
  <string id="Importing CaCert pem File...">正在导入 CaCert pem 文件...</string>
  <string id="Importing license...">正在导入许可证...</string>
  <string id="Importing software client group profile...">正在导入软件客户组配置文件...</string>
  <string id="Importing Solution(s)...">正在导入解决方案...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">插入 - 这将插入剪切按钮并使其余按钮下移</string>
  <string id="Install Time">安装时间</string>
  <string id="Install Time:">安装时间：</string>
  <string id="Install-Upgrade">安装/升级</string>
  <string id="It is recommended to run reports during off hours.">建议在非工作时间运行报告。</string>
  <string id="Items">项目</string>
  <string id="Jasper Report File Name:">Jasper 报告文件名：</string>
  <string id="Job State">作业状态</string>
  <string id="Job State:">作业状态：</string>
  <string id="Jobs">作业数</string>
  <string id="Jobs by user">基于用户的作业数</string>
  <string id="Jobs Filters Table">作业过滤器表格</string>
  <string id="Jobs Report">作业报告</string>
  <string id="Jobs Report - CSV">作业报告 - CSV</string>
  <string id="Keep previous backups">保留以前的备份</string>
  <string id="Krank">Krank</string>  
  <string id='Language:'>语言:</string>
  <string id="Last">前</string>
  <string id="Last 12 Hours">前 12 小时</string>
  <string id="Last 15 Minutes">前 15 分钟</string>
  <string id="Last 24 Hours">前 24 小时</string>
  <string id="Last 3 Hours">前 3 小时</string>
  <string id="Last 30 Days">前 30 天</string>
  <string id="Last 30 Minutes">前 30 分钟</string>
  <string id="Last 6 Hours">前 6 小时</string>
  <string id="Last 7 Days">前 7 天</string>
  <string id="Last Discovered">上次发现</string>
  <string id="Last Discovered:">上次发现：</string>
  <string id="Last Hour">前一小时</string>
  <string id="Last Kranked">上次 Kranked</string>
  <string id="Last Modified">上次修改</string>
  <string id="Layout">布局</string>
  <string id="Layout:">布局：</string>
  <string id="LDAP Server Settings:">LDAP 服务器设置：</string>
  <string id="Ldap Settings Saved.">LDAP 设置已保存。</string>
  <string id="LDAP Setup">LDAP 设置</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark 打印管理</string>
  <string id="License">许可证</string>
  <string id="LICENSE">许可证</string>
  <string id="License Files">许可证文件</string>
  <string id="License Type">许可证类型</string>
  <string id="License Upload Results.">许可证上载结果。</string>
  <string id="License Upload Results:">许可证上载结果：</string>
  <string id="Licensed">已许可</string>
  <string id="Licenses">许可证</string>
  <string id="Licenses in Use">许可证正在使用中</string>
  <string id="Limit batch size">限制批次大小</string>
  <string id="Line Chart with Time Period Slider.">带时间段滑块的线图。</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>负载平衡器完全合格主机名或 IP 地址</string>
  <string id="LOADING">正在加载</string>
  <string id="Loading...">正在加载...</string>
  <string id="LOADING...">正在加载...</string>
  <string id="Lock Device">锁定设备</string>
  <string id="Log">日志</string>
  <string id="Log Report - CSV">日志报告 - CSV</string>
  <string id="Log Report - Failed Jobs">日志报告 - 失败的作业</string>
  <string id="Log State">日志状态</string>
  <string id="Log State:">日志状态：</string>
  <string id="Logging In">正在登录</string>
  <string id="Login">登录</string>
  <string id="Logout">注销</string>
  <string id="Logs Filters Table">日志过滤器表格</string>
  <string id='Max:'>最大：</string>
  <string id="Member of Group(s):">组成员：</string>
  <string id="Memory Usage">内存使用情况</string>
  <string id="Message">消息</string>
  <string id="Message:">消息：</string>
  <string id="Messages">消息</string>
  <string id='Min:'>最小：</string>
  <string id='Minimum length:'>最小长度：</string>
  <string id='Minimum:'>最小：</string>
  <string id="Missing">缺少</string>
  <string id="Missing Device">缺少的设备</string>
  <string id="Missing Devices">缺少的设备</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">缺少的设备是指曾经被发现，但在最近的寻找期间无法找到（例如：由于设备脱离网络）的设备。</string>
  <string id="Missing devices:">缺少的设备：</string>
  <string id="Missing Devices:">缺少的设备：</string>
  <string id="Model">型号</string>
  <string id="Model:">型号：</string>
  <string id="Mon">月</string>
  <string id="MONITOR">监视器</string>
  <string id="Move Down">下移</string>
  <string id="Move Up">上移</string>
  <string id="Name">名称</string>
  <string id="Name :">名称：</string>
  <string id="Name changed.">名称已更改。</string>
  <string id="Name:">名称：</string>
  <string id="Network Load">网络负载</string>
  <string id="Network share password">网络共享密码</string>
  <string id="Network share user name">网络共享用户名</string>
  <string id="New Password:">新密码：</string>
  <string id="New Username:">新用户名：</string>
  <string id="Next">下一步</string>
  <string id="No">否</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>不存在此设备组的 cSF 应用程序。在您能够关联此操作到按钮之前，您需要有至少一个 cSF 应用程序。</string>
  <string id="No devices are currently Out of Policy for the system.">当前系统没有设备脱离策略。</string>
  <string id="No devices are currently Out of Policy for this device group.">当前此设备组没有设备脱离策略。</string>
  <string id="No home screen is configured for this device type.">没有为此设备类型配置主屏幕。</string>
  <string id="No matches found">没有发现匹配项</string>
  <string id='No Privilege'>没有权限</string>    
  <string id="No Privilege Alert">没有权限警报</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">由于没有解决方案与配置文件相关联，不存在此设备组的配置文件。</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">不存在此设备组的配置文件。在您能够关联此操作到按钮之前，您需要有至少一个配置文件。</string>
  <string id="No records match the selected filter criteria.">没有记录符合选定的过滤条件。</string>
  <string id="No records matched the filter criteria.">没有记录符合过滤条件。</string>
  <string id="No schedulable scripts are available.">没有可调度的脚本。</string>
  <string id="No UCF File selected">没有选定安全设置文件</string>
  <string id="None">无</string>
  <string id="None of the selected devices are missing.">没有缺少的选定设备。</string>
  <string id="None of the selected devices are unlicensed.">没有未许可的选定设备。</string>
  <string id="Number of Jobs per Page">每页作业数</string>
  <string id="Number of Licenses">许可证数</string>
  <string id="Number of Logs per Page">每页日志数</string>
  <string id="Off">关</string>
  <string id="OK">确定</string>
  <string id="Once">一次</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">当前配置中的一个或多个按钮是无效的。&lt;font color="#ff0000"&gt;(以红色显示)&lt;/font&gt; 请确认所有按钮是有效的。</string>
  <string id="One or more tests did not pass.">一个或多个测试未通过。</string>
  <string id="Only"> 仅</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">同一时间只能有一次寻找。当前寻找完成后，您可以开始新的寻找。</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">同一时间只能发生一次策略更新。当前更新完成后，您可以开始新的策略更新。</string>
  <string id="Only update those devices which are Out of Policy">只更新那些脱离策略的设备</string>
  <string id="Orientation :">方向：</string>
  <string id="Out of Policy">脱离策略</string>
  <string id="Out of Policy Device">脱离策略的设备</string>
  <string id="Out of Policy Devices">脱离策略的设备</string>
  <string id="Out of Policy Devices:">脱离策略的设备：</string>
  <string id="Output Format">输出格式</string>
  <string id="Overwrite if file already exists">如果文件已经存在则改写</string>
  <string id="Page 1">第 1 页</string>
  <string id="Page 2">第 2 页</string>
  <string id="Page 3">第 3 页</string>
  <string id="Page 4">第 4 页</string>
  <string id="Paper Size :">纸张尺寸：</string>
  <string id="Parameters">参数</string>
  <string id="Password Changed Successfully.">密码已成功更改。</string>
  <string id="Password updated.">密码已更新。</string>
  <string id="Password*">密码*</string>
  <string id="Password:">密码：</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">使用每个组的策略为选定的设备组执行策略更新。</string>
  <string id="Perform a Policy Update for selected devices.">为选定的设备执行策略更新。</string>
  <string id="Perform a Policy Update for this device group.">为此设备组执行策略更新。</string>
  <string id="Placeholder">占位符</string>
  <string id="Please choose a filter:">请选择过滤器：</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">请选择能够访问预定脚本中解决方案的本地解决方案设置的组类型：</string>
  <string id="Please choose a script:">请选择脚本：</string>
  <string id="Please choose a task to schedule :">请选择要预定的任务：</string>
  <string id="Please choose an action:">请选择操作：</string>
  <string id="Please choose client groups to schedule :">请选择要预定的客户组：</string>
  <string id="Please choose device groups to schedule :">请选择要预定的设备组：</string>
  <string id="Please choose one of the following options:">请选择下列选项之一：</string>
  <string id="Please choose solution and script :">请选择解决方案和脚本：</string>
  <string id="Please choose solution and script to schedule :">请选择要预定的解决方案和脚本：</string>
  <string id="Please choose start time and frequency :">请选择开始时间和频率：</string>
  <string id="Please choose the datasource for the new report.">请为新报告选择数据来源。</string>
  <string id="Please choose the jasper filename for the new report.">请为新报告选择 jasper 文件名。</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">请为新报告选择 jasper 文件名。如果没有列出，请上载 jasper 报告。</string>
  <string id="Please choose the output format for the new report.">请为新报告选择输出格式。</string>
  <string id="Please choose the report to schedule :">请选择要预定的报告：</string>
  <string id="Please Contact Lexmark for Software Client License Information.">请联系 Lexmark 以获取软件客户端许可证信息。</string>
  <string id="Please enter a non-expired date">请输入非过期的日期（mm/dd/yyyy）。</string>
  <string id="Please enter a valid Address.">请输入有效的地址。</string>
  <string id="Please enter a valid date">请输入有效的日期（mm/dd/yyyy）。</string>
  <string id="Please enter a valid End From Time">请输入有效的结束起始时间（HH:MM AM/PM）。</string>
  <string id="Please enter a valid End To Time">请输入有效的结束终止时间（HH:MM AM/PM）。</string>
  <string id="Please enter a valid From date">请输入有效的起始日期（mm/dd/yyyy）。</string>
  <string id="Please enter a valid From time">请输入有效的起始时间（hh:mm AM/PM）。</string>
  <string id='Please enter a valid range:'>请输入有效的范围：</string>
  <string id="Please enter a valid range: 1 - 12">请输入有效的范围：1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">请输入有效的范围：1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">请输入有效的范围：1 - 59</string>
  <string id="Please enter a valid Start From Time">请输入有效的开始起始时间（HH:MM AM/PM）。</string>
  <string id="Please enter a valid Start To Time">请输入有效的开始终止时间（HH:MM AM/PM）。</string>
  <string id="Please enter a valid time">请输入有效的时间（HH:MM AM/PM）</string>
  <string id="Please enter a valid To date">请输入有效的终止日期（mm/dd/yyyy）。</string>
  <string id="Please enter a valid To time">请输入有效的终止时间（hh:mm AM/PM）。</string>
  <string id="Please enter the Database driver and URL for the external database.">请输入外部数据库的数据库驱动程序和 URL。</string>
  <string id="Please enter the Directory information:">请输入目录信息：</string>
  <string id="Please enter the location where you want the report to be saved.">请输入您要保存报告的位置。</string>
  <string id="Please enter the name of the new report.">请输入新报告的名称。</string>
  <string id="Please enter the network share user name and password.">请输入网络共享用户名和密码。</string>
  <string id="Please enter the recipients to whom the report will be emailed.">请输入将接收报告电子邮件的收件人。</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">请为备份和还原输入请求的信息：</string>
  <string id="Please make sure that all the necessary fields are filled in.">请确认所有必需的字段都已填写。</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">请确认您的 cron 表达式有 6 或 7 个选项，用空格分隔。</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">请确认您的 cron 表达式在第 4 或第 6 个位置有一个“?”，但不是在两个位置上同时出现。</string>
  <string id="Please select a file to upload.">请选择要上载的文件。</string>
  <string id="Please select a group on the left to modify its task privileges.">请在左边选择一个组以修改它的任务权限。</string>
  <string id="Please select a group to save privileges for.">请选择要保存其权限的组。</string>
  <string id="Please select a profile to view its settings.">请选择配置文件以查看其设置。</string>
  <string id="Please select the Group to delete.">请选择要删除的组。</string>
  <string id="Please select the report to delete.">请选择要删除的报告。</string>
  <string id="Please select the report to edit.">请选择要编辑的报告。</string>
  <string id="Please select the report to run.">请选择要运行的报告。</string>
  <string id="Please specify a port:">请指定端口：</string>
  <string id="Please Verify MinMax, Length and Required Settings.">请检验最小值/最大值，长度和必需的设置。</string>
  <string id="Policy Last Applied">上次应用的策略</string>
  <string id="Policy Update">策略更新</string>
  <string id="Policy Update has Completed for...">策略更新已完成...</string>
  <string id="Policy Update in Progress for...">策略更新正在进行中...</string>
  <string id="Policy Update on all effected Device Groups.">在所有受影响设备组上的策略更新。</string>
  <string id="Port">端口</string>
  <string id="Port:">端口：</string>
  <string id="Present">存在</string>
  <string id="Previous">上一步</string>
  <string id="Print (Default)">打印（默认）</string>
  <string id="Print and Forward">打印并转发</string>
  <string id="Printer Panel">打印机面板</string>
  <string id="Printer Report">打印机报告</string>
  <string id="Privileges">权限</string>
  <string id="Process finished with exit code 0">使用退出代码 0 结束进程</string>
  <string id="Profile Filters">配置文件过滤器</string>
  <string id="Profile:">配置文件：</string>
  <string id="Profiles">配置文件</string>
  <string id="Profiles :">配置文件 ：</string>
  <string id="Profiles:"> 配置文件：</string>
  <string id="Progress %">进度 %</string>
  <string id="Property Tag">属性标记</string>
  <string id="Property Tag:">属性标记：</string>
  <string id="Quality :">质量：</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">重复</string>
  <string id="Refresh">刷新</string>
  <string id="Refresh Defaults">刷新默认值</string>
  <string id="Regular Expression">常规表达式</string>
  <string id="Release Held Faxes">释放挂起传真</string>
  <string id="Remove">移除</string>
  <string id="Remove All">全部删除</string>
  <string id="Remove from System">从系统移除</string>
  <string id="Remove Server(s)">移除服务器</string>
  <string id="RemoveAll">RemoveAll</string>
  <string id="Removing selected servers...">正在移除选定的服务器...</string>
  <string id="Repeat this event :">重复此事件：</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">替换 - 这将删除选定的按钮并使用剪切按钮替换。</string>
  <string id="Replace Me">替换我</string>
  <string id="Report">报告</string>
  <string id="Report by Time">按时间的报告</string>
  <string id="Report Files">报告文件</string>
  <string id="Report From">报告发件人</string>
  <string id="Report Name:">报告名称：</string>
  <string id="Report Parameters:">报告参数：</string>
  <string id="Report To">报告收件人</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME 已经成功生成</string>
  <string id="Reporting Period">报告期间</string>
  <string id="Reports">报告</string>
  <string id="Reports:">报告：</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">请求超时。请缩窄您的搜索标准并重试。</string>
  <string id="Required field">必需的字段</string>
  <string id="Reset">重置</string>
  <string id="Reset Filter">重置过滤器</string>
  <string id="Reset to Default">重置为默认值</string>
  <string id="Resolution :">分辨率：</string>
  <string id="Return to Original">返回原点</string>
  <string id="Retype New Password:">重新键入新密码：</string>
  <string id="Retype New Username:">重新键入新用户名：</string>
  <string id="Run on All Servers">在所有服务器上运行</string>
  <string id="Run Report">运行报告</string>
  <string id="Running">正在运行</string>
  <string id="Running Tasks">运行任务</string>
  <string id="Running...">正在运行...</string>
  <string id="Sat">星期六</string>
  <string id="Save">保存</string>
  <string id="Save Privileges">保存权限</string>
  <string id="Save Settings">保存设置</string>
  <string id="Save To">保存至</string>
  <string id="Saving eSF Settings..."> 正在保存 eSF 设置...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">正在保存 LDAP 设置...</string>
  <string id="Schedule">时间表</string>
  <string id="Scheduled task createdupdated">预定任务已创建/更新</string>
  <string id="Scheduled task deleted">预定任务已删除</string>
  <string id="Scheduled tasks for all client groups:">所有客户组的预定任务：</string>
  <string id="Scheduled tasks for all device groups:">所有设备组的预定任务：</string>
  <string id="Script">脚本</string>
  <string id="Script:">脚本：</string>
  <string id="Search">搜索</string>
  <string id="Search Base:">搜索库：</string>
  <string id="Search Held Jobs">搜索挂起作业</string>
  <string id="Search LDAP for Groups:">搜索 LDAP 中的组：</string>
  <string id="Searching...">正在搜索...</string>
  <string id="Second">第二</string>
  <string id="Secure Server Communication">安全服务器通讯</string>
  <string id="Secure Server Communication:">安全服务器通讯：</string>
  <string id="Security">安全</string>
  <string id="Security setting updated.">安全设置已更新。</string>
  <string id="Security setup file updated successfully">安全设置文件已更新成功</string>
  <string id="Security setup file update failed">安全设置文件更新失败</string>
  <string id="Select a Group Name:">选择组名：</string>
  <string id="Select a report">选择报告</string>
  <string id="Select a script task">选择脚本任务</string>
  <string id="Select one...">选择一个...</string>
  <string id="Select Profile...">选择配置文件...</string>
  <string id="Select the group to copy">选择要复制的组</string>
  <string id="Sent when any leaf is checked or unchecked, in">当任何叶被选中或取消选中时发送，</string>
  <string id="Serial Number">序列号</string>
  <string id="Serial Number:">序列号：</string>
  <string id="Server Address">服务器地址</string>
  <string id="Server Address:">服务器地址：</string>
  <string id="Server handling this LMC session">服务器处理此 LMC 会话</string>
  <string id="Server is currently offline">服务器当前脱机</string>
  <string id="Server is not communicating">服务器没有通讯</string>
  <string id="Server is unlicensed">服务器未被许可</string>
  <string id="Server Port:">服务器端口：</string>
  <string id="Server Report">服务器报告</string>
  <string id="Server(s) Error">服务器错误</string>
  <string id="Server(s) Offline">服务器脱机</string>
  <string id="Servers">服务器</string>
  <string id="Service settings updated">服务设置已更新</string>
  <string id="Services">服务</string>
  <string id="Set Offline">设置脱机</string>
  <string id="Set Online">设置联机</string>
  <string id="Setting selected servers offline...">正在设置选定的服务器脱机...</string>
  <string id="Setting selected servers online...">正在设置选定的服务器联机...</string>
  <string id="Settings :">设置：</string>
  <string id="Settings:">设置：</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task home screen updated."> SFP e-Task 主屏幕已更新。</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated."> SFP e-Task2 主屏幕已更新。</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated."> SFP e-Task2+ 主屏幕已更新。</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated."> SFP e-Task3 主屏幕已更新。</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4（7 英寸）</string>
  <string id="SFP e-Task4 (7in.) home screen updated."> SFP e-Task4（7 英寸）主屏幕已更新。</string>
  <string id="SFP e-Task4 home screen updated."> SFP e-Task4 主屏幕已更新。</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">快捷方式</string>
  <string id="Shortcut :">快捷方式 ：</string>
  <string id="Shortcut:">快捷方式：</string>
  <string id="Show Settings">显示设置</string>
  <string id="Since Last Month">自上月起</string>
  <string id="Since Yesterday">自昨天起</string>
  <string id="Single Profile">单个配置文件</string>
  <string id="SNMP Timeout Retries:">SNMP 超时重试：</string>
  <string id="Software Client Group">软件客户组</string>
  <string id="Software Client Group created">软件客户组已创建</string>
  <string id="Software Client Group:">软件客户组：</string>
  <string id="Software Client Groups">软件客户组</string>
  <string id="Software Client Report">软件客户报告</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">解决方案</string>
  <string id="Solution deleted from software client group.">解决方案已从软件客户组删除。</string>
  <string id="Solution deployed to device group"> 解决方案已部署到设备组</string>
  <string id="Solution deployed to software client group">解决方案已部署到软件客户组</string>
  <string id="Solution Name">解决方案名称</string>
  <string id="Solution Name:">解决方案名称：</string>
  <string id="Solution Report">解决方案报告</string>
  <string id="Solution settings updated.">解决方案设置已更新。</string>
  <string id="Solution: Deleting device group deployment..."> 解决方案：正在删除设备组部署...</string>
  <string id="Solution: Deleting solution from software client group...">解决方案：正在从软件客户组删除解决方案...</string>
  <string id="Solution: device group deployment deleted."> 解决方案：设备组部署已删除。</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">解决方案</string>
  <string id="Solutions to deploy:">要部署的解决方案：</string>
  <string id="Solutions:">解决方案：</string> 
  <string id='Specify Restore system information'>指定还原系统信息</string>  
  <string id="Specify where the generated report should be saved">指定保存已生成报告的位置</string>
  <string id="Start Button Default Action">开始按钮默认操作</string>
  <string id="Start Date :">开始日期：</string>
  <string id="Start Time">开始时间</string>
  <string id="Start Time:">开始时间：</string>
  <string id="State">状态</string>
  <string id="Status">状态</string>
  <string id="Steps for viewing device information:">查看设备信息的步骤：</string>
  <string id="Stop">停止</string>
  <string id="Stop Task">停止任务</string>
  <string id="Subform">子表单</string>
  <string id="Subject:">主题：</string>
  <string id="Success">成功</string>
  <string id="Successfully added the group.">已成功添加到组。</string>
  <string id="Successfully Deleted All Solution(s) from the System.">已经从系统成功删除所有解决方案。</string>
  <string id="Successfully Deleted Solution(s) from the System.">已经从系统成功删除解决方案。</string>
  <string id="Successfully Imported Solution(s) into the System.">已经成功导入解决方案到系统中。</string>
  <string id="Summary">摘要</string>
  <string id="Sun">星期日</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">开关 - 这将切换选定和剪切按钮之间的位置。</string>
  <string id="System">系统</string>
  <string id="System Health...">系统运行状况...</string>
  <string id="System Status">系统状态</string>
  <string id="System Status 1">系统状态 1</string>
  <string id="Task Id">任务 ID</string>
  <string id="Task Id:">任务 ID：</string>
  <string id="Task Name">任务名称</string>
  <string id="Task Name:">任务名称：</string>
  <string id="Task Summary Report">任务摘要报告</string>
  <string id="Test Progress">测试进度</string>
  <string id="Test Results">测试结果</string>
  <string id="Test Settings">测试设置</string>
  <string id="Testing LDAP Settings...">正在测试 LDAP 设置...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">第一个屏幕上的按钮可以按自定义方式排列。</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">下面的报告已经成功生成：REPORT_NAME。请查看所附的报告。</string>
  <string id="The password provided is incorrect.">提供的密码不正确。</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">此组的策略现在正在从组中的所有设备上被撤销部署。</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">报告现已准备好下载。请单击“确定”以继续。</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">报告期间的终止日期早于起始日期。当生成报告时，系统将自动为您切换它们。您要继续吗？</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">当前没有用于此软件客户组的客户端配置文件。请通过填写上面的字段来添加它们。</string>
  <string id="There are currently no cSF Apps associated with this device group."> 当前没有与此设备组相关联的 cSF 应用程序。</string>
  <string id="There are currently no cSF Apps to add to this device group."> 当前没有 cSF 应用程序添加到此设备组。</string>
  <string id="There are currently no device groups to perform discovery.">当前没有设备组执行寻找。</string>
  <string id='There are currently no device groups to perform policy update.'>当前没有设备组执行策略更新。</string>  
  <string id="There are currently no device groups to schedule.">当前没有设备组预定。</string>
  <string id="There are currently no client groups to schedule.">当前没有客户组预定。</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>当前没有设备组。请通过单击左边的“添加”按钮来添加设备组。</string>
  <string id="There are currently no devices discovered for this device group.">当前没有为此设备组发现设备。</string>
  <string id="There are currently no devices in this device group.">当前在此设备组中没有设备。</string>
  <string id="There are currently no discovered devices.">当前没有发现的设备。</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">当前没有用于此设备组的寻找配置文件。请通过填写上面的适当字段来添加它们。</string>
  <string id="There are currently no forms printers in the system.">当前系统中没有 表单打印机</string>
  <string id="There are currently no licenses installed.">当前没有安装许可证。</string>
  <string id="There are currently no licensing changes made by this upload.">当前没有由此次上载作出的许可更改。</string>
  <string id="There are currently no missing devices for this device group.">当前此设备组没有缺少的设备。</string>
  <string id="There are currently no missing devices.">当前没有缺少的设备。</string>
  <string id="There are currently no out of policy devices for this device group.">当前此设备组没有脱离策略的设备。</string>
  <string id="There are currently no out of policy devices.">当前没有脱离策略的设备。</string>
  <string id="There are currently no scheduled tasks">当前没有预定任务</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">当前没有软件客户组。请通过单击左边的“添加”按钮来添加组。</string>
  <string id="There are currently no solutions associated with this device group."> 当前没有与此设备组相关联的解决方案。</string>
  <string id="There are currently no solutions associated with this software client group.">当前没有与此软件客户组相关联的解决方案。</string>
  <string id="There are currently no solutions installed.">当前没有安装解决方案。</string>
  <string id='There are currently no solutions to add to this device group.'>当前没有解决方案添加到此设备组。</string>
  <string id="There are currently no solutions to add to this software client group.">当前没有解决方案添加到此软件客户组。</string>
  <string id="There are currently no unlicensed devices for this device group.">当前此设备组没有未许可的设备。</string>
  <string id="There are currently no unlicensed devices in this device group.">当前在此设备组中没有未许可的设备。</string>
  <string id="There are currently no unlicensed devices.">当前没有未许可的设备。</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">当前存在与此组的策略相关联的解决方案或 cSF 应用程序和/或主屏幕。您想立即撤销此策略的部署吗？请注意，这样做将不会立即删除设备组。请在策略更新完成时移除设备组。</string>
  <string id="There are no associated UCF Files for this Solution.">没有用于此解决方案的相关安全设置文件。</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">在此设备组中没有用于解决方案的相关安全设置文件。</string>
  <string id="There are no configuration settings for this eSF application.">没有用于此 eSF 应用程序的配置设置。</string>
  <string id="There are no configuration settings in this solution.">此解决方案中没有配置设置。</string>
  <string id="There are no configuration settings in this webapp.">此 webapp 中没有配置设置。</string>
  <string id="There are no cSF Apps installed currently.">当前没有安装 cSF 应用程序。</string>
  <string id="There are no deployments setting for this solution.">没有用于此解决方案的部署设置。</string>
  <string id="There are no devices in the system that match the filter.">系统中没有与过滤器相匹配的设备。</string>
  <string id="There are no eSF Applications for this solution.">没有用于此解决方案的 eSF 应用程序。</string>
  <string id="There are no e-Task profiles for this device group."> 没有用于此设备组的 e-Task 配置文件。</string>
  <string id="There are no e-Task2 profiles for this device group."> 没有用于此设备组的 e-Task2 配置文件。</string>
  <string id="There are no forms for this solution.">没有用于此解决方案的表单。</string>
  <string id="There are no forms in the system.">系统中没有表单。</string>
  <string id="There are no parameters in this service.">此服务内没有参数。</string>
  <string id="There are no profiles for this software client group.">没有用于此软件客户组的配置文件。</string>
  <string id="There are no settings for this action.">没有用于此操作的设置。</string>
  <string id="There are no settings for this solution.">没有用于此解决方案的设置。</string>
  <string id="There is currently a Policy Update running...">当前有策略更新正在运行...</string>
  <string id="There is currently no Version Info.">当前没有版本信息。</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">这些 eSF 应用程序是与此设备组相关联的解决方案的一部分。请选择应用程序以查看其设置。</string>
  <string id="These group settings are currently hidden.">这些组设置当前已隐藏。</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">这些配置文件是每个型号的组策略的一部分。请选择每个型号的配置文件以查看其设置。</string>
  <string id="Third">第三</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">此链接将通往 Lexmark 的 Webkit 配置 UI，您要继续吗？</string>
  <string id="This Month">本月</string>
  <string id="This name has been given to another device group. Please choose a different name.">此名称已被赋予另一个设备组。请选择其他名称。</string>
  <string id="This name has been given to another software client group. Please choose a different name.">此名称已被赋予另一个软件客户组。请选择其他名称。</string>
  <string id="Thread Count">线程计数</string>
  <string id="Thu">星期四</string>
  <string id="Time">时间</string>
  <string id="Time of Next Run">下次运行时间</string>
  <string id="Time Policies Last Applied">上次应用策略时间</string>
  <string id="Time:">时间：</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">要将它们添加到主屏幕，请从上面的下拉框选择自定义布局并添加配置文件。</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">要自己排列它们，请从上面的下拉框选择布局之一。</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">要配置一种布局，请从上面的下拉框选择布局之一。</string>
  <string id="To:">收件人：</string>
  <string id="Today">今天</string>
  <string id="Today date">今天日期</string>
  <string id="Tops Report">高级报告</string>
  <string id="Tue">星期二</string>
  <string id="UCF">安全设置文件</string>
  <string id="UCF:">安全设置文件:</string>  
  <string id="Unable to Change Password.">无法更改密码。</string>
  <string id="Unable to Change Username.">无法更改用户名。</string>
  <string id="Unable to validate all settings!">无法验证所有设置！</string>
  <string id="Uncounted">未计数</string>
  <string id="Un-deploying all cSF Apps(s)...">正在撤销部署所有 cSF 应用程序...</string>
  <string id="Un-deploying cSF App(s)...">正在撤销部署 cSF 应用程序...</string>
  <string id="Unknown">未知</string>
  <string id="Unknown Error Occured! Please Check System Log">出现未知的错误！请检查系统日志</string>
  <string id='Unknown Secure State'>未知的安全状态</string>
  <string id="Unlicensed">未许可</string>
  <string id="Unlicensed Device">未许可的设备</string>
  <string id="Unlicensed Devices">未许可的设备</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">未许可的设备是指那些已发现，但在最近的寻找中不能被分配许可证的设备。（例如，由于许可证到期或者所有许可证都正在使用中）。</string>
  <string id="Unlicensed devices:">未许可的设备：</string>
  <string id="Unlicensed Devices:">未许可的设备：</string>
  <string id="Unlicensed:">未许可：</string>
  <string id="Unlimited">无限制</string>
  <string id="Up icon:">“向上”图标：</string>
  <string id="Update">更新</string>
  <string id="Update Policy">更新策略</string>
  <string id="Update Time">更新时间</string>
  <string id="Update Time:">更新时间：</string>
  <string id="Updating client profile...">正在更新客户端配置文件...</string>
  <string id="Updating discovery profile..."> 正在更新寻找配置文件...</string>
  <string id="Updating e-Task home screen...">正在更新 e-Task 主屏幕...</string>
  <string id="Updating e-Task2 home screen..."> 正在更新 e-Task2 主屏幕...</string>
  <string id="Updating e-Task2+ home screen..."> 正在更新 e-Task2+ 主屏幕...</string>
  <string id="Updating e-Task3 home screen..."> 正在更新 e-Task3 主屏幕...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen..."> 正在更新 e-Task4（4.3 英寸）主屏幕...</string>
  <string id="Updating e-Task4 home screen..."> 正在更新 e-Task4 主屏幕...</string>
  <string id="Updating Fax Forward settings..."> 正在更新传真转发设置...</string>
  <string id="Updating password...">正在更新密码...</string>
  <string id="Updating Security setting...">正在更新安全设置...</string>
  <string id="Updating service settings...">正在更新服务设置...</string>
  <string id="Updating SFP e-Task home screen..."> 正在更新 SFP e-Task 主屏幕...</string>
  <string id="Updating SFP e-Task2 home screen..."> 正在更新 SFP e-Task2 主屏幕...</string>
  <string id="Updating SFP e-Task2+ home screen..."> 正在更新 SFP e-Task2+ 主屏幕...</string>
  <string id="Updating SFP e-Task3 home screen..."> 正在更新 SFP e-Task3 主屏幕...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen..."> 正在更新 SFP e-Task4（7 英寸）主屏幕...</string>
  <string id="Updating SFP e-Task4 home screen..."> 正在更新 SFP e-Task4 主屏幕...</string>
  <string id="Updating solution settings...">正在更新解决方案设置...</string>
  <string id="Updating username...">正在更新用户名...</string>
  <string id="Updating X642 home screen..."> 正在更新 X642 主屏幕...</string>
  <string id='Updating webapp settings...'>正在更新 webapp 设置...</string>
  <string id="Upgrading or deleting solutions here will require">将需要升级或删除此处的解决方案</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">升级或撤销部署此处的 cSF 应用程序将要求在所有受影响设备组上的 &lt;b&gt;策略更新&lt;/b&gt;。</string>
  <string id="Upload">上载</string>
  <string id="Upload custom icons">上载自定义图标</string>
  <string id="Upload Report Files">上载报告文件</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">上载 AP Bundle 和描述符已完成。</string>
  <string id="Uploading AP Bundle and Descriptor...">正在上载 AP Bundle 和描述符...</string>
  <string id="Uploading cSF Ap cert files....">正在上载 cSF 应用程序证书文件....</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">正在上载 cSF 应用程序证书文件（cacert.pem 和 key.pem）...</string>
  <string id="Uploading of cSF App cert files Completed.">上载 cSF 应用程序证书文件已完成。</string>
  <string id="Uploading Report(s)...">正在上载报告...</string>
  <string id="Uploading...">正在上载...</string>
  <string id="Usage:">使用情况：</string>
  <string id="Usb Drive">USB 驱动器</string>
  <string id="Use default settings">使用默认设置</string>
  <string id="Use Secure Connection. (SSLTLS)">使用安全连接。（SSL/TLS）</string>
  <string id="Use Solution Configuration">使用解决方案配置</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">仅在现有 LDD 系统的数据库、中央 webdav 数据需要与另一个活动的 LDD 系统同步（将作为“备份 LDD 系统”）时使用此对话。如需有关此特性的信息，请参考管理员指南。</string>
  <string id="Use this home screen as part of the device groups policy.">将此主屏幕作为设备组策略的一部分使用。</string>
  <string id='Used:'>已使用：</string>
  <string id="User Name">用户名</string>
  <string id="User Name:">用户名：</string>
  <string id="User Report">用户报告</string>
  <string id="User Search Base:">用户搜索库：</string>
  <string id="User Search Filter:">用户搜索过滤器：</string>
  <string id="Username amp; Password">用户名和密码</string>
  <string id="Username and Password">用户名和密码</string>
  <string id="Username Changed Successfully.">用户名已更改成功。</string>
  <string id="Username Password">用户名密码</string>
  <string id="Username updated.">用户名已更新。</string>
  <string id="Username*">用户名*</string>
  <string id="Username:">用户名：</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">检验 eSF 应用程序部署并部署这些 eSF 设置。</string>
  <string id="Version">版本</string>
  <string id="Version Info:">版本信息：</string>
  <string id="Version:">版本：</string>
  <string id="VersionInfo">版本信息</string>
  <string id="Very very very long long long text">非常长的文本</string>
  <string id="View Details">查看详细信息</string>
  <string id="View Source">查看来源</string>
  <string id="Waiting for License Upload Results ...">正在等待许可证上载结果 ...</string>
  <string id="WebApps">WebApps</string>
  <string id="WebClient Version">WebClient 版本</string>
  <string id="WebClient Version:">WebClient 版本：</string>
  <string id="Wed">星期三</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated."> X642 主屏幕已更新。</string>
  <string id="Yes">是</string>
  <string id="You are viewing the Kranked version of the application">您正在查看应用程序的 Kranked 版本</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">您没有权限访问“所有 cSF 应用程序”中的任何任务</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">您没有权限访问“所有设备组”中的任何任务</string>
  <string id="You have no privilege to this task.">您没有权限访问此任务。</string>
  <string id="You must first select a Task to Edit">您必须先选择要编辑的任务</string>
  <string id="active">活动</string>
  <string id="active:">活动：</string>
  <string id="addition to the two events below.">除了下面两个事件。</string>
  <string id="avg response (ms)">平均响应时间（毫秒）</string>
  <string id="be set back to the default values next time.">在下次设置回默认值。</string>
  <string id="cache">缓存</string>
  <string id="cc:">抄送：</string>
  <string id="change">更改</string>
  <string id="cSF App">cSF 应用程序</string>
  <string id="cSF App Cert File">cSF 应用程序证书文件</string>
  <string id="cSF App Certificates">cSF 应用程序证书</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">cSF 应用程序证书（cacert.pem、key.pem）上载</string>
  <string id="cSF App Key File">cSF 应用程序密钥文件</string>
  <string id="cSF App settings updated.">cSF 应用程序设置已更新。</string>
  <string id="cSF App Version">cSF 应用程序版本</string>
  <string id="cSF App Version:">cSF 应用程序版本：</string>
  <string id="cSF Apps">cSF 应用程序</string>
  <string id="cSF Apps deployed to device group">cSF 应用程序已部署到设备组</string>
  <string id="cSF Apps to deploy:">要部署的 cSF 应用程序：</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF 应用程序：设备组部署已删除。</string>
  <string id="day(s)">天</string>
  <string id="devices failed">设备失败</string>
  <string id="devices updated">设备已更新</string>
  <string id="device(s) discovered">设备已发现</string>
  <string id="device(s) missing">设备缺少</string>
  <string id="disk-in-use=">disk-in-use=</string>
  <string id="disk-total=">disk-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">eSF 应用程序设置：</string>
  <string id="eSF Application Version:">eSF 应用程序版本：</string>
  <string id="eSF Applications">eSF 应用程序</string>
  <string id="eSF Applications:">eSF 应用程序：</string>
  <string id="eSF Applications: (Solution)">eSF 应用程序：（解决方案）</string>
  <string id="eSF Configuration">eSF 配置</string>
  <string id="eSF Settings Saved."> eSF 设置已保存。</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">e-Task 主屏幕已更新。</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated."> e-Task2 主屏幕已更新。</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated."> e-Task2+ 主屏幕已更新。</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated."> e-Task3 主屏幕已更新。</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4（4.3 英寸）</string>
  <string id="e-Task4 (4.3 in.) home screen updated."> e-Task4（4.3 英寸）主屏幕已更新。</string>
  <string id="e-Task4 home screen updated."> e-Task4 主屏幕已更新。</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">失败。</string>
  <string id="Finished downloading">已完成下载</string>
  <string id="hide">隐藏</string>
  <string id="hour(s)">小时</string>
  <string id="in order to add a group.">为了添加组。</string>
  <string id="info">信息</string>
  <string id="load">加载</string>
  <string id="mem-in-use=">mem-in-use=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">分钟</string>
  <string id="month(s)">月</string>
  <string id="not communicating">未通讯</string>
  <string id="null">null</string>
  <string id="offline">脱机</string>
  <string id="on">开</string>
  <string id="on all effected Device Groups.">在所有受影响的设备组上。</string>
  <string id="oncheck">oncheck</string>
  <string id="online">联机</string>
  <string id="or home screen support for this device does not exist.">或者支持此设备的主屏幕不存在。</string>
  <string id="requests">请求</string>
  <string id="requests/sec">请求/秒</string>
  <string id="saving report...">正在保存报告...</string>
  <string id="server">服务器</string>
  <string id="show">显示</string>
  <string id="test">测试</string>
  <string id="to">至</string>
  <string id="to change them.">来更改它们。</string>
  <string id="to take effect on the devices.">来在设备上生效。</string>
  <string id="total requests:">总请求数：</string>
  <string id="total responses:">总响应数：</string>
  <string id="undo">撤销</string>
  <string id="uploaded.">已上载。</string>
  <string id="week(s)">周</string>
  <string id="{0} Groups">{0} 组</string>
  <string id="{0} Reports">{0} 报告</string>
  <string id="{0} Software Client Groups">{0} 软件客户组</string>
  <string id="{0} Solutions">{0} 解决方案</string>
  <string id="{0} eForms">{0} eForms</string>
  <string id="{0} eSF Applications">{0} eSF 应用程序</string>
  <string id="Policy update required for changes to take effect on the devices">此处任何更改都将需要&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;策略更新&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;，以便在设备上生效。</string>
  <string id="Group search base must be set for adding group based Privileges">必须设置组搜索库以添加基于组的&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;权限&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">必须在&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP 设置中设置组搜索库以添加组。</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">SMB 许可安装！MFP 许可证将被限制为最多</string>
  <string id="licenses!">许可证！</string>
</localize>
`;