export const PT = `
<localize>
  <string id="% Completed">% Concluído</string>
  <string id="% Completed:">% concluído:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;Informações da versão&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">(Opcional) Digite uma descrição</string>
  <string id="( Username must be a Distinguished Name )">( O nome de usuário deve ser um nome diferenciado)</string>
  <string id="(1-999)">(1-999)</string>
  <string id="(Cron expression)">(Expressão Cron)</string>
  <string id="(progress)">(progresso)</string>
  <string id="* Software Client License Not Found.">* Licença do cliente do software não encontrada.</string>
  <string id="[EXTERNAL]">[EXTERNO]</string>
  <string id="[None]">[Nenhum]</string>
  <string id="1 Button">1 Botão</string>
  <string id="1 minute load">1 minuto de carga</string>
  <string id="1. cSF Apps">1. Aplicativos cSF</string>
  <string id="1. Device Groups">1. Grupos de dispositivo</string>
  <string id="1. Search">1. Pesquisar</string>
  <string id="1. Services">1. Serviços</string>
  <string id="1. Software Client Groups">1. Grupos de cliente de software</string>
  <string id="1. Solutions">1. Soluções</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. Digite os critérios de pesquisa e clique no botão &quot;Procurar&quot;.</string>
  <string id="1. WebApps">1. WebApps</string>
  <string id="10 Buttons">10 botões</string>
  <string id="15 minute load">15 minuto de carga</string>
  <string id="15sec">15 segundos</string>
  <string id="2 Buttons">2 botões</string>
  <string id="2. Choose one or more devices if any are found.">2. Escolha um ou mais dispositivos se algum for encontrado.</string>
  <string id="2. Devices">2. Dispositivos</string>
  <string id="2. Tasks">2. Tarefas</string>
  <string id="3 Buttons">3 botões</string>
  <string id="3. Choose a Task.">3. Escolha uma tarefa.</string>
  <string id="3. Tasks">3. Tarefas</string>
  <string id="30sec">30 segundos</string>
  <string id="4 Buttons">4 botões</string>
  <string id="4-16 Buttons">4-16 botões</string>
  <string id="5 Buttons">5 botões</string>
  <string id="5 minute load">5 minuto de carga</string>
  <string id="5sec">5 segundos</string>
  <string id="6 Buttons">6 botões</string>
  <string id="60sec">60 segundos</string>
  <string id="7 Buttons">7 botões</string>
  <string id="8 Buttons">8 botões</string>
  <string id="9 Buttons">9 botões</string>
  <string id="A Policy Update is currently running...">Uma atualização de política está sendo executada...</string>
  <string id="About">Sobre</string>
  <string id="Action">Ação</string>
  <string id="Action Settings...">Configurações de ação...</string>
  <string id="Action Settings:">Configurações de ação:</string>
  <string id="Action:">Ação:</string>
  <string id="Add">Adicionar</string>
  <string id="Add a cSF App to deploy:">Adicionar um aplicativo cSF para implantar:</string>
  <string id="Add a new Group to the system">Adicionar um novo grupo ao sistema</string>
  <string id="Add a new report to the system">Adicionar um novo relatório ao sistema</string>
  <string id="Add a solution to deploy: Step 1 of 2">Adicionar uma solução para implantar: Etapa 1 de 2</string>
  <string id="Add a solution to deploy: Step 2 of 2">Adicionar uma solução para implantar: Etapa 2 de 2</string>
  <string id="Add a solution: Step 1 of 2">Adicionar uma solução: Etapa 1 de 2</string>
  <string id="Add a solution: Step 2 of 2">Adicionar uma solução: Etapa 2 de 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Adicionar uma tarefa a ser programada: Etapa 1 de 3</string>
  <string id="Add Device Group">Adicionar grupo de dispositivo</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Adicionar grupos de dispositivo a serem programados: Etapa 2 de 3</string>
  <string id="Add Forms Printer">Adicionar impressora de formulários</string>
  <string id="Add License">Adicionar licença</string>
  <string id="Add Software Client Group">Adicionar grupo de cliente de software</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Adicionar a freqüência a ser programada: Etapa 3 de 3</string>
  <string id="Add...">Adicionar...</string>
  <string id="Adding Formset(s)...">Adicionando formset(s)...</string>
  <string id="Adding Group Name from LDAP...">Adicionando nome de grupo de LDAP...</string>
  <string id="Adding solution to software client group...">Adicionando solução a grupo de cliente de software...</string>
  <string id="Additional Options">Opções adicionais</string>
  <string id="Additional Parameters">Parâmetros adicionais</string>
  <string id="Additional Parameters...">Parâmetros adicionais...</string>
  <string id="Additional Report Parameters">Parâmetros de relatório adicionais</string>
  <string id="Address">Endereço</string>
  <string id="Address:">Endereço:</string>
  <string id="Admin password:">Senha do administrador:</string>
  <string id="All">Todos</string>
  <string id="All cSF Apps">Todos os aplicativos cSF</string>
  <string id="All Device Groups">Todos os grupos de dispositivo</string>
  <string id="All scheduled tasks for the system.">Todas as tarefas programadas para o sistema.</string>
  <string id="All scheduled tasks for this device group:">Todas as tarefas programadas para o grupo de dispositivo:</string>
  <string id="All scheduled tasks for this sftClient group">Todas as tarefas programadas para este grupo do sftClient</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">Todos os dispositivos selecionados serão completamente removidos do sistema. Tem certeza de que deseja remover esses dispositivos?</string>
  <string id="All Servers Offline">Todos os servidores off-line</string>
  <string id="All Servers Online">Todos os servidores on-line</string>
  <string id="All Software Client Groups">Todos os grupos de cliente de software</string>
  <string id="All Solutions">Todas as soluções</string>
  <string id="All Tabs">Todas as guias</string>
  <string id="An error occurred while attempting to connect to this device,">Ocorreu um erro ao tentar conectar a esse dispositivo,</string>
  <string id="Anonymous">Anônimo</string>
  <string id="Any changes here will require">Todas as alterações aqui exigirão</string>
  <string id="Any Changes to the parameters are temporary and will">Todas as alterações nos parâmetros são temporárias e vão</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Todas as alterações nos parâmetros são temporárias e vão ser definidas de volta aos valores padrão da próxima vez.</string>
  <string id="AP (Advanced Prompting) Bundle Upload">Upload de conjunto AP (Solicitação avançada)</string>
  <string id="AP Bundle">Conjunto AP</string>
  <string id="AP Bundle Application File">Arquivo de aplicativo de conjunto AP</string>
  <string id="AP Bundle descriptor">Descritor de conjunto AP</string>
  <string id="AP Bundle Descriptor File">Arquivo de descritor de conjunto AP</string>
  <string id="App Reservation">Reserva de aplicativo</string>
  <string id="Application">Aplicativo</string>
  <string id="Apply">Aplicar</string>
  <string id="Are you sure you want to change the edited profile?">Tem certeza de que deseja mudar o perfil editado?</string>
  <string id="Are you sure you want to change these profiles?">Tem certeza de que deseja mudar estes perfis?</string>
  <string id="Are you sure you want to delete all the forms?">Tem certeza de que deseja excluir todos os formulários?</string>
  <string id="Are you sure you want to delete all the profiles?">Tem certeza de que deseja excluir todos os perfis?</string>
  <string id="Are you sure you want to delete all the solutions?">Tem certeza de que deseja excluir todas as soluções?</string>
  <string id="Are you sure you want to delete the selected forms?">Tem certeza de que deseja excluir os formulários selecionados?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">Tem certeza de que deseja excluir o grupo selecionado?  Qualquer privilégio associado a este grupo também será excluído automaticamente.</string>
  <string id="Are you sure you want to delete the selected profiles?">Tem certeza de que deseja excluir os perfis selecionados?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">Tem certeza de que deseja excluir o relatório selecionado?  Quaisquer tarefas de relatório programadas para este relatório também serão excluídas automaticamente.</string>
  <string id="Are you sure you want to delete the selected solutions?">Tem certeza de que deseja excluir as soluções selecionadas?</string>
  <string id="Are you sure you want to delete these profiles?">Tem certeza de que deseja excluir estes perfis?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">Tem certeza de que deseja desimplantar todos os aplicativos cSF?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">Tem certeza de que deseja desimplantar o(s) aplicativo(s) cSF selecionado(s)?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">Tem certeza de que deseja excluir este +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">Tem certeza de que deseja excluir este grupo de dispositivo?</string>
  <string id="Are you sure you would like to delete this forms printer?">Tem certeza de que deseja excluir esta impressora de formulários?</string>
  <string id="Are you sure you would like to delete this scheduled task?">Tem certeza de que deseja excluir esta tarefa programada?</string>
  <string id="Are you sure you would like to delete this software client Group?">Tem certeza de que deseja excluir este grupo de cliente de software?</string>
  <string id="Are you sure you would like to delete this solution?">Tem certeza de que deseja excluir esta solução?</string>
  <string id="Associated Device Group :">Grupo de dispositivo associado:</string>
  <string id="Associated Solution :">Solução associada:</string>
  <string id="Associated Solution:">Solução associada:</string>
  <string id="Authentication Method:">Método de autenticação:</string>
  <string id="Author">Autor</string>
  <string id="Auto Refresh:">Atualização automática:</string>
  <string id="Available Columns">Colunas disponíveis</string>
  <string id="Available Reports">Relatórios disponíveis</string>
  <string id="Back">Voltar</string>
  <string id="Background Image:">Imagem de plano de fundo:</string>
  <string id="Backup &amp; Restore information">Informações de restauração do backup</string>
  <string id="Backup amp; Restore">Backup amp; Restauração</string>
  <string id="Backup Jobs Logs Database">Backup de banco de dados de registros de trabalhos</string>
  <string id="Backup Share Path">Caminho de compartilhamento de backup</string>
  <string id="Bar Chart">Gráfico de barras</string>
  <string id="Binary Files">Arquivos binários</string>
  <string id="Bookmarks">Marcadores</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">Os arquivos cacert.pem e key.pem são necessários para atualizar os certificados de aplicativo cSF.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">Os arquivos descritores e eSF flash são necessários para atualizar o pacote AP.</string>
  <string id="Browse">Procurar</string>
  <string id="Browse...">Procurar...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">Por padrão, a multifuncional organiza automaticamente os botões na tela inicial.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">Por padrão, a SFP adiciona os perfis à pasta de trabalhos suspensos.</string>
  <string id="Cancel">Cancelar</string>
  <string id="Canceled">Cancelado</string>
  <string id="Canceling...">Cancelando...</string>
  <string id="Change Default Values">Alterar valores padrão</string>
  <string id="Change Language">Alterar idioma</string>
  <string id="Change Password">Alterar senha</string>
  <string id="Change Username">Alterar nome de usuário</string>
  <string id="Changing name...">Alterando nome...</string>
  <string id="Choose a cSF App to deploy:">Escolher um aplicativo cSF para implantar:</string>
  <string id="Choose a solution to deploy:">Escolha uma solução a ser implantada:</string>
  <string id="Choose a solution:">Escolha uma solução:</string>
  <string id="Choose Client Groups">Escolha grupos de cliente</string>
  <string id="Choose deployment settings for">Escolher configurações de implantação para</string>
  <string id="Choose Device Groups">Escolher grupos de dispositivos</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">Escolha cada botão e defina a sua ação. Botões sem nenhuma ação não serão exibidos na tela inicial.</string>
  <string id="Choose one...">Escolha um...</string>
  <string id="Choose task">Escolher tarefa</string>
  <string id="Choose the frequency">Escolha a freqüência</string>
  <string id="Choose the group type">Escolher o tipo de grupo</string>
  <string id="Class">Classe</string>
  <string id="Click">Clique em</string>
  <string id="Click Add to create a Home screen button.">Clique em Adicionar para criar um botão de tela inicial.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Clique nas caixas de seleção para marcar ou desmarcar privilégios.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Clique no quadrado, depois solte o botão do mouse para selecionar uma nova cor.</string>
  <string id="Client Groups:">Grupos de cliente:</string>
  <string id="Client Profile created.">Perfil de cliente criado.</string>
  <string id="Client Profiles">Perfis de cliente</string>
  <string id="Close">Fechar</string>
  <string id="Color :">Colorida:</string>
  <string id="Column Chart.">Gráfico de colunas.</string>
  <string id="Compile">Compilar</string>
  <string id="Compile Options:">Compilar opções:</string>
  <string id="Completed">Concluído</string>
  <string id="Components">Componentes</string>
  <string id="Config Service">Config serviço</string>
  <string id="Configuration">Configuração</string>
  <string id="Configuration:">Configuração:</string>
  <string id="Configurations for this discovery:">Configurações para essa descoberta:</string>
  <string id="Connect To App">Conectar ao aplicativo</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Conectado à VM de destino, endereço: 127.0.0.1:61023, transporte: socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">Tempo limite de conexão. Verifique a configuração do servidor, incluindo definições de firewall.</string>
  <string id="Contact Location">Localização do contato</string>
  <string id="Contact Location:">Localização do contato:</string>
  <string id="Contact Name">Nome do contato</string>
  <string id="Contact Name:">Nome do contato:</string>
  <string id="Content :">Conteúdo:</string>
  <string id="Copy">Copiar</string>
  <string id="Copy + Profile">Copiar + Perfil</string>
  <string id="Copy Shortcuts">Copiar atalhos</string>
  <string id="CPU Usage">Uso de CPU</string>
  <string id="Creating client profile...">Criando perfil de cliente...</string>
  <string id="Creating device group...">Criando grupo de dispositivo...</string>
  <string id="Creating discovery profile...">Criando perfil de localização...</string>
  <string id="Creating or updating a forms printer...">Criando ou atualizando uma impressora de formulários...</string>
  <string id="Creating software client group...">Criando grupo de cliente de software...</string>
  <string id="Creatingupdating the scheduled task...">Criando/atualizando a tarefa programada...</string>
  <string id="Cron expression)">(Expressão Cron)</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">Colunas atuais</string>
  <string id="Current password is incorrect.">A senha atual está incorreta.</string>
  <string id="Current Password:">Senha atual:</string>
  <string id="Currently discovering Missing Devices...">Descobrindo no momento dispositivos não encontrados...</string>
  <string id="Currently discovering Unlicensed Devices...">Descobrindo no momento dispositivos sem licença...</string>
  <string id="Custom">Personalizado</string>
  <string id="Custom icons:">Ícones personalizados:</string>
  <string id="Custom...">Personalizado...</string>
  <string id="Customize Jobs Table">Personalizar tabela de trabalhos</string>
  <string id="Customize Logs Table">Personalizar tabela de registros</string>
  <string id="Customize Table...">Personalizar tabela...</string>
  <string id="Danger, Will Robinson!">Perigo!</string>
  <string id="Darkness :">Tonalidade:</string>
  <string id="Database Driver:">Driver do banco de dados:</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>Nome do host OU Endereço IP totalmente qualificado para banco de dados</string>
  <string id="Database URL:">URL do banco de dados:</string>
  <string id="Datasource:">DataSource:</string>
  <string id="Datatype Filter">Filtro de tipo de dados</string>
  <string id="Datatype filter:">Filtro de tipo de dados:</string>
  <string id="Date">Dados</string>
  <string id="Debug">Depurar</string>
  <string id="Default">Padrão</string>
  <string id="Default Group">Grupo padrão</string>
  <string id="Default Group can not be deleted.">O grupo padrão não pode ser excluído.</string>
  <string id="Default Output Format:">Formato de saída padrão:</string>
  <string id="Default: 389">Padrão: 389</string>
  <string id="Delete">Excluir</string>
  <string id="Delete file on failure?">Excluir arquivo em caso de falha?</string>
  <string id="Delete file on success?">Excluir arquivo em caso de êxito?</string>
  <string id="Deleted device group. One or more devices must now be updated.">Grupo de dispositivo excluído. Um ou mais dispositivos devem ser atualizados agora.</string>
  <string id="Deleted selected FormSet(s).">O(s) FormSet(s) selecionado(s) foi(foram) excluído(s).</string>
  <string id="Deleted software client group.">Grupo de cliente de software excluído.</string>
  <string id="Deleting All FormSet(s)...">Excluindo todo(s) o(s) FormSet(s)...</string>
  <string id="Deleting All solution(s)...">Excluindo toda(s) a(s) solução(ões)...</string>
  <string id="Deleting client profile(s)...">Excluindo perfil(s) de cliente...</string>
  <string id="Deleting device group...">Excluindo grupo de dispositivo...</string>
  <string id="Deleting discovery profile(s)...">Excluindo perfil(s) de localização...</string>
  <string id="Deleting forms printer...">Excluindo impressora de formulários...</string>
  <string id="Deleting Formset(s)...">Excluindo formset(s)...</string>
  <string id="Deleting scheduled task...">Excluindo tarefa programada...</string>
  <string id="Deleting selected FormSet(s)...">Excluindo FormSet(s) selecionado(s)...</string>
  <string id="Deleting software client group...">Excluindo grupo de cliente de software...</string>
  <string id="Deleting solution(s)...">Excluindo solução(ões)...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Implantar para:</string>
  <string id="Deploy:">Implantar:</string>
  <string id="Deploying home screen to">Implantando a tela inicial para</string>
  <string id="Deploying solution to device group...">Implantando solução em grupo de dispositivos...</string>
  <string id="Deploying WAR file:">Implantando arquivo WAR: </string>
  <string id="Description">Descrição</string>
  <string id="Description:">Descrição:</string>
  <string id="Descriptor">Descritor</string>
  <string id="Destination Folder Path">Caminho da pasta de destino</string>
  <string id="Developer Forums">Fóruns do desenvolvedor</string>
  <string id="Developer Network">Rede do desenvolvedor</string>
  <string id="Device Address">Endereço do dispositivo</string>
  <string id="Device Address:">Endereço do dispositivo:</string>
  <string id="Device Class">Classe do dispositivo</string>
  <string id="Device Group">Grupo de dispositivo</string>
  <string id="Device Group created">Grupo de dispositivo criado</string>
  <string id="Device Group was successfully removed from the system.">Grupo de dispositivo foi removido com êxito do sistema.</string>
  <string id="Device Group:">Grupo de dispositivo:</string>
  <string id="Device Groups">Grupos de dispositivo</string>
  <string id="Device Groups:">Grupos de dispositivo:</string>
  <string id="Device Information Directions">Rota de informações de dispositivo</string>
  <string id="Device Model">Modelo do dispositivo</string>
  <string id="Device Model:">Modelo do dispositivo:</string>
  <string id="Device Profiles">Perfis do dispositivo</string>
  <string id="Device Summary">Resumo de dispositivo</string>
  <string id="Device update complete.">Atualização do dispositivo concluída.</string>
  <string id="Device update started...">Atualização do dispositivo iniciada...</string>    
  <string id="DeviceGroup">Grupo de dispositivo</string>
  <string id="Devices">Dispositivos</string>
  <string id="Directory">Diretório</string>
  <string id="Directory Path">Caminho do diretório</string>
  <string id="Directory path*">Caminho do diretório*</string>
  <string id="Directory Watcher">Inspetor do diretório</string>
  <string id='Directory Watcher information'>Informações do inspetor do diretório</string>
  <string id="Disabled">Desativado</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Desconectado da VM de destino, endereço: 127.0.0.1:60902, transporte: socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Desconectado da VM de destino, endereço: 127.0.0.1:61015, transporte: socket</string>
  <string id="Discover">Descobrir</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Descubra dispositivos para grupos de dispositivos selecionados usando os próprios perfis de localização de cada grupo.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Descubra dispositivos para este grupo de dispositivos usando seus perfis de localização.</string>
  <string id="Discover Missing">Descobrir ausentes</string>
  <string id="Discover new devices only">Descobrir somente novos dispositivos</string>
  <string id="Discover Unlicensed">Descobrir sem licença</string>
  <string id="Discover...">Descobrir...</string>
  <string id="Discovered">Descoberto</string>
  <string id="Discovered Devices">Dispositivos descobertos</string>
  <string id="Discovered Devices:">Dispositivos descobertos:</string>
  <string id="Discovery">Descoberta</string>
  <string id="Discovery has Completed for...">Descoberta foi concluída para...</string>
  <string id="Discovery in Progress for...">Descoberta em andamento para...</string>
  <string id="Discovery Profile created.">Perfil de localização criado.</string>
  <string id="Discovery Profiles">Perfis de descoberta</string>
  <string id="Discovery Profiles:">Perfis de localização:</string>
  <string id="Display Text">Exibir texto</string>
  <string id="Display Text:">Exibir texto:</string>
  <string id="Documentation">Documentação</string>
  <string id="Done">Concluído</string>
  <string id="Done generating the jobs report for downloading.">Geração de relatórios de trabalhos para download concluída.</string>
  <string id="Done generating the logs report for downloading.">Geração de relatório de registros para download concluída.</string>
  <string id="Down icon">Ícone para baixo</string>
  <string id="Down icon:">Ícone para baixo:</string>
  <string id='Download Details'>Detalhes do download</string>
  <string id="Duplex :">Duplex:</string>
  <string id="Edit">Editar</string>
  <string id="Edit a solution">Editar uma solução</string>
  <string id="Edit a solution to deploy">Editar uma solução para implantar</string>
  <string id="Edit the information about the report :">Edite as informações sobre o relatório:</string>
  <string id="Edit the report settings">Editar as definições de relatório</string>
  <string id="Edit...">Editar...</string>
  <string id="EForms">Formulários eletrônicos</string>
  <string id="E-Forms">Formulários eletrônicos</string>
  <string id="EForms:">Formulários eletrônicos:</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">Os campos de data e hora de início devem ser preenchidos ou ambos devem ser deixados em branco.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">Os campos Data e hora até devem ser preenchidos ou ambos devem ser deixados em branco.</string>
  <string id="Email">E-mail</string>
  <string id="Email + Profile">E-mail + Perfil</string>
  <string id="Email Shortcuts">Atalhos de e-mail</string>
  <string id="Email the Report">Enviar relatório por e-mail</string>
  <string id="Email To">E-mail para</string>
  <string id="Enable Fax Forwarding.">Ativar o encaminhamento de fax.</string>
  <string id="Enable LDAP Authentication.">Ativar autenticação LDAP.</string>
  <string id="Enabled for Credentials">Ativado para credenciais</string>
  <string id="Enabled for Session">Ativado para sessão</string>
  <string id="End Time">Horário final</string>
  <string id="End Time:">Hora de término:</string>
  <string id="Enter a unique group name">Insira um nome de grupo exclusivo</string>
  <string id="Enter a unique name for this group">Insira um nome exclusivo para este grupo</string>
  <string id="Enter appropriate fields and click the Add button:">Preencha os campos apropriados e clique no botão Adicionar:</string>
  <string id="Enter appropriate fields and click the Save button:">Preencha os campos apropriados e clique no botão Salvar:</string>
  <string id="Enter the appropriate fields and click the Add button:">Preencha os campos apropriados e clique no botão Adicionar:</string>
  <string id="Enter the information about the new report :">Digite as informações sobre o novo relatório:</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Digite os valores de tempo limite em milissegundos, separados por um espaço entre cada nova tentativa.</string>
  <string id="Error">Erro</string>
  <string id="Error importing license.">Erro na importação da licença.</string>
  <string id="Error in changing name.">Erro na alteração de nome.</string>
  <string id="Error in creating device group...">Erro na criação de grupo de dispositivo...</string>
  <string id="Error in creating software client group...">Erro na criação de grupo de cliente de software...</string>
  <string id="Error in deleting device group.">Erro na exclusão de grupo de dispositivo.</string>
  <string id="Error in deleting software client group.">Erro na exclusão de grupo de cliente de software.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">Erro na exclusão do(s) FormSet(s). Verifique os registros para obter mais detalhes.</string>
  <string id="Error in generating the report.">Erro na geração do relatório.</string>
  <string id="Error in saving Ldap settings.">Erro para salvar configurações de Ldap.</string>
  <string id="Error in saving settings.">Erro para salvar configurações.</string>
  <string id="Error in updating password.">Erro na atualização de senha.</string>
  <string id="Error in updating security settings.">Erro na atualização de configuração de segurança.</string>
  <string id="Error in updating service settings.">Erro na atualização das configurações de serviço.</string>
  <string id="Error in updating solution settings.">Erro na atualização das configurações de solução.</string>
  <string id="Error while deploying home screen to">Erro na implantação da tela inicial para</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Avaliar em +app_url}</string>
  <string id="Evaluate in remote app">Avaliar em aplicativo remoto</string>
  <string id="Every">Cada</string>
  <string id="Expiration Date">Data de expiração</string>
  <string id="Expired Formset">Formset expirado</string>
  <string id="Expired!">Expirada!</string>
  <string id="Expires on:">Expira em:</string>
  <string id="Export Report">Exportar relatório</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">Falhou</string>
  <string id="FALSE">FALSO</string>
  <string id="Fax">Fax</string>
  <string id="Fax + Profile">Fax + Perfil</string>
  <string id="Fax Forward settings updated.">Configurações de encaminhamento de fax atualizadas.</string>
  <string id="Fax Forwarding">Encaminhamento de fax</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax">Atalho de destino de encaminhamento de fax: (E-mail, FTP, Fax </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Atalho de destino de encaminhamento de fax: (E-mail, FTP, Fax)</string>
  <string id="Fax Forwarding Destination:">Destino de encaminhamento de fax:</string>
  <string id="Fax Forwarding LDSS Script:">Script LDSS de encaminhamento de fax:</string>
  <string id="Fax Forwarding Receive Mode:">Modo de recebimento de encaminhamento de fax:</string>
  <string id="Fax Shortcuts">Atalhos de fax</string>
  <string id="Feature Id">ID de recurso</string>
  <string id="Filter">Filtro</string>
  <string id="Filters...">Filtros...</string>
  <string id="Finish">Concluir</string>
  <string id="Finished AP Bundle Descriptor File">Arquivo do descritor de conjunto AP concluído</string>
  <string id="Finished AP Bundle Flash File">Arquivo flash de conjunto AP concluído</string>
  <string id="Finished upload of key.pem File.">Upload do arquivo key.pem concluído.</string>
  <string id="First">Primeira</string>
  <string id="Form field must be a single word or valid email address.">O campo de formulário deve ser uma única palavra ou um endereço de e-mail válido.</string>
  <string id="Form Printers">Impressoras de formulário</string>
  <string id="Format :">Formato:</string>
  <string id="Forms">Formulários</string>
  <string id="Forms Printer is unlicensed">A impressora de formulário não tem licença</string>
  <string id="Forms printer successfully created or updated.">Impressora de formulários criada ou atualizada com sucesso.</string>
  <string id="Forms printer successfully deleted.">Impressora de formulários excluída com sucesso.</string>
  <string id="Formsets">Formsets</string>
  <string id="FormsetsSubforms">Formsets/subformulários</string>
  <string id="Forward Only">Apenas para a frente</string>
  <string id="Fourth">Quarto</string>
  <string id="FRAMEWORK">ESTRUTURA</string>
  <string id="Fri">Sex</string>
  <string id="From:">De:</string>
  <string id="Ftp">Ftp</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">Ftp + Perfil</string>
  <string id="Ftp Shortcuts">Atalhos de Ftp</string>
  <string id="Generating logs report for downloading...">Geração de relatório de registros para download...</string>
  <string id="Generating Report">Geração de relatório</string>
  <string id="Generating Report...">Geração de relatórios...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">A geração de relatórios durante o horário comercial regular pode afetar negativamente o desempenho do sistema. Recomenda-se gerar relatórios fora do horário normal.</string>
  <string id="Generating the jobs report for downloading...">Geração de relatório de trabalhos para download...</string>
  <string id="Graphic">Gráfico</string>
  <string id="Graphic:">Gráfico:</string>
  <string id="Group Description placeholder">Espaço reservado para descrição de grupo</string>
  <string id="Group Identifier:">Identificador de grupo:</string>
  <string id="Group Names from LDAP">Nomes dos grupos de LDAP</string>
  <string id="Group Names from LDAP:">Nomes dos grupos de LDAP:</string>
  <string id="Group search base must be set for adding group based">A base de pesquisa de grupo deve ser definida para adição de grupo com base </string>
  <string id="Group search base must be set in">A base da pesquisa de grupo deve ser definida na configuração LDAP para adicionar um grupo</string>
  <string id="Group Search Base:">Base de pesquisa de grupo:</string>
  <string id="Group Search Filter:">Filtro de pesquisa de grupo:</string>
  <string id="Group Search Identifier:">Identificador de pesquisa de grupo:</string>
  <string id="Groups">Grupos</string>
  <string id="Held Jobs">Trabalhos suspensos</string>
  <string id="Hide Settings">Ocultar definições</string>
  <string id="Home">Início</string>
  <string id="Home Screen">Tela Bem-vindo</string>
  <string id="Home screen deployed to">Tela inicial implantada para</string>
  <string id="Home Screens">Telas iniciais</string>
  <string id="Home Tab">Guia Início</string>
  <string id="Hostname">Nome do host</string>
  <string id="Hostname:">Nome do host:</string>
  <string id="Id">Id</string>
  <string id="IDR License Summary">Resumo de licença IDR</string>
  <string id="IDR License Summary:">Resumo de licença IDR:</string>
  <string id="Images">Imagens</string>
  <string id="Import">Importar</string>
  <string id="Import...">Importar...</string>
  <string id="Importing AP Bundle Descriptor File...">Importando arquivo do descritor de conjunto AP...</string>
  <string id="Importing AP Bundle Flash File...">Importando arquivo flash de conjunto AP...</string>
  <string id='Importing Binary String...'>Importando seqüência binária...</string>  
  <string id="Importing CaCert pem File...">Importando arquivo CaCert pem...</string>
  <string id="Importing license...">Importando licença...</string>
  <string id="Importing software client group profile...">Importando perfil de grupo de cliente de software...</string>
  <string id="Importing Solution(s)...">Importando solução(ões)...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Inserir - isso vai inserir o botão de corte e apertar os botões restantes</string>
  <string id="Install Time">Tempo de instalação</string>
  <string id="Install Time:">Tempo de instalação:</string>
  <string id="Install-Upgrade">Instalar/atualizar</string>
  <string id="It is recommended to run reports during off hours.">Recomenda-se gerar relatórios fora do horário normal.</string>
  <string id="Items">Itens</string>
  <string id="Jasper Report File Name:">Nome do arquivo do relatório Jasper:</string>
  <string id="Job State">Estado do trabalho</string>
  <string id="Job State:">Estado do trabalho:</string>
  <string id="Jobs">Trabalhos</string>
  <string id="Jobs by user">Trabalhos por usuário</string>
  <string id="Jobs Filters Table">Tabela de filtros de trabalhos</string>
  <string id="Jobs Report">Relatórios de trabalho</string>
  <string id="Jobs Report - CSV">Relatórios de trabalho - CSV</string>
  <string id="Keep previous backups">Manter backups anteriores</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>Idioma:</string>
  <string id="Last">Duração</string>
  <string id="Last 12 Hours">Últimas 12 horas</string>
  <string id="Last 15 Minutes">Últimos 15 minutos</string>
  <string id="Last 24 Hours">Últimas 24 horas</string>
  <string id="Last 3 Hours">Últimas 3 horas</string>
  <string id="Last 30 Days">Últimos 30 dias</string>
  <string id="Last 30 Minutes">Últimos 30 minutos</string>
  <string id="Last 6 Hours">Últimas 6 horas</string>
  <string id="Last 7 Days">Últimos 7 dias</string>
  <string id="Last Discovered">Descoberto pela última vez</string>
  <string id="Last Discovered:">Descoberto pela última vez:</string>
  <string id="Last Hour">Última hora</string>
  <string id="Last Kranked">Última vez que foi feito Krank</string>
  <string id="Last Modified">Última modificação</string>
  <string id="Layout">Layout</string>
  <string id="Layout:">Layout:</string>
  <string id="LDAP Server Settings:">Definições do servidor LDAP:</string>
  <string id="Ldap Settings Saved.">Definições Ldap salvas.</string>
  <string id="LDAP Setup">Configuração do LDAP</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Gerenciamento de impressão da Lexmark</string>
  <string id="License">Licença</string>
  <string id="LICENSE">LICENÇA</string>
  <string id="License Files">Arquivos de licença</string>
  <string id="License Type">Tipo de licença</string>
  <string id="License Upload Results.">Resultados de upload de licença.</string>
  <string id="License Upload Results:">Resultados de upload de licença:</string>
  <string id="Licensed">Licenciado</string>
  <string id="Licenses">Licenças</string>
  <string id="Licenses in Use">Licenças em uso</string>
  <string id="Limit batch size">Limitar o tamanho do lote</string>
  <string id="Line Chart with Time Period Slider.">Gráfico de linha com controle deslizante de período de tempo.</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>Nome do host OU Endereço IP totalmente qualificado para balanceador de carga</string>
  <string id="LOADING">CARREGANDO</string>
  <string id="Loading...">Carregando...</string>
  <string id="LOADING...">CARREGANDO...</string>
  <string id="Lock Device">Bloquear dispositivo</string>
  <string id="Log">Registrar</string>
  <string id="Log Report - CSV">Relatório de registro - CSV</string>
  <string id="Log Report - Failed Jobs">Relatório de registro - Trabalhos suspensos</string>
  <string id="Log State">Registrar estado</string>
  <string id="Log State:">Estado do registro:</string>
  <string id="Logging In">Login</string>
  <string id="Login">Login</string>
  <string id="Logout">Sair</string>
  <string id="Logs Filters Table">Tabela de filtros de registros</string>
  <string id='Max:'>Máx:</string>
  <string id="Member of Group(s):">Membro de grupos:</string>
  <string id="Memory Usage">Utilização da memória</string>
  <string id="Message">Mensagem</string>
  <string id="Message:">Mensagem:</string>
  <string id="Messages">Mensagens</string>
  <string id='Min:'>Mín:</string>
  <string id='Minimum length:'>Extensão mínima:</string>
  <string id='Minimum:'>Mínimo:</string>  
  <string id="Missing">Ausente</string>
  <string id="Missing Device">Dispositivo ausente</string>
  <string id="Missing Devices">Dispositivos ausentes</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Dispositivos ausentes são dispositivos que já foram descobertos, mas que, durante a descoberta mais recente, não foram encontrados (por exemplo, pelo fato de o dispositivo estar fora da rede).</string>
  <string id="Missing devices:">Dispositivos ausentes:</string>
  <string id="Missing Devices:">Dispositivos ausentes:</string>
  <string id="Model">Modelo</string>
  <string id="Model:">Modelo:</string>
  <string id="Mon">Seg</string>
  <string id="MONITOR">MONITOR</string>
  <string id="Move Down">Mover para baixo</string>
  <string id="Move Up">Mover para cima</string>
  <string id="Name">Nome</string>
  <string id="Name :">Nome:</string>
  <string id="Name changed.">Nome alterado.</string>
  <string id="Name:">Nome:</string>
  <string id="Network Load">Carga de Rede</string>
  <string id="Network share password">Senha de compartilhamento de rede</string>
  <string id="Network share user name">Nome de usuário do compartilhamento de rede</string>
  <string id="New Password:">Nova senha:</string>
  <string id="New Username:">Novo nome de usuário:</string>
  <string id="Next">Avançar</string>
  <string id="No">Não</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>Não existem aplicativos de cSF para este grupo de dispositivos. Você precisa ter pelo menos um aplicativo de cSF antes de associar esta ação ao botão.</string>
  <string id="No devices are currently Out of Policy for the system.">Não há dispositivos atualmente fora da política para o sistema.</string>
  <string id="No devices are currently Out of Policy for this device group.">Não há dispositivos atualmente fora da política para este grupo de dispositivos.</string>
  <string id="No home screen is configured for this device type.">Nenhuma tela inicial configurada para este tipo de dispositivo.</string>
  <string id="No matches found">Nenhum resultado encontrado</string>
  <string id='No Privilege'>Sem privilégios</string>
  <string id="No Privilege Alert">Sem alerta de privilégio</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">Não existem perfis para este grupo de dispositivo porque não foram associadas soluções com perfis.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">Não existem perfis para este grupo de dispositivo. Você precisa ter pelo menos um perfil antes de associar esta ação ao botão.</string>
  <string id="No records match the selected filter criteria.">Nenhum registro corresponde ao critério de filtro selecionado.</string>
  <string id="No records matched the filter criteria.">Nenhum registro corresponde ao critério de filtro.</string>
  <string id="No schedulable scripts are available.">Não há scripts programáveis disponíveis.</string>
  <string id="No UCF File selected">Nenhum Arquivo de configuração de segurança selecionado</string>
  <string id="None">Nenhum</string>
  <string id="None of the selected devices are missing.">Nenhum dos dispositivos selecionados está ausente.</string>
  <string id="None of the selected devices are unlicensed.">Nenhum dos dispositivos selecionados está sem licença.</string>
  <string id="Number of Jobs per Page">Número de trabalhos por página</string>
  <string id="Number of Licenses">Número de licenças</string>
  <string id="Number of Logs per Page">Número de registros por página</string>
  <string id="Off">Desligado</string>
  <string id="OK">Ok</string>
  <string id="Once">Uma vez</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">Um ou mais botões na configuração atual não são válidos. &lt;font color="#ff0000"&gt;(mostrado em vermelho)&lt;/font&gt; Verifique se todos os botões são válidos.</string>
  <string id="One or more tests did not pass.">Um ou mais testes foram reprovados.</string>
  <string id="Only">Apenas</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">Apenas uma descoberta pode ocorrer ao mesmo tempo. É possível iniciar uma nova descoberta após o término da atual.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">Apenas uma atualização de política pode ocorrer ao mesmo tempo.  É possível iniciar uma nova atualização de política após o término da atual.</string>
  <string id="Only update those devices which are Out of Policy">Só atualize os dispositivos que estão fora da política</string>
  <string id="Orientation :">Orientação:</string>
  <string id="Out of Policy">Fora da política</string>
  <string id="Out of Policy Device">Dispositivo fora da política</string>
  <string id="Out of Policy Devices">Dispositivos fora da política</string>
  <string id="Out of Policy Devices:">Dispositivos fora da política:</string>
  <string id="Output Format">Formato de saída</string>
  <string id="Overwrite if file already exists">Substituir se arquivo já existir</string>
  <string id="Page 1">Página 1</string>
  <string id="Page 2">Página 2</string>
  <string id="Page 3">Página 3</string>
  <string id="Page 4">Página 4</string>
  <string id="Paper Size :">Tamanho do papel:</string>
  <string id="Parameters">Parâmetros</string>
  <string id="Password Changed Successfully.">Senha alterada com sucesso.</string>
  <string id="Password updated.">Senha atualizada.</string>
  <string id="Password*">Senha*</string>
  <string id="Password:">Senha:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Realize uma atualização de política para os grupos de dispositivos selecionados utilizando a política de cada grupo.</string>
  <string id="Perform a Policy Update for selected devices.">Realize uma atualização de política para os dispositivos selecionados.</string>
  <string id="Perform a Policy Update for this device group.">Realize uma atualização de política este grupo de dispositivos.</string>
  <string id="Placeholder">Espaço reservado</string>
  <string id="Please choose a filter:">Escolha um filtro:</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Escolha um tipo de grupo para conseguir acessar as configurações de solução local de uma solução no script programado:</string>
  <string id="Please choose a script:">Escolha um script:</string>
  <string id="Please choose a task to schedule :">Escolha uma tarefa a ser programada:</string>
  <string id="Please choose an action:">Escolha uma ação:</string>
  <string id="Please choose client groups to schedule :">Escolha grupos de clientes a serem programados:</string>
  <string id="Please choose device groups to schedule :">Escolha grupos de dispositivos a serem programados:</string>
  <string id="Please choose one of the following options:">Escolha uma das opções a seguir:</string>
  <string id="Please choose solution and script :">Escolha a solução e o script:</string>
  <string id="Please choose solution and script to schedule :">Escolha a solução e o script a serem programados:</string>
  <string id="Please choose start time and frequency :">Escolha a hora de início e a freqüência:</string>
  <string id="Please choose the datasource for the new report.">Escolha a origem de dados para o novo relatório.</string>
  <string id="Please choose the jasper filename for the new report.">Escolha o nome de arquivo jasper para o novo relatório.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">Escolha o nome de arquivo jasper para o novo relatório.  Fazer upload do relatório jasper se ele ainda não estiver na lista.</string>
  <string id="Please choose the output format for the new report.">Escolha o formato de saída para o novo relatório.</string>
  <string id="Please choose the report to schedule :">Escolha um relatório a ser programado:</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Entre em contato com a Lexmark para obter informações sobre a licença do cliente de software.</string>
  <string id="Please enter a non-expired date">Informe uma data não expirada (dd/mm/aaaa).</string>
  <string id="Please enter a valid Address.">Informe um endereço válido.</string>
  <string id="Please enter a valid date">Informe uma data válida (dd/mm/aaaa).</string>
  <string id="Please enter a valid End From Time">Informe uma hora (HH:MM) de término De válida.</string>
  <string id="Please enter a valid End To Time">Informe uma hora (HH:MM) de término Até válida.</string>
  <string id="Please enter a valid From date">Informe uma data De válida (dd/mm/aaaa).</string>
  <string id="Please enter a valid From time">Informe uma hora (hh:mm) De válida.</string>
  <string id='Please enter a valid range:'>Informe um intervalo válido:</string>
  <string id="Please enter a valid range: 1 - 12">Informe um intervalo válido. 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">Informe um intervalo válido. 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">Informe um intervalo válido. 1 - 59</string>
  <string id="Please enter a valid Start From Time">Informe uma hora (HH:MM) de início De válida.</string>
  <string id="Please enter a valid Start To Time">Informe uma hora (HH:MM) de início até válida.</string>
  <string id="Please enter a valid time">Informe uma hora (HH:MM) válida.</string>
  <string id="Please enter a valid To date">Informe uma data Até válida (dd/mm/aaaa).</string>
  <string id="Please enter a valid To time">Informe uma hora Até (hh:mm) válida.</string>
  <string id="Please enter the Database driver and URL for the external database.">Informe o driver e o URL de banco de dados para o banco de dados externo.</string>
  <string id="Please enter the Directory information:">Insira as informações de diretório:</string>
  <string id="Please enter the location where you want the report to be saved.">Informe o local onde deseja que o relatório seja salvo.</string>
  <string id="Please enter the name of the new report.">Insira o nome do novo relatório.</string>
  <string id="Please enter the network share user name and password.">Informe o nome de usuário e a senha de compartilhamento de rede.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">Informe os destinatários para quem você deseja enviar os relatórios por e-mail.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">Digite as informações solicitadas para backup e restauração:</string>
  <string id="Please make sure that all the necessary fields are filled in.">Verifique se todos os campos necessários foram preenchidos.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Verifique se sua expressão cron tem 6 ou 7 opções separadas por espaços.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Verifique se sua expressão cron tem um "?" na 4a. ou 6a. posição, mas não em ambas.</string>
  <string id="Please select a file to upload.">Selecione um arquivo para upload.</string>
  <string id="Please select a group on the left to modify its task privileges.">Selecione um grupo à esquerda para modificar os privilégios de tarefa.</string>
  <string id="Please select a group to save privileges for.">Selecione um grupo para quem deseja salvar privilégios.</string>
  <string id="Please select a profile to view its settings.">Selecione um perfil para visualizar suas configurações.</string>
  <string id="Please select the Group to delete.">Selecione o grupo que deseja excluir.</string>
  <string id="Please select the report to delete.">Selecione o relatório que deseja excluir.</string>
  <string id="Please select the report to edit.">Selecione o relatório que deseja editar.</string>
  <string id="Please select the report to run.">Selecione o relatório que deseja executar.</string>
  <string id="Please specify a port:">Especifique uma porta:</string>
  <string id="Please Verify MinMax, Length and Required Settings.">Verifique definições min/max, comprimento e obrigatórias.</string>
  <string id="Policy Last Applied">Última política aplicada</string>
  <string id="Policy Update">Atualização de política</string>
  <string id="Policy Update has Completed for...">A atualização de política foi concluída para...</string>
  <string id="Policy Update in Progress for...">Atualização de política em andamento para...</string>
  <string id="Policy Update on all effected Device Groups.">Atualização de política em todos os grupos de dispositivos afetados.</string>
  <string id="Port">Porta</string>
  <string id="Port:">Porta:</string>
  <string id="Present">Presente</string>
  <string id="Previous">Anterior</string>
  <string id="Print (Default)">Impressora (padrão)</string>
  <string id="Print and Forward">Imprimir e encaminhar</string>
  <string id="Printer Panel">Painel da impressora</string>
  <string id="Printer Report">Relatório da impressora</string>
  <string id="Privileges">Privilégios</string>
  <string id="Process finished with exit code 0">Processo concluído com código de saída 0</string>
  <string id="Profile Filters">Filtros de perfil</string>
  <string id="Profile:">Perfil:</string>
  <string id="Profiles">Perfis</string>
  <string id="Profiles :">Perfis:</string>
  <string id="Profiles:">Perfis:</string>
  <string id="Progress %">Progresso %</string>
  <string id="Property Tag">Etiqueta de propriedade</string>
  <string id="Property Tag:">Etiqueta de propriedade:</string>
  <string id="Quality :">Qualidade:</string>
  <string id="QUARTZ">QUARTZO</string>
  <string id="Recurrence">Recorrência</string>
  <string id="Refresh">Atualizar</string>
  <string id="Refresh Defaults">Atualizar padrões</string>
  <string id="Regular Expression">Expressão regular</string>
  <string id="Release Held Faxes">Liberar fax retidos</string>
  <string id="Remove">Remover</string>
  <string id="Remove All">Remover Tudo</string>
  <string id="Remove from System">Remover do sistema</string>
  <string id="Remove Server(s)">Remover servidor(es)</string>
  <string id="RemoveAll">Remover Tudo</string>
  <string id="Removing selected servers...">Removendo servidores selecionados...</string>
  <string id="Repeat this event :">Repetir este evento:</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Substituir - Isso vai excluir o botão selecionado e substituí-lo pelo botão de corte.</string>
  <string id="Replace Me">Substituir-me</string>
  <string id="Report">Relatório</string>
  <string id="Report by Time">Relatório por hora</string>
  <string id="Report Files">Arquivos de relatório</string>
  <string id="Report From">Relatório de</string>
  <string id="Report Name:">Nome do relatório:</string>
  <string id="Report Parameters:">Parâmetros de relatório:</string>
  <string id="Report To">Relatório para</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME gerado com sucesso</string>
  <string id="Reporting Period">Período de relatório</string>
  <string id="Reports">Relatórios</string>
  <string id="Reports:">Relatórios:</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">Tempo limite da solicitação. Restrinja seus critérios de pesquisa e tente novamente.</string>
  <string id="Required field">Campo obrigatório</string>
  <string id="Reset">Redefinir</string>
  <string id="Reset Filter">Redefinir filtro</string>
  <string id="Reset to Default">Redefinir para o padrão</string>
  <string id="Resolution :">Resolução:</string>
  <string id="Return to Original">Retornar ao original</string>
  <string id="Retype New Password:">Digite novamente uma nova senha:</string>
  <string id="Retype New Username:">Digite novamente um novo nome de usuário:</string>
  <string id="Run on All Servers">Executar em todos os servidores</string>
  <string id="Run Report">Executar relatório</string>
  <string id="Running">Executando</string>
  <string id="Running Tasks">Tarefas em execução</string>
  <string id="Running...">Executando...</string>
  <string id="Sat">Sáb</string>
  <string id="Save">Salvar</string>
  <string id="Save Privileges">Salvar privilégios</string>
  <string id="Save Settings">Salvar definições</string>
  <string id="Save To">Salvar em</string>
  <string id="Saving eSF Settings...">Salvando definições eSF...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">Salvando definições LDAP...</string>
  <string id="Schedule">Programar</string>
  <string id="Scheduled task createdupdated">Tarefa programada criada/atualizada</string>
  <string id="Scheduled task deleted">Tarefa programada excluída</string>
  <string id="Scheduled tasks for all client groups:">Tarefas programadas para todos os grupos de cliente:</string>
  <string id="Scheduled tasks for all device groups:">Tarefas programadas para todos os grupos de dispositivo:</string>
  <string id="Script">Script</string>
  <string id="Script:">Script:</string>
  <string id="Search">Pesquisar</string>
  <string id="Search Base:">Base de pesquisa:</string>
  <string id="Search Held Jobs">Pesquisar trabalhos suspensos</string>
  <string id="Search LDAP for Groups:">Pesquisar LDAP para grupos:</string>
  <string id="Searching...">Pesquisando...</string>
  <string id="Second">Segundo</string>
  <string id="Secure Server Communication">Comunicação de servidor seguro</string>
  <string id="Secure Server Communication:">Comunicação de servidor seguro:</string>
  <string id="Security">Segurança</string>
  <string id="Security setting updated.">Configuração de segurança atualizada.</string>
  <string id="Security setup file updated successfully">Arquivo de configuração de segurança atualizado com sucesso</string>
  <string id="Security setup file update failed">Falha na atualização do arquivo de configuração de segurança</string>  
  <string id="Select a Group Name:">Selecione um nome de grupo:</string>
  <string id="Select a report">Selecionar um relatório</string>
  <string id="Select a script task">Selecione uma tarefa de script</string>
  <string id="Select one...">Selecione um...</string>
  <string id="Select Profile...">Selecione perfil...</string>
  <string id="Select the group to copy">Selecione o grupo para copiar</string>
  <string id="Sent when any leaf is checked or unchecked, in">Enviado quando alguma folha é marcada ou desmarcada, além dos dois eventos abaixo.</string>
  <string id="Serial Number">Número de série</string>
  <string id="Serial Number:">Número de série:</string>
  <string id="Server Address">Endereço do servidor</string>
  <string id="Server Address:">Endereço do servidor:</string>
  <string id="Server handling this LMC session">Servidor manipulando esta sessão LMC</string>
  <string id="Server is currently offline">O servidor está off-line no momento</string>
  <string id="Server is not communicating">O servidor não está se comunicando</string>
  <string id="Server is unlicensed">O servidor não está licenciado</string>
  <string id="Server Port:">Porta do servidor:</string>
  <string id="Server Report">Relatório do servidor</string>
  <string id="Server(s) Error">Erro do(s) servidor(es)</string>
  <string id="Server(s) Offline">Servidor(es) off-line</string>
  <string id="Servers">Servidores</string>
  <string id="Service settings updated">Configurações de segurança atualizadas</string>
  <string id="Services">Serviços</string>
  <string id="Set Offline">Definir off-line</string>
  <string id="Set Online">Definir on-line</string>
  <string id="Setting selected servers offline...">Configurando servidores selecionados off-line...</string>
  <string id="Setting selected servers online...">Configurando servidores selecionados on-line...</string>
  <string id="Settings :">Definições:</string>
  <string id="Settings:">Definições:</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task home screen updated.">Tela inicial SFP e-Task atualizada.</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated.">Tela inicial SFP e-Task2 atualizada.</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated.">Tela inicial SFP e-Task2+ atualizada.</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated.">Tela inicial SFP e-Task3 atualizada.</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4 (7 pol.)</string>
  <string id="SFP e-Task4 (7in.) home screen updated.">Tela inicial SFP e-Task4 (7 pol.) atualizada.</string>
  <string id="SFP e-Task4 home screen updated.">Tela inicial SFP e-Task4 atualizada.</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">Atalho</string>
  <string id="Shortcut :">Atalho:</string>
  <string id="Shortcut:">Atalho:</string>
  <string id="Show Settings">Exibir configurações</string>
  <string id="Since Last Month">Desde o mês passado</string>
  <string id="Since Yesterday">Desde ontem</string>
  <string id="Single Profile">Perfil simples</string>
  <string id="SNMP Timeout Retries:">Tentativas de tempo limite SNMP:</string>
  <string id="Software Client Group">Grupo de cliente de software</string>
  <string id="Software Client Group created">Grupo de cliente de software criado</string>
  <string id="Software Client Group:">Grupo de cliente de software:</string>
  <string id="Software Client Groups">Grupos de cliente de software</string>
  <string id="Software Client Report">Relatório de cliente de software</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">Solução</string>
  <string id="Solution deleted from software client group.">Solução excluída do grupo de cliente de software.</string>
  <string id="Solution deployed to device group">Solução implantada em grupo de dispositivos</string>
  <string id="Solution deployed to software client group">Solução implantada em grupo de cliente de software</string>
  <string id="Solution Name">Nome da solução</string>
  <string id="Solution Name:">Nome da solução:</string>
  <string id="Solution Report">Relatório de soluções</string>
  <string id="Solution settings updated.">Configurações de solução atualizadas.</string>
  <string id="Solution: Deleting device group deployment...">Solução: Excluindo implantação de grupo de dispositivo...</string>
  <string id="Solution: Deleting solution from software client group...">Solução: Excluindo solução do grupo de cliente de software...</string>
  <string id="Solution: device group deployment deleted.">Solução: implantação de grupo de dispositivo excluída.</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">Soluções</string>
  <string id="Solutions to deploy:">Soluções para implantar:</string>
  <string id="Solutions:">Soluções:</string>
  <string id='Specify Restore system information'>Especifique a restauração de informações do sistema</string>
  <string id="Specify where the generated report should be saved">Especifique onde o relatório gerado deve ser salvo</string>
  <string id="Start Button Default Action">Iniciar ação padrão do botão</string>
  <string id="Start Date :">Data de início:</string>
  <string id="Start Time">Hora de início</string>
  <string id="Start Time:">Hora inicial:</string>
  <string id="State">Estado</string>
  <string id="Status">Status</string>
  <string id="Steps for viewing device information:">Etapas para ver as informações do dispositivo:</string>
  <string id="Stop">Parar</string>
  <string id="Stop Task">Parar tarefa</string>
  <string id="Subform">Subformulário</string>
  <string id="Subject:">Assunto:</string>
  <string id="Success">Sucesso</string>
  <string id="Successfully added the group.">Grupo adicionado com sucesso.</string>
  <string id="Successfully Deleted All Solution(s) from the System.">Toda(s) a(s) solução(ções) foi(foram) excluída(s) com sucesso.</string>
  <string id="Successfully Deleted Solution(s) from the System.">Solução(ões) excluída(s) com sucesso do sistema.</string>
  <string id="Successfully Imported Solution(s) into the System.">Solução(ões) importada(s) para o sistema com sucesso.</string>
  <string id="Summary">Resumo</string>
  <string id="Sun">Dom</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Mudar - Isso vai mudar as posições entre os botões selecionados e o de corte.</string>
  <string id="System">Sistema</string>
  <string id="System Health...">Integridade do sistema...</string>
  <string id="System Status">Status do sistema</string>
  <string id="System Status 1">Status do sistema 1</string>
  <string id="Task Id">ID da tarefa</string>
  <string id="Task Id:">Id da tarefa:</string>
  <string id="Task Name">Nome da tarefa</string>
  <string id="Task Name:">Nome da tarefa:</string>
  <string id="Task Summary Report">Relatório de resumo de tarefa</string>
  <string id="Test Progress">Progresso do teste</string>
  <string id="Test Results">Resultados do teste</string>
  <string id="Test Settings">Definições do teste</string>
  <string id="Testing LDAP Settings...">Testando definições LDAP...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">Os botões na primeira tela podem ser organizados de maneira personalizada.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">O relatório a seguir foi gerado com sucesso:  REPORT_NAME.  Veja o relatório em anexo.</string>
  <string id="The password provided is incorrect.">A senha fornecida está incorreta.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">A política deste grupo está agora deixando de ser implantada em todos os dispositivos do grupo.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">O relatório já está pronto para download. Clique em OK para continuar.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">A data Até para o período de relatório é anterior à data De.  O sistema irá alterná-los automaticamente para você na geração do relatório.  Deseja continuar?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">Não existem perfis de cliente para este grupo de cliente de software atualmente. Adicione-os ao preencher os campos acima.</string>
  <string id="There are currently no cSF Apps associated with this device group.">Não existem aplicativos cSF associados a este grupo de dispositivo atualmente.</string>
  <string id="There are currently no cSF Apps to add to this device group.">Não existem aplicativos cSF para adicionar a este grupo de dispositivo atualmente.</string>
  <string id="There are currently no device groups to perform discovery.">Não existem grupos de dispositivo para realizar a localização atualmente.</string>
  <string id='There are currently no device groups to perform policy update.'>Não existem grupos de dispositivos para realizar a atualização da política atualmente.</string>
  <string id="There are currently no device groups to schedule.">Não existem grupos de dispositivo para programar atualmente.</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>Não há atualmente grupos de dispositivos.  Adicione um grupo de dispositivos clicando no botão Adicionar no lado esquerdo.</string>
  <string id="There are currently no devices discovered for this device group.">Não existem dispositivos localizados para este grupo de dispositivo atualmente.</string>
  <string id="There are currently no devices in this device group.">Não há dispositivos atualmente neste grupo de dispositivos.</string>
  <string id="There are currently no discovered devices.">Não há atualmente dispositivos não descobertos.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">Não existem perfis de localização para este grupo de dispositivo atualmente. Adicione-os ao preencher os campos acima apropriados.</string>
  <string id="There are currently no forms printers in the system.">Não existem impressoras de formulários no sistema atualmente.</string>
  <string id="There are currently no licenses installed.">Não existem licenças instaladas atualmente.</string>
  <string id="There are currently no licensing changes made by this upload.">Não existem alterações de licença realizadas por este upload atualmente.</string>
  <string id="There are currently no missing devices for this device group.">Não existem dispositivos ausentes para este grupo de dispositivo atualmente.</string>
  <string id="There are currently no missing devices.">Não há dispositivos ausentes atualmente.</string>
  <string id="There are currently no out of policy devices for this device group.">Não existem dispositivos fora da política para este grupo de dispositivos atualmente.</string>
  <string id="There are currently no out of policy devices.">Não existem dispositivos fora da política atualmente.</string>
  <string id="There are currently no scheduled tasks">Não existem tarefas programadas atualmente</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">Não existem grupos de cliente de software atualmente.  Adicione um grupo clicando no botão Adicionar no lado esquerdo.</string>
  <string id="There are currently no solutions associated with this device group.">Não existem soluções associadas a este grupo de dispositivo.</string>
  <string id="There are currently no solutions associated with this software client group.">Não existem soluções associadas a este grupo de cliente de software atualmente.</string>
  <string id="There are currently no solutions installed.">Não existem soluções instaladas atualmente.</string>
  <string id='There are currently no solutions to add to this device group.'>Não existem soluções para adicionar a este grupo de dispositivo atualmente.</string>
  <string id="There are currently no solutions to add to this software client group.">Não existem soluções para adicionar a este grupo de cliente de software atualmente.</string>
  <string id="There are currently no unlicensed devices for this device group.">Não existem dispositivos não licenciados para este grupo de dispositivo atualmente.</string>
  <string id="There are currently no unlicensed devices in this device group.">Não há dispositivos sem licença atualmente neste grupo de dispositivos.</string>
  <string id="There are currently no unlicensed devices.">Não há dispositivos sem licença atualmente.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">Existem soluções ou aplicativos cSF e/ou telas iniciais associadas à política deste grupo atualmente. Gostaria de desimplantar esta política agora? Observe que, ao fazer isso, o grupo de dispositivos não será excluído imediatamente. Remova o grupo de dispositivos quando a atualização da política for concluída.</string>
  <string id="There are no associated UCF Files for this Solution.">Não há arquivos de configuração de segurança associados para esta solução.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">Não há arquivos de configuração de segurança associados para as soluções neste grupo de dispositivos.</string>
  <string id="There are no configuration settings for this eSF application.">Não há nenhuma definição de configuração para este aplicativo eSF.</string>
  <string id="There are no configuration settings in this solution.">Não há nenhuma definição de configuração nesta solução.</string>
  <string id="There are no configuration settings in this webapp.">Não há nenhuma definição de configuração neste webapp.</string>
  <string id="There are no cSF Apps installed currently.">Não existem aplicativos cSF instalados atualmente.</string>
  <string id="There are no deployments setting for this solution.">Não há definições de implementação para esta solução.</string>
  <string id="There are no devices in the system that match the filter.">Não existem dispositivos no sistema que correspondam ao filtro.</string>
  <string id="There are no eSF Applications for this solution.">Não há aplicativos eSF para esta solução.</string>
  <string id="There are no e-Task profiles for this device group.">Não existem perfis de e-Task para este grupo de dispositivo atualmente.</string>
  <string id="There are no e-Task2 profiles for this device group.">Não existem perfis de e-Task2 para este grupo de dispositivo.</string>
  <string id="There are no forms for this solution.">Não há formulários para esta solução.</string>
  <string id="There are no forms in the system.">Não existem formulários no sistema.</string>
  <string id="There are no parameters in this service.">Não há parâmetros neste serviço.</string>
  <string id="There are no profiles for this software client group.">Não existem perfis para este grupo de cliente de software.</string>
  <string id="There are no settings for this action.">Não há configurações para esta ação.</string>
  <string id="There are no settings for this solution.">Não há configurações para esta solução.</string>
  <string id="There is currently a Policy Update running...">Não há uma atualização de política em execução atualmente...</string>
  <string id="There is currently no Version Info.">Não existem informações da versão no momento.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">Estes aplicativos eSF são parte das soluções associadas a este grupo de dispositivos. Selecione um aplicativo para visualizar suas configurações.</string>
  <string id="These group settings are currently hidden.">Essas configurações de grupo estão atualmente ocultas.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">Esses perfis são parte da política de grupo para cada modelo. Selecione um perfil para cada modelo para visualizar suas configurações.</string>
  <string id="Third">Terceiro</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">Este link encaminhará você para a Interface de usuário de configuração do Webkit da Lexmark. Deseja continuar?</string>
  <string id="This Month">Este mês</string>
  <string id="This name has been given to another device group. Please choose a different name.">Este nome foi dado a outro grupo de dispositivos. Escolha um nome diferente.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">Este nome foi dado a outro grupo de clientes de software. Escolha um nome diferente.</string>
  <string id="Thread Count">Contagem de thread</string>
  <string id="Thu">Qui</string>
  <string id="Time">Hora</string>
  <string id="Time of Next Run">Hora da próxima execução</string>
  <string id="Time Policies Last Applied">Hora das últimas políticas aplicadas</string>
  <string id="Time:">Hora:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">Para adicioná-los à tela inicial, selecione layout Personalizado na caixa suspensa acima e adicione os perfis.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">Para organizá-los, selecione um dos layouts na caixa suspensa acima.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">Para configurar um, selecione um dos layouts da caixa suspensa acima.</string>
  <string id="To:">Para:</string>
  <string id="Today">Hoje</string>
  <string id="Today date">Data de hoje</string>
  <string id="Tops Report">Principais relatórios</string>
  <string id="Tue">Ter</string>
  <string id="UCF">Arquivos de configuração de segurança</string>
  <string id="UCF:">Arquivos de configuração de segurança:</string>  
  <string id="Unable to Change Password.">Não foi possível alterar a senha.</string>
  <string id="Unable to Change Username.">Não foi possível alterar o nome de usuário.</string>
  <string id="Unable to validate all settings!">Não foi possível validar todas as configurações!</string>
  <string id="Uncounted">Não contado</string>
  <string id="Un-deploying all cSF Apps(s)...">Desimplantando todos os aplicativos cSF...</string>
  <string id="Un-deploying cSF App(s)...">Desimplantando aplicativos cSF...</string>
  <string id="Unknown">Desconhecido</string>
  <string id="Unknown Error Occured! Please Check System Log">Ocorreu um erro desconhecido! Verifique o registro do sistema</string>
  <string id='Unknown Secure State'>Estado de proteção desconhecido</string>
  <string id="Unlicensed">Não licenciado</string>
  <string id="Unlicensed Device">Dispositivo não licenciado</string>
  <string id="Unlicensed Devices">Dispositivos não licenciados</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Dispositivos não licenciados são dispositivos que já foram descobertos, mas que, durante a descoberta mais recente, não tiveram nenhuma licença atribuída a eles. (por exemplo, pelo fato de a licença estar expirada ou de todas as licenças estarem em uso).</string>
  <string id="Unlicensed devices:">Dispositivos não licenciados:</string>
  <string id="Unlicensed Devices:">Dispositivos não licenciados:</string>
  <string id="Unlicensed:">Não licenciado:</string>
  <string id="Unlimited">Ilimitado</string>
  <string id="Up icon:">Ícone para cima:</string>
  <string id="Update">Atualizar</string>
  <string id="Update Policy">Atualizar política</string>
  <string id="Update Time">Atualizar hora</string>
  <string id="Update Time:">Hora da atualização:</string>
  <string id="Updating client profile...">Atualizando perfil de cliente...</string>
  <string id="Updating discovery profile...">Atualizando perfil de localização...</string>
  <string id="Updating e-Task home screen...">Atualizando a tela inicial do e-Task...</string>
  <string id="Updating e-Task2 home screen...">Atualizando a tela inicial do e-Task2...</string>
  <string id="Updating e-Task2+ home screen...">Atualizando a tela inicial do e-Task2+...</string>
  <string id="Updating e-Task3 home screen...">Atualizando a tela inicial do e-Task3...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">Atualizando a tela inicial do e-Task4...</string>
  <string id="Updating e-Task4 home screen...">Atualizando a tela inicial do e-Task4...</string>
  <string id="Updating Fax Forward settings...">Atualizando as configurações de encaminhamento de fax...</string>
  <string id="Updating password...">Atualizando senha...</string>
  <string id="Updating Security setting...">Atualizando configuração de segurança...</string>
  <string id="Updating service settings...">Atualizando configurações de serviço...</string>
  <string id="Updating SFP e-Task home screen...">Atualizando a tela inicial do SFP e-Task...</string>
  <string id="Updating SFP e-Task2 home screen...">Atualizando a tela inicial do SFP e-Task2...</string>
  <string id="Updating SFP e-Task2+ home screen...">Atualizando a tela inicial do SFP e-Task2+...</string>
  <string id="Updating SFP e-Task3 home screen...">Atualizando a tela inicial do SFP e-Task3...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen...">Atualizando a tela inicial do SFP e-Task4 (7 pol)...</string>
  <string id="Updating SFP e-Task4 home screen...">Atualizando a tela inicial do SFP e-Task4...</string>
  <string id="Updating solution settings...">Atualizando as configurações de solução...</string>
  <string id="Updating username...">Atualizando nome de usuário...</string>
  <string id="Updating X642 home screen...">Atualizando a tela inicial do X642...</string>
  <string id='Updating webapp settings...'>Atualizando as configurações do webapp...</string>
  <string id="Upgrading or deleting solutions here will require">Atualizar ou excluir soluções aqui exigirá</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">Para atualizar ou desimplantar o(s) aplicativo(s) cSF aqui será necessária a &lt;b&gt;Atualização de política&lt;/b&gt; em todos os grupos de dispositivo afetados</string>
  <string id="Upload">Upload</string>
  <string id="Upload custom icons">Upload de ícones personalizados</string>
  <string id="Upload Report Files">Upload de arquivos de relatório</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">Upload de conjunto AP e descritor concluído.</string>
  <string id="Uploading AP Bundle and Descriptor...">Fazendo o upload de conjunto AP...</string>
  <string id="Uploading cSF Ap cert files....">Fazendo o upload de arquivos certificados de aplicativo cSF...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">Fazendo o upload de arquivos certificados de aplicativo cSF (cacert.pem e key.pem ...</string>
  <string id="Uploading of cSF App cert files Completed.">Upload de arquivos certificados de aplicativo cSF concluído.</string>
  <string id="Uploading Report(s)...">Fazendo upload de relatório(s)...</string>
  <string id="Uploading...">Fazendo upload...</string>
  <string id="Usage:">Uso:</string>
  <string id="Usb Drive">Unidade USB</string>
  <string id="Use default settings">Utilizar configurações padrão</string>
  <string id="Use Secure Connection. (SSLTLS)">Utilizar conexão segura. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Usar configuração da solução</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">Use esta caixa de diálogo somente se os dados webdav centrais e do banco de dados do sistema LDD existente precisarem ser sincronizados com outro sistema LDD ativo que funcionará como um "sistema LDD de backup". Para obter mais informações sobre esse recurso, consulte o guia do Administrador.</string>
  <string id="Use this home screen as part of the device groups policy.">Use esta tela inicial como parte da política do grupo de dispositivos.</string>
  <string id='Used:'>Usado:</string>
  <string id="User Name">Nome de usuário</string>
  <string id="User Name:">Nome de usuário:</string>
  <string id="User Report">Relatório do usuário</string>
  <string id="User Search Base:">Base de pesquisa de usuário:</string>
  <string id="User Search Filter:">Filtro de pesquisa de usuário:</string>
  <string id="Username amp; Password">Nome de usuário e senha</string>
  <string id="Username and Password">Nome de usuário e senha</string>
  <string id="Username Changed Successfully.">Nome de usuário alterado com sucesso.</string>
  <string id="Username Password">Nome de usuário senha</string>
  <string id="Username updated.">Nome de usuário atualizado.</string>
  <string id="Username*">Nome de usuário*</string>
  <string id="Username:">Nome do usuário:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Verifique a implantação de aplicativos eSF e implante essas configurações de eSF.</string>
  <string id="Version">Versão</string>
  <string id="Version Info:">Informações do fornecedor:</string>
  <string id="Version:">Versão:</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">Texto muito longo</string>
  <string id="View Details">Exibir detalhes</string>
  <string id="View Source">Visualizar origem</string>
  <string id="Waiting for License Upload Results ...">Esperando pelos resultados de carregamento de licença...</string>
  <string id="WebApps">WebApps</string>
  <string id="WebClient Version">Versão WebClient:</string>
  <string id="WebClient Version:">Versão WebClient:</string>
  <string id="Wed">Qua</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated.">Tela inicial do X642 atualizada.</string>
  <string id="Yes">Sim</string>
  <string id="You are viewing the Kranked version of the application">Você está vendo a versão com Krank do aplicativo</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">Você não tem privilégio para acessar nenhuma das tarefas no aplicativo cSF</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">Você não tem privilégio para acessar nenhuma das tarefas em todos os grupos de dispositivos</string>
  <string id="You have no privilege to this task.">Você não tem privilégios para esta tarefa.</string>
  <string id="You must first select a Task to Edit">Você deve primeiro selecionar uma tarefa para editar</string>
  <string id="active">ativo</string>
  <string id="active:">ativo:</string>
  <string id="addition to the two events below.">adição aos dois eventos abaixo.</string>
  <string id="avg response (ms)">resposta média (ms)</string>
  <string id="be set back to the default values next time.">vão ser definidas de volta aos valores padrão da próxima vez.</string>
  <string id="cache">cache</string>
  <string id="cc:">cc:</string>
  <string id="change">alteração</string>
  <string id="cSF App">Aplicativo cSF</string>
  <string id="cSF App Cert File">Arquivo certificado de aplicativo cSF</string>
  <string id="cSF App Certificates">Certificados de aplicativo cSF</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">Upload de certificados de aplicativo cSF (cacert.pem e key.pem )</string>
  <string id="cSF App Key File">Arquivo principal de aplicativo cSF</string>
  <string id="cSF App settings updated.">Configurações de aplicativo cSF atualizadas.</string>
  <string id="cSF App Version">Versão do aplicativo cSF</string>
  <string id="cSF App Version:">Versão do aplicativo cSF:</string>
  <string id="cSF Apps">Aplicativos cSF</string>
  <string id="cSF Apps deployed to device group">Aplicativo cSF implantado em grupo de dispositivos</string>
  <string id="cSF Apps to deploy:">Aplicativos cSF para implantar:</string>
  <string id="cSF Apps: Device group deployment deleted.">Aplicativos cSF: Implantação de grupo de dispositivo excluída.</string>
  <string id="day(s)">dia(s)</string>
  <string id="devices failed">falha de dispositivos</string>
  <string id="devices updated">dispositivos atualizados</string>
  <string id="device(s) discovered">dispositivo(s) localizado(s)</string>
  <string id="device(s) missing">dispositivo(s) ausente(s)</string>
  <string id="disk-in-use=">disco em uso=</string>
  <string id="disk-total=">disco-total=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">Definições de aplicativo eSF:</string>
  <string id="eSF Application Version:">Versão do aplicativo eSF:</string>
  <string id="eSF Applications">Aplicativos eSF</string>
  <string id="eSF Applications:">Aplicativos eSF:</string>
  <string id="eSF Applications: (Solution)">Aplicativos eSF: (Solução)</string>
  <string id="eSF Configuration">Configuração eSF</string>
  <string id="eSF Settings Saved.">Definições eSF salvas.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">Tela inicial do e-Task atualizada.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated.">Tela inicial do e-Task2 atualizada.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated.">Tela inicial do e-Task2+ atualizada.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated.">Tela inicial do e-Task3 atualizada.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4,3 pol.)</string>
  <string id="e-Task4 (4.3 in.) home screen updated.">Tela inicial e-Task4 (4,3 pol.) atualizada.</string>
  <string id="e-Task4 home screen updated.">Tela inicial e-Task4 atualizada.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">falhou.</string>
  <string id="hide">ocultar</string>
  <string id="hour(s)">hora(s)</string>
  <string id="in order to add a group.">a fim de adicionar um grupo.</string>
  <string id="info">informações</string>
  <string id="load">carregar</string>
  <string id="mem-in-use=">mem-em-uso=</string>
  <string id="mem-total=">mem-total=</string>
  <string id="min(s)">min(s)</string>
  <string id="month(s)">mês(s)</string>
  <string id="not communicating">não se comunicando</string>
  <string id="null">nulo</string>
  <string id="offline">off-line</string>
  <string id="on">ativado</string>
  <string id="on all effected Device Groups.">em todos os grupos de dispositivos afetados.</string>
  <string id="oncheck">desmarque</string>
  <string id="online">on-line</string>
  <string id="or home screen support for this device does not exist.">ou o suporte de tela inicial para este dispositivo não existe.</string>
  <string id="requests">solicitações</string>
  <string id="requests/sec">solicitações/seg</string>
  <string id="saving report...">salvando relatório...</string>
  <string id="server">servidor</string>
  <string id="show">mostrar</string>
  <string id="test">teste</string>
  <string id="to">para</string>
  <string id="to change them.">para mudá-los.</string>
  <string id="to take effect on the devices.">para ter efeito nos dispositivos.</string>
  <string id="total requests:">total de solicitações:</string>
  <string id="total responses:">total de respostas:</string>
  <string id="undo">desfazer</string>
  <string id="uploaded.">carregado.</string>
  <string id="week(s)">semana(s)</string>
  <string id="{0} Groups">Grupos {0}</string>
  <string id="{0} Reports">Relatórios {0}</string>
  <string id="{0} Software Client Groups">Grupos de cliente de software {0}</string>
  <string id="{0} Solutions">Soluções {0}</string>
  <string id="{0} eForms">eForms {0}</string>
  <string id="{0} eSF Applications">Aplicativos eSF {0}</string>
  <string id="Policy update required for changes to take effect on the devices">Todas as alterações aqui exigirão &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Atualização de política&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; para ter efeito nos dispositivos.</string>
  <string id="Group search base must be set for adding group based Privileges">A base de pesquisa de grupos deve ser definida para adição de &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Previlégios&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; com base em grupos</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">A base da pesquisa de grupos deve ser definida na &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Configuração do LDAP&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; para poder adicionar um grupo.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">Instalação de SMB licenciado! A MFP estará limitada a, no máximo,</string>
  <string id="licenses!">licenças!</string>
</localize>
`;