export const JA = `
<localize>
  <string id="% Completed">% 完了</string>
  <string id="% Completed:">% 完了：</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;バージョン情報&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">（任意）説明を入力してください。</string>
  <string id="( Username must be a Distinguished Name )">（ユーザー名は識別名である必要があります）</string>
  <string id="(1-999)">（1 ～ 999）</string>
  <string id="(Cron expression)">（Cron 表現）</string>
  <string id="(progress)">（進行状況）</string>
  <string id="* Software Client License Not Found.">* ソフトウェアクライアントのライセンスが見つかりません。</string>
  <string id="[EXTERNAL]">[EXTERNAL]</string>
  <string id="[None]">[None]</string>
  <string id="1 Button">1 個のボタン</string>
  <string id="1 minute load">1 分間の負荷</string>
  <string id="1. cSF Apps">1.cSF アプリケーション</string>
  <string id="1. Device Groups">1.デバイスグループ</string>
  <string id="1. Search">1.検索</string>
  <string id="1. Services">1.サービス</string>
  <string id="1. Software Client Groups">1.ソフトウェアクライアントグループ</string>
  <string id="1. Solutions">1.ソリューション</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. 検索条件を入力し、［検索］ボタンをクリックします。</string>
  <string id="1. WebApps">1. Web アプリ</string>
  <string id="10 Buttons">10 個のボタン</string>
  <string id="15 minute load">15 分間の負荷</string>
  <string id="15sec">15秒</string>
  <string id="2 Buttons">2 個のボタン</string>
  <string id="2. Choose one or more devices if any are found.">2. 1 つ以上のデバイスを選択します（検出された場合）。</string>
  <string id="2. Devices">2.デバイス</string>
  <string id="2. Tasks">2.タスク</string>
  <string id="3 Buttons">3 個のボタン</string>
  <string id="3. Choose a Task.">3. タスクを選択します。</string>
  <string id="3. Tasks">3.タスク</string>
  <string id="30sec">30秒</string>
  <string id="4 Buttons">4 個のボタン</string>
  <string id="4-16 Buttons">4 ～ 16 個のボタン</string>
  <string id="5 Buttons">5 個のボタン</string>
  <string id="5 minute load">5 分間の負荷</string>
  <string id="5sec">5秒</string>
  <string id="6 Buttons">6 個のボタン</string>
  <string id="60sec">60秒</string>
  <string id="7 Buttons">7 個のボタン</string>
  <string id="8 Buttons">8 個のボタン</string>
  <string id="9 Buttons">9 個のボタン</string>
  <string id="A Policy Update is currently running...">ポリシーを更新しています...</string>
  <string id="About">バージョン情報</string>
  <string id="Action">アクション</string>
  <string id="Action Settings...">アクションの設定...</string>
  <string id="Action Settings:">アクションの設定：</string>
  <string id="Action:">アクション：</string>
  <string id="Add">追加</string>
  <string id="Add a cSF App to deploy:">展開する cSF アプリを追加：</string>
  <string id="Add a new Group to the system">システムに新しいグループを追加</string>
  <string id="Add a new report to the system">システムに新しいレポートを追加</string>
  <string id="Add a solution to deploy: Step 1 of 2">展開するソリューションを追加： ステップ 1/2</string>
  <string id="Add a solution to deploy: Step 2 of 2">展開するソリューションを追加： ステップ 2/2</string>
  <string id="Add a solution: Step 1 of 2">ソリューションを追加： ステップ 1/2</string>
  <string id="Add a solution: Step 2 of 2">ソリューションを追加： ステップ 2/2</string>
  <string id="Add a task to Schedule : Step 1 of 3">定期設定するタスクを追加：ステップ 1/３</string>
  <string id="Add Device Group">デバイスグループを追加</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">定期設定するデバイスグループを追加：ステップ 2/３</string>
  <string id="Add Forms Printer">Forms Printer を追加</string>
  <string id="Add License">ライセンスを追加</string>
  <string id="Add Software Client Group">ソフトウェアクライアントグループを追加</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">定期設定する頻度を追加：ステップ 3/３</string>
  <string id="Add...">追加...</string>
  <string id="Adding Formset(s)...">フォームセットを追加しています...</string>
  <string id="Adding Group Name from LDAP...">LDAP からグループ名を追加しています...</string>
  <string id="Adding solution to software client group...">ソフトウェア クライアント グループにソフトウェアを追加しています...</string>
  <string id="Additional Options">その他のオプション</string>
  <string id="Additional Parameters">その他のパラメータ</string>
  <string id="Additional Parameters...">その他のパラメータ...</string>
  <string id="Additional Report Parameters">その他のレポートパラメータ</string>
  <string id="Address">アドレス</string>
  <string id="Address:">アドレス：</string>
  <string id="Admin password:">管理者パスワード：</string>
  <string id="All">すべて</string>
  <string id="All cSF Apps">すべての cSF アプリ</string>
  <string id="All Device Groups">すべてのデバイスグループ</string>
  <string id="All scheduled tasks for the system.">システムのすべてのスケジュール済みタスク。</string>
  <string id="All scheduled tasks for this device group:">このデバイスグループのすべてのスケジュール済みタスク：</string>
  <string id="All scheduled tasks for this sftClient group">この sftClient グループのすべてのスケジュール済みタスク</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">選択されたデバイスはすべて、システムから完全に削除されます。これらのデバイスを削除してもよろしいですか？</string>
  <string id="All Servers Offline">すべてのサーバーがオフライン</string>
  <string id="All Servers Online">すべてのサーバーがオンライン</string>
  <string id="All Software Client Groups">すべてのソフトウェアクライアントグループ</string>
  <string id="All Solutions">すべてのソリューション</string>
  <string id="All Tabs">すべてのタブ</string>
  <string id="An error occurred while attempting to connect to this device,">このデバイスへの接続中にエラーが発生しました。</string>
  <string id="Anonymous">匿名</string>
  <string id="Any changes here will require">ここで変更するには、次のもの（こと）が必要です：</string>
  <string id="Any Changes to the parameters are temporary and will">パラメータの変更は一時的なものです。</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">パラメータの変更は一時的なものです。次回には標準設定の値に戻ります。</string>
  <string id="AP (Advanced Prompting) Bundle Upload">AP（Advanced Prompting）バンドルのアップロード</string>
  <string id="AP Bundle">AP バンドル</string>
  <string id="AP Bundle Application File">AP バンドルアプリケーションファイル</string>
  <string id="AP Bundle descriptor">AP バンドル記述子</string>
  <string id="AP Bundle Descriptor File">AP バンドル記述子ファイル</string>
  <string id="App Reservation">アプリケーションの保留</string>
  <string id="Application">アプリケーション</string>
  <string id="Apply">適用</string>
  <string id="Are you sure you want to change the edited profile?">編集したプロファイルを変更してもよろしいですか？</string>
  <string id="Are you sure you want to change these profiles?">これらのプロファイルを変更してもよろしいですか？</string>
  <string id="Are you sure you want to delete all the forms?">すべてのフォームを削除してもよろしいですか？</string>
  <string id="Are you sure you want to delete all the profiles?">すべてのプロファイルを削除してもよろしいですか？</string>
  <string id="Are you sure you want to delete all the solutions?">すべてのソリューションを削除してもよろしいですか？</string>
  <string id="Are you sure you want to delete the selected forms?">選択したフォームを削除してもよろしいですか？</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">選択したグループを削除してもよろしいですか？  このグループに関連付けられた権限は、すべて自動的に削除されます。</string>
  <string id="Are you sure you want to delete the selected profiles?">選択したプロファイルを削除してもよろしいですか？</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">選択されたレポートを削除しますか？  このレポートにスケジュールされたレポートタスクは、すべて自動的に削除されます。</string>
  <string id="Are you sure you want to delete the selected solutions?">選択されたソリューションを削除しますか？</string>
  <string id="Are you sure you want to delete these profiles?">これらのプロファイルを削除してもよろしいですか？</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">すべての cSF アプリを展開解除してもよろしいですか？</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">選択した cSF アプリを展開解除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">この +webAppsString.getWebAppString()+?} を削除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this Device Group?">このデバイスグループを削除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this forms printer?">このフォームプリンタを削除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this scheduled task?">このスケジュール済みタスクを削除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this software client Group?">このソフトウェア クライアント グループを削除してもよろしいですか？</string>
  <string id="Are you sure you would like to delete this solution?">このソリューションを削除してもよろしいですか？</string>
  <string id="Associated Device Group :">関連付けられたデバイスグループ：</string>
  <string id="Associated Solution :">関連付けられたソリューション：</string>
  <string id="Associated Solution:">関連付けられたソリューション：</string>
  <string id="Authentication Method:">認証方法：</string>
  <string id="Author">作成者</string>
  <string id="Auto Refresh:">自動更新：</string>
  <string id="Available Columns">使用可能な列</string>
  <string id="Available Reports">使用可能なレポート</string>
  <string id="Back">戻る</string>
  <string id="Background Image:">背景画像：</string>
  <string id="Backup &amp; Restore information">バックアップと復元の情報</string>
  <string id="Backup amp; Restore">バックアップと復元</string>
  <string id="Backup Jobs Logs Database">ジョブのログのデータベースをバックアップ</string>
  <string id="Backup Share Path">バックアップ共有パス</string>
  <string id="Bar Chart">棒グラフ</string>
  <string id="Binary Files">バイナリファイル</string>
  <string id="Bookmarks">ブックマーク</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">cSF アプリ証明書を更新するには、cacert.pem ファイルおよび key.pem ファイルが両方とも必要です。</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">AP バンドルを更新するには、eSF フラッシュおよび記述子ファイルが両方とも必要です。</string>
  <string id="Browse">参照</string>
  <string id="Browse...">参照....</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">標準設定では、MFP はホーム画面のボタンを自動的に配置します。</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">標準設定では、SFP は保留中のジョブのフォルダにプロファイルを追加します。</string>
  <string id="Cancel">キャンセル</string>
  <string id="Canceled">キャンセル済み</string>
  <string id="Canceling...">キャンセル処理中...</string>
  <string id="Change Default Values">標準設定の値を変更</string>
  <string id="Change Language">言語の変更</string>
  <string id="Change Password">パスワード変更</string>
  <string id="Change Username">ユーザー名を変更</string>
  <string id="Changing name...">名前を変更しています...</string>
  <string id="Choose a cSF App to deploy:">展開する cSF アプリを選択：</string>
  <string id="Choose a solution to deploy:">展開するソリューションを選択：</string>
  <string id="Choose a solution:">ソリューションを選択：</string>
  <string id="Choose Client Groups">クライアントグループを選択</string>
  <string id="Choose deployment settings for">次のもの用の展開設定を選択：</string>
  <string id="Choose Device Groups">デバイスグループを選択</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">各ボタンを選択し、アクションを設定します。 アクションが設定されていないボタンは、ホーム画面に表示されません。</string>
  <string id="Choose one...">1 つ選択...</string>
  <string id="Choose task">タスクを選択</string>
  <string id="Choose the frequency">頻度を選択</string>
  <string id="Choose the group type">グループタイプを選択</string>
  <string id="Class">クラス</string>
  <string id="Click">次をクリック：</string>
  <string id="Click Add to create a Home screen button.">ホーム画面ボタンを作成するには、［追加］をクリックします。</string>
  <string id="Click on checkboxes to select or deselect privileges.">権限を選択または選択解除するには、チェックボックスをクリックします。</string>
  <string id="Click on the square, then release the mouse button to select a new color.">四角をクリックし、マウスボタンをリリースして新しいカラーを選択します。</string>
  <string id="Client Groups:">クライアントグループ：</string>
  <string id="Client Profile created.">クライアントプロファイルが作成されました。</string>
  <string id="Client Profiles">クライアントプロファイル</string>
  <string id="Close">閉じる</string>
  <string id="Color :">カラー：</string>
  <string id="Column Chart.">列チャート</string>
  <string id="Compile">コンパイル</string>
  <string id="Compile Options:">コンパイルのオプション：</string>
  <string id="Completed">完了</string>
  <string id="Components">コンポーネント</string>
  <string id="Config Service">設定サービス</string>
  <string id="Configuration">設定</string>
  <string id="Configuration:">設定：</string>
  <string id="Configurations for this discovery:">この検出の設定：</string>
  <string id="Connect To App">アプリケーションに接続</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">ターゲット VM（アドレス：127.0.0.1:61023、トランスポート：socket）に接続されました</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">接続がタイムアウトしました。 ファイアウォールの設定を含め、サーバーの設定を確認してください。</string>
  <string id="Contact Location">担当者の場所</string>
  <string id="Contact Location:">担当者の場所：</string>
  <string id="Contact Name">担当者名</string>
  <string id="Contact Name:">担当者名：</string>
  <string id="Content :">コンテンツ：</string>
  <string id="Copy">コピー</string>
  <string id="Copy + Profile">コピー + プロファイル</string>
  <string id="Copy Shortcuts">ショートカットをコピー</string>
  <string id="CPU Usage">CPU 使用状況</string>
  <string id="Creating client profile...">クライアントプロファイルを作成しています...</string>
  <string id="Creating device group...">デバイスグループを作成しています...</string>
  <string id="Creating discovery profile...">検索プロファイルを作成しています...</string>
  <string id="Creating or updating a forms printer...">フォームプリンタを作成/更新しています...</string>
  <string id="Creating software client group...">ソフトウェア クライアント グループを作成しています...</string>
  <string id="Creatingupdating the scheduled task...">スケジュール済みタスクを作成/更新しています...</string>
  <string id="Cron expression)">（Cron 表現）</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">現在の列</string>
  <string id="Current password is incorrect.">現在のパスワードは間違っています。</string>
  <string id="Current Password:">現在のパスワード：</string>
  <string id="Currently discovering Missing Devices...">現在、不明デバイスを検索しています...</string>
  <string id="Currently discovering Unlicensed Devices...">現在、未ライセンスのデバイスを検索しています...</string>
  <string id="Custom">ユーザー定義</string>
  <string id="Custom icons:">ユーザー定義アイコン：</string>
  <string id="Custom...">ユーザー定義...</string>
  <string id="Customize Jobs Table">ジョブの表をカスタマイズ</string>
  <string id="Customize Logs Table">ログの表をカスタマイズ</string>
  <string id="Customize Table...">表をカスタマイズ...</string>
  <string id="Danger, Will Robinson!">警告!</string>
  <string id="Darkness :">濃さ：</string>
  <string id="Database Driver:">データベースドライバ：</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>データベースの完全修飾ホスト名または IP アドレス</string>
  <string id="Database URL:">データベース URL：</string>
  <string id="Datasource:">データソース：</string>
  <string id="Datatype Filter">データタイプフィルタ</string>
  <string id="Datatype filter:">データタイプフィルタ：</string>
  <string id="Date">日付</string>
  <string id="Debug">デバッグ</string>
  <string id="Default">標準設定</string>
  <string id="Default Group">デフォルトグループ</string>
  <string id="Default Group can not be deleted.">標準設定のグループは削除できません。</string>
  <string id="Default Output Format:">標準設定の出力形式：</string>
  <string id="Default: 389">標準設定： 389</string>
  <string id="Delete">削除</string>
  <string id="Delete file on failure?">エラー時にファイルを削除しますか？</string>
  <string id="Delete file on success?">成功時にファイルを削除しますか？</string>
  <string id="Deleted device group. One or more devices must now be updated.">デバイスグループが削除されました。 1 つ以上のデバイスを今すぐ更新する必要があります。</string>
  <string id="Deleted selected FormSet(s).">選択されたフォームセットが削除されました。</string>
  <string id="Deleted software client group.">ソフトウェア クライアント グループが削除されました。</string>
  <string id="Deleting All FormSet(s)...">すべてのフォームセットを削除しています...</string>
  <string id="Deleting All solution(s)...">すべてのソリューションを削除しています...</string>
  <string id="Deleting client profile(s)...">クライアントプロファイルを削除しています...</string>
  <string id="Deleting device group...">デバイスグループを削除しています...</string>
  <string id="Deleting discovery profile(s)...">検索プロファイルを削除しています...</string>
  <string id="Deleting forms printer...">フォームプリンタを削除しています...</string>
  <string id="Deleting Formset(s)...">フォームセットを削除しています...</string>
  <string id="Deleting scheduled task...">スケジュール済みタスクを削除しています...</string>
  <string id="Deleting selected FormSet(s)...">選択されたフォームセットを削除しています...</string>
  <string id="Deleting software client group...">ソフトウェア クライアント グループを削除しています...</string>
  <string id="Deleting solution(s)...">ソリューションを削除しています...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">展開先：</string>
  <string id="Deploy:">展開：</string>
  <string id="Deploying home screen to">ホーム画面を次の場所に展開しています：</string>
  <string id="Deploying solution to device group...">ソリューションをデバイスグループに展開しています...</string>
  <string id="Deploying WAR file:">WAR ファイルを展開しています： </string>
  <string id="Description">説明</string>
  <string id="Description:">説明：</string>
  <string id="Descriptor">記述子</string>
  <string id="Destination Folder Path">インストール先フォルダパス</string>
  <string id="Developer Forums">開発者フォーラム</string>
  <string id="Developer Network">開発者ネットワーク</string>
  <string id="Device Address">デバイスのアドレス</string>
  <string id="Device Address:">デバイスのアドレス：</string>
  <string id="Device Class">デバイスクラス</string>
  <string id="Device Group">デバイスグループ</string>
  <string id="Device Group created">デバイスグループが作成されました</string>
  <string id="Device Group was successfully removed from the system.">デバイスグループはシステムから正常に削除されました。</string>
  <string id="Device Group:">デバイスグループ：</string>
  <string id="Device Groups">デバイスグループ</string>
  <string id="Device Groups:">デバイスグループ：</string>
  <string id="Device Information Directions">デバイス情報の説明</string>
  <string id="Device Model">デバイスの機種</string>
  <string id="Device Model:">デバイスの機種：</string>
  <string id="Device Profiles">デバイスプロファイル</string>
  <string id="Device Summary">デバイス概要</string>
  <string id="Device update complete.">デバイスの更新が完了しました。</string>
  <string id="Device update started...">デバイスの更新が開始されました...</string>    
  <string id="DeviceGroup">デバイスグループ</string>
  <string id="Devices">デバイス</string>
  <string id="Directory">ディレクトリ</string> 
  <string id="Directory Path">ディレクトリパス</string>
  <string id="Directory path*">ディレクトリパス*</string>
  <string id="Directory Watcher">ディレクトリウォッチャー</string>
  <string id='Directory Watcher information'>ディレクトリウォッチャーの情報</string>  
  <string id="Disabled">無効</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">ターゲット VM（アドレス：127.0.0.1:60902、トランスポート：socket）から切断されました</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">ターゲット VM（アドレス：127.0.0.1:61015、トランスポート：socket）から切断されました</string>
  <string id="Discover">検出</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">各グループ固有の検出プロファイルを使用して、選択したデバイスグループのデバイスを検出します。</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">このデバイスグループの検出プロファイルを使用して、このデバイスグループのデバイスを検出します。</string>
  <string id="Discover Missing">なくなっているものを検出</string>
  <string id="Discover new devices only">新しいデバイスのみを検出</string>
  <string id="Discover Unlicensed">未ライセンスのものを検出</string>
  <string id="Discover...">検出...</string>
  <string id="Discovered">検出済み</string>
  <string id="Discovered Devices">検出されたデバイス</string>
  <string id="Discovered Devices:">検出されたデバイス：</string>
  <string id="Discovery">検出</string>
  <string id="Discovery has Completed for...">次のものの検出が完了しました：</string>
  <string id="Discovery in Progress for...">次のものを検出しています...</string>
  <string id="Discovery Profile created.">検索プロファイルが作成されました。</string>
  <string id="Discovery Profiles">検出プロファイル</string>
  <string id="Discovery Profiles:">検索プロファイル：</string>
  <string id="Display Text">表示テキスト</string>
  <string id="Display Text:">表示テキスト：</string>
  <string id="Documentation">ドキュメント</string>
  <string id="Done">完了</string>
  <string id="Done generating the jobs report for downloading.">ダウンロードのジョブレポートが生成されました。</string>
  <string id="Done generating the logs report for downloading.">ダウンロードのログレポートが生成されました。</string>
  <string id="Down icon">［ダウン］アイコン</string>
  <string id="Down icon:">［ダウン］アイコン：</string>
  <string id='Download Details'>詳細のダウンロード</string>
  <string id="Duplex :">両面：</string>
  <string id="Edit">編集</string>
  <string id="Edit a solution">ソリューションを編集</string>
  <string id="Edit a solution to deploy">展開するソリューションを編集</string>
  <string id="Edit the information about the report :">レポートに関する情報を編集：</string>
  <string id="Edit the report settings">レポートの設定を編集</string>
  <string id="Edit...">編集...</string>
  <string id="EForms">Eフォーム</string>
  <string id="E-Forms">E-フォーム</string>
  <string id="EForms:">Eフォーム：</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">開始日と開始時刻のフィールドは、両方とも入力するか両方とも空白にする必要があります。</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">終了日と終了時刻のフィールドは、両方とも入力するか両方とも空白にする必要があります。</string>
  <string id="Email">E メール</string>
  <string id="Email + Profile">E メール + プロファイル</string>
  <string id="Email Shortcuts">E メールショートカット</string>
  <string id="Email the Report">レポートを E メール送信</string>
  <string id="Email To">E メール送信先</string>
  <string id="Enable Fax Forwarding.">FAX 転送を有効にします。</string>
  <string id="Enable LDAP Authentication.">LDAP 認証を有効にします。</string>
  <string id="Enabled for Credentials">資格証明書用に有効化済み</string>
  <string id="Enabled for Session">セッション用に有効化済み</string>
  <string id="End Time">終了時刻</string>
  <string id="End Time:">終了時刻：</string>
  <string id="Enter a unique group name">一意のグループ名を入力</string>
  <string id="Enter a unique name for this group">このグループの一意の名前を入力</string>
  <string id="Enter appropriate fields and click the Add button:">適切なフィールドに入力して、［追加］ボタンをクリックします：</string>
  <string id="Enter appropriate fields and click the Save button:">適切なフィールドに入力して、［保存］ボタンをクリックします：</string>
  <string id="Enter the appropriate fields and click the Add button:">適切なフィールドに入力して、［追加］ボタンをクリックします：</string>
  <string id="Enter the information about the new report :">新しいレポートに関する情報を入力：</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">タイムアウト値をミリ秒で入力します（各エントリ間は空白区切り）。</string>
  <string id="Error">エラー</string>
  <string id="Error importing license.">ライセンスのインポート中にエラーが発生しました。</string>
  <string id="Error in changing name.">名前を変更中にエラーが発生しました。</string>
  <string id="Error in creating device group...">デバイスグループの作成中にエラーが発生しました...</string>
  <string id="Error in creating software client group...">ソフトウェア クライアント グループの作成中にエラーが発生しました...</string>
  <string id="Error in deleting device group.">デバイスグループの削除中にエラーが発生しました。</string>
  <string id="Error in deleting software client group.">ソフトウェア クライアント グループの削除中にエラーが発生しました。</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">フォームセットの削除中にエラーが発生しました。 詳細については、ログを参照してください。</string>
  <string id="Error in generating the report.">レポートの生成中にエラーが発生しました。</string>
  <string id="Error in saving Ldap settings.">LDAP 設定の保存中にエラーが発生しました。</string>
  <string id="Error in saving settings.">設定の保存中にエラーが発生しました。</string>
  <string id="Error in updating password.">パスワードの更新中にエラーが発生しました。</string>
  <string id="Error in updating security settings.">セキュリティの更新中にエラーが発生しました。</string>
  <string id="Error in updating service settings.">サービス設定の更新中にエラーが発生しました。</string>
  <string id="Error in updating solution settings.">ソリューション設定の更新中にエラーが発生しました。</string>
  <string id="Error while deploying home screen to">ホーム画面を次の場所に展開している途中でエラーが発生しました：</string>
  <string id="Eval">評価</string>
  <string id="Evaluate in +app_url}">+app_url} で評価</string>
  <string id="Evaluate in remote app">リモートアプリケーションで評価</string>
  <string id="Every">毎</string>
  <string id="Expiration Date">有効期限</string>
  <string id="Expired Formset">期限切れフォームセット</string>
  <string id="Expired!">有効期限切れです。</string>
  <string id="Expires on:">失効日：</string>
  <string id="Export Report">レポートをエクスポート</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">失敗</string>
  <string id="FALSE">偽</string>
  <string id="Fax">FAX</string>
  <string id="Fax + Profile">FAX + プロファイル</string>
  <string id="Fax Forward settings updated.">FAX 転送設定が更新されました。</string>
  <string id="Fax Forwarding">FAX 転送</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax">FAX 転送先のショートカット：（E メール、FTP、FAX</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">FAX 転送先のショートカット：（E メール、FTP、FAX）</string>
  <string id="Fax Forwarding Destination:">FAX 転送先：</string>
  <string id="Fax Forwarding LDSS Script:">FAX 転送 LDSS スクリプト：</string>
  <string id="Fax Forwarding Receive Mode:">FAX 転送受信モード：</string>
  <string id="Fax Shortcuts">FAX ショートカット</string>
  <string id="Feature Id">機能 ID</string>
  <string id="Filter">フィルタ</string>
  <string id="Filters...">フィルタ...</string>
  <string id="Finish">完了</string>
  <string id="Finished AP Bundle Descriptor File">AP バンドル記述子ファイルが完了しました</string>
  <string id="Finished AP Bundle Flash File">AP バンドルフラッシュファイルが完了しました</string>
  <string id="Finished upload of key.pem File.">key.pem ファイルのアップロードが完了しました。</string>
  <string id="First">1 番目</string>
  <string id="Form field must be a single word or valid email address.">［フォーム］フィールドには、単語 1 つまたは有効な E メールアドレスを入力してください。</string>
  <string id="Form Printers">フォームプリンタ</string>
  <string id="Format :">形式：</string>
  <string id="Forms">フォーム</string>
  <string id="Forms Printer is unlicensed">フォームプリンタのライセンスがありません</string>
  <string id="Forms printer successfully created or updated.">フォームプリンタが正常に作成/更新されました。</string>
  <string id="Forms printer successfully deleted.">フォームプリンタが正常に削除されました。</string>
  <string id="Formsets">フォームセット</string>
  <string id="FormsetsSubforms">フォームセット/サブフォーム</string>
  <string id="Forward Only">転送のみ</string>
  <string id="Fourth">4 番目</string>
  <string id="FRAMEWORK">フレームワーク</string>
  <string id="Fri">金曜</string>
  <string id="From:">送信元：</string>
  <string id="Ftp">FTP</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + プロファイル</string>
  <string id="Ftp Shortcuts">FTP ショートカット</string>
  <string id="Generating logs report for downloading...">ダウンロードのログレポートを生成しています...</string>
  <string id="Generating Report">レポート生成</string>
  <string id="Generating Report...">レポートを生成しています...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">通常の業務時間中にレポートを生成すると、システムのパフォーマンスに悪影響を与える可能性があります。レポート生成は業務時間外に行うことが推奨されます。</string>
  <string id="Generating the jobs report for downloading...">ダウンロードのジョブレポートを生成しています...</string>
  <string id="Graphic">グラフィック</string>
  <string id="Graphic:">グラフィックス：</string>
  <string id="Group Description placeholder">グループの説明のプレースホルダ</string>
  <string id="Group Identifier:">グループ識別子：</string>
  <string id="Group Names from LDAP">LDAP からのグループ名</string>
  <string id="Group Names from LDAP:">LDAP からのグループ名：</string>
  <string id="Group search base must be set for adding group based">グループ検索ベースは、グループベースの次のものを追加するために設定する必要があります： </string>
  <string id="Group search base must be set in">グループ検索ベースは次のもので設定する必要があります：</string>
  <string id="Group Search Base:">グループ検索ベース：</string>
  <string id="Group Search Filter:">グループ検索フィルタ：</string>
  <string id="Group Search Identifier:">グループ検索識別子：</string>
  <string id="Groups">グループ</string>
  <string id="Held Jobs">保留中のジョブ</string>
  <string id="Hide Settings">設定を非表示</string>
  <string id="Home">ホーム</string>
  <string id="Home Screen">ホーム画面</string>
  <string id="Home screen deployed to">ホーム画面が次の場所に展開されました：</string>
  <string id="Home Screens">ホーム画面</string>
  <string id="Home Tab">［ホーム］タブ</string>
  <string id="Hostname">ホスト名</string>
  <string id="Hostname:">ホスト名：</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">IDR ライセンスの概要</string>
  <string id="IDR License Summary:">IDR ライセンスの概要：</string>
  <string id="Images">イメージ</string>
  <string id="Import">インポート</string>
  <string id="Import...">インポート...</string>
  <string id="Importing AP Bundle Descriptor File...">AP バンドル記述子ファイルをインポートしています...</string>
  <string id="Importing AP Bundle Flash File...">AP バンドルフラッシュファイルをインポートしています...</string>
  <string id='Importing Binary String...'>バイナリストリングをインポートしています...</string>  
  <string id="Importing CaCert pem File...">CaCert pem ファイルをインポートしています...</string>
  <string id="Importing license...">ライセンスをインポートしています...</string>
  <string id="Importing software client group profile...">ソフトウェア クライアント グループ プロファイルをインポートしています...</string>
  <string id="Importing Solution(s)...">ソリューションをインポートしています...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">挿入 - これによって、切り取りされたボタンが挿入され、残りのボタンが下に移動します。</string>
  <string id="Install Time">インストール時間</string>
  <string id="Install Time:">インストール時間：</string>
  <string id="Install-Upgrade">インストール/アップグレード</string>
  <string id="It is recommended to run reports during off hours.">レポート生成は業務時間外に行うことが推奨されます。</string>
  <string id="Items">項目</string>
  <string id="Jasper Report File Name:">Jasper Report のファイル名：</string>
  <string id="Job State">ジョブの状態</string>
  <string id="Job State:">ジョブの状態：</string>
  <string id="Jobs">ジョブ</string>
  <string id="Jobs by user">ユーザー別ジョブ</string>
  <string id="Jobs Filters Table">ジョブのフィルタの表</string>
  <string id="Jobs Report">ジョブレポート</string>
  <string id="Jobs Report - CSV">ジョブレポート - CSV</string>
  <string id="Keep previous backups">以前のバックアップを保持</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>言語:</string>  
  <string id="Last">最後の</string>
  <string id="Last 12 Hours">最後の 12 時間</string>
  <string id="Last 15 Minutes">最後の 15 分間</string>
  <string id="Last 24 Hours">最後の 24 時間</string>
  <string id="Last 3 Hours">最後の 3 時間</string>
  <string id="Last 30 Days">最後の 30 日間</string>
  <string id="Last 30 Minutes">最後の 30 分間</string>
  <string id="Last 6 Hours">最後の 6 時間</string>
  <string id="Last 7 Days">最後の 7 日間</string>
  <string id="Last Discovered">最後に検出した日</string>
  <string id="Last Discovered:">最後に検出した日：</string>
  <string id="Last Hour">最後の 1 時間</string>
  <string id="Last Kranked">Last Kranked</string>
  <string id="Last Modified">最終更新日</string>
  <string id="Layout">レイアウト</string>
  <string id="Layout:">レイアウト：</string>
  <string id="LDAP Server Settings:">LDAP サーバー設定：</string>
  <string id="Ldap Settings Saved.">LDAP 設定が保存されました。</string>
  <string id="LDAP Setup">LDAP 設定</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark 印刷管理</string>
  <string id="License">ライセンス</string>
  <string id="LICENSE">ライセンス</string>
  <string id="License Files">ライセンスファイル</string>
  <string id="License Type">ライセンスの種類</string>
  <string id="License Upload Results.">ライセンスのアップロード結果。</string>
  <string id="License Upload Results:">ライセンスのアップロード結果：</string>
  <string id="Licensed">ライセンス済み</string>
  <string id="Licenses">ライセンス</string>
  <string id="Licenses in Use">使用中のライセンス</string>
  <string id="Limit batch size">バッチサイズを制限</string>
  <string id="Line Chart with Time Period Slider.">時間スライダー付き折れ線グラフ。</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>ロードバランサの完全修飾ホスト名または IP アドレス</string>
  <string id="LOADING">読み込み中</string>
  <string id="Loading...">読み込み中です...</string>
  <string id="LOADING...">読み込み中です...</string>
  <string id="Lock Device">デバイスをロック</string>
  <string id="Log">ログ</string>
  <string id="Log Report - CSV">ログレポート - CSV</string>
  <string id="Log Report - Failed Jobs">ログレポート - 失敗したジョブ</string>
  <string id="Log State">状態を記録</string>
  <string id="Log State:">ログの状態：</string>
  <string id="Logging In">ログイン中</string>
  <string id="Login">ログイン</string>
  <string id="Logout">ログアウト</string>
  <string id="Logs Filters Table">ログのフィルタの表</string>
  <string id='Max:'>最大：</string>
  <string id="Member of Group(s):">グループのメンバー：</string>
  <string id="Memory Usage">メモリ使用量</string>
  <string id="Message">メッセージ</string>
  <string id="Message:">メッセージ：</string>
  <string id="Messages">メッセージ</string>  
  <string id='Min:'>最小：</string>
  <string id='Minimum length:'>最小の長さ：</string>
  <string id='Minimum:'>最小：</string>  
  <string id="Missing">ありません</string>
  <string id="Missing Device">不明デバイス</string>
  <string id="Missing Devices">不明デバイス</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">不明デバイスとは、一度検出されているが、一番最後の検出中に（そのデバイスがネットワークに接続されていなかったなどの理由で）見つからなかったデバイスのことです。</string>
  <string id="Missing devices:">不明デバイス：</string>
  <string id="Missing Devices:">不明デバイス：</string>
  <string id="Model">機種</string>
  <string id="Model:">モデル：</string>
  <string id="Mon">月曜</string>
  <string id="MONITOR">モニタ</string>
  <string id="Move Down">下に移動</string>
  <string id="Move Up">上に移動</string>
  <string id="Name">名前</string>
  <string id="Name :">名前：</string>
  <string id="Name changed.">名前が変更されました。</string>
  <string id="Name:">名前：</string>
  <string id="Network Load">ネットワークロード</string>
  <string id="Network share password">ネットワーク共有のパスワード</string>
  <string id="Network share user name">ネットワーク共有のユーザー名</string>
  <string id="New Password:">新しいパスワード：</string>
  <string id="New Username:">新しいユーザー名：</string>
  <string id="Next">次へ</string>
  <string id="No">いいえ</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>このデバイスグループの cSF アプリはありません。 このアクションをボタンに関連付けるには、少なくとも 1 つの cSF アプリが必要です。</string>
  <string id="No devices are currently Out of Policy for the system.">このシステムで現在ポリシー外のデバイスはありません。</string>
  <string id="No devices are currently Out of Policy for this device group.">このデバイスグループで現在ポリシー外のデバイスはありません。</string>
  <string id="No home screen is configured for this device type.">このデバイスタイプ用に設定されたホーム画面はありません。</string>
  <string id="No matches found">一致するものがありません</string>
  <string id='No Privilege'>権限がありません</string>
  <string id="No Privilege Alert">権限アラートがありません</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">プロファイルを持つソリューションが関連付けられていないため、このデバイスグループのプロファイルはありません。</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">このデバイスグループのプロファイルはありません。 このアクションをボタンに関連付けるには、少なくとも 1 つのプロファイルが必要です。</string>
  <string id="No records match the selected filter criteria.">選択されたフィルタ条件に一致するレコードがありません。</string>
  <string id="No records matched the filter criteria.">フィルタ条件に一致するレコードがありません。</string>
  <string id="No schedulable scripts are available.">定期設定できるスクリプトはありません。</string>
  <string id="No UCF File selected">セキュリティ設定ファイルが選択されていません</string>
  <string id="None">なし</string>
  <string id="None of the selected devices are missing.">選択されたデバイスで見つからないものはありません。</string>
  <string id="None of the selected devices are unlicensed.">選択されたデバイスでライセンスがないものはありません。</string>
  <string id="Number of Jobs per Page">1 ページあたりのジョブの数</string>
  <string id="Number of Licenses">ライセンス数</string>
  <string id="Number of Logs per Page">1 ページあたりのログの数</string>
  <string id="Off">オフ</string>
  <string id="OK">OK</string>
  <string id="Once">1 回</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">現在の設定の 1 つ以上のボタンが無効です。すべてのボタンが有効であ &lt;font color="#ff0000"&gt;(赤で表示)&lt;/font&gt; ることを確認してください。</string>
  <string id="One or more tests did not pass.">1 つ以上のテストに合格しませんでした。</string>
  <string id="Only">これのみ（他になし）</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">一度に実行できる検出は 1 つのみです。 現在の検出が終了したら、新しい検出を開始できます。</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">一度に実行できるポリシー更新は 1 つのみです。現在のポリシー更新が終了したら、新しいポリシー更新を開始できます。</string>
  <string id="Only update those devices which are Out of Policy">ポリシー外のデバイスのみを更新します。</string>
  <string id="Orientation :">用紙の向き：</string>
  <string id="Out of Policy">ポリシー外</string>
  <string id="Out of Policy Device">ポリシー外のデバイス</string>
  <string id="Out of Policy Devices">ポリシー外のデバイス</string>
  <string id="Out of Policy Devices:">ポリシー外のデバイス：</string>
  <string id="Output Format">出力形式</string>
  <string id="Overwrite if file already exists">ファイルがすでに存在する場合は上書きする</string>
  <string id="Page 1">ページ 1</string>
  <string id="Page 2">ページ 2</string>
  <string id="Page 3">ページ 3</string>
  <string id="Page 4">ページ 4</string>
  <string id="Paper Size :">用紙サイズ：</string>
  <string id="Parameters">パラメータ</string>
  <string id="Password Changed Successfully.">パスワードが正常に変更されました。</string>
  <string id="Password updated.">パスワードが更新されました。</string>
  <string id="Password*">パスワード*</string>
  <string id="Password:">パスワード:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">各グループのポリシーを使用して、選択したデバイスグループのポリシー更新を実行します。</string>
  <string id="Perform a Policy Update for selected devices.">選択したデバイスのポリシー更新を実行します。</string>
  <string id="Perform a Policy Update for this device group.">このデバイスグループのポリシー更新を実行します。</string>
  <string id="Placeholder">プレースホルダ</string>
  <string id="Please choose a filter:">フィルタを選択してください：</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">定期設定されたスクリプトで、ソリューションのローカルソリューション設定にアクセスできるグループのタイプを選択してください：</string>
  <string id="Please choose a script:">スクリプトを選択してください：</string>
  <string id="Please choose a task to schedule :">定期設定するタスクを選択してください：</string>
  <string id="Please choose an action:">アクションを選択してください：</string>
  <string id="Please choose client groups to schedule :">定期設定するクライアントグループを選択してください：</string>
  <string id="Please choose device groups to schedule :">定期設定するデバイスグループを選択してください：</string>
  <string id="Please choose one of the following options:">以下のオプションのうち、いずれかを選択してください：</string>
  <string id="Please choose solution and script :">ソリューションとスクリプトを選択してください：</string>
  <string id="Please choose solution and script to schedule :">定期設定するソリューションとスクリプトを選択してください：</string>
  <string id="Please choose start time and frequency :">開始時間と頻度を選択してください：</string>
  <string id="Please choose the datasource for the new report.">新しいレポート用にデータソースを選択してください。</string>
  <string id="Please choose the jasper filename for the new report.">新しいレポート用に jasper ファイル名を選択してください。</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">新しいレポート用に jasper ファイル名を選択してください。  jasper レポートが一覧にない場合は、アップロードしてください。</string>
  <string id="Please choose the output format for the new report.">新しいレポート用に出力形式を選択してください。</string>
  <string id="Please choose the report to schedule :">定期設定するレポートを選択してください：</string>
  <string id="Please Contact Lexmark for Software Client License Information.">ソフトウェアクライアントのライセンス情報については、Lexmark にお問い合わせください。</string>
  <string id="Please enter a non-expired date">期限切れでない日付を入力してください（mm/dd/yyyy）。</string>
  <string id="Please enter a valid Address.">有効なアドレスを入力してください。</string>
  <string id="Please enter a valid date">有効な日付を入力してください（mm/dd/yyyy）。</string>
  <string id="Please enter a valid End From Time">有効な終了時刻を入力してください（HH:MM AM/PM）。</string>
  <string id="Please enter a valid End To Time">有効な終了時刻を入力してください（HH:MM AM/PM）。</string>
  <string id="Please enter a valid From date">有効な開始日を入力してください（mm/dd/yyyy）。</string>
  <string id="Please enter a valid From time">有効な開始時刻を入力してください（hh:mm AM/PM）。</string>
  <string id='Please enter a valid range:'>有効な範囲を入力してください：</string>
  <string id="Please enter a valid range: 1 - 12">有効な範囲を入力してください： 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">有効な範囲を入力してください： 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">有効な範囲を入力してください： 1 - 59</string>
  <string id="Please enter a valid Start From Time">有効な開始時刻を入力してください（HH:MM AM/PM）。</string>
  <string id="Please enter a valid Start To Time">有効な開始時刻を入力してください（HH:MM AM/PM）。</string>
  <string id="Please enter a valid time">有効な時刻を入力してください（HH:MM AM/PM）。</string>
  <string id="Please enter a valid To date">有効な終了日を入力してください（mm/dd/yyyy）。</string>
  <string id="Please enter a valid To time">有効な終了時刻を入力してください（hh:mm AM/PM）。</string>
  <string id="Please enter the Database driver and URL for the external database.">外部データベース用のデータベースドライバおよび URL を入力してください。</string>
  <string id="Please enter the Directory information:">ディレクトリ情報を入力してください：</string>
  <string id="Please enter the location where you want the report to be saved.">レポートを保存する場所を入力してください。</string>
  <string id="Please enter the name of the new report.">新しいレポートの名前を入力してください。</string>
  <string id="Please enter the network share user name and password.">ネットワーク共有のユーザー名とパスワードを入力してください。</string>
  <string id="Please enter the recipients to whom the report will be emailed.">レポートを E メール送信する宛先を入力してください。</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">バックアップと復元に関して必要な情報を入力してください：</string>
  <string id="Please make sure that all the necessary fields are filled in.">必須フィールドがすべて入力されていることを確認してください。</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Cron 表現で 6 または 7 個の値（空白区切り）があることを確認してください。</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Cron 表現で 4 番目または 6 番目のいずれか一方の値が「?」であることを確認してください。</string>
  <string id="Please select a file to upload.">アップロードするファイルを選択してください。</string>
  <string id="Please select a group on the left to modify its task privileges.">グループのタスクの権限を修正するには、左のグループを選択してください。</string>
  <string id="Please select a group to save privileges for.">権限を保存するグループを選択してください。</string>
  <string id="Please select a profile to view its settings.">プロファイルの設定を見るには、プロファイルを選択してください。</string>
  <string id="Please select the Group to delete.">削除するグループを選択してください。</string>
  <string id="Please select the report to delete.">削除するレポートを選択してください。</string>
  <string id="Please select the report to edit.">編集するレポートを選択してください。</string>
  <string id="Please select the report to run.">実行するレポートを選択してください。</string>
  <string id="Please specify a port:">ポートを指定してください：</string>
  <string id="Please Verify MinMax, Length and Required Settings.">最小/最大、長さ、および必須の設定を検証してください。</string>
  <string id="Policy Last Applied">最後に適用されたポリシー</string>
  <string id="Policy Update">ポリシーを更新する必要があります。</string>
  <string id="Policy Update has Completed for...">次のもののポリシー更新が完了しました...</string>
  <string id="Policy Update in Progress for...">次のもののポリシーを更新しています...</string>
  <string id="Policy Update on all effected Device Groups.">影響を受けるすべてのデバイスグループでポリシーを更新する必要があります。</string>
  <string id="Port">ポート</string>
  <string id="Port:">ポート:</string>
  <string id="Present">現在</string>
  <string id="Previous">以前の</string>
  <string id="Print (Default)">印刷（標準設定）</string>
  <string id="Print and Forward">印刷して転送</string>
  <string id="Printer Panel">プリンタパネル</string>
  <string id="Printer Report">Printer Report</string>
  <string id="Privileges">権限</string>
  <string id="Process finished with exit code 0">終了コード 0 で処理が終了しました</string>
  <string id="Profile Filters">プロファイルフィルタ</string>
  <string id="Profile:">プロファイル：</string>
  <string id="Profiles">プロファイル</string>
  <string id="Profiles :">プロファイル：</string>
  <string id="Profiles:">プロファイル：</string>
  <string id="Progress %">進行状況 %</string>
  <string id="Property Tag">プロパティタグ</string>
  <string id="Property Tag:">プロパティタグ：</string>
  <string id="Quality :">品質：</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">繰り返し</string>
  <string id="Refresh">更新</string>
  <string id="Refresh Defaults">標準設定に戻す</string>
  <string id="Regular Expression">正規表現</string>
  <string id="Release Held Faxes">保持された FAX をリリース</string>
  <string id="Remove">削除</string>
  <string id="Remove All">すべて削除</string>
  <string id="Remove from System">システムから削除</string>
  <string id="Remove Server(s)">サーバーを削除</string>
  <string id="RemoveAll">すべて削除</string>
  <string id="Removing selected servers...">選択されたサーバーを削除しています...</string>
  <string id="Repeat this event :">このイベントを繰り返す：</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">置換 - これによっ¦、選択されたボタンが削除され、切り取りされたボタンが代わりに配置されます。</string>
  <string id="Replace Me">置換対象</string>
  <string id="Report">レポート</string>
  <string id="Report by Time">時間別レポート</string>
  <string id="Report Files">レポートファイル</string>
  <string id="Report From">レポート元：</string>
  <string id="Report Name:">レポート名：</string>
  <string id="Report Parameters:">レポートのパラメータ：</string>
  <string id="Report To">レポート先：</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME が正常に生成されました</string>
  <string id="Reporting Period">レポート期間</string>
  <string id="Reports">レポート</string>
  <string id="Reports:">レポート：</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">リクエストがタイムアウトしました。 検索条件を絞り込んで、もう一度実行してください。</string>
  <string id="Required field">必須フィールド</string>
  <string id="Reset">リセット</string>
  <string id="Reset Filter">フィルタをリセット</string>
  <string id="Reset to Default">標準設定にリセット</string>
  <string id="Resolution :">解像度：</string>
  <string id="Return to Original">原稿に戻る</string>
  <string id="Retype New Password:">新しいパスワードを再入力：</string>
  <string id="Retype New Username:">新しいユーザー名を再入力：</string>
  <string id="Run on All Servers">すべてのサーバーで実行</string>
  <string id="Run Report">レポーを実行</string>
  <string id="Running">実行中</string>
  <string id="Running Tasks">実行中­のタスク</string>
  <string id="Running...">実行中...</string>
  <string id="Sat">土曜</string>
  <string id="Save">保存</string>
  <string id="Save Privileges">権限を保存</string>
  <string id="Save Settings">設定を保存</string>
  <string id="Save To">保存先</string>
  <string id="Saving eSF Settings...">eSF 設定を保存しています...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">LDAP 設定を保存しています...</string>
  <string id="Schedule">定期設定</string>
  <string id="Scheduled task createdupdated">スケジュール済みタスクが作成/更新されました</string>
  <string id="Scheduled task deleted">スケジュール済みタスクが削除されました</string>
  <string id="Scheduled tasks for all client groups:">すべてのクライアントグループのスケジュール済みタスク：</string>
  <string id="Scheduled tasks for all device groups:">すべてのデバイスグループのスケジュール済みタスク：</string>
  <string id="Script">スクリプト</string>
  <string id="Script:">スクリプト：</string>
  <string id="Search">検索</string>
  <string id="Search Base:">検索ベース：</string>
  <string id="Search Held Jobs">保留中のジョブを検索</string>
  <string id="Search LDAP for Groups:">グループの LDAP を検索：</string>
  <string id="Searching...">検索中...</string>
  <string id="Second">2 番目</string>
  <string id="Secure Server Communication">セキュリティで保護されたサーバーの通信</string>
  <string id="Secure Server Communication:">セキュリティで保護されたサーバーの通信：</string>
  <string id="Security">セキュリティ</string>
  <string id="Security setting updated.">セキュリティ設定が更新されました。</string>
  <string id="Security setup file updated successfully">セキュリティ設定ファイルは正常に更新されました</string>
  <string id="Security setup file update failed">セキュリティ設定ファイルの更新が失敗しました</string>
  <string id="Select a Group Name:">グループ名を選択：</string>
  <string id="Select a report">レポートを選択</string>
  <string id="Select a script task">スクリプトタスクを選択</string>
  <string id="Select one...">1 つを選択...</string>
  <string id="Select Profile...">プロファイルを選択...</string>
  <string id="Select the group to copy">コピーするグループを選択</string>
  <string id="Sent when any leaf is checked or unchecked, in">leaf がチェックされているかどうかにかかわらず送信されます。</string>
  <string id="Serial Number">シリアル番号</string>
  <string id="Serial Number:">シリアル番号：</string>
  <string id="Server Address">サーバーアドレス</string>
  <string id="Server Address:">サーバーアドレス：</string>
  <string id="Server handling this LMC session">この LMC セッションを処理するサーバー</string>
  <string id="Server is currently offline">サーバーは現在オフラインです</string>
  <string id="Server is not communicating">サーバーは通信していません</string>
  <string id="Server is unlicensed">サーバーはライセンスされていません</string>
  <string id="Server Port:">サーバーポート：</string>
  <string id="Server Report">サーバーレポート</string>
  <string id="Server(s) Error">サーバーエラー</string>
  <string id="Server(s) Offline">サーバーがオフラインです</string>
  <string id="Servers">サーバー</string>
  <string id="Service settings updated">サービス設定が更新されました</string>
  <string id="Services">サービス</string>
  <string id="Set Offline">オフラインに設定</string>
  <string id="Set Online">オンラインに設定</string>
  <string id="Setting selected servers offline...">選択されたサーバーをオフラインにしています...</string>
  <string id="Setting selected servers online...">選択されたサーバーをオンラインにしています...</string>
  <string id="Settings :">設定：</string>
  <string id="Settings:">設定：</string>
  <string id="SFP e-Task">SFP e-Task</string>
  <string id="SFP e-Task home screen updated.">SFP e-Task のホーム画面が更新されました。</string>
  <string id="SFP e-Task2">SFP e-Task2</string>
  <string id="SFP e-Task2 home screen updated.">SFP e-Task2 のホーム画面が更新されました。</string>
  <string id="SFP e-Task2+">SFP e-Task2+</string>
  <string id="SFP e-Task2+ home screen updated.">SFP e-Task2+ のホーム画面が更新されました。</string>
  <string id="SFP e-Task3">SFP e-Task3</string>
  <string id="SFP e-Task3 home screen updated.">SFP e-Task3 のホーム画面が更新されました。</string>
  <string id="SFP e-Task4">SFP e-Task4</string>
  <string id="SFP e-Task4 (7in.)">SFP e-Task4（7 インチ）</string>
  <string id="SFP e-Task4 (7in.) home screen updated.">SFP e-Task4（7 インチ）のホーム画面が更新されました。</string>
  <string id="SFP e-Task4 home screen updated.">SFP e-Task4 のホーム画面が更新されました。</string>
  <string id="SftClientGroup">SftClientGroup</string>
  <string id="SftClientGroups">SftClientGroups</string>
  <string id="Shortcut">ショートカット</string>
  <string id="Shortcut :">ショートカット：</string>
  <string id="Shortcut:">ショートカット：</string>
  <string id="Show Settings">設定を表示</string>
  <string id="Since Last Month">先月から</string>
  <string id="Since Yesterday">昨日から</string>
  <string id="Single Profile">1 つプロファイル</string>
  <string id="SNMP Timeout Retries:">SNMP タイムアウトの再試行：</string>
  <string id="Software Client Group">ソフトウェアクライアントグループ</string>
  <string id="Software Client Group created">ソフトウェア クライアント グループが作成されました。</string>
  <string id="Software Client Group:">ソフトウェアクライアントグループ：</string>
  <string id="Software Client Groups">ソフトウェアクライアントグループ</string>
  <string id="Software Client Report">ソフトウェアクライアントレポート</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">ソリューション</string>
  <string id="Solution deleted from software client group.">ソフトウェア クライアント グループからソリューションが削除されました。</string>
  <string id="Solution deployed to device group">ソリューションがデバイスグループに展開されました</string>
  <string id="Solution deployed to software client group">ソフトウェア クライアント グループにソフトウェアが展開されました</string>
  <string id="Solution Name">ソリューション名</string>
  <string id="Solution Name:">ソリューション名：</string>
  <string id="Solution Report">ソリューションレポート</string>
  <string id="Solution settings updated.">ソリューション設定が更新されました。</string>
  <string id="Solution: Deleting device group deployment...">ソリューション： デバイスグループの展開を削除しています...</string>
  <string id="Solution: Deleting solution from software client group...">ソリューション： ソフトウェア クライアント グループからソリューションを削除しています...</string>
  <string id="Solution: device group deployment deleted.">ソリューション： デバイスグループの展開が削除されました。</string>
  <string id="SOLUTIONINFO">SOLUTIONINFO</string>
  <string id="Solutions">ソリューション</string>
  <string id="Solutions to deploy:">展開するソリューション：</string>
  <string id="Solutions:">ソリューション：</string>
  <string id='Specify Restore system information'>復元システムの情報を指定</string>
  <string id="Specify where the generated report should be saved">生成されたレポートの保存を指定</string>
  <string id="Start Button Default Action">スタートボタンの標準設定アクション</string>
  <string id="Start Date :">開始日：</string>
  <string id="Start Time">開始時間</string>
  <string id="Start Time:">開始時刻:</string>
  <string id="State">状態</string>
  <string id="Status">ステータス</string>
  <string id="Steps for viewing device information:">デバイス情報を表示する手順：</string>
  <string id="Stop">停止</string>
  <string id="Stop Task">タスクを停止</string>
  <string id="Subform">サブフォーム</string>
  <string id="Subject:">件名：</string>
  <string id="Success">成功</string>
  <string id="Successfully added the group.">グループは正常に追加されました。</string>
  <string id="Successfully Deleted All Solution(s) from the System.">システムからすべてのソリューションを正常に削除しました。</string>
  <string id="Successfully Deleted Solution(s) from the System.">システムからソリューションを正常に削除しました。</string>
  <string id="Successfully Imported Solution(s) into the System.">システムにソリューションを正常にインポートしました。</string>
  <string id="Summary">概要</string>
  <string id="Sun">日曜</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">スイッチ - これによって、選択されたボタンと切り取りされたボタンの位置が入れ換わります。</string>
  <string id="System">システム</string>
  <string id="System Health...">システムヘルス...</string>
  <string id="System Status">システムステータス</string>
  <string id="System Status 1">システムステータス 1</string>
  <string id="Task Id">タスク ID</string>
  <string id="Task Id:">タスク ID：</string>
  <string id="Task Name">タスク名</string>
  <string id="Task Name:">タスク名：</string>
  <string id="Task Summary Report">タスク概要レポート</string>
  <string id="Test Progress">テストの進行状況</string>
  <string id="Test Results">テスト結果</string>
  <string id="Test Settings">テストの設定</string>
  <string id="Testing LDAP Settings...">LDAP 設定をテストしています...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">最初の画面のボタンは、配置をカスタマイズできます。</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">次のレポートが正常に生成されました：REPORT_NAME。  添付のレポートを確認してください。</string>
  <string id="The password provided is incorrect.">入力されたパスワードは間違っています。</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">このグループのポリシーは、現在グループのすべてのデバイスで展開解除されています。</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">レポートをダウンロードする用意ができました。 続行するには［OK］をクリックしてください。</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">レポート期間の終了日が開始日より前の日付になっています。  システムは、この 2 つを自動的に入れ換えてレポートを生成します。  続行しますか？</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">現在、このソフトウェア クライアント グループのクライアントプロファイルはありません。 上記のフィールドに入力して、それらを追加してください。</string>
  <string id="There are currently no cSF Apps associated with this device group.">現在、このデバイスグループに関連付けられた cSF アプリはありません。</string>
  <string id="There are currently no cSF Apps to add to this device group.">現在、このデバイスグループに追加された cSF アプリはありません。</string>
  <string id="There are currently no device groups to perform discovery.">現在、検出を実行するデバイスグループはありません。</string>
  <string id='There are currently no device groups to perform policy update.'>現在、ポリシー更新を実行するデバイスグループはありません。</string>  
  <string id="There are currently no device groups to schedule.">現在、スケジュールするデバイスグループはありません。</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>現在、デバイスグループがありません。  左の［追加］ボタンをクリックしてデバイスグループを追加してください。</string>
  <string id="There are currently no devices discovered for this device group.">現在、このデバイスグループで検出されたデバイスはありません。</string>
  <string id="There are currently no devices in this device group.">現在、このデバイスグループにデバイスはありません。</string>
  <string id="There are currently no discovered devices.">現在、検出されたデバイスはありません。</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">現在、このデバイスグループの検索プロファイルはありません。 上記の適切なフィールドに入力して、それらを追加してください。</string>
  <string id="There are currently no forms printers in the system.">現在、システムにフォームプリンタはありません。</string>
  <string id="There are currently no licenses installed.">現在、インストールされているライセンスはありません。</string>
  <string id="There are currently no licensing changes made by this upload.">現在、このアップロードで変更されるライセンスはありません。</string>
  <string id="There are currently no missing devices for this device group.">現在、このデバイスグループで不明デバイスはありません。</string>
  <string id="There are currently no missing devices.">現在、不明デバイスはありません。</string>
  <string id="There are currently no out of policy devices for this device group.">現在、このデバイスグループでポリシー外のデバイスはありません。</string>
  <string id="There are currently no out of policy devices.">現在、ポリシー外のデバイスはありません。</string>
  <string id="There are currently no scheduled tasks">現在、スケジュール済みタスクはありません</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">現在、ソフトウェア クライアント グループはありません。  左の［追加］ボタンをクリックしてグループを追加してください。</string>
  <string id="There are currently no solutions associated with this device group.">現在、このデバイスグループに関連付けられたソリューションはありません。</string>
  <string id="There are currently no solutions associated with this software client group.">現在、このソフトウェア クライアント グループに関連付けられたソリューションはありません。</string>
  <string id="There are currently no solutions installed.">現在、インストールされているソリューションはありません。</string>
  <string id='There are currently no solutions to add to this device group.'>現在、このデバイスグループに追加するソリューションはありません。</string>
  <string id="There are currently no solutions to add to this software client group.">現在、このソフトウェア クライアント グループに追加されたソリューションはありません。</string>
  <string id="There are currently no unlicensed devices for this device group.">現在、このデバイスグループで未ライセンスのデバイスはありません。</string>
  <string id="There are currently no unlicensed devices in this device group.">現在、このデバイスグループに、未ライセンスのデバイスはありません。</string>
  <string id="There are currently no unlicensed devices.">現在、未ライセンスのデバイスはありません。</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">現在、このグループのポリシーと関連付けられたソリューション、または cSF アプリおよび/またはホーム画面があります。 このポリシーを今すぐ展開解除しますか？ 展開解除しても、デバイスグループが直ちに削除されることはありません。 ポリシー更新が完了したら、デバイスグループを削除してください。</string>
  <string id="There are no associated UCF Files for this Solution.">このソリューションには、関連付けられたセキュリティ設定ファイルはありません。</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">現在、このデバイスグループのソリューションには、関連付けられたセキュリティ設定ファイルはありません。</string>
  <string id="There are no configuration settings for this eSF application.">この eSF アプリケーションの構成設定がありません。</string>
  <string id="There are no configuration settings in this solution.">このソリューションの構成設定がありません。</string>
  <string id="There are no configuration settings in this webapp.">この WebApps の構成設定がありません。</string>
  <string id="There are no cSF Apps installed currently.">現在、インストールされている cSF アプリはありません。</string>
  <string id="There are no deployments setting for this solution.">このソリューションの展開設定がありません。</string>
  <string id="There are no devices in the system that match the filter.">システムには、フィルタに一致するデバイスはありません。</string>
  <string id="There are no eSF Applications for this solution.">このソリューションの eSF アプリケーションはありません。</string>
  <string id="There are no e-Task profiles for this device group.">このデバイスグループの e-Task プロファイルはありません。</string>
  <string id="There are no e-Task2 profiles for this device group.">このデバイスグループの e-Task2 プロファイルはありません。</string>
  <string id="There are no forms for this solution.">このソリューションのフォームはありません。</string>
  <string id="There are no forms in the system.">システムにフォームはありません。</string>
  <string id="There are no parameters in this service.">このサービスのパラメータがありません。</string>
  <string id="There are no profiles for this software client group.">このソフトウェア クライアント グループのプロファイルはありません。</string>
  <string id="There are no settings for this action.">このアクションの設定がありません。</string>
  <string id="There are no settings for this solution.">このソリューションの設定がありません。</string>
  <string id="There is currently a Policy Update running...">現在、ポリシー更新を実行しています...</string>
  <string id="There is currently no Version Info.">現在、バージョン情報はありません。</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">これらの eSF アプリケーションは、このデバイスグループと関連付けられたソリューションの一部です。アプリケーションの設定を見るには、アプリケーションを選択してください。</string>
  <string id="These group settings are currently hidden.">これらのグループ設定は現在非表示です。</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">このプロファイルは各機種のグループポリシーの一部です。設定を見るには各機種のプロファイルを選択してください。</string>
  <string id="Third">3 番目</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">このリンクをクリックすると、Lexmark の Webkit 設定ユーザーインターフェイスにアクセスします。続行しますか？</string>
  <string id="This Month">今月</string>
  <string id="This name has been given to another device group. Please choose a different name.">この名前は別のデバイスグループに与えられています。他の名前を選択してください。</string>
  <string id="This name has been given to another software client group. Please choose a different name.">この名前は別のソフトウェアクライアントグループに与えられています。他の名前を選択してください。</string>
  <string id="Thread Count">スレッド数</string>
  <string id="Thu">木曜</string>
  <string id="Time">時刻</string>
  <string id="Time of Next Run">次の実行の時刻</string>
  <string id="Time Policies Last Applied">最後に適用された時間ポリシー</string>
  <string id="Time:">時刻：</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">ホーム画面に追加するには、上記のドロップダウンボックスから［ユーザー定義］レイアウトを選択してプロファイルを追加します。</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">自分で配置するには、上記のドロップダウンボックスからレイアウトを 1 つ選択します。</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">自分で設定するには、上記のドロップダウンボックスからレイアウトを 1 つ選択します。</string>
  <string id="To:">送信先：</string>
  <string id="Today">今日</string>
  <string id="Today date">今日の日付</string>
  <string id="Tops Report">トップ（最上位）レポート</string>
  <string id="Tue">火曜</string>
  <string id="UCF">セキュリティ設定ファイル</string>
  <string id="UCF:">セキュリティ設定ファイル:</string>  
  <string id="Unable to Change Password.">パスワードを変更できません。</string>
  <string id="Unable to Change Username.">ユーザー名を変更できません。</string>
  <string id="Unable to validate all settings!">検証できない設定があります。</string>
  <string id="Uncounted">数えられていません</string>
  <string id="Un-deploying all cSF Apps(s)...">すべての cSF アプリを展開解除しています...</string>
  <string id="Un-deploying cSF App(s)...">cSF アプリを展開解除しています...</string>
  <string id="Unknown">不明</string>
  <string id="Unknown Error Occured! Please Check System Log">不明なエラーが発生しました。 システムログを確認してください</string>
  <string id='Unknown Secure State'>不明なセキュリティ状態</string>
  <string id="Unlicensed">未ライセンス</string>
  <string id="Unlicensed Device">未ライセンスのデバイス</string>
  <string id="Unlicensed Devices">未ライセンスのデバイス</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">未ライセンスのデバイスとは、検出されているが、一番最後の検出中にライセンスを割り当てることができなかったデバイスのことです。（例：ライセンスの期限切れ、または、すべてのライセンスが使用中）</string>
  <string id="Unlicensed devices:">未ライセンスのデバイス：</string>
  <string id="Unlicensed Devices:">未ライセンスのデバイス：</string>
  <string id="Unlicensed:">未ライセンス：</string>
  <string id="Unlimited">無制限</string>
  <string id="Up icon:">［アップ］アイコン：</string>
  <string id="Update">更新</string>
  <string id="Update Policy">ポリシーを更新</string>
  <string id="Update Time">更新時刻</string>
  <string id="Update Time:">更新時間：</string>
  <string id="Updating client profile...">クライアントプロファイルを更新しています...</string>
  <string id="Updating discovery profile...">検索プロファイルを更新しています...</string>
  <string id="Updating e-Task home screen...">e-Task のホーム画面を更新しています...</string>
  <string id="Updating e-Task2 home screen...">e-Task2 のホーム画面を更新しています...</string>
  <string id="Updating e-Task2+ home screen...">e-Task2+ のホーム画面を更新しています...</string>
  <string id="Updating e-Task3 home screen...">e-Task3 のホーム画面を更新しています...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">e-Task4（4.3 インチ）のホーム画面を更新しています...</string>
  <string id="Updating e-Task4 home screen...">e-Task4 のホーム画面を更新しています...</string>
  <string id="Updating Fax Forward settings...">FAX 転送設定を更新しています...</string>
  <string id="Updating password...">パスワードを更新しています...</string>
  <string id="Updating Security setting...">セキュリティ設定を更新しています...</string>
  <string id="Updating service settings...">サービス設定を更新しています...</string>
  <string id="Updating SFP e-Task home screen...">SFP e-Task のホーム画面を更新しています...</string>
  <string id="Updating SFP e-Task2 home screen...">SFP e-Task2 のホーム画面を更新しています...</string>
  <string id="Updating SFP e-Task2+ home screen...">SFP e-Task2+ のホーム画面を更新しています...</string>
  <string id="Updating SFP e-Task3 home screen...">SFP e-Task3 のホーム画面を更新しています...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen...">SFP e-Task4（7 インチ）のホーム画面を更新しています...</string>
  <string id="Updating SFP e-Task4 home screen...">SFP e-Task4 のホーム画面を更新しています...</string>
  <string id="Updating solution settings...">ソリューション設定を更新しています...</string>
  <string id="Updating username...">ユーザー名を更新しています...</string>
  <string id="Updating X642 home screen...">X642 のホーム画面を更新しています...</string>
  <string id='Updating webapp settings...'>Web アプリの設定を更新しています...</string>
  <string id="Upgrading or deleting solutions here will require">ここでソリューションをアップグレードまたは削除するには、</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">ここで cSF アプリをアップグレードまたは展開解除すると、影響を受けるすべてのデバイスグループで&lt;b&gt;ポリシーを更新&lt;/b&gt;する必要があります。</string>
  <string id="Upload">アップロード</string>
  <string id="Upload custom icons">ユーザー定義アイコンをアップロード</string>
  <string id="Upload Report Files">レポートファイルのアップロード</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">AP バンドルおよび記述子のアップロードが完了しました。</string>
  <string id="Uploading AP Bundle and Descriptor...">AP バンドルおよび記述子をアップロードしています...</string>
  <string id="Uploading cSF Ap cert files....">cSF アプリ証明書ファイルをアップロードしています...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">cSF アプリ証明書ファイル（cacert.pem、key.pem）をアップロードしています...</string>
  <string id="Uploading of cSF App cert files Completed.">cSF アプリ証明書ファイルのアップロードが完了しました。</string>
  <string id="Uploading Report(s)...">レポートをアップロードしています...</string>
  <string id="Uploading...">アップロード中...</string>
  <string id="Usage:">使用量：</string>
  <string id="Usb Drive">USB ドライブ</string>
  <string id="Use default settings">標準設定を使用</string>
  <string id="Use Secure Connection. (SSLTLS)">セキュリティで保護された接続を使用します。 （SSL/TLS）</string>
  <string id="Use Solution Configuration">ソリューション構成を使用</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">データベース（既存の Lexmark Document Distributor（LDD）システムの中央 WebDAV データ）を、「バックアップ LDD システム」として動作する別のアクティブな LDD システムと同期させる必要がある場合にのみ、このダイアログを使用してください。 この機能の詳細については、『管理者ガイド』を参照してください。</string>  
  <string id="Use this home screen as part of the device groups policy.">このホーム画面をデバイスグループポリシーの一部として使用します。</string>
  <string id='Used:'>使用済み：</string>
  <string id="User Name">ユーザー名</string>
  <string id="User Name:">ユーザー名：</string>
  <string id="User Report">ユーザーレポート</string>
  <string id="User Search Base:">ユーザー検索ベース：</string>
  <string id="User Search Filter:">ユーザー検索フィルタ：</string>
  <string id="Username amp; Password">ユーザー名とパスワード</string>
  <string id="Username and Password">ユーザー名とパスワード</string>
  <string id="Username Changed Successfully.">ユーザー名が正常に変更されました。</string>
  <string id="Username Password">ユーザー名とパスワード</string>
  <string id="Username updated.">ユーザー名が更新されました。</string>
  <string id="Username*">ユーザー名*</string>
  <string id="Username:">ユーザー名:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">eSF アプリケーションの展開を検証し、これら eSF 設定を展開します。</string>
  <string id="Version">バージョン</string>
  <string id="Version Info:">バージョン情報：</string>
  <string id="Version:">バージョン：</string>
  <string id="VersionInfo">バージョン情報</string>
  <string id="Very very very long long long text">非常に長いテキスト</string>
  <string id="View Details">詳細表示</string>
  <string id="View Source">ソースを表示</string>
  <string id="Waiting for License Upload Results ...">ライセンスアップロードの結果を待っています...</string>
  <string id="WebApps">Web アプリ</string>
  <string id="WebClient Version">WebClient バージョン</string>
  <string id="WebClient Version:">WebClient バージョン：</string>
  <string id="Wed">水曜</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated.">X642 のホーム画面が更新されました。</string>
  <string id="Yes">はい</string>
  <string id="You are viewing the Kranked version of the application">アプリケーションの Kranked バージョンを表示しています。</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">すべての cSF アプリのどのタスクにもアクセスする権限がありません</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">すべてのデバイスグループのどのタスクにもアクセスする権限がありません。</string>
  <string id="You have no privilege to this task.">このタスクに対する権限がありません。</string>
  <string id="You must first select a Task to Edit">まず編集するタスクを選択する必要があります。</string>
  <string id="active">アクティブ</string>
  <string id="active:">アクティブ：</string>
  <string id="addition to the two events below.">以下の 2 つのイベントに加え、</string>
  <string id="avg response (ms)">平均応答時間（ms）</string>
  <string id="be set back to the default values next time.">次回には標準設定の値に戻ります。</string>
  <string id="cache">キャッシュ</string>
  <string id="cc:">cc:</string>
  <string id="change">変更</string>
  <string id="cSF App">cSF アプリ</string>
  <string id="cSF App Cert File">cSF アプリ証明書ファイル</string>
  <string id="cSF App Certificates">cSF アプリ証明書</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">cSF アプリ証明書（cacert.pem、key.pem）のアップロード</string>
  <string id="cSF App Key File">cSF アプリのキーファイル</string>
  <string id="cSF App settings updated.">cSF アプリ設定が更新されました。</string>
  <string id="cSF App Version">cSF アプリのバージョン</string>
  <string id="cSF App Version:">cSF アプリのバージョン：</string>
  <string id="cSF Apps">cSF アプリケーション</string>
  <string id="cSF Apps deployed to device group">cSF アプリがデバイスグループに展開されました</string>
  <string id="cSF Apps to deploy:">展開する cSF アプリ：</string>
  <string id="cSF Apps: Device group deployment deleted.">cSF アプリ： デバイスグループの展開が削除されました。</string>
  <string id="day(s)">日</string>
  <string id="devices failed">デバイスが失敗しました</string>
  <string id="devices updated">デバイスが更新されました</string>
  <string id="device(s) missing">デバイスがありません</string>
  <string id="device(s) discovered">デバイスが検出されました</string>
  <string id="disk-in-use=">使用中のディスク=</string>
  <string id="disk-total=">ディスク合計=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">eSF アプリケーション設定：</string>
  <string id="eSF Application Version:">eSF アプリケーションのバージョン：</string>
  <string id="eSF Applications">eSF アプリケーション</string>
  <string id="eSF Applications:">eSF アプリケーション：</string>
  <string id="eSF Applications: (Solution)">eSF アプリケーション：（ソリューション）</string>
  <string id="eSF Configuration">eSF 設定</string>
  <string id="eSF Settings Saved.">eSF 設定が保存されました。</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">e-Task のホーム画面が更新されました。</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated.">e-Task2 のホーム画面が更新されました。</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated.">e-Task2+ のホーム画面が更新されました。</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated.">e-Task3 のホーム画面が更新されました。</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4（4.3 インチ）</string>
  <string id="e-Task4 (4.3 in.) home screen updated.">e-Task4（4.3 インチ）のホーム画面が更新されました。</string>
  <string id="e-Task4 home screen updated.">e-Task4 のホーム画面が更新されました。</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">失敗しました。</string>
  <string id="hide">非表示</string>
  <string id="hour(s)">時間</string>
  <string id="in order to add a group.">グループを追加するために。</string>
  <string id="info">情報</string>
  <string id="load">読み込む</string>
  <string id="mem-in-use=">使用中のメモリ=</string>
  <string id="mem-total=">メモリ合計=</string>
  <string id="min(s)">分</string>
  <string id="month(s)">月</string>
  <string id="not communicating">通信していません</string>
  <string id="null">ヌル</string>
  <string id="offline">オフライン</string>
  <string id="on">の or で</string>
  <string id="on all effected Device Groups.">影響を受けるすべてのデバイスグループで</string>
  <string id="oncheck">oncheck</string>
  <string id="online">オンライン</string>
  <string id="or home screen support for this device does not exist.">このデバイス用のホーム画面サポートはありません。</string>
  <string id="requests">要求</string>
  <string id="requests/sec">要求/秒</string>
  <string id="saving report...">レポートを保存しています...</string>
  <string id="server">サーバー</string>
  <string id="show">表示</string>
  <string id="test">テスト</string>
  <string id="to">～</string>
  <string id="to change them.">それらを変更することは</string>
  <string id="to take effect on the devices.">デバイスに適用することは</string>
  <string id="total requests:">要求合計：</string>
  <string id="total responses:">応答合計：</string>
  <string id="undo">取り消し</string>
  <string id="uploaded.">アップロードされました。</string>
  <string id="week(s)">週</string>
  <string id="{0} Groups">{0} グループ</string>
  <string id="{0} Reports">{0} レポート</string>
  <string id="{0} Software Client Groups">{0} ソフトウェア クライアント グループ</string>
  <string id="{0} Solutions">{0} ソリューション</string>
  <string id="{0} eForms">{0} Eフォーム</string>
  <string id="{0} eSF Applications">{0} eSF アプリケーション</string>
  <string id="Policy update required for changes to take effect on the devices">ここで変更した内容をデバイスに適用するには、&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;ポリシーの更新が必要です。&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;</string>
  <string id="Group search base must be set for adding group based Privileges">グループベースの&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;権限&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;を追加するには、グループ検索ベースを設定する必要があります</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">グループを追加するには、&lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;LDAP 設定&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;でグループ検索ベースを設定する必要があります。</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">SMB ライセンス版インストール! MFP ライセンスは、最大</string>
  <string id="licenses!">ライセンスまでです!</string>
</localize>
`;