export const ES = `<localize>
  <string id="% Completed">% completado</string>
  <string id="% Completed:">% Completado:</string>
  <string id="&lt;u&gt;VersionInfo&lt;u&gt;">&lt;u&gt;VersionInfo&lt;u&gt;</string>
  <string id="( Optional ) Please type in a description">Escriba una descripción (opcional)</string>
  <string id="( Username must be a Distinguished Name )">(El nombre de usuario debe ser un nombre distintivo)</string>
  <string id="(1-999)">(1-999)</string>
  <string id="(Cron expression)">(Expresión CRON)</string>
  <string id="(progress)">(progreso)</string>
  <string id="* Software Client License Not Found.">* No se encontró la licencia de cliente de software.</string>
  <string id="[EXTERNAL]">[EXTERNO]</string>
  <string id="[None]">[Ninguno]</string>
  <string id="1 Button">1 botón</string>
  <string id="1 minute load">1 minuto de carga</string>
  <string id="1. cSF Apps">1. Aplicaciones cSF</string>
  <string id="1. Device Groups">1. Grupos de dispositivos</string>
  <string id="1. Search">1. Buscar</string>
  <string id="1. Services">1. Servicios</string>
  <string id="1. Software Client Groups">1. Grupos de clientes de software</string>
  <string id="1. Solutions">1. Soluciones</string>
  <string id="1. Type in the search criteria and click the &quot;Search&quot; button.">1. Escriba los criterios de búsqueda y haga clic en el botón &quot;Buscar&quot;.</string>
  <string id="1. WebApps">1. Aplicaciones web</string>
  <string id="10 Buttons">10 botones</string>
  <string id="15 minute load">15 minutos de carga</string>
  <string id="15sec">15 seg.</string>
  <string id="2 Buttons">2 botones</string>
  <string id="2. Choose one or more devices if any are found.">2. Seleccione uno o varios dispositivos si se encuentra alguno.</string>
  <string id="2. Devices">2. Dispositivos</string>
  <string id="2. Tasks">2. Tareas</string>
  <string id="3 Buttons">3 botones</string>
  <string id="3. Choose a Task.">3. Seleccione una tarea.</string>
  <string id="3. Tasks">3. Tareas</string>
  <string id="30sec">30 seg.</string>
  <string id="4 Buttons">4 botones</string>
  <string id="4-16 Buttons">4-16 botones</string>
  <string id="5 Buttons">5 botones</string>
  <string id="5 minute load">5 minutos de carga</string>
  <string id="5sec">5 seg.</string>
  <string id="6 Buttons">6 botones</string>
  <string id="60sec">60 seg.</string>
  <string id="7 Buttons">7 botones</string>
  <string id="8 Buttons">8 botones</string>
  <string id="9 Buttons">9 botones</string>
  <string id="A Policy Update is currently running...">En este momento se está ejecutando una actualización de políticas...</string>
  <string id="About">Acerca de</string>
  <string id="Action">Acción</string>
  <string id="Action Settings...">Valores de acción...</string>
  <string id="Action Settings:">Valores de acción:</string>
  <string id="Action:">Acción:</string>
  <string id="Add">Agregar</string>
  <string id="Add a cSF App to deploy:">Añada una aplicación cSF para su implementación:</string>
  <string id="Add a new Group to the system">Añadir un nuevo grupo al sistema</string>
  <string id="Add a new report to the system">Añadir un nuevo informe al sistema</string>
  <string id="Add a solution to deploy: Step 1 of 2">Añada una solución para su implementación: Paso 1 de 2</string>
  <string id="Add a solution to deploy: Step 2 of 2">Añada una solución para su implementación: Paso 2 de 2</string>
  <string id="Add a solution: Step 1 of 2">Añada una solución: Paso 1 de 2</string>
  <string id="Add a solution: Step 2 of 2">Añada una solución: Paso 2 de 2</string>
  <string id="Add a task to Schedule : Step 1 of 3">Agregue la tarea que desee programar: Paso 1 de 3</string>
  <string id="Add Device Group">Agregar grupo de dispositivos</string>
  <string id="Add Device Groups to Schedule : Step 2 of 3">Agregue los grupos de dispositivos que desee programar: Paso 2 de 3</string>
  <string id="Add Forms Printer">Añadir Forms Printer</string>
  <string id="Add License">Agregar licencia</string>
  <string id="Add Software Client Group">Agregar grupo de clientes de software</string>
  <string id="Add the frequency to Schedule : Step 3 of 3">Agregue la frecuencia que desee programar: Paso 3 de 3</string>
  <string id="Add...">Agregar...</string>
  <string id="Adding Formset(s)...">Añadiendo formsets...</string>
  <string id="Adding Group Name from LDAP...">Añadiendo nombre de grupo de LDAP...</string>
  <string id="Adding solution to software client group...">Añadiendo solución al grupo de clientes de software...</string>
  <string id="Additional Options">Opciones adicionales</string>
  <string id="Additional Parameters">Parámetros adicionales</string>
  <string id="Additional Parameters...">Parámetros adicionales...</string>
  <string id="Additional Report Parameters">Parámetros del informe adicionales</string>
  <string id="Address">Dirección</string>
  <string id="Address:">Dirección:</string>
  <string id="Admin password:">Contraseña de Admin:</string>
  <string id="All">Todos</string>
  <string id="All cSF Apps">Todas las aplicaciones cSF</string>
  <string id="All Device Groups">Todos los grupos de dispositivos</string>
  <string id="All scheduled tasks for the system.">Todas las tareas programadas del sistema.</string>
  <string id="All scheduled tasks for this device group:">Todas las tareas para este grupo de dispositivos:</string>
  <string id="All scheduled tasks for this sftClient group">Todas las tareas programadas para este grupo sftClient</string>
  <string id="All selected devices will be completely removed from the system. Are you sure you want to remove these devices?">Todos los dispositivos seleccionados se eliminarán por completo del sistema. ¿Seguro de que desea eliminar estos dispositivos?</string>
  <string id="All Servers Offline">Todos los servidores sin conexión</string>
  <string id="All Servers Online">Todos los servidores en línea</string>
  <string id="All Software Client Groups">Todos los grupos de clientes de software</string>
  <string id="All Solutions">Todas las soluciones</string>
  <string id="All Tabs">Todas las fichas</string>
  <string id="An error occurred while attempting to connect to this device,">Error al intentar conectar con este dispositivo,</string>
  <string id="Anonymous">Anónimo</string>
  <string id="Any changes here will require">Todos los cambios que se realicen aquí requerirán</string>
  <string id="Any Changes to the parameters are temporary and will">Todos los cambios en los parámetros son temporales y</string>
  <string id="Any Changes to the parameters are temporary and will be set back to the default values next time.">Todos los cambios en los parámetros son temporales y se restablecerán los valores predeterminados la próxima vez.</string>
  <string id="AP (Advanced Prompting) Bundle Upload">Actualización del paquete de AP (Advanced Prompting)</string>
  <string id="AP Bundle">Paquete de AP</string>
  <string id="AP Bundle Application File">Archivo de aplicación del paquete de AP</string>
  <string id="AP Bundle descriptor">Descriptor del paquete de AP</string>
  <string id="AP Bundle Descriptor File">Archivo descriptor del paquete de AP</string>
  <string id="App Reservation">Reserva de aplicaciones</string>
  <string id="Application">Aplicación</string>
  <string id="Apply">Aplicar</string>
  <string id="Are you sure you want to change the edited profile?">¿Seguro de que desea cambiar el perfil editado?</string>
  <string id="Are you sure you want to change these profiles?">¿Seguro de que desea cambiar estos perfiles?</string>
  <string id="Are you sure you want to delete all the forms?">¿Seguro que desea eliminar todos los formularios?</string>
  <string id="Are you sure you want to delete all the profiles?">¿Seguro que desea eliminar todos los perfiles?</string>
  <string id="Are you sure you want to delete all the solutions?">¿Seguro que desea eliminar todas las soluciones?</string>
  <string id="Are you sure you want to delete the selected forms?">¿Seguro que desea eliminar los formularios seleccionados?</string>
  <string id="Are you sure you want to delete the selected group?  Any privilege associated with  this group will automatically be deleted as well.">¿Seguro que desea eliminar el grupo seleccionado?  Cualquier privilegio asociado con este grupo también será eliminado automáticamente.</string>
  <string id="Are you sure you want to delete the selected profiles?">¿Seguro que desea eliminar los perfiles seleccionados?</string>
  <string id="Are you sure you want to delete the selected report?  Any scheduled report tasks for this report will automatically be deleted as well.">¿Seguro que desea eliminar el informe seleccionado?  Cualquier tarea de informe programado para este informe también será eliminada automáticamente.</string>
  <string id="Are you sure you want to delete the selected solutions?">¿Seguro que desea eliminar las soluciones seleccionadas?</string>
  <string id="Are you sure you want to delete these profiles?">¿Seguro de que desea eliminar estos perfiles?</string>
  <string id="Are you sure you want to un-deploy all cSF Apps?">¿Seguro que desea eliminar la implementación de todas las aplicaciones cSF?</string>
  <string id="Are you sure you want to un-deploy the selected cSF App(s)?">¿Seguro que desea eliminar la implementación de las aplicaciones cSF seleccionadas?</string>
  <string id="Are you sure you would like to delete this +webAppsString.getWebAppString()+?}">¿Seguro que desea eliminar este/a +webAppsString.getWebAppString()+?}</string>
  <string id="Are you sure you would like to delete this Device Group?">¿Seguro que desea eliminar este grupo de dispositivos?</string>
  <string id="Are you sure you would like to delete this forms printer?">¿Seguro que desea eliminar esta impresora de formularios?</string>
  <string id="Are you sure you would like to delete this scheduled task?">¿Seguro que desea eliminar esta tarea programada?</string>
  <string id="Are you sure you would like to delete this software client Group?">¿Seguro que desea eliminar este grupo de clientes de software?</string>
  <string id="Are you sure you would like to delete this solution?">¿Seguro que desea eliminar esta solución?</string>
  <string id="Associated Device Group :">Grupo de dispositivos asociado:</string>
  <string id="Associated Solution :">Solución asociada:</string>
  <string id="Associated Solution:">Solución asociada:</string>
  <string id="Authentication Method:">Método de autenticación:</string>
  <string id="Author">Autor</string>
  <string id="Auto Refresh:">Actualización automática:</string>
  <string id="Available Columns">Columnas disponibles</string>
  <string id="Available Reports">Informes disponibles</string>
  <string id="Back">Atrás</string>
  <string id="Background Image:">Imagen de fondo:</string>
  <string id="Backup &amp; Restore information">Información de copia de seguridad y restauración</string>
  <string id="Backup amp; Restore">Copia de seguridad y restaurar</string>
  <string id="Backup Jobs Logs Database">Base de datos de registros de trabajos de copias de seguridad</string>
  <string id="Backup Share Path">Ruta de uso compartido de copia de seguridad</string>
  <string id="Bar Chart">Gráfico de barras</string>
  <string id="Binary Files">Archivos binarios</string>
  <string id="Bookmarks">Marcadores</string>
  <string id="Both the cacert.pem and key.pem files are required to update cSF App certificates.">Los archivos cacert.pem y key.pem son necesarios para actualizar los certificados de aplicaciones cSF.</string>
  <string id="Both the eSF flash and descriptor files are required to update the AP bundle.">Los archivos descriptores y flash de eSF son necesarios para actualizar el paquete de AP.</string>
  <string id="Browse">Examinar</string>
  <string id="Browse...">Examinar...</string>
  <string id="By default, the MFP automatically arranges the buttons on the Home Screen.">De forma predeterminada, la impresora multifunción ordena automáticamente los botones de la pantalla de inicio.</string>
  <string id="By default, the SFP adds the profiles to the Held jobs folder.">De forma predeterminada, la impresora monofunción añade los perfiles a la carpeta Trabajos en espera.</string>
  <string id="Cancel">Cancelar</string>
  <string id="Canceled">Cancelado</string>
  <string id="Canceling...">Cancelando...</string>
  <string id="Change Default Values">Cambiar valores predeterminados</string>
  <string id="Change Language">Cambiar idioma</string>
  <string id="Change Password">Cambiar contraseña</string>
  <string id="Change Username">Cambiar nombre de usuario</string>
  <string id="Changing name...">Cambiando nombre...</string>
  <string id="Choose a cSF App to deploy:">Seleccione una aplicación cSF para su implementación:</string>
  <string id="Choose a solution to deploy:">Seleccione la solución que se va a implementar:</string>
  <string id="Choose a solution:">Seleccione una solución:</string>
  <string id="Choose Client Groups">Seleccionar grupos de clientes</string>
  <string id="Choose deployment settings for">Seleccione los valores de implementación para</string>
  <string id="Choose Device Groups">Seleccione los grupos de dispositivos</string>
  <string id="Choose each button and set its action. Buttons with no actions will not appear on the Home Screen.">Seleccione cada botón y establezca su acción. Los botones que no tengan acciones no aparecerán en la pantalla de inicio.</string>
  <string id="Choose one...">Seleccione uno...</string>
  <string id="Choose task">Seleccione la tarea</string>
  <string id="Choose the frequency">Seleccione la frecuencia</string>
  <string id="Choose the group type">Seleccione el tipo de grupo</string>
  <string id="Class">Clase</string>
  <string id="Click">Haga clic</string>
  <string id="Click Add to create a Home screen button.">Haga clic en Agregar para crear un botón Pantalla de inicio.</string>
  <string id="Click on checkboxes to select or deselect privileges.">Haga clic en las casillas de verificación para seleccionar privilegios o anular su selección.</string>
  <string id="Click on the square, then release the mouse button to select a new color.">Haga clic en el cuadrado y suelte el botón del ratón para seleccionar un color nuevo.</string>
  <string id="Client Groups:">Grupos de clientes:</string>
  <string id="Client Profile created.">Se ha creado el perfil de cliente.</string>
  <string id="Client Profiles">Perfiles de clientes</string>
  <string id="Close">Cerrar</string>
  <string id="Color :">Color:</string>
  <string id="Column Chart.">Gráfico de columnas</string>
  <string id="Compile">Compilar</string>
  <string id="Compile Options:">Opciones de compilación:</string>
  <string id="Completed">Completado</string>
  <string id="Components">Componentes</string>
  <string id="Config Service">Servicio de configuración</string>
  <string id="Configuration">Configuración</string>
  <string id="Configuration:">Configuración:</string>
  <string id="Configurations for this discovery:">Configuraciones de esta detección:</string>
  <string id="Connect To App">Conectar con la aplicación</string>
  <string id="Connected to the target VM, address: 127.0.0.1:61023, transport: socket">Conectado con la VM de destino, dirección: 127.0.0.1:61023, transporte: socket</string>
  <string id="Connection Timed Out. Please check the server configuration, including firewall settings.">La conexión ha caducado. Compruebe la configuración del servidor, incluidos los valores del cortafuegos.</string>
  <string id="Contact Location">Ubicación de contacto</string>
  <string id="Contact Location:">Ubicación de contacto:</string>
  <string id="Contact Name">Nombre de contacto</string>
  <string id="Contact Name:">Nombre de contacto:</string>
  <string id="Content :">Contenido:</string>
  <string id="Copy">Copiar</string>
  <string id="Copy + Profile">Copiar + perfil</string>
  <string id="Copy Shortcuts">Métodos abreviados de copia</string>
  <string id="CPU Usage">Uso de la CPU</string>
  <string id="Creating client profile...">Creando perfil de cliente...</string>
  <string id="Creating device group...">Creando grupo de dispositivos...</string>
  <string id="Creating discovery profile...">Creando perfil de búsqueda...</string>
  <string id="Creating or updating a forms printer...">Creando o actualizando una impresora de formularios...</string>
  <string id="Creating software client group...">Creando grupo de clientes de software...</string>
  <string id="Creatingupdating the scheduled task...">Creando o actualizando la tarea programada...</string>
  <string id="Cron expression)">(Expresión CRON)</string>
  <string id="CSV">CSV</string>
  <string id="Current Columns">Columnas actuales</string>
  <string id="Current password is incorrect.">La contraseña actual no es correcta.</string>
  <string id="Current Password:">Contraseña actual:</string>
  <string id="Currently discovering Missing Devices...">Detectando los dispositivos que faltan...</string>
  <string id="Currently discovering Unlicensed Devices...">Detectando los dispositivos sin licencia...</string>
  <string id="Custom">Personalizado</string>
  <string id="Custom icons:">Iconos personalizados:</string>
  <string id="Custom...">Personalizado...</string>
  <string id="Customize Jobs Table">Personalizar tabla de trabajos</string>
  <string id="Customize Logs Table">Personalizar tabla de registros</string>
  <string id="Customize Table...">Personalizar tabla...</string>
  <string id="Danger, Will Robinson!">Precaución</string>
  <string id="Darkness :">Intensidad:</string>
  <string id="Database Driver:">Controlador de la base de datos:</string>
  <string id='Database Fully Qualified Hostname OR IpAddress'>Nombre de host completo O dirección IP de la base de datos</string>
  <string id="Database URL:">URL de la base de datos:</string>
  <string id="Datasource:">Origen de datos:</string>
  <string id="Datatype Filter">Filtro de tipos de datos</string>
  <string id="Datatype filter:">Filtro de tipos de datos:</string>
  <string id="Date">Fecha</string>
  <string id="Debug">Depuración</string>
  <string id="Default">Predeterminado</string>
  <string id="Default Group">Grupo predeterminado</string>
  <string id="Default Group can not be deleted.">El grupo predeterminado no puede eliminarse.</string>
  <string id="Default Output Format:">Formato de salida predeterminado:</string>
  <string id="Default: 389">Valor predeterminado: 389</string>
  <string id="Delete">Eliminar</string>
  <string id="Delete file on failure?">¿Desea eliminar el archivo en caso de error?</string>
  <string id="Delete file on success?">¿Desea eliminar el archivo si se realiza correctamente?</string>
  <string id="Deleted device group. One or more devices must now be updated.">Grupo de dispositivos eliminado. Uno o más dispositivos deben actualizarse ahora.</string>
  <string id="Deleted selected FormSet(s).">Formsets seleccionados eliminados.</string>
  <string id="Deleted software client group.">Grupo de clientes de software eliminado.</string>
  <string id="Deleting All FormSet(s)...">Eliminando todos los formsets...</string>
  <string id="Deleting All solution(s)...">Eliminando todas las soluciones...</string>
  <string id="Deleting client profile(s)...">Eliminando perfiles de clientes...</string>
  <string id="Deleting device group...">Eliminando grupo de dispositivos...</string>
  <string id="Deleting discovery profile(s)...">Eliminando perfiles de búsqueda...</string>
  <string id="Deleting forms printer...">Eliminando impresora de formularios...</string>
  <string id="Deleting Formset(s)...">Eliminando formsets...</string>
  <string id="Deleting scheduled task...">Eliminando tarea programada...</string>
  <string id="Deleting selected FormSet(s)...">Eliminando formsets seleccionados...</string>
  <string id="Deleting software client group...">Eliminando grupo de clientes de software...</string>
  <string id="Deleting solution(s)...">Eliminando soluciones...</string>
  <string id="Delta">Delta</string>
  <string id="Deploy to:">Implementar en:</string>
  <string id="Deploy:">Implementar:</string>
  <string id="Deploying home screen to">Implementando pantalla de inicio en</string>
  <string id="Deploying solution to device group...">Implementando solución en grupo de dispositivos...</string>
  <string id="Deploying WAR file:">Implementando archivo WAR: </string>
  <string id="Description">Descripción</string>
  <string id="Description:">Descripción:</string>
  <string id="Descriptor">Descriptor</string>
  <string id="Destination Folder Path">Ruta de la carpeta de destino</string>
  <string id="Developer Forums">Foros de desarrolladores</string>
  <string id="Developer Network">Red de desarrolladores</string>
  <string id="Device Address">Dirección del dispositivo</string>
  <string id="Device Address:">Dirección del dispositivo:</string>
  <string id="Device Class">Clase de dispositivo</string>
  <string id="Device Group">Grupo de dispositivos</string>
  <string id="Device Group created">Grupo de dispositivos creado</string>
  <string id="Device Group was successfully removed from the system.">El grupo de dispositivos se ha eliminado del sistema correctamente.</string>
  <string id="Device Group:">Grupo de dispositivos:</string>
  <string id="Device Groups">Grupos de dispositivos</string>
  <string id="Device Groups:">Grupos de dispositivos:</string>
  <string id="Device Information Directions">Indicaciones de información de dispositivo</string>
  <string id="Device Model">Modelo de dispositivo</string>
  <string id="Device Model:">Modelo de dispositivo:</string>
  <string id="Device Profiles">Perfiles de dispositivo:</string>
  <string id="Device Summary">Resumen de dispositivo</string>
  <string id="Device update complete.">Actualización de dispositivo finalizada.</string>
  <string id="Device update started...">Actualización de dispositivo iniciada...</string>
  <string id="DeviceGroup">Grupo de dispositivos</string>
  <string id="Devices">Dispositivos</string>
  <string id="Directory">Directorio</string>  
  <string id="Directory Path">Ruta del directorio</string>
  <string id="Directory path*">Ruta del directorio*</string>
  <string id="Directory Watcher">Observador de directorio</string>
  <string id='Directory Watcher information'>Información del observador de directorio</string>
  <string id="Disabled">Desactivado</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:60902, transport: socket">Desconectado de la VM de destino, dirección: 127.0.0.1:60902, transporte: socket</string>
  <string id="Disconnected from the target VM, address: 127.0.0.1:61015, transport: socket">Desconectado de la VM de destino, dirección: 127.0.0.1:61015, transporte: socket</string>
  <string id="Discover">Detectar</string>
  <string id="Discover devices for selected device groups using each groups own Discovery Profiles.">Detecta dispositivos para los grupos de dispositivos seleccionados utilizando los perfiles de búsqueda de cada grupo.</string>
  <string id="Discover devices for this device group using its Discovery Profiles.">Detecta dispositivos para este grupo de dispositivos utilizando sus perfiles de búsqueda.</string>
  <string id="Discover Missing">Detectar lo que falta</string>
  <string id="Discover new devices only">Detectar solo dispositivos nuevos</string>
  <string id="Discover Unlicensed">Detectar los que no tengan licencia</string>
  <string id="Discover...">Detectar...</string>
  <string id="Discovered">Detectados</string>
  <string id="Discovered Devices">Dispositivos detectados</string>
  <string id="Discovered Devices:">Dispositivos detectados:</string>
  <string id="Discovery">Detección</string>
  <string id="Discovery has Completed for...">Detección completada para...</string>
  <string id="Discovery in Progress for...">Detección en curso para...</string>
  <string id="Discovery Profile created.">Perfil de búsqueda creado.</string>
  <string id="Discovery Profiles">Perfiles de búsqueda</string>
  <string id="Discovery Profiles:">Perfiles de búsqueda:</string>
  <string id="Display Text">Texto para mostrar</string>
  <string id="Display Text:">Texto para mostrar:</string>
  <string id="Documentation">Documentación</string>
  <string id="Done">Hecho</string>
  <string id="Done generating the jobs report for downloading.">Se ha completado la generación del informe de trabajos para su descarga.</string>
  <string id="Done generating the logs report for downloading.">Se ha completado la generación del informe de registros para su descarga.</string>
  <string id="Down icon">Icono hacia abajo</string>
  <string id="Down icon:">Icono hacia abajo:</string>
  <string id='Download Details'>Detalles de descargas</string>
  <string id="Duplex :">Doble cara:</string>
  <string id="Edit">Editar</string>
  <string id="Edit a solution">Editar una solución</string>
  <string id="Edit a solution to deploy">Editar una solución para su implementación</string>
  <string id="Edit the information about the report :">Edite la información acerca del informe:</string>
  <string id="Edit the report settings">Editar la configuración del informe</string>
  <string id="Edit...">Editar...</string>
  <string id="EForms">Formularios en línea</string>
  <string id="E-Forms">Formularios en línea</string>
  <string id="EForms:">Formularios en línea:</string>
  <string id="Either both the From date and time fields must be filled, or they must both be left blank.">Los campos de fecha y hora de inicio deben rellenarse o bien dejarse en blanco.</string>
  <string id="Either both the To date and time fields must be filled, or they must both be left blank.">Los campos de fecha y hora de finalización deben rellenarse o bien dejarse en blanco.</string>
  <string id="Email">Correo electrónico</string>
  <string id="Email + Profile">Correo electrónico + perfil</string>
  <string id="Email Shortcuts">Métodos abreviados de correo electrónico</string>
  <string id="Email the Report">Enviar el informe por correo electrónico</string>
  <string id="Email To">Enviar correo a</string>
  <string id="Enable Fax Forwarding.">Activar el reenvío de faxes.</string>
  <string id="Enable LDAP Authentication.">Activar autenticación de LDAP.</string>
  <string id="Enabled for Credentials">Credenciales activadas</string>
  <string id="Enabled for Session">Sesión activada</string>
  <string id="End Time">Hora de finalización</string>
  <string id="End Time:">Hora de finalización:</string>
  <string id="Enter a unique group name">Introduzca un nombre de grupo único</string>
  <string id="Enter a unique name for this group">Introduzca un nombre único para este grupo</string>
  <string id="Enter appropriate fields and click the Add button:">Introduzca los campos pertinentes y haga clic en el botón Agregar:</string>
  <string id="Enter appropriate fields and click the Save button:">Introduzca los campos correspondientes y haga clic en el botón Guardar:</string>
  <string id="Enter the appropriate fields and click the Add button:">Introduzca los campos correspondientes y haga clic en el botón Añadir:</string>
  <string id="Enter the information about the new report :">Introduzca la información acerca del nuevo informe:</string>
  <string id="Enter the timeout values in milliseconds, separated by a space in between each retry.">Introduzca los valores de tiempo de espera en milisegundos (separando cada reintento con un espacio).</string>
  <string id="Error">Error</string>
  <string id="Error importing license.">Error al importar licencia.</string>
  <string id="Error in changing name.">Error al cambiar nombre.</string>
  <string id="Error in creating device group...">Error al crear grupo de dispositivos...</string>
  <string id="Error in creating software client group...">Error al crear grupo de clientes de software...</string>
  <string id="Error in deleting device group.">Error al eliminar grupo de dispositivos.</string>
  <string id="Error in deleting software client group.">Error al borrar grupo de clientes de software.</string>
  <string id="Error in deleting the FormSet(s). Please check the logs for more details.">Error al eliminar los formsets. Compruebe los registros para obtener más información.</string>
  <string id="Error in generating the report.">Error al generar el informe.</string>
  <string id="Error in saving Ldap settings.">Error al guardar la configuración de LDAP.</string>
  <string id="Error in saving settings.">Error al guardar la configuración.</string>
  <string id="Error in updating password.">Error al actualizar la contraseña.</string>
  <string id="Error in updating security settings.">Error al actualizar la configuración de seguridad.</string>
  <string id="Error in updating service settings.">Error al actualizar la configuración del servicio.</string>
  <string id="Error in updating solution settings.">Error al actualizar la configuración de la solución.</string>
  <string id="Error while deploying home screen to">Error al implementar la pantalla de inicio en</string>
  <string id="Eval">Eval</string>
  <string id="Evaluate in +app_url}">Evaluar en +app_url}</string>
  <string id="Evaluate in remote app">Evaluar en aplicación remota</string>
  <string id="Every">Cada</string>
  <string id="Expiration Date">Fecha de caducidad</string>
  <string id="Expired Formset">Formset caducado</string>
  <string id="Expired!">Ha caducado.</string>
  <string id="Expires on:">Fecha de caducidad:</string>
  <string id="Export Report">Exportar informe</string>
  <string id="Export AuditLog">Export Audit Log</string>
  <string id="Failed">Error</string>
  <string id="FALSE">FALSO</string>
  <string id="Fax">Fax</string>
  <string id="Fax + Profile">Fax + perfil</string>
  <string id="Fax Forward settings updated.">La configuración del reenvío de faxes se ha actualizado.</string>
  <string id="Fax Forwarding">Reenvío de faxes</string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax">Método abreviado de destino de reenvío de faxes: (Correo electrónico, FTP, fax </string>
  <string id="Fax Forwarding Destination Shortcut: (Email, FTP, Fax)">Método abreviado de destino de reenvío de faxes: (Correo electrónico, FTP, fax)</string>
  <string id="Fax Forwarding Destination:">Destino de reenvío de faxes:</string>
  <string id="Fax Forwarding LDSS Script:">Script de LDSS de reenvío de faxes:</string>
  <string id="Fax Forwarding Receive Mode:">Modo de recepción de reenvío de faxes:</string>
  <string id="Fax Shortcuts">Métodos abreviados de fax</string>
  <string id="Feature Id">ID de función</string>
  <string id="Filter">Filtro</string>
  <string id="Filters...">Filtros...</string>
  <string id="Finish">Finalizar</string>
  <string id="Finished AP Bundle Descriptor File">Archivo descriptor del paquete de AP terminado</string>
  <string id="Finished AP Bundle Flash File">Archivo flash del paquete de AP terminado</string>
  <string id="Finished upload of key.pem File.">Carga del archivo key.pem terminada.</string>
  <string id="First">Primera</string>
  <string id="Form field must be a single word or valid email address.">El campo Formulario debe contener una sola palabra o una dirección de correo electrónico válida.</string>
  <string id="Form Printers">Impresoras de formularios</string>
  <string id="Format :">Formato:</string>
  <string id="Forms">Formularios</string>
  <string id="Forms Printer is unlicensed">La impresora de formularios no tiene licencia</string>
  <string id="Forms printer successfully created or updated.">La impresora de formularios se ha creado o actualizado correctamente.</string>
  <string id="Forms printer successfully deleted.">La impresora de formularios se ha eliminado correctamente.</string>
  <string id="Formsets">Formsets</string>
  <string id="FormsetsSubforms">Formsets/subformularios</string>
  <string id="Forward Only">Solo reenvío</string>
  <string id="Fourth">Cuarto</string>
  <string id="FRAMEWORK">FRAMEWORK</string>
  <string id="Fri">Vie</string>
  <string id="From:">De:</string>
  <string id="Ftp">Ftp</string>
  <string id="FTP">FTP</string>
  <string id="Ftp + Profile">FTP + perfil</string>
  <string id="Ftp Shortcuts">Métodos abreviados de FTP</string>
  <string id="Generating logs report for downloading...">Generando el informe de registros para su descarga...</string>
  <string id="Generating Report">Generación de informes</string>
  <string id="Generating Report...">Generando informe...</string>
  <string id="Generating reports during regular business hours can negatively impact the system performance. It is recommended to run reports during off hours.">La generación de informes durante el horario laborable normal puede afectar de forma negativa al rendimiento del sistema. Se recomienda ejecutar los informes durante el horario no laborable.</string>
  <string id="Generating the jobs report for downloading...">Generando el informe de trabajos para su descarga...</string>
  <string id="Graphic">Gráfico</string>
  <string id="Graphic:">Gráfico:</string>
  <string id="Group Description placeholder">Marcador de posición de descripción de grupo</string>
  <string id="Group Identifier:">Identificador de grupo:</string>
  <string id="Group Names from LDAP">Nombres de grupos de LDAP</string>
  <string id="Group Names from LDAP:">Nombres de grupos de LDAP:</string>
  <string id="Group search base must be set for adding group based">La base de búsqueda de grupos debe estar configurada para añadir un grupo en función de </string>
  <string id="Group search base must be set in">La base de búsqueda de grupos debe estar configurada para agregar un grupo</string>
  <string id="Group Search Base:">Base de búsqueda de grupo:</string>
  <string id="Group Search Filter:">Filtro de búsqueda de grupo:</string>
  <string id="Group Search Identifier:">Identificador de búsqueda de grupo:</string>
  <string id="Groups">Grupos</string>
  <string id="Held Jobs">Trabajos en espera</string>
  <string id="Hide Settings">Ocultar valores</string>
  <string id="Home">Inicio</string>
  <string id="Home Screen">Pantalla de inicio</string>
  <string id="Home screen deployed to">Pantalla de inicio implementada en</string>
  <string id="Home Screens">Pantallas de inicio</string>
  <string id="Home Tab">Ficha Inicio</string>
  <string id="Hostname">Nombre de host</string>
  <string id="Hostname:">Nombre de host:</string>
  <string id="Id">ID</string>
  <string id="IDR License Summary">Resumen de licencia de IDR</string>
  <string id="IDR License Summary:">Resumen de licencia de IDR:</string>
  <string id="Images">Imágenes</string>
  <string id="Import">Importar</string>
  <string id="Import...">Importar...</string>
  <string id="Importing AP Bundle Descriptor File...">Importando archivo descriptor del paquete de AP...</string>
  <string id="Importing AP Bundle Flash File...">Importando archivo flash del paquete de AP...</string>
  <string id='Importing Binary String...'>Importando cadena binaria...</string>  
  <string id="Importing CaCert pem File...">Importando archivo CaCert.pem...</string>
  <string id="Importing license...">Importando licencia...</string>
  <string id="Importing software client group profile...">Importando perfil de grupo de clientes de software...</string>
  <string id="Importing Solution(s)...">Importando soluciones...</string>
  <string id="Insert - This will insert the cut button and push the remaining buttons down">Insertar (se insertará el botón de método abreviado y se empujarán los demás botones hacia abajo)</string>
  <string id="Install Time">Tiempo de instalación</string>
  <string id="Install Time:">Tiempo de instalación:</string>
  <string id="Install-Upgrade">Instalar/actualizar</string>
  <string id="It is recommended to run reports during off hours.">Se recomienda ejecutar los informes durante el horario no laborable.</string>
  <string id="Items">Elementos</string>
  <string id="Jasper Report File Name:">Nombre del archivo del informe Jasper:</string>
  <string id="Job State">Estado del trabajo</string>
  <string id="Job State:">Estado del trabajo:</string>
  <string id="Jobs">Trabajos</string>
  <string id="Jobs by user">Trabajos por usuario</string>
  <string id="Jobs Filters Table">Tabla de filtros de trabajo</string>
  <string id="Jobs Report">Informes de trabajo</string>
  <string id="Jobs Report - CSV">Informes de trabajo: CSV</string>
  <string id="Keep previous backups">Conservar las copias de seguridad anteriores</string>
  <string id="Krank">Krank</string>
  <string id='Language:'>Idioma:</string>
  <string id="Last">Últimas</string>
  <string id="Last 12 Hours">Últimas 12 horas</string>
  <string id="Last 15 Minutes">Últimos 15 minutos</string>
  <string id="Last 24 Hours">Últimas 24 horas</string>
  <string id="Last 3 Hours">Últimas 3 horas</string>
  <string id="Last 30 Days">Últimos 30 días</string>
  <string id="Last 30 Minutes">Últimos 30 minutos</string>
  <string id="Last 6 Hours">Últimas 6 horas</string>
  <string id="Last 7 Days">Últimos 7 días</string>
  <string id="Last Discovered">Última detección</string>
  <string id="Last Discovered:">Última detección:</string>
  <string id="Last Hour">Última hora</string>
  <string id="Last Kranked">Last Kranked</string>
  <string id="Last Modified">Última modificación:</string>
  <string id="Layout">Presentación</string>
  <string id="Layout:">Presentación:</string>
  <string id="LDAP Server Settings:">Configuración del servidor LDAP:</string>
  <string id="Ldap Settings Saved.">Se han guardado la configuración de LDAP.</string>
  <string id="LDAP Setup">Configuración LDAP</string>
  <string id="LDSS">LDSS</string>
  <string id="Lexmark 6500e">Lexmark 6500e</string>
  <string id="Lexmark C520">Lexmark C520</string>
  <string id="Lexmark C524">Lexmark C524</string>
  <string id="Lexmark C532">Lexmark C532</string>
  <string id="Lexmark C534">Lexmark C534</string>
  <string id="Lexmark C734">Lexmark C734</string>
  <string id="Lexmark C748">Lexmark C748</string>
  <string id="Lexmark C782">Lexmark C782</string>
  <string id="Lexmark C792">Lexmark C792</string>
  <string id="Lexmark C920">Lexmark C920</string>
  <string id="Lexmark C935">Lexmark C935</string>
  <string id="Lexmark CS510">Lexmark CS510</string>
  <string id="Lexmark E450">Lexmark E450</string>
  <string id="Lexmark MS610">Lexmark MS610</string>
  <string id="Lexmark MS812">Lexmark MS812</string>
  <string id="Lexmark MX610">Lexmark MX610</string>
  <string id="Lexmark MX611">Lexmark MX611</string>
  <string id="Lexmark MX6500e">Lexmark MX6500e</string>
  <string id="Lexmark MX710">Lexmark MX710</string>
  <string id="Lexmark MX810">Lexmark MX810</string>
  <string id="Lexmark MX910de">Lexmark MX910de</string>
  <string id="Lexmark MX911de">Lexmark MX911de</string>
  <string id="Lexmark T642">Lexmark T642</string>
  <string id="Lexmark T654">Lexmark T654</string>
  <string id="Lexmark W840">Lexmark W840</string>
  <string id="Lexmark X464">Lexmark X464</string>
  <string id="Lexmark X548">Lexmark X548</string>
  <string id="Lexmark X620">Lexmark X620</string>
  <string id="Lexmark X632">Lexmark X632</string>
  <string id="Lexmark X642">Lexmark X642</string>
  <string id="Lexmark X644">Lexmark X644</string>
  <string id="Lexmark X652">Lexmark X652</string>
  <string id="Lexmark X658">Lexmark X658</string>
  <string id="Lexmark X738">Lexmark X738</string>
  <string id="Lexmark X752">Lexmark X752</string>
  <string id="Lexmark X792">Lexmark X792</string>
  <string id="Lexmark X832">Lexmark X832</string>
  <string id="Lexmark X854">Lexmark X854</string>
  <string id="Lexmark X864">Lexmark X864</string>
  <string id="Lexmark X940">Lexmark X940</string>
  <string id="Lexmark X945">Lexmark X945</string>
  <string id="Lexmark X954">Lexmark X954</string>
  <string id="Lexmark CS820">Lexmark CS820</string>
  <string id="Lexmark CS720">Lexmark CS720</string>
  <string id="Lexmark CS725">Lexmark CS725</string>
  <string id="Lexmark CX820">Lexmark CX820</string>
  <string id="Lexmark CX725">Lexmark CX725</string>
  <string id="Lexmark CX825">Lexmark CX825</string>
  <string id="Lexmark CX860">Lexmark CX860</string>
  <string id="Lexmark Print Management">Lexmark Print Management</string>
  <string id="License">Licencia</string>
  <string id="LICENSE">LICENCIA</string>
  <string id="License Files">Archivos de licencia</string>
  <string id="License Type">Tipo de licencia</string>
  <string id="License Upload Results.">Resultados de la carga de licencias.</string>
  <string id="License Upload Results:">Resultados de la carga de licencias:</string>
  <string id="Licensed">Con licencia</string>
  <string id="Licenses">Licencias</string>
  <string id="Licenses in Use">Licencias en uso</string>
  <string id="Limit batch size">Límite de tamaño de lotes</string>
  <string id="Line Chart with Time Period Slider.">Gráfico de líneas con regulador de período de tiempo</string>
  <string id='LoadBalancer Fully Qualified Hostname OR IpAddress'>Nombre de host completo O dirección IP del equilibrador de carga</string>
  <string id="LOADING">CARGANDO</string>
  <string id="Loading...">Cargando...</string>
  <string id="LOADING...">CARGANDO...</string>
  <string id="Lock Device">Bloquear dispositivo</string>
  <string id="Log">Registro</string>
  <string id="Log Report - CSV">Informes de registro: CSV</string>
  <string id="Log Report - Failed Jobs">Informe de registro: trabajos con errores</string>
  <string id="Log State">Estado de registro</string>
  <string id="Log State:">Estado de registro:</string>
  <string id="Logging In">Iniciando sesión</string>
  <string id="Login">Iniciar sesión</string>
  <string id="Logout">Cerrar sesión</string>
  <string id="Logs Filters Table">Tabla de filtros de registro</string>
  <string id='Max:'>Máx.:</string>
  <string id="Member of Group(s):">Miembros de grupos:</string>
  <string id="Memory Usage">Uso de memoria</string>
  <string id="Message">Mensaje</string>
  <string id="Message:">Mensaje:</string>
  <string id="Messages">Mensajes</string>
  <string id="Missing">Falta</string>
  <string id='Min:'>Mín.:</string>
  <string id='Minimum length:'>Longitud mínima:</string>
  <string id='Minimum:'>Mínimo:</string>
  <string id="Missing Device">Dispositivo que falta</string>
  <string id="Missing Devices">Dispositivos que faltan</string>
  <string id="Missing devices are devices that were once discovered, but during the most recent discovery, they were unable to be found (e.g., due to the device being off network).">Los dispositivos que faltan son aquellos que se detectaron una vez, pero no se encontraron durante la detección más reciente (por ejemplo, debido a que el dispositivo se encuentra desconectado de la red).</string>
  <string id="Missing devices:">Dispositivos que faltan:</string>
  <string id="Missing Devices:">Dispositivos que faltan:</string>
  <string id="Model">Modelo</string>
  <string id="Model:">Modelo:</string>
  <string id="Mon">Lun</string>
  <string id="MONITOR">MONITOR</string>
  <string id="Move Down">Bajar</string>
  <string id="Move Up">Subir</string>
  <string id="Name">Nombre</string>
  <string id="Name :">Nombre:</string>
  <string id="Name changed.">Se ha cambiado el nombre.</string>
  <string id="Name:">Nombre:</string>
  <string id="Network Load">Carga de red</string>
  <string id="Network share password">Contraseña de recurso compartido de red</string>
  <string id="Network share user name">Nombre de usuario de recurso compartido de red</string>
  <string id="New Password:">Nueva contraseña:</string>
  <string id="New Username:">Nuevo nombre de usuario:</string>
  <string id="Next">Siguiente</string>
  <string id="No">No</string>
  <string id='No cSF Apps exist for this device group. You need to have at least one cSF App before you can associate this action to the button.'>No existen aplicaciones cSF para este grupo de dispositivos. Debe disponer de al menos una aplicación cSF para poder asociar esta acción al botón.</string>
  <string id="No devices are currently Out of Policy for the system.">En este momento, no hay ningún dispositivo que no esté actualizado en el sistema.</string>
  <string id="No devices are currently Out of Policy for this device group.">En este momento, no hay ningún dispositivo que no esté actualizado en este grupo de dispositivos.</string>
  <string id="No home screen is configured for this device type.">No se ha configurado la pantalla de inicio para este tipo de dispositivo.</string>
  <string id="No matches found">No hay coincidencias</string>
  <string id='No Privilege'>Sin privilegios</string>
  <string id="No Privilege Alert">No hay alerta de privilegios</string>
  <string id="No Profiles exist for this device group because no solutions with profiles have been associated.">No existen perfiles para este grupo de dispositivos porque no se han asociado soluciones con perfiles.</string>
  <string id="No Profiles exist for this device group. You need to have at least one profile before you can associate this action to the button.">No existen perfiles para este grupo de dispositivos. Debe disponer de al menos un perfil antes de que pueda asociar esta acción con el botón.</string>
  <string id="No records match the selected filter criteria.">No hay registros que coincidan con los criterios de filtro seleccionados.</string>
  <string id="No records matched the filter criteria.">Ningún registro coincide con los criterios de filtro.</string>
  <string id="No schedulable scripts are available.">No hay disponible ningún script programable.</string>
  <string id="No UCF File selected">No se ha seleccionado ningún archivo de configuración de seguridad</string>
  <string id="None">Ninguno</string>
  <string id="None of the selected devices are missing.">No falta ninguno de los dispositivos seleccionados.</string>
  <string id="None of the selected devices are unlicensed.">Todos los dispositivos seleccionados tienen licencia.</string>
  <string id="Number of Jobs per Page">Número de trabajos por página</string>
  <string id="Number of Licenses">Número de licencias</string>
  <string id="Number of Logs per Page">Número de registros por página</string>
  <string id="Off">Desactivado</string>
  <string id="OK">Aceptar</string>
  <string id="Once">Una vez</string>
  <string id="One or more buttons in the current configuration are not valid. Please make sure that all the buttons are valid.">Uno o varios botones de la configuración actual no son válidos. &lt;font color="#ff0000"&gt;(se muestra en rojo)&lt;/font&gt; Asegúrese de que todos los botones sean válidos.</string>
  <string id="One or more tests did not pass.">No se han superado una o varias pruebas.</string>
  <string id="Only">Solamente</string>
  <string id="Only one discovery can occur at a time. You can start a new Discovery after the current one finishes.">Solamente se puede realizar una detección a la vez. Puede iniciar una detección nueva cuando acabe la que está en curso.</string>
  <string id="Only one Policy Update can occur at a time.  You can start a new Policy Update after the current one finishes.">Solamente se puede llevar a cabo una actualización de políticas a la vez.  Puede iniciar una actualización de políticas nueva cuando acabe la que está en curso.</string>
  <string id="Only update those devices which are Out of Policy">Actualizar solo los dispositivos que no estén actualizados</string>
  <string id="Orientation :">Orientación:</string>
  <string id="Out of Policy">No está actualizado</string>
  <string id="Out of Policy Device">Dispositivo que no está actualizado</string>
  <string id="Out of Policy Devices">Dispositivos que no están actualizados</string>
  <string id="Out of Policy Devices:">Dispositivos que no están actualizados:</string>
  <string id="Output Format">Formato de salida</string>
  <string id="Overwrite if file already exists">Sobrescribir si el archivo ya existe</string>
  <string id="Page 1">Página 1</string>
  <string id="Page 2">Página 2</string>
  <string id="Page 3">Página 3</string>
  <string id="Page 4">Página 4</string>
  <string id="Paper Size :">Tamaño del papel:</string>
  <string id="Parameters">Parámetros</string>
  <string id="Password Changed Successfully.">Contraseña modificada correctamente.</string>
  <string id="Password updated.">Contraseña actualizada.</string>
  <string id="Password*">Contraseña*</string>
  <string id="Password:">Contraseña:</string>
  <string id="PDF">PDF</string>
  <string id="Perform a Policy Update for selected device groups using each groups Policy.">Llevar a cabo una actualización de políticas para los grupos de dispositivos seleccionados utilizando la política de cada grupo.</string>
  <string id="Perform a Policy Update for selected devices.">Llevar a cabo la actualización de políticas para los dispositivos seleccionados.</string>
  <string id="Perform a Policy Update for this device group.">Llevar a cabo la actualización de políticas para este grupo de dispositivos.</string>
  <string id="Placeholder">Marcador de posición</string>
  <string id="Please choose a filter:">Seleccione un filtro:</string>
  <string id="Please choose a group type to be able to access a solutions local solution settings in the scheduled script:">Seleccione el tipo de grupo que podrá acceder a los valores de la solución local en el script programado:</string>
  <string id="Please choose a script:">Seleccione un script:</string>
  <string id="Please choose a task to schedule :">Seleccione la tarea que desea programar:</string>
  <string id="Please choose an action:">Seleccione una acción:</string>
  <string id="Please choose client groups to schedule :">Seleccione los grupos de clientes que desea programar:</string>
  <string id="Please choose device groups to schedule :">Seleccione los grupos de dispositivos que desea programar:</string>
  <string id="Please choose one of the following options:">Seleccione una de los siguientes opciones:</string>
  <string id="Please choose solution and script :">Seleccione una solución y un script:</string>
  <string id="Please choose solution and script to schedule :">Seleccione la solución y el script que desea programar:</string>
  <string id="Please choose start time and frequency :">Seleccione la hora de inicio y la frecuencia:</string>
  <string id="Please choose the datasource for the new report.">Seleccione el origen de datos para el nuevo informe.</string>
  <string id="Please choose the jasper filename for the new report.">Seleccione el nombre de archivo jasper para el nuevo informe.</string>
  <string id="Please choose the jasper filename for the new report.  Upload the jasper report if its not already listed.">Seleccione el nombre de archivo jasper para el nuevo informe.  Cargue el informe jasper si no aparece ya en la lista.</string>
  <string id="Please choose the output format for the new report.">Seleccione el formato de salida para el nuevo informe.</string>
  <string id="Please choose the report to schedule :">Seleccione el informe que desea programar:</string>
  <string id="Please Contact Lexmark for Software Client License Information.">Póngase en contacto con Lexmark para obtener información sobre las licencias de clientes de software.</string>
  <string id="Please enter a non-expired date">Introduzca una fecha no vencida (mm/dd/aaaa).</string>
  <string id="Please enter a valid Address.">Introduzca una dirección válida.</string>
  <string id="Please enter a valid date">Introduzca una fecha válida (mm/dd/aaaa).</string>
  <string id="Please enter a valid End From Time">Introduzca una hora de finalización válida (hh:mm AM/PM).</string>
  <string id="Please enter a valid End To Time">Introduzca una hora de finalización válida (hh:mm AM/PM).</string>
  <string id="Please enter a valid From date">Introduzca una fecha de inicio (mm/dd/aaaa).</string>
  <string id="Please enter a valid From time">Introduzca una hora de inicio válida (hh:mm AM/PM).</string>
  <string id='Please enter a valid range:'>Introduzca un rango válido:</string>
  <string id="Please enter a valid range: 1 - 12">Introduzca un rango válido: 1 - 12</string>
  <string id="Please enter a valid range: 1 - 23">Introduzca un rango válido: 1 - 23</string>
  <string id="Please enter a valid range: 1 - 59">Introduzca un rango válido: 1 - 59</string>
  <string id="Please enter a valid Start From Time">Introduzca una hora Iniciar desde válida (hh:mm AM/PM).</string>
  <string id="Please enter a valid Start To Time">Introduzca una hora Iniciar hasta válida (HH:MM-AM/PM).</string>
  <string id="Please enter a valid time">Introduzca una hora válida (hh:mm AM/PM)</string>
  <string id="Please enter a valid To date">Introduzca una fecha de finalización válida (mm/dd/aaaa).</string>
  <string id="Please enter a valid To time">Introduzca una hora de finalización válida (hh:mm AM/PM).</string>
  <string id="Please enter the Database driver and URL for the external database.">Introduzca el controlador y la URL de la base de datos para la base de datos externa.</string>
  <string id="Please enter the Directory information:">Introduzca la información del directorio:</string>
  <string id="Please enter the location where you want the report to be saved.">Introduzca la ubicación donde desea guardar el informe.</string>
  <string id="Please enter the name of the new report.">Introduzca el nombre del nuevo informe.</string>
  <string id="Please enter the network share user name and password.">Introduzca el nombre de usuario y la contraseña de uso compartido de red.</string>
  <string id="Please enter the recipients to whom the report will be emailed.">Introduzca los destinatarios a quienes se enviará el informe por correo electrónico.</string>
  <string id="Please enter the requested information for Backup &amp; Restore :">Introduzca la información solicitada para Copia de seguridad y restaurar:</string>
  <string id="Please make sure that all the necessary fields are filled in.">Asegúrese de que se han rellenado todos los campos requeridos.</string>
  <string id="Please make sure the your cron expression has 6 or 7 options seperated by spaces.">Asegúrese de que su expresión CRON dispone de 6 o 7 opciones separadas por espacios.</string>
  <string id="Please make sure the your cron expression has a &quot;?&quot; in either the 4th or 6th position, but not in both.">Asegúrese de que su expresión CRON dispone de un símbolo “?” en la 4.ª o 6.ª posición, pero no en ambas.</string>
  <string id="Please select a file to upload.">Seleccione el archivo que desea cargar.</string>
  <string id="Please select a group on the left to modify its task privileges.">Seleccione un grupo de la izquierda para modificar sus privilegios de tareas.</string>
  <string id="Please select a group to save privileges for.">Seleccione un grupo para el que guardar los privilegios.</string>
  <string id="Please select a profile to view its settings.">Seleccione un perfil para ver sus valores.</string>
  <string id="Please select the Group to delete.">Seleccione el grupo que desea eliminar.</string>
  <string id="Please select the report to delete.">Seleccione el informe que desea eliminar.</string>
  <string id="Please select the report to edit.">Seleccione el informe que desea editar:</string>
  <string id="Please select the report to run.">Seleccione el informe que desea ejecutar:</string>
  <string id="Please specify a port:">Especifique un puerto:</string>
  <string id="Please Verify MinMax, Length and Required Settings.">Verifique los valores obligatorios, mínimos y máximos y de longitud.</string>
  <string id="Policy Last Applied">Última aplicación de políticas</string>
  <string id="Policy Update">Actualización de políticas</string>
  <string id="Policy Update has Completed for...">Actualización de políticas completada para...</string>
  <string id="Policy Update in Progress for...">Actualización de políticas en curso para...</string>
  <string id="Policy Update on all effected Device Groups.">Actualización de políticas en todos los grupos de dispositivos afectados.</string>
  <string id="Port">Puerto</string>
  <string id="Port:">Puerto:</string>
  <string id="Present">Presente</string>
  <string id="Previous">Anterior</string>
  <string id="Print (Default)">Imprimir (predeterminado)</string>
  <string id="Print and Forward">Imprimir y reenviar</string>
  <string id="Printer Panel">Panel de la impresora</string>
  <string id="Printer Report">Informe de impresora</string>
  <string id="Privileges">Privilegios</string>
  <string id="Process finished with exit code 0">Proceso finalizado con el código de salida 0.</string>
  <string id="Profile Filters">Filtros de perfil</string>
  <string id="Profile:">Perfil:</string>
  <string id="Profiles">Perfiles</string>
  <string id="Profiles :">Perfiles:</string>
  <string id="Profiles:">Perfiles:</string>
  <string id="Progress %">% de progreso</string>
  <string id="Property Tag">Etiqueta de propiedad</string>
  <string id="Property Tag:">Etiqueta de propiedad:</string>
  <string id="Quality :">Calidad:</string>
  <string id="QUARTZ">QUARTZ</string>
  <string id="Recurrence">Recurrencia</string>
  <string id="Refresh">Actualizar</string>
  <string id="Refresh Defaults">Actualizar valores predeterminados</string>
  <string id="Regular Expression">Expresión normal</string>
  <string id="Release Held Faxes">Enviar faxes retenidos</string>
  <string id="Remove">Eliminar</string>
  <string id="Remove All">Eliminar todo</string>
  <string id="Remove from System">Eliminar del sistema</string>
  <string id="Remove Server(s)">Servidor(es) remoto(s)</string>
  <string id="RemoveAll">Eliminar todo</string>
  <string id="Removing selected servers...">Eliminando los servidores seleccionados...</string>
  <string id="Repeat this event :">Repetir este evento:</string>
  <string id="Replace - This will delete the selected button and replace it with the cut button.">Sustituir (se eliminará el botón seleccionado y se sustituirá por el botón de método abreviado).</string>
  <string id="Replace Me">Sustituirme</string>
  <string id="Report">Informe</string>
  <string id="Report by Time">Informe por hora</string>
  <string id="Report Files">Archivos de informe</string>
  <string id="Report From">Informe de</string>
  <string id="Report Name:">Nombre del informe:</string>
  <string id="Report Parameters:">Parámetros del informe:</string>
  <string id="Report To">Informe para</string>
  <string id="REPORT_NAME successfully generated">REPORT_NAME se ha generado correctamente</string>
  <string id="Reporting Period">Período de elaboración de informes</string>
  <string id="Reports">Informes</string>
  <string id="Reports:">Informes:</string>
  <string id="Request timed out. Please narrow your search criteria and try again.">Tiempo de espera de la solicitud agotado. Restrinja sus criterios de búsqueda e inténtelo de nuevo.</string>
  <string id="Required field">Campo obligatorio</string>
  <string id="Reset">Restablecer</string>
  <string id="Reset Filter">Restablecer filtro</string>
  <string id="Reset to Default">Restablecer valores predeterminados</string>
  <string id="Resolution :">Resolución:</string>
  <string id="Return to Original">Volver a original</string>
  <string id="Retype New Password:">Vuelva a escribir la contraseña nueva:</string>
  <string id="Retype New Username:">Vuelva a escribir el nombre de usuario nuevo:</string>
  <string id="Run on All Servers">Ejecutar en todos los servidores</string>
  <string id="Run Report">Ejecutar informe</string>
  <string id="Running">En ejecución</string>
  <string id="Running Tasks">Tareas en ejecución</string>
  <string id="Running...">En ejecución...</string>
  <string id="Sat">Sáb</string>
  <string id="Save">Guardar</string>
  <string id="Save Privileges">Guardar privilegios</string>
  <string id="Save Settings">Guardar valores</string>
  <string id="Save To">Guardar en</string>
  <string id="Saving eSF Settings...">Guardando configuración de eSF...</string>
  <string id="Saving eSF deployment order...">Saving eSF deployment order...</string>
  <string id="Saving LDAP Settings...">Guardando configuración de LDAP...</string>
  <string id="Schedule">Programar</string>
  <string id="Scheduled task createdupdated">Tarea programada creada o actualizada</string>
  <string id="Scheduled task deleted">Tarea programada eliminada</string>
  <string id="Scheduled tasks for all client groups:">Tareas programadas para todos los grupos de clientes:</string>
  <string id="Scheduled tasks for all device groups:">Tareas programadas para todos los grupos de dispositivos:</string>
  <string id="Script">Script</string>
  <string id="Script:">Script:</string>
  <string id="Search">Buscar</string>
  <string id="Search Base:">Base de búsqueda:</string>
  <string id="Search Held Jobs">Buscar trabajos en espera</string>
  <string id="Search LDAP for Groups:">Buscar LDAP para grupos:</string>
  <string id="Searching...">Buscando...</string>
  <string id="Second">Segundo</string>
  <string id="Secure Server Communication">Comunicación de servidor segura</string>
  <string id="Secure Server Communication:">Comunicación de servidor segura:</string>
  <string id="Security">Seguridad</string>
  <string id="Security setting updated.">Configuración de seguridad actualizada.</string>
  <string id="Security setup file updated successfully">El archivo de configuración de seguridad se ha actualizado correctamente.</string>
  <string id="Security setup file update failed">Se ha producido un error al actualizar el archivo de configuración de seguridad.</string>
  <string id="Select a Group Name:">Seleccione un nombre de grupo:</string>
  <string id="Select a report">Seleccionar un informe</string>
  <string id="Select a script task">Seleccione una tarea de script</string>
  <string id="Select one...">Seleccione uno...</string>
  <string id="Select Profile...">Seleccione un perfil...</string>
  <string id="Select the group to copy">Seleccione el grupo que desea copiar</string>
  <string id="Sent when any leaf is checked or unchecked, in">Se envía cuando al seleccionar cualquier hoja o al anular su selección,</string>
  <string id="Serial Number">Número de serie</string>
  <string id="Serial Number:">Número de serie:</string>
  <string id="Server Address">Dirección de servidor</string>
  <string id="Server Address:">Dirección de servidor:</string>
  <string id="Server handling this LMC session">Servidor que gestiona esta sesión de LMC</string>
  <string id="Server is currently offline">El servidor está desconectado en este momento</string>
  <string id="Server is not communicating">El servidor no se está comunicando</string>
  <string id="Server is unlicensed">Servidor sin licencia</string>
  <string id="Server Port:">Puerto de servidor:</string>
  <string id="Server Report">Informe de servidor</string>
  <string id="Server(s) Error">Errores de servidor</string>
  <string id="Server(s) Offline">Servidores sin conexión</string>
  <string id="Servers">Servidores</string>
  <string id="Service settings updated">Configuración del servicio actualizada</string>
  <string id="Services">Servicios</string>
  <string id="Set Offline">Desconectar</string>
  <string id="Set Online">Conectar</string>
  <string id="Setting selected servers offline...">Configurando servidores seleccionados sin conexión...</string>
  <string id="Setting selected servers online...">Configurando servidores seleccionados en línea...</string>
  <string id="Settings :">Valores:</string>
  <string id="Settings:">Valores:</string>
  <string id="SFP e-Task">e-Task de la impresora monofunción</string>
  <string id="SFP e-Task home screen updated.">Pantalla de inicio de e-Task de la impresora monofunción actualizada.</string>
  <string id="SFP e-Task2">e-Task2 de la impresora monofunción</string>
  <string id="SFP e-Task2 home screen updated.">Pantalla de inicio de e-Task2 de la impresora monofunción actualizada.</string>
  <string id="SFP e-Task2+">e-Task2+ de la impresora monofunción</string>
  <string id="SFP e-Task2+ home screen updated.">Pantalla de inicio de e-Task2+ de la impresora monofunción actualizada.</string>
  <string id="SFP e-Task3">e-Task3 de la impresora monofunción</string>
  <string id="SFP e-Task3 home screen updated.">Pantalla de inicio de e-Task3 de la impresora monofunción actualizada.</string>
  <string id="SFP e-Task4">e-Task4 de la impresora monofunción</string>
  <string id="SFP e-Task4 (7in.)">e-Task4 de la impresora monofunción (7 pulg.)</string>
  <string id="SFP e-Task4 (7in.) home screen updated.">Pantalla de inicio de e-Task4 (7 pulg.) de la impresora monofunción actualizada.</string>
  <string id="SFP e-Task4 home screen updated.">Pantalla de inicio de e-Task4 de la impresora monofunción actualizada.</string>
  <string id="SftClientGroup">Grupo de clientes de software</string>
  <string id="SftClientGroups">Grupos de clientes de software</string>
  <string id="Shortcut">Método abreviado</string>
  <string id="Shortcut :">Acceso directo:</string>
  <string id="Shortcut:">Acceso directo:</string>
  <string id="Show Settings">Mostrar valores</string>
  <string id="Since Last Month">Desde el mes pasado</string>
  <string id="Since Yesterday">Desde ayer</string>
  <string id="Single Profile">Perfil único</string>
  <string id="SNMP Timeout Retries:">Reintentos de tiempo de espera de SNMP:</string>
  <string id="Software Client Group">Grupo de clientes de software</string>
  <string id="Software Client Group created">Grupo de clientes de software creado</string>
  <string id="Software Client Group:">Grupo de clientes de software:</string>
  <string id="Software Client Groups">Grupos de clientes de software</string>
  <string id="Software Client Report">Informe de clientes de software</string>
  <string id="SOLO">SOLO</string>
  <string id="Solution">Solución</string>
  <string id="Solution deleted from software client group.">Solución eliminada del grupo de clientes de software.</string>
  <string id="Solution deployed to device group">Solución implementada en el grupo de dispositivos</string>
  <string id="Solution deployed to software client group">Solución implementada en el grupo de clientes de software</string>
  <string id="Solution Name">Nombre de la solución</string>
  <string id="Solution Name:">Nombre de la solución:</string>
  <string id="Solution Report">Informe de solución</string>
  <string id="Solution settings updated.">Configuración de la solución actualizada.</string>
  <string id="Solution: Deleting device group deployment...">Solución: Eliminando implementación del grupo de dispositivos...</string>
  <string id="Solution: Deleting solution from software client group...">Solución: Eliminando solución del grupo de clientes de software...</string>
  <string id="Solution: device group deployment deleted.">Solución: implementación del grupo de dispositivos eliminada.</string>
  <string id="SOLUTIONINFO">INFO. DE LA SOLUCIÓN</string>
  <string id="Solutions">Soluciones</string>
  <string id="Solutions to deploy:">Soluciones que se implementarán:</string>
  <string id="Solutions:">Soluciones:</string>
  <string id='Specify Restore system information'>Especifique la información de restauración del sistema</string>
  <string id="Specify where the generated report should be saved">Especifique dónde se guardará el informe generado</string>
  <string id="Start Button Default Action">Acción predeterminada del botón de inicio</string>
  <string id="Start Date :">Fecha de inicio:</string>
  <string id="Start Time">Hora de inicio</string>
  <string id="Start Time:">Hora de inicio:</string>
  <string id="State">Estado</string>
  <string id="Status">Estado</string>
  <string id="Steps for viewing device information:">Pasos para ver la información del dispositivo:</string>
  <string id="Stop">Detener</string>
  <string id="Stop Task">Detener tarea</string>
  <string id="Subform">Subformulario</string>
  <string id="Subject:">Asunto:</string>
  <string id="Success">Correcto</string>
  <string id="Successfully added the group.">El grupo se ha añadido correctamente.</string>
  <string id="Successfully Deleted All Solution(s) from the System.">Todas las soluciones se han eliminado correctamente del sistema.</string>
  <string id="Successfully Deleted Solution(s) from the System.">Las soluciones se han eliminado correctamente del sistema.</string>
  <string id="Successfully Imported Solution(s) into the System.">Las soluciones se han importado correctamente en el sistema.</string>
  <string id="Summary">Resumen</string>
  <string id="Sun">Dom</string>
  <string id="Switch - This will switch the positions between the selected and cut buttons.">Cambiar (se cambiarán las posiciones de los elementos seleccionados y los botones de método abreviado).</string>
  <string id="System">Sistema</string>
  <string id="System Health...">Estado del sistema...</string>
  <string id="System Status">Estado del sistema</string>
  <string id="System Status 1">Estado del sistema 1</string>
  <string id="Task Id">ID de tarea</string>
  <string id="Task Id:">ID de tarea:</string>
  <string id="Task Name">Nombre de tarea</string>
  <string id="Task Name:">Nombre de la tarea:</string>
  <string id="Task Summary Report">Informe de resumen de la tarea</string>
  <string id="Test Progress">Progreso de la prueba</string>
  <string id="Test Results">Resultados de la prueba</string>
  <string id="Test Settings">Probar valores</string>
  <string id="Testing LDAP Settings...">Probando configuración de LDAP...</string>
  <string id="The buttons on the first screen can be arranged in a custom manner.">Los botones de la primera pantalla pueden ordenarse de forma personalizada.</string>
  <string id="The following report has been successfully generated:  REPORT_NAME.  Please view the attached report.">El siguiente informe se ha generado correctamente:  REPORT_NAME.  Vea el informe adjunto.</string>
  <string id="The password provided is incorrect.">La contraseña proporcionada no es correcta.</string>
  <string id="The policy of this group is now being undeployed from all devices in the group.">La política de este grupo está dejando de ser implementada en todos los dispositivos del grupo.</string>
  <string id="The report is now ready for downloading. Please click OK to continue.">El informe ya está listo para su descarga. Haga clic en Aceptar para continuar.</string>
  <string id="The To date for the reporting period is earlier than the From date.  The system will automatically switch them for you when generating the report.  Do you want to continue?">La fecha de finalización para el período de elaboración de informes es anterior a la fecha de inicio.  El sistema las cambiará automáticamente cuando genere el informe.  ¿Desea continuar?</string>
  <string id="There are currently no client profiles for this software client group. Please add them by filling out the fields above.">En este momento, no hay perfiles de cliente para este grupo de clientes de software. Añádalos rellenando los campos anteriores.</string>
  <string id="There are currently no cSF Apps associated with this device group.">En este momento, no hay aplicaciones cSF asociadas a este grupo de dispositivos.</string>
  <string id="There are currently no cSF Apps to add to this device group.">En este momento, no hay aplicaciones cSF que añadir a este grupo de dispositivos.</string>
  <string id="There are currently no device groups to perform discovery.">En este momento, no hay grupos de dispositivos para realizar la búsqueda.</string>
  <string id='There are currently no device groups to perform policy update.'>En este momento no hay grupos de dispositivos para actualizar la política.</string>
  <string id="There are currently no device groups to schedule.">En este momento, no hay grupos de dispositivos que programar.</string>
  <string id='There are currently no device groups.  Please add a device group by clicking on the Add button on the left.'>En este momento no hay grupos de dispositivos.  Añada un grupo de dispositivos haciendo clic en el botón Añadir que hay a la izquierda.</string>
  <string id="There are currently no devices discovered for this device group.">En este momento, no hay dispositivos detectados para este grupo de dispositivos.</string>
  <string id="There are currently no devices in this device group.">En este momento no hay ningún dispositivo en este grupo de dispositivos.</string>
  <string id="There are currently no discovered devices.">En este momento no se ha detectado ningún dispositivo.</string>
  <string id="There are currently no discovery profiles for this device group. Please add them by filling out the appropriate fields above.">En este momento, no hay perfiles de búsqueda para este grupo de dispositivos. Añádalos rellenando los campos anteriores correspondientes.</string>
  <string id="There are currently no forms printers in the system.">En este momento, no hay impresoras de formularios en el sistema.</string>
  <string id="There are currently no licenses installed.">En este momento, no hay licencias instaladas.</string>
  <string id="There are currently no licensing changes made by this upload.">En este momento, no se han producido cambios de licencia por esta carga.</string>
  <string id="There are currently no missing devices for this device group.">En este momento, no falta ningún dispositivo para este grupo de dispositivos.</string>
  <string id="There are currently no missing devices.">En este momento, no falta ningún dispositivo.</string>
  <string id="There are currently no out of policy devices for this device group.">En este momento, no hay ningún dispositivo que no esté actualizado en este grupo de dispositivos.</string>
  <string id="There are currently no out of policy devices.">En este momento, no hay ningún dispositivo que no esté actualizado.</string>
  <string id="There are currently no scheduled tasks">En este momento, no hay tareas programadas.</string>
  <string id="There are currently no software client groups.  Please add a group by clicking on the Add button on the left.">En este momento, no hay grupos de clientes de software.  Añada un grupo haciendo clic en el botón Añadir que hay a la izquierda.</string>
  <string id="There are currently no solutions associated with this device group.">En este momento, no hay soluciones asociadas a este grupo de dispositivos.</string>
  <string id="There are currently no solutions associated with this software client group.">En este momento, no hay soluciones asociadas a este grupo de clientes de software.</string>
  <string id="There are currently no solutions installed.">En este momento, no hay soluciones instaladas.</string>
  <string id='There are currently no solutions to add to this device group.'>En este momento no existen soluciones que añadir a este grupo de dispositivos.</string>
  <string id="There are currently no solutions to add to this software client group.">En este momento, no hay soluciones que añadir a este grupo de clientes de software.</string>
  <string id="There are currently no unlicensed devices for this device group.">En este momento, no hay dispositivos sin licencia para este grupo de dispositivos.</string>
  <string id="There are currently no unlicensed devices in this device group.">En este momento no hay ningún dispositivo sin licencia en este grupo de dispositivos.</string>
  <string id="There are currently no unlicensed devices.">En este momento no hay ningún dispositivo sin licencia.</string>
  <string id="There are currently solutions or cSF Apps andor home screens associated with the policy of this group. Would you like to undeploy this policy now? Please note that in doing so the device group will not be deleted immediately. Please remove the device group when the policy update completes.">En este momento, hay soluciones o aplicaciones cSF y/o pantallas de inicio asociadas a la política de este grupo. ¿Desea dejar de implementar esta política ahora? Tenga en cuenta que, al hacerlo, no se eliminará el grupo de dispositivos de inmediato. Elimine el grupo de dispositivos cuando finalice la actualización de políticas.</string>
  <string id="There are no associated UCF Files for this Solution.">No hay ningún archivo de configuración de seguridad asociado para esta solución.</string>
  <string id="There are no associated UCF Files for the Solutions in this device group.">En este momento no hay archivos de configuración de seguridad para las soluciones de este grupo de dispositivos.</string>
  <string id="There are no configuration settings for this eSF application.">No hay ningún valor de configuración para esta aplicación eSF.</string>
  <string id="There are no configuration settings in this solution.">No hay ningún valor de configuración en esta solución.</string>
  <string id="There are no configuration settings in this webapp.">No hay ningún valor de configuración en esta aplicación web.</string>
  <string id="There are no cSF Apps installed currently.">En este momento, no hay aplicaciones cSF instaladas.</string>
  <string id="There are no deployments setting for this solution.">No hay ningún valor de implementación para esta solución.</string>
  <string id="There are no devices in the system that match the filter.">No hay dispositivos en el sistema que coincidan con el filtro.</string>
  <string id="There are no eSF Applications for this solution.">No hay aplicaciones eSF para esta solución.</string>
  <string id="There are no e-Task profiles for this device group.">En este momento, no hay perfiles de e-Task para este grupo de dispositivos.</string>
  <string id="There are no e-Task2 profiles for this device group.">En este momento, no hay perfiles de e-Task2 para este grupo de dispositivos.</string>
  <string id="There are no forms for this solution.">No hay formularios para esta solución.</string>
  <string id="There are no forms in the system.">No hay formularios en el sistema.</string>
  <string id="There are no parameters in this service.">No existen parámetros en este servicio.</string>
  <string id="There are no profiles for this software client group.">No hay perfiles para este grupo de clientes de software.</string>
  <string id="There are no settings for this action.">No existen valores para esta acción.</string>
  <string id="There are no settings for this solution.">No existen valores para esta solución.</string>
  <string id="There is currently a Policy Update running...">En este momento se está ejecutando una actualización de políticas...</string>
  <string id="There is currently no Version Info.">En este momento, no hay información de la versión.</string>
  <string id="These eSF Applications are part of the solutions associated with this device group. Please select an application to view its settings.">Estas aplicaciones eSF son parte de las soluciones asociadas a este grupo de dispositivos. Seleccione una aplicación para ver sus valores.</string>
  <string id="These group settings are currently hidden.">Estos valores de grupo están ocultos en este momento.</string>
  <string id="These profiles are part of the group policy for each model. Please select a profile for each model to view its settings.">Estos perfiles forman parte de la política de grupo de cada modelo. Seleccione un perfil para ver los valores de cada modelo.</string>
  <string id="Third">Tercero</string>
  <string id="This link will route you to Lexmark's Webkit Configuration UI , do you want to continue?">Este vínculo le guiará a la interfaz de usuario de la configuración de WebKit de Lexmark, ¿desea continuar?</string>
  <string id="This Month">Este mes</string>
  <string id="This name has been given to another device group. Please choose a different name.">Se ha otorgado este nombre a otro grupo de dispositivos. Seleccione otro nombre.</string>
  <string id="This name has been given to another software client group. Please choose a different name.">Se ha otorgado este nombre a otro grupo de clientes de software. Seleccione otro nombre.</string>
  <string id="Thread Count">Recuento de hilos</string>
  <string id="Thu">Jue</string>
  <string id="Time">Hora</string>
  <string id="Time of Next Run">Hora de la siguiente ejecución</string>
  <string id="Time Policies Last Applied">Hora de la última aplicación de políticas</string>
  <string id="Time:">Hora:</string>
  <string id="To add them to the home screen, choose Custom layout from the above drop down box and add the profiles.">Para añadirlas a la pantalla de inicio, seleccione Presentación personalizada en el cuadro desplegable anterior y añada los perfiles.</string>
  <string id="To arrange them yourself, choose one of the layouts from the above drop down box.">Para ordenarlos, seleccione una de las presentaciones del cuadro desplegable anterior.</string>
  <string id="To configure one, please choose one of the layouts from the above drop down box.">Para configurar una de las presentaciones, selecciónela del cuadro desplegable anterior.</string>
  <string id="To:">Para:</string>
  <string id="Today">Hoy</string>
  <string id="Today date">Fecha de hoy</string>
  <string id="Tops Report">Informe de actividades más frecuentes</string>
  <string id="Tue">Mar</string>
  <string id="UCF">Archivos de configuración de seguridad</string>
  <string id="UCF:">Archivos de configuración de seguridad:</string>    
  <string id="Unable to Change Password.">No se puede cambiar la contraseña.</string>
  <string id="Unable to Change Username.">No se puede cambiar el nombre de usuario.</string>
  <string id="Unable to validate all settings!">No se pueden validar todos los valores.</string>
  <string id="Uncounted">Sin contar</string>
  <string id="Un-deploying all cSF Apps(s)...">Eliminando la implementación de todas las aplicaciones cSF...</string>
  <string id="Un-deploying cSF App(s)...">Eliminando la implementación de las aplicaciones cSF...</string>
  <string id="Unknown">Desconocido</string>
  <string id="Unknown Error Occured! Please Check System Log">Se ha producido un error desconocido. Compruebe el registro del sistema</string>
  <string id='Unknown Secure State'>Estado de seguridad desconocido</string>
  <string id="Unlicensed">Sin licencia</string>
  <string id="Unlicensed Device">Dispositivo sin licencia</string>
  <string id="Unlicensed Devices">Dispositivos sin licencia</string>
  <string id="Unlicensed devices are devices that were discovered, but during the most recent discovery, they were unable to be asssigned a License. (e.g., due to License expired or all licenses are in use).">Los dispositivos sin licencia son aquellos que se detectaron, pero no se les pudo asignar una licencia en la detección más reciente (por ejemplo, debido a que la licencia caducó o a que todas las licencias están en uso).</string>
  <string id="Unlicensed devices:">Dispositivos sin licencia:</string>
  <string id="Unlicensed Devices:">Dispositivos sin licencia:</string>
  <string id="Unlicensed:">Sin licencia:</string>
  <string id="Unlimited">Ilimitado</string>
  <string id="Up icon:">Icono hacia arriba:</string>
  <string id="Update">Actualizar</string>
  <string id="Update Policy">Actualizar política</string>
  <string id="Update Time">Hora de la actualización</string>
  <string id="Update Time:">Hora de la actualización:</string>
  <string id="Updating client profile...">Actualizando perfil de cliente...</string>
  <string id="Updating discovery profile...">Actualizando perfil de búsqueda...</string>
  <string id="Updating e-Task home screen...">Actualizando la pantalla de inicio de e-Task...</string>
  <string id="Updating e-Task2 home screen...">Actualizando la pantalla de inicio de e-Task2...</string>
  <string id="Updating e-Task2+ home screen...">Actualizando la pantalla de inicio de e-Task2+...</string>
  <string id="Updating e-Task3 home screen...">Actualizando la pantalla de inicio de e-Task3...</string>
  <string id="Updating e-Task4 (4.3 in.) home screen...">Actualizando la pantalla de inicio de e-Task4 (4,3 pulg.)...</string>
  <string id="Updating e-Task4 home screen...">Actualizando la pantalla de inicio de e-Task4...</string>
  <string id="Updating Fax Forward settings...">Actualizando configuración del reenvío de faxes...</string>
  <string id="Updating password...">Actualizando contraseña...</string>
  <string id="Updating Security setting...">Actualizando configuración de seguridad...</string>
  <string id="Updating service settings...">Actualizando configuración del servicio...</string>
  <string id="Updating SFP e-Task home screen...">Actualizando la pantalla de inicio de e-Task de la impresora monofunción...</string>
  <string id="Updating SFP e-Task2 home screen...">Actualizando la pantalla de inicio de e-Task2 de la impresora monofunción...</string>
  <string id="Updating SFP e-Task2+ home screen...">Actualizando la pantalla de inicio de e-Task2+ de la impresora monofunción...</string>
  <string id="Updating SFP e-Task3 home screen...">Actualizando la pantalla de inicio de e-Task3 de la impresora monofunción...</string>
  <string id="Updating SFP e-Task4 (7in.) home screen...">Actualizando la pantalla de inicio de e-Task4 (7 pulg.) de la impresora monofunción...</string>
  <string id="Updating SFP e-Task4 home screen...">Actualizando la pantalla de inicio de e-Task4 de la impresora monofunción...</string>
  <string id="Updating solution settings...">Actualizando configuración de la solución...</string>
  <string id="Updating username...">Actualizando nombre de usuario...</string>
  <string id="Updating X642 home screen...">Actualizando la pantalla de inicio de X642...</string>
  <string id='Updating webapp settings...'>Actualizando la configuración de aplicación web...</string>
  <string id="Upgrading or deleting solutions here will require">Para actualizar o eliminar soluciones aquí se necesitará</string>
  <string id="Upgrading or un-deploying cSF App(s) here will require Policy Update on all effected Device Groups">La actualización o eliminación de la implementación de aplicaciones cSF aquí requerirá la &lt;b&gt;Actualización de políticas&lt;/b&gt; en todos los grupos de dispositivos afectados</string>
  <string id="Upload">Cargar</string>
  <string id="Upload custom icons">Cargar iconos personalizados</string>
  <string id="Upload Report Files">Cargar archivos de informes</string>
  <string id="Uploading AP Bundle and Descriptor Completed.">Carga del paquete de AP y el descriptor completa.</string>
  <string id="Uploading AP Bundle and Descriptor...">Cargando paquete de AP y descriptor...</string>
  <string id="Uploading cSF Ap cert files....">Cargando archivos cert de aplicación cSF...</string>
  <string id="Uploading cSF App Cert files(cacert.pem and key.pem ...">Cargando archivos Cert de aplicación cSF (cacert.pem y key.pem)...</string>
  <string id="Uploading of cSF App cert files Completed.">Carga de archivos cert de aplicación cSF completa.</string>
  <string id="Uploading Report(s)...">Cargando informes...</string>
  <string id="Uploading...">Cargando...</string>
  <string id="Usage:">Uso:</string>
  <string id="Usb Drive">Unidad USB</string>
  <string id="Use default settings">Utilizar valores predeterminados</string>
  <string id="Use Secure Connection. (SSLTLS)">Utilice una conexión segura. (SSL/TLS)</string>
  <string id="Use Solution Configuration">Utilizar la configuración de soluciones</string>
  <string id="Use this dialog only if the database, central webdav data of the existing LDD system needs to be synched up with another active LDD system which will act as a 'backup LDD system'. For information about this feature refer Admin guide.">Use este cuadro de diálogo únicamente si los datos de Webdav central de la base de datos del sistema LDD existente se deben sincronizar con otro sistema LDD activo que actúe como "sistema LDD de seguridad". Para obtener más información acerca de esta función, consulte la Guía del administrador.</string>
  <string id="Use this home screen as part of the device groups policy.">Utilizar esta pantalla de inicio como parte de la política del grupo de dispositivos.</string>
  <string id='Used:'>Utilizado:</string>
  <string id="User Name">Nombre de usuario</string>
  <string id="User Name:">Nombre de usuario:</string>
  <string id="User Report">Informe de usuario</string>
  <string id="User Search Base:">Base de búsqueda de usuario:</string>
  <string id="User Search Filter:">Filtro de búsqueda de usuario:</string>
  <string id="Username amp; Password">Nombre de usuario y contraseña</string>
  <string id="Username and Password">Nombre de usuario y contraseña</string>
  <string id="Username Changed Successfully.">Nombre de usuario modificado correctamente.</string>
  <string id="Username Password">Nombre de usuario y contraseña</string>
  <string id="Username updated.">Nombre de usuario actualizado.</string>
  <string id="Username*">Nombre de usuario*</string>
  <string id="Username:">Nombre de usuario:</string>
  <string id="Verify eSF application deployment and deploy these eSF settings.">Comprobar la implementación de la aplicación eSF e implementar estos valores de eSF.</string>
  <string id="Version">Versión</string>
  <string id="Version Info:">Información de la versión:</string>
  <string id="Version:">Versión:</string>
  <string id="VersionInfo">VersionInfo</string>
  <string id="Very very very long long long text">Texto muy muy muy largo largo largo</string>
  <string id="View Details">Ver detalles</string>
  <string id="View Source">Ver origen</string>
  <string id="Waiting for License Upload Results ...">Esperando los resultados de la carga de la licencia...</string>
  <string id="WebApps">Aplicaciones web</string>
  <string id="WebClient Version">Versión del cliente web</string>
  <string id="WebClient Version:">Versión del cliente web:</string>
  <string id="Wed">Mié</string>
  <string id="X642">X642</string>
  <string id="X642 home screen updated.">Pantalla de inicio de X642 actualizada.</string>
  <string id="Yes">Sí</string>
  <string id="You are viewing the Kranked version of the application">Está viendo la versión de Krank de la aplicación</string>
  <string id="You have no privilege to access any of the tasks in All cSF Apps">No dispone de privilegios para acceder a las tareas de Todas las aplicaciones cSF.</string>
  <string id="You have no privilege to access any of the tasks in All Device Groups">No dispone de privilegios para acceder a las tareas de Todos los grupos de dispositivos</string>
  <string id="You have no privilege to this task.">No dispone de privilegios para esta tarea.</string>
  <string id="You must first select a Task to Edit">Primero debe seleccionar una tarea para editarla</string>
  <string id="active">activo</string>
  <string id="active:">activo:</string>
  <string id="addition to the two events below.">adición a los dos eventos siguientes.</string>
  <string id="avg response (ms)">respuesta media (ms)</string>
  <string id="be set back to the default values next time.">se restablecerán los valores predeterminados la próxima vez.</string>
  <string id="cache">caché</string>
  <string id="cc:">cc:</string>
  <string id="change">cambio</string>
  <string id="cSF App">Aplicación cSF</string>
  <string id="cSF App Cert File">Archivo Cert de aplicación cSF</string>
  <string id="cSF App Certificates">Certificados de aplicación cSF</string>
  <string id="cSF App Certificates (cacert.pem, key.pem ) Upload">Carga de certificados (cacert.pem y key.pem) de aplicación cSF</string>
  <string id="cSF App Key File">Archivo de clave de aplicación cSF</string>
  <string id="cSF App settings updated.">Configuración de la aplicación cSF actualizada.</string>
  <string id="cSF App Version">Versión de aplicación cSF</string>
  <string id="cSF App Version:">Versión de aplicación cSF:</string>
  <string id="cSF Apps">Aplicaciones cSF</string>
  <string id="cSF Apps deployed to device group">Aplicaciones cSF implementadas en el grupo de dispositivos:</string>
  <string id="cSF Apps to deploy:">Aplicaciones cSF para su implementación:</string>
  <string id="cSF Apps: Device group deployment deleted.">Aplicaciones cSF: Implementación del grupo de dispositivos eliminada.</string>
  <string id="day(s)">día(s)</string>
  <string id="devices failed">dispositivos con errores</string>
  <string id="devices updated">dispositivos actualizados</string>
  <string id="device(s) discovered">dispositivos detectados</string>
  <string id="device(s) missing">dispositivos que faltan</string>
  <string id="disk-in-use=">disco en uso=</string>
  <string id="disk-total=">total de disco=</string>
  <string id="eSF">eSF</string>
  <string id="eSF Application Settings:">Valores de la aplicación eSF:</string>
  <string id="eSF Application Version:">Versión de la aplicación eSF:</string>
  <string id="eSF Applications">Aplicaciones eSF</string>
  <string id="eSF Applications:">Aplicaciones eSF:</string>
  <string id="eSF Applications: (Solution)">Aplicaciones eSF: (Solución)</string>
  <string id="eSF Configuration">Configuración eSF</string>
  <string id="eSF Settings Saved.">Configuración de eSF guardada.</string>
  <string id="eSF deployment order saved.">eSF deployment order saved.</string>
  <string id="e-Task">e-Task</string>
  <string id="e-Task home screen updated.">Pantalla de inicio de e-Task actualizada.</string>
  <string id="e-Task2">e-Task2</string>
  <string id="e-Task2 home screen updated.">Pantalla de inicio de e-Task2 actualizada.</string>
  <string id="e-Task2+">e-Task2+</string>
  <string id="e-Task2+ home screen updated.">Pantalla de inicio de e-Task2+ actualizada.</string>
  <string id="e-Task3">e-Task3</string>
  <string id="e-Task3 home screen updated.">Pantalla de inicio de e-Task3 actualizada.</string>
  <string id="e-Task4">e-Task4</string>
  <string id="e-Task4 (4.3 in.)">e-Task4 (4,3 pulg.)</string>
  <string id="e-Task4 (4.3 in.) home screen updated.">Pantalla de inicio de e-Task4 (4,3 pulg.) actualizada.</string>
  <string id="e-Task4 home screen updated.">Pantalla de inicio de e-Task4 actualizada.</string>
  <string id="e-Task5">e-Task5</string>
  <string id="failed.">error.</string>
  <string id="hide">ocultar</string>
  <string id="hour(s)">hora(s)</string>
  <string id="in order to add a group.">para añadir un grupo.</string>
  <string id="info">información</string>
  <string id="load">carga</string>
  <string id="mem-in-use=">memoria en uso =</string>
  <string id="mem-total=">memoria total =</string>
  <string id="min(s)">min.</string>
  <string id="month(s)">mes</string>
  <string id="not communicating">sin comunicación</string>
  <string id="null">nulo</string>
  <string id="offline">sin conexión</string>
  <string id="on">Activado</string>
  <string id="on all effected Device Groups.">en todos los grupos de dispositivos afectados.</string>
  <string id="oncheck">desactivar</string>
  <string id="online">en línea</string>
  <string id="or home screen support for this device does not exist.">o este dispositivo no es compatible con la pantalla de inicio.</string>
  <string id="requests">solicitudes</string>
  <string id="requests/sec">solicitudes/seg.</string>
  <string id="saving report...">guardando informe...</string>
  <string id="server">servidor</string>
  <string id="show">mostrar</string>
  <string id="test">prueba</string>
  <string id="to">para</string>
  <string id="to change them.">para cambiarlos.</string>
  <string id="to take effect on the devices.">para que tengan efecto en los dispositivos.</string>
  <string id="total requests:">solicitudes totales:</string>
  <string id="total responses:">respuestas totales:</string>
  <string id="undo">deshacer</string>
  <string id="uploaded.">cargado.</string>
  <string id="week(s)">semana(s)</string>
  <string id="{0} Groups">Grupos {0}</string>
  <string id="{0} Reports">Informes {0}</string>
  <string id="{0} Software Client Groups">Grupos de clientes de software {0}</string>
  <string id="{0} Solutions">Soluciones {0}</string>
  <string id="{0} eForms">Formularios en línea {0}</string>
  <string id="{0} eSF Applications">Aplicaciones eSF {0}</string>
  <string id="Policy update required for changes to take effect on the devices">Todos los cambios que se realicen aquí requerirán la &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Actualización de políticas&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; para que tengan efecto en los dispositivos.</string>
  <string id="Group search base must be set for adding group based Privileges">La base de búsqueda de grupos debe estar configurada para añadir un grupo en función de &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Privilegios&lt;/font&gt;&lt;/b&gt;&lt;/u&gt;.</string>
  <string id="Group search base must be set in LDAP Setup in order to add a group.">La base de búsqueda de grupos debe estar configurada en &lt;u&gt;&lt;b&gt;&lt;font color=&quot;#0000ff&quot;&gt;Configuración LDAP&lt;/font&gt;&lt;/b&gt;&lt;/u&gt; para añadir un grupo.</string>
  <string id="SMB licensed installation! MFP Licenses will be limited to a maximum of">Instalación con licencia SMB Las licencias MFP se limitarán a un máximo de</string>
  <string id="licenses!">licencias</string>
</localize>`;